#ifndef SYSTEMC_LINKER_H
#define SYSTEMC_LINKER_H

#include "SvgParser.h" // Include the header file for the SvgParser inherited class

#include "ComponentsStruct.h"

/**
 * @brief The SvgParseManager class
 * This class is responsible for managing the parsing of an SVG file
 * and detecting any global parsing errors.
 * It uses the structures generated by the SvgParser class to validate and link components found in the SVG file,
 * ensuring the data is error-free for further processing.
*/
class SvgParseManager: public SvgParser
{

public:
    SvgParseManager(QString svg_file);
    ~SvgParseManager();

    bool getGlobalParsingError();


private:
};
#endif // SVG_LINKER_H
