#ifndef SYSTEMC_LINKER_H
#define SYSTEMC_LINKER_H

#include "SvgParser.h" // Include the header file for the SvgParser inherited class

//#include <systemc.h>

/**
 * @brief The svg_linker class
 * This class will generate the systemC link between the different components of the svg file
 * It will use the structure generated by the svg_link_parser class
 */

class SystemcLinker: public SvgParser
{
private:
    //SvgLinkParser::s_components_list components;
    void link_components();

    void create_sysc_module(const s_element& elem);

public:
    SystemcLinker(QString svg_file);
    ~SystemcLinker();
};

#endif // SVG_LINKER_H
