#ifndef SVG_LINKER_H
#define SVG_LINKER_H

#include "svg_link_parser.h"

/**
 * @brief The svg_linker class
 * This class will generate the systemC link between the different components of the svg file
 * It will use the structure generated by the svg_link_parser class
 */

class Svg_linker
{
private:
    SvgLinkParser::s_components_list components;
    void link_components();

public:
    Svg_linker(SvgLinkParser* parser);
    ~Svg_linker();
};

#endif // SVG_LINKER_H
