#ifndef SVG_LINKER_H
#define SVG_LINKER_H

#include "SvgParser.h"

/**
 * @brief The svg_linker class
 * This class will generate the systemC link between the different components of the svg file
 * It will use the structure generated by the svg_link_parser class
 */

class SvgLinker: public SvgParser
{
private:
    //SvgLinkParser::s_components_list components;
    void link_components();

public:
    SvgLinker(QString svg_file);
    ~SvgLinker();
};

#endif // SVG_LINKER_H
