.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/mpl/aux_/adl_barrier.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/mpl/aux_/adl_barrier.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <sysc/packages/boost/mpl/aux_/config/adl\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/mpl/aux_/config/gcc\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/mpl/aux_/config/workaround\&.hpp>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSC_BOOST_MPL_AUX_ADL_BARRIER_NAMESPACE\fP"
.br
.ti -1c
.RI "namespace \fBSC_BOOST_MPL_AUX_ADL_BARRIER_NAMESPACE::aux\fP"
.br
.ti -1c
.RI "namespace \fBsc_boost\fP"
.br
.ti -1c
.RI "namespace \fBsc_boost::mpl\fP"
.br
.ti -1c
.RI "namespace \fBsc_boost::mpl::aux\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_MPL_AUX_ADL_BARRIER_NAMESPACE\fP   \fBsc_mpl_\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_MPL_AUX_ADL_BARRIER_NAMESPACE_OPEN\fP   \fBnamespace\fP \fBsc_mpl_\fP {"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_MPL_AUX_ADL_BARRIER_NAMESPACE_CLOSE\fP   }"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_MPL_AUX_ADL_BARRIER_DECL\fP(type)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_MPL_AUX_ADL_BARRIER_DECL(type)"
\fBValue:\fP.PP
.nf
    namespace sc_boost { namespace mpl { \\
    using ::SC_BOOST_MPL_AUX_ADL_BARRIER_NAMESPACE::type; \\
    } } \\
.fi

.SS "#\fBdefine\fP SC_BOOST_MPL_AUX_ADL_BARRIER_NAMESPACE   \fBsc_mpl_\fP"

.SS "#\fBdefine\fP SC_BOOST_MPL_AUX_ADL_BARRIER_NAMESPACE_CLOSE   }"

.SS "#\fBdefine\fP SC_BOOST_MPL_AUX_ADL_BARRIER_NAMESPACE_OPEN   \fBnamespace\fP \fBsc_mpl_\fP {"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
