.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/platform/aix.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/platform/aix.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <sysc/packages/boost/config/posix_features\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_PLATFORM\fP   'IBM \fBAix'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_UNISTD_H\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_NL_TYPES_H\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_NANOSLEEP\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_CLOCK_GETTIME\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_STDINT_H\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_PTHREADS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_PTHREAD_DELAY_NP\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_SCHED_YIELD\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_HAS_CLOCK_GETTIME"

.SS "#\fBdefine\fP SC_BOOST_HAS_NANOSLEEP"

.SS "#\fBdefine\fP SC_BOOST_HAS_NL_TYPES_H"

.SS "#\fBdefine\fP SC_BOOST_HAS_PTHREAD_DELAY_NP"

.SS "#\fBdefine\fP SC_BOOST_HAS_PTHREADS"

.SS "#\fBdefine\fP SC_BOOST_HAS_SCHED_YIELD"

.SS "#\fBdefine\fP SC_BOOST_HAS_STDINT_H"

.SS "#\fBdefine\fP SC_BOOST_HAS_UNISTD_H"

.SS "#\fBdefine\fP SC_BOOST_PLATFORM   'IBM \fBAix'\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
