.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/qt/b.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/qt/b.h
.SH SYNOPSIS
.br
.PP
\fR#include 'copyright\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBB_H\fP   '$Header: /\fBUsers\fP/\fBacg\fP/\fBCVSROOT\fP/\fBsystemc\fP\-2\&.3/\fBsrc\fP/\fBsysc\fP/\fBqt\fP/b\&.h,v 1\&.1\&.1\&.1 2006/12/15 20:20:06 \fBacg\fP \fBExp\fP $'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBb_call_reg\fP (int \fBn\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBb_call_imm\fP (int \fBn\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBb_add\fP (int \fBn\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBb_load\fP (int \fBn\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP B_H   '$Header: /\fBUsers\fP/\fBacg\fP/\fBCVSROOT\fP/\fBsystemc\fP\-2\&.3/\fBsrc\fP/\fBsysc\fP/\fBqt\fP/b\&.h,v 1\&.1\&.1\&.1 2006/12/15 20:20:06 \fBacg\fP \fBExp\fP $'"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP b_add (int n)\fR [extern]\fP"

.SS "\fBvoid\fP b_call_imm (int n)\fR [extern]\fP"

.SS "\fBvoid\fP b_call_reg (int n)\fR [extern]\fP"

.SS "\fBvoid\fP b_load (int n)\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
