.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/bind.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/bind.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <sysc/packages/boost/config\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/ref\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/mem_fn\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/type\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/bind/arg\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/detail/workaround\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/bind/bind_template\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/bind/bind_cc\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/bind/bind_mf_cc\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/bind/placeholders\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsc_boost::_bi::result_traits< R, F >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::unspecified\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::result_traits< unspecified, F >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::result_traits< unspecified, reference_wrapper< F > >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::value< T >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::type< T >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::list0\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::list1< A1 >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::list2< A1, A2 >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::list3< A1, A2, A3 >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::list4< A1, A2, A3, A4 >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::list5< A1, A2, A3, A4, A5 >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::list6< A1, A2, A3, A4, A5, A6 >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::list7< A1, A2, A3, A4, A5, A6, A7 >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::list8< A1, A2, A3, A4, A5, A6, A7, A8 >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::list9< A1, A2, A3, A4, A5, A6, A7, A8, A9 >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::_bi::bind_t< R, F, L >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::add_value< T >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::add_value< value< T > >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::add_value< reference_wrapper< T > >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::add_value< arg< I > >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::add_value< arg< I >(*)() >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::add_value< bind_t< R, F, L > >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::list_av_1< A1 >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::list_av_2< A1, A2 >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::list_av_3< A1, A2, A3 >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::list_av_4< A1, A2, A3, A4 >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::list_av_5< A1, A2, A3, A4, A5 >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::list_av_6< A1, A2, A3, A4, A5, A6 >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::list_av_7< A1, A2, A3, A4, A5, A6, A7 >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::list_av_8< A1, A2, A3, A4, A5, A6, A7, A8 >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::list_av_9< A1, A2, A3, A4, A5, A6, A7, A8, A9 >\fP"
.br
.ti -1c
.RI "struct \fBsc_boost::_bi::logical_not\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_boost\fP"
.br
.ti -1c
.RI "namespace \fBsc_boost::_bi\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_BIND_VISIT_EACH\fP   visit_each"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_BIND_RETURN\fP   \fBreturn\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_BIND_OPERATOR\fP(\fBop\fP,  name)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_BIND\fP   bind"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_BIND_CC\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_BIND_ST\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_BIND_MF_NAME\fP(X)   X"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_BIND_MF_CC\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBbool\fP \fBsc_boost::_bi::ref_compare\fP (\fBT\fP \fBconst\fP &\fBa\fP, \fBT\fP \fBconst\fP &b, \fBlong\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBbool\fP \fBsc_boost::_bi::ref_compare\fP (\fBreference_wrapper\fP< \fBT\fP > \fBconst\fP &\fBa\fP, \fBreference_wrapper\fP< \fBT\fP > \fBconst\fP &b, int)"
.br
.ti -1c
.RI "template<\fBclass\fP F > F & \fBsc_boost::_bi::unwrap\fP (F *f, \fBlong\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP F > F & \fBsc_boost::_bi::unwrap\fP (\fBreference_wrapper\fP< F > *f, int)"
.br
.ti -1c
.RI "template<\fBclass\fP F > F & \fBsc_boost::_bi::unwrap\fP (\fBreference_wrapper\fP< F > \fBconst\fP *f, int)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fB_mfi::dm\fP< \fBR\fP, \fBT\fP > \fBsc_boost::_bi::unwrap\fP (\fBR\fP T::**\fBpm\fP, int)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fB_mfi::dm\fP< \fBR\fP, \fBT\fP > \fBsc_boost::_bi::unwrap\fP (\fBR\fP T::*\fBconst\fP *\fBpm\fP, int)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBL\fP > \fBbool\fP \fBsc_boost::_bi::function_equal\fP (\fBbind_t\fP< \fBR\fP, F, \fBL\fP > \fBconst\fP &\fBa\fP, \fBbind_t\fP< \fBR\fP, F, \fBL\fP > \fBconst\fP &b)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBL\fP > \fBbind_t\fP< \fBbool\fP, \fBlogical_not\fP, \fBlist1\fP< \fBbind_t\fP< \fBR\fP, F, \fBL\fP > > > \fBsc_boost::_bi::operator!\fP (\fBbind_t\fP< \fBR\fP, F, \fBL\fP > \fBconst\fP &f)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBV\fP , \fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_boost::visit_each\fP (\fBV\fP &v, \fB_bi::value\fP< \fBT\fP > \fBconst\fP &t, int)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBV\fP , \fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBL\fP > \fBvoid\fP \fBsc_boost::visit_each\fP (\fBV\fP &v, \fB_bi::bind_t\fP< \fBR\fP, F, \fBL\fP > \fBconst\fP &t, int)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F > \fB_bi::bind_t\fP< \fBR\fP, F, \fB_bi::list0\fP > \fBsc_boost::SC_BOOST_BIND\fP (F f)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_1\fP< \fBA1\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_2\fP< \fBA1\fP, \fBA2\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_3\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_5\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_6\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_7\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP, \fBA7\fP \fBa7\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_8\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP, \fBA8\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP, \fBA7\fP \fBa7\fP, \fBA8\fP \fBa8\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP , \fBclass\fP \fBA9\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_9\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP, \fBA8\fP, \fBA9\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP, \fBA7\fP \fBa7\fP, \fBA8\fP \fBa8\fP, \fBA9\fP \fBa9\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F > \fB_bi::bind_t\fP< \fBR\fP, F, \fB_bi::list0\fP > \fBsc_boost::SC_BOOST_BIND\fP (\fBsc_boost::type\fP< \fBR\fP >, F f)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_1\fP< \fBA1\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (\fBsc_boost::type\fP< \fBR\fP >, F f, \fBA1\fP a1)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_2\fP< \fBA1\fP, \fBA2\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (\fBsc_boost::type\fP< \fBR\fP >, F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_3\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (\fBsc_boost::type\fP< \fBR\fP >, F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (\fBsc_boost::type\fP< \fBR\fP >, F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_5\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (\fBsc_boost::type\fP< \fBR\fP >, F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_6\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (\fBsc_boost::type\fP< \fBR\fP >, F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_7\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (\fBsc_boost::type\fP< \fBR\fP >, F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP, \fBA7\fP \fBa7\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_8\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP, \fBA8\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (\fBsc_boost::type\fP< \fBR\fP >, F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP, \fBA7\fP \fBa7\fP, \fBA8\fP \fBa8\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP , \fBclass\fP \fBA9\fP > \fB_bi::bind_t\fP< \fBR\fP, F, \fBtypename\fP \fB_bi::list_av_9\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP, \fBA8\fP, \fBA9\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (\fBsc_boost::type\fP< \fBR\fP >, F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP, \fBA7\fP \fBa7\fP, \fBA8\fP \fBa8\fP, \fBA9\fP \fBa9\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP F > \fB_bi::bind_t\fP< \fB_bi::unspecified\fP, F, \fB_bi::list0\fP > \fBsc_boost::SC_BOOST_BIND\fP (F f)"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP > \fB_bi::bind_t\fP< \fB_bi::unspecified\fP, F, \fBtypename\fP \fB_bi::list_av_1\fP< \fBA1\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1)"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP > \fB_bi::bind_t\fP< \fB_bi::unspecified\fP, F, \fBtypename\fP \fB_bi::list_av_2\fP< \fBA1\fP, \fBA2\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP > \fB_bi::bind_t\fP< \fB_bi::unspecified\fP, F, \fBtypename\fP \fB_bi::list_av_3\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fB_bi::bind_t\fP< \fB_bi::unspecified\fP, F, \fBtypename\fP \fB_bi::list_av_4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP > \fB_bi::bind_t\fP< \fB_bi::unspecified\fP, F, \fBtypename\fP \fB_bi::list_av_5\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP > \fB_bi::bind_t\fP< \fB_bi::unspecified\fP, F, \fBtypename\fP \fB_bi::list_av_6\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP > \fB_bi::bind_t\fP< \fB_bi::unspecified\fP, F, \fBtypename\fP \fB_bi::list_av_7\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP, \fBA7\fP \fBa7\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP > \fB_bi::bind_t\fP< \fB_bi::unspecified\fP, F, \fBtypename\fP \fB_bi::list_av_8\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP, \fBA8\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP, \fBA7\fP \fBa7\fP, \fBA8\fP \fBa8\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP , \fBclass\fP \fBA9\fP > \fB_bi::bind_t\fP< \fB_bi::unspecified\fP, F, \fBtypename\fP \fB_bi::list_av_9\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP, \fBA8\fP, \fBA9\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (F f, \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP, \fBA7\fP \fBa7\fP, \fBA8\fP \fBa8\fP, \fBA9\fP \fBa9\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP , \fBclass\fP \fBA1\fP > \fB_bi::bind_t\fP< \fBR\fP, \fB_mfi::dm\fP< \fBR\fP, \fBT\fP >, \fBtypename\fP \fB_bi::list_av_1\fP< \fBA1\fP >::type > \fBsc_boost::SC_BOOST_BIND\fP (\fBR\fP T::*f, \fBA1\fP a1)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_BIND   bind"

.SS "#\fBdefine\fP SC_BOOST_BIND_CC"

.SS "#\fBdefine\fP SC_BOOST_BIND_MF_CC"

.SS "#\fBdefine\fP SC_BOOST_BIND_MF_NAME(X)   X"

.SS "#\fBdefine\fP SC_BOOST_BIND_OPERATOR(\fBop\fP, name)"
\fBValue:\fP.PP
.nf
\\
struct name \\
{ \\
    template<class V, class W> bool operator()(V const & v, W const & w) const { return v op w; } \\
}; \\
 \\
template<class R, class F, class L, class A2> \\
    bind_t< bool, name, list2< bind_t<R, F, L>, typename add_value<A2>::type > > \\
    operator op (bind_t<R, F, L> const & f, A2 a2) \\
{ \\
    typedef typename add_value<A2>::type B2; \\
    typedef list2< bind_t<R, F, L>, B2> list_type; \\
    return bind_t<bool, name, list_type> ( name(), list_type(f, a2) ); \\
}
.fi

.SS "#\fBdefine\fP SC_BOOST_BIND_RETURN   \fBreturn\fP"

.SS "#\fBdefine\fP SC_BOOST_BIND_ST"

.SS "#\fBdefine\fP SC_BOOST_BIND_VISIT_EACH   visit_each"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
