.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/bind/bind_cc.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/bind/bind_cc.hpp
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBclass\fP \fBR\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(), _bi::list0 > \fBSC_BOOST_BIND\fP (\fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *f)())"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP \fBA1\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1), \fBtypename\fP _bi::list_av_1< \fBA1\fP >::type > \fBSC_BOOST_BIND\fP (\fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *f)(B1), \fBA1\fP a1)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2), \fBtypename\fP _bi::list_av_2< \fBA1\fP, \fBA2\fP >::type > \fBSC_BOOST_BIND\fP (\fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *f)(B1, B2), \fBA1\fP a1, \fBA2\fP \fBa2\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3), \fBtypename\fP _bi::list_av_3< \fBA1\fP, \fBA2\fP, \fBA3\fP >::type > \fBSC_BOOST_BIND\fP (\fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *f)(B1, B2, B3), \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP B4 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3, B4), \fBtypename\fP _bi::list_av_4< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >::type > \fBSC_BOOST_BIND\fP (\fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *f)(B1, B2, B3, B4), \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP B4 , \fBclass\fP B5 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3, B4, B5), \fBtypename\fP _bi::list_av_5< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP >::type > \fBSC_BOOST_BIND\fP (\fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *f)(B1, B2, B3, B4, B5), \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP B4 , \fBclass\fP B5 , \fBclass\fP B6 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3, B4, B5, B6), \fBtypename\fP _bi::list_av_6< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP >::type > \fBSC_BOOST_BIND\fP (\fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *f)(B1, B2, B3, B4, B5, B6), \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP B4 , \fBclass\fP B5 , \fBclass\fP B6 , \fBclass\fP B7 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3, B4, B5, B6, B7), \fBtypename\fP _bi::list_av_7< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP >::type > \fBSC_BOOST_BIND\fP (\fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *f)(B1, B2, B3, B4, B5, B6, B7), \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP, \fBA7\fP \fBa7\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP B4 , \fBclass\fP B5 , \fBclass\fP B6 , \fBclass\fP B7 , \fBclass\fP B8 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3, B4, B5, B6, B7, B8), \fBtypename\fP _bi::list_av_8< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP, \fBA8\fP >::type > \fBSC_BOOST_BIND\fP (\fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *f)(B1, B2, B3, B4, B5, B6, B7, B8), \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP, \fBA7\fP \fBa7\fP, \fBA8\fP \fBa8\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP B4 , \fBclass\fP B5 , \fBclass\fP B6 , \fBclass\fP B7 , \fBclass\fP B8 , \fBclass\fP B9 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP , \fBclass\fP \fBA9\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3, B4, B5, B6, B7, B8, B9), \fBtypename\fP _bi::list_av_9< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP, \fBA8\fP, \fBA9\fP >::type > \fBSC_BOOST_BIND\fP (\fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *f)(B1, B2, B3, B4, B5, B6, B7, B8, B9), \fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP, \fBA5\fP \fBa5\fP, \fBA6\fP \fBa6\fP, \fBA7\fP \fBa7\fP, \fBA8\fP \fBa8\fP, \fBA9\fP \fBa9\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(), _bi::list0 > SC_BOOST_BIND (\fBSC_BOOST_BIND_ST\fP  RSC_BOOST_BIND_CC *f)()"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP \fBA1\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1), \fBtypename\fP _bi::list_av_1< \fBA1\fP >::type > SC_BOOST_BIND (\fBSC_BOOST_BIND_ST\fP  RSC_BOOST_BIND_CC *f)(B1, \fBA1\fP a1)"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2), \fBtypename\fP _bi::list_av_2< \fBA1\fP, \fBA2\fP >::type > SC_BOOST_BIND (\fBSC_BOOST_BIND_ST\fP  RSC_BOOST_BIND_CC *f)(B1, B2, \fBA1\fP a1, \fBA2\fP a2)"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3), \fBtypename\fP _bi::list_av_3< \fBA1\fP, \fBA2\fP, \fBA3\fP >::type > SC_BOOST_BIND (\fBSC_BOOST_BIND_ST\fP  RSC_BOOST_BIND_CC *f)(B1, B2, B3, \fBA1\fP a1, \fBA2\fP a2, \fBA3\fP a3)"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP B4 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3, B4), \fBtypename\fP _bi::list_av_4< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >::type > SC_BOOST_BIND (\fBSC_BOOST_BIND_ST\fP  RSC_BOOST_BIND_CC *f)(B1, B2, B3, B4, \fBA1\fP a1, \fBA2\fP a2, \fBA3\fP a3, \fBA4\fP a4)"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP B4 , \fBclass\fP B5 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3, B4, B5), \fBtypename\fP _bi::list_av_5< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP >::type > SC_BOOST_BIND (\fBSC_BOOST_BIND_ST\fP  RSC_BOOST_BIND_CC *f)(B1, B2, B3, B4, B5, \fBA1\fP a1, \fBA2\fP a2, \fBA3\fP a3, \fBA4\fP a4, \fBA5\fP a5)"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP B4 , \fBclass\fP B5 , \fBclass\fP B6 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3, B4, B5, B6), \fBtypename\fP _bi::list_av_6< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP >::type > SC_BOOST_BIND (\fBSC_BOOST_BIND_ST\fP  RSC_BOOST_BIND_CC *f)(B1, B2, B3, B4, B5, B6, \fBA1\fP a1, \fBA2\fP a2, \fBA3\fP a3, \fBA4\fP a4, \fBA5\fP a5, \fBA6\fP a6)"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP B4 , \fBclass\fP B5 , \fBclass\fP B6 , \fBclass\fP B7 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3, B4, B5, B6, B7), \fBtypename\fP _bi::list_av_7< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP >::type > SC_BOOST_BIND (\fBSC_BOOST_BIND_ST\fP  RSC_BOOST_BIND_CC *f)(B1, B2, B3, B4, B5, B6, B7, \fBA1\fP a1, \fBA2\fP a2, \fBA3\fP a3, \fBA4\fP a4, \fBA5\fP a5, \fBA6\fP a6, \fBA7\fP a7)"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP B4 , \fBclass\fP B5 , \fBclass\fP B6 , \fBclass\fP B7 , \fBclass\fP B8 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3, B4, B5, B6, B7, B8), \fBtypename\fP _bi::list_av_8< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP, \fBA8\fP >::type > SC_BOOST_BIND (\fBSC_BOOST_BIND_ST\fP  RSC_BOOST_BIND_CC *f)(B1, B2, B3, B4, B5, B6, B7, B8, \fBA1\fP a1, \fBA2\fP a2, \fBA3\fP a3, \fBA4\fP a4, \fBA5\fP a5, \fBA6\fP a6, \fBA7\fP a7, \fBA8\fP a8)"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP B1 , \fBclass\fP B2 , \fBclass\fP B3 , \fBclass\fP B4 , \fBclass\fP B5 , \fBclass\fP B6 , \fBclass\fP B7 , \fBclass\fP B8 , \fBclass\fP B9 , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP , \fBclass\fP \fBA9\fP > _bi::bind_t< \fBR\fP, \fBSC_BOOST_BIND_ST\fP \fBR\fP(\fBSC_BOOST_BIND_CC\fP *)(B1, B2, B3, B4, B5, B6, B7, B8, B9), \fBtypename\fP _bi::list_av_9< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP, \fBA5\fP, \fBA6\fP, \fBA7\fP, \fBA8\fP, \fBA9\fP >::type > SC_BOOST_BIND (\fBSC_BOOST_BIND_ST\fP  RSC_BOOST_BIND_CC *f)(B1, B2, B3, B4, B5, B6, B7, B8, B9, \fBA1\fP a1, \fBA2\fP a2, \fBA3\fP a3, \fBA4\fP a4, \fBA5\fP a5, \fBA6\fP a6, \fBA7\fP a7, \fBA8\fP a8, \fBA9\fP a9)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
