.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/bind/bind_template.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/bind/bind_template.hpp
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP result_traits< \fBR\fP, F >::type \fBresult_type\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBresult_type\fP \fBoperator()\fP ()"
.br
.ti -1c
.RI "template<\fBclass\fP \fBA1\fP > \fBresult_type\fP \fBoperator()\fP (\fBA1\fP &a1)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP > \fBresult_type\fP \fBoperator()\fP (\fBA1\fP &a1, \fBA2\fP &\fBa2\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP > \fBresult_type\fP \fBoperator()\fP (\fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBresult_type\fP \fBoperator()\fP (\fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP, \fBA4\fP &\fBa4\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP > \fBresult_type\fP \fBoperator()\fP (\fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP, \fBA4\fP &\fBa4\fP, \fBA5\fP &\fBa5\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP > \fBresult_type\fP \fBoperator()\fP (\fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP, \fBA4\fP &\fBa4\fP, \fBA5\fP &\fBa5\fP, \fBA6\fP &\fBa6\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP > \fBresult_type\fP \fBoperator()\fP (\fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP, \fBA4\fP &\fBa4\fP, \fBA5\fP &\fBa5\fP, \fBA6\fP &\fBa6\fP, \fBA7\fP &\fBa7\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP > \fBresult_type\fP \fBoperator()\fP (\fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP, \fBA4\fP &\fBa4\fP, \fBA5\fP &\fBa5\fP, \fBA6\fP &\fBa6\fP, \fBA7\fP &\fBa7\fP, \fBA8\fP &\fBa8\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP , \fBclass\fP \fBA9\fP > \fBresult_type\fP \fBoperator()\fP (\fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP, \fBA4\fP &\fBa4\fP, \fBA5\fP &\fBa5\fP, \fBA6\fP &\fBa6\fP, \fBA7\fP &\fBa7\fP, \fBA8\fP &\fBa8\fP, \fBA9\fP &\fBa9\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBA\fP > \fBresult_type\fP \fBeval\fP (\fBA\fP &\fBa\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBV\fP > \fBvoid\fP \fBaccept\fP (\fBV\fP &v) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBcompare\fP (this_type \fBconst\fP &\fBrhs\fP) \fBconst\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "F \fBf_\fP"
.br
.ti -1c
.RI "\fBL\fP \fBl_\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "\fBtypedef\fP result_traits<\fBR\fP,F>::type \fBresult_type\fP"

.SH "Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBV\fP > \fBvoid\fP accept (\fBV\fP & v) const"

.SS "\fBbool\fP compare (this_type \fBconst\fP & rhs) const"

.SS "template<\fBclass\fP \fBA\fP > \fBresult_type\fP eval (\fBA\fP & a)"

.SS "\fBresult_type\fP \fBoperator\fP() ()"

.SS "template<\fBclass\fP \fBA1\fP > \fBresult_type\fP \fBoperator\fP() (\fBA1\fP & a1)"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP > \fBresult_type\fP \fBoperator\fP() (\fBA1\fP & a1, \fBA2\fP & a2)"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP > \fBresult_type\fP \fBoperator\fP() (\fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3)"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBresult_type\fP \fBoperator\fP() (\fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3, \fBA4\fP & a4)"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP > \fBresult_type\fP \fBoperator\fP() (\fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3, \fBA4\fP & a4, \fBA5\fP & a5)"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP > \fBresult_type\fP \fBoperator\fP() (\fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3, \fBA4\fP & a4, \fBA5\fP & a5, \fBA6\fP & a6)"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP > \fBresult_type\fP \fBoperator\fP() (\fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3, \fBA4\fP & a4, \fBA5\fP & a5, \fBA6\fP & a6, \fBA7\fP & a7)"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP > \fBresult_type\fP \fBoperator\fP() (\fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3, \fBA4\fP & a4, \fBA5\fP & a5, \fBA6\fP & a6, \fBA7\fP & a7, \fBA8\fP & a8)"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP , \fBclass\fP \fBA9\fP > \fBresult_type\fP \fBoperator\fP() (\fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3, \fBA4\fP & a4, \fBA5\fP & a5, \fBA6\fP & a6, \fBA7\fP & a7, \fBA8\fP & a8, \fBA9\fP & a9)"

.SH "Variable Documentation"
.PP 
.SS "F f_\fR [private]\fP"

.SS "\fBL\fP l_\fR [private]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
