.TH "bool_< C_ >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bool_< C_ >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bool\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBintegral_c_tag\fP \fBtag\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBbool_\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBbool\fP \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSC_BOOST_STATIC_CONSTANT\fP (\fBbool\fP, \fBvalue\fP=\fBC_\fP)"
.br
.ti -1c
.RI "\fBoperator bool\fP () \fBconst\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBbool\fP C_> \fBtypedef\fP \fBintegral_c_tag\fP \fBbool_\fP< \fBC_\fP >::tag"

.SS "template<\fBbool\fP C_> \fBtypedef\fP \fBbool_\fP \fBbool_\fP< \fBC_\fP >::type"

.SS "template<\fBbool\fP C_> \fBtypedef\fP \fBbool\fP \fBbool_\fP< \fBC_\fP >::value_type"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBbool\fP C_> \fBbool_\fP< \fBC_\fP >\fB::operator\fP \fBbool\fP () const\fR [inline]\fP"

.SS "template<\fBbool\fP C_> \fBbool_\fP< \fBC_\fP >::SC_BOOST_STATIC_CONSTANT (\fBbool\fP, \fBvalue\fP = \fR\fBC_\fP\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
