.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/borland.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/borland.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <climits>\fP
.br
\fR#include <cwchar>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MEMBER_TEMPLATE_FRIENDS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_CV_SPECIALIZATIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_CV_VOID_SPECIALIZATIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_LIMITS_COMPILE_TIME_CONSTANTS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_DEDUCED_TYPENAME\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBWCHAR_MAX\fP   0xffff"
.br
.ti -1c
.RI "#\fBdefine\fP \fBWCHAR_MIN\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_SFINAE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INTEGRAL_INT64_T\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_DEPENDENT_NESTED_DERIVATIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_PRIVATE_IN_AGGREGATE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_USING_TEMPLATE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_BCB_PARTIAL_SPECIALIZATION_BUG\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_TEMPLATE_TEMPLATES\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_USING_DECLARATION_OVERLOADS_FROM_TYPENAME_BASE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MEMBER_TEMPLATE_FRIENDS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_LIMITS_COMPILE_TIME_CONSTANTS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_FUNCTION_SCOPE_USING_DECLARATION_BREAKS_ADL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_IS_ABSTRACT\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_EXCEPTIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_DIRENT_H\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_DECLSPEC\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_ABI_PREFIX\fP   'sysc/\fBpackages\fP/\fBboost\fP/\fBconfig\fP/\fBabi\fP/\fBborland_prefix\&.hpp'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_ABI_SUFFIX\fP   'sysc/\fBpackages\fP/\fBboost\fP/\fBconfig\fP/\fBabi\fP/\fBborland_suffix\&.hpp'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_COMPILER\fP   'Borland \fBC\fP++ \fBversion\fP ' SC_BOOST_STRINGIZE(\fB__BORLANDC__\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_ABI_PREFIX   'sysc/\fBpackages\fP/\fBboost\fP/\fBconfig\fP/\fBabi\fP/\fBborland_prefix\&.hpp'\fP"

.SS "#\fBdefine\fP SC_BOOST_ABI_SUFFIX   'sysc/\fBpackages\fP/\fBboost\fP/\fBconfig\fP/\fBabi\fP/\fBborland_suffix\&.hpp'\fP"

.SS "#\fBdefine\fP SC_BOOST_BCB_PARTIAL_SPECIALIZATION_BUG"

.SS "#\fBdefine\fP SC_BOOST_COMPILER   'Borland \fBC\fP++ \fBversion\fP ' SC_BOOST_STRINGIZE(\fB__BORLANDC__\fP)"

.SS "#\fBdefine\fP SC_BOOST_FUNCTION_SCOPE_USING_DECLARATION_BREAKS_ADL"

.SS "#\fBdefine\fP SC_BOOST_HAS_DECLSPEC"

.SS "#\fBdefine\fP SC_BOOST_HAS_DIRENT_H"

.SS "#\fBdefine\fP SC_BOOST_NO_CV_SPECIALIZATIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_CV_VOID_SPECIALIZATIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_DEDUCED_TYPENAME"

.SS "#\fBdefine\fP SC_BOOST_NO_DEPENDENT_NESTED_DERIVATIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_EXCEPTIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_INTEGRAL_INT64_T"

.SS "#\fBdefine\fP SC_BOOST_NO_IS_ABSTRACT"

.SS "#\fBdefine\fP SC_BOOST_NO_LIMITS_COMPILE_TIME_CONSTANTS"

.SS "#\fBdefine\fP SC_BOOST_NO_LIMITS_COMPILE_TIME_CONSTANTS"

.SS "#\fBdefine\fP SC_BOOST_NO_MEMBER_TEMPLATE_FRIENDS"

.SS "#\fBdefine\fP SC_BOOST_NO_MEMBER_TEMPLATE_FRIENDS"

.SS "#\fBdefine\fP SC_BOOST_NO_PRIVATE_IN_AGGREGATE"

.SS "#\fBdefine\fP SC_BOOST_NO_SFINAE"

.SS "#\fBdefine\fP SC_BOOST_NO_TEMPLATE_TEMPLATES"

.SS "#\fBdefine\fP SC_BOOST_NO_USING_DECLARATION_OVERLOADS_FROM_TYPENAME_BASE"

.SS "#\fBdefine\fP SC_BOOST_NO_USING_TEMPLATE"

.SS "#\fBdefine\fP WCHAR_MAX   0xffff"

.SS "#\fBdefine\fP WCHAR_MIN   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
