.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/common_edg.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/common_edg.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INTEGRAL_INT64_T\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_SFINAE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_VOID_RETURNS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_ARGUMENT_DEPENDENT_LOOKUP\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_TEMPLATE_TEMPLATES\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_IS_ABSTRACT\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_FUNCTION_SCOPE_USING_DECLARATION_BREAKS_ADL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_EXCEPTIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_LONG_LONG\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_FUNCTION_SCOPE_USING_DECLARATION_BREAKS_ADL"

.SS "#\fBdefine\fP SC_BOOST_HAS_LONG_LONG"

.SS "#\fBdefine\fP SC_BOOST_NO_ARGUMENT_DEPENDENT_LOOKUP"

.SS "#\fBdefine\fP SC_BOOST_NO_EXCEPTIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_INTEGRAL_INT64_T"

.SS "#\fBdefine\fP SC_BOOST_NO_IS_ABSTRACT"

.SS "#\fBdefine\fP SC_BOOST_NO_SFINAE"

.SS "#\fBdefine\fP SC_BOOST_NO_TEMPLATE_TEMPLATES"

.SS "#\fBdefine\fP SC_BOOST_NO_VOID_RETURNS"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
