.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/parser_linker/ComponentsStruct.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/parser_linker/ComponentsStruct.h
.SH SYNOPSIS
.br
.PP
\fR#include <QString>\fP
.br
\fR#include <QList>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBs_parse_error\fP"
.br
.ti -1c
.RI "struct \fBs_element_io\fP"
.br
.ti -1c
.RI "struct \fBs_sim_I_O\fP"
.br
.ti -1c
.RI "struct \fBs_sim_I_Os\fP"
.br
.ti -1c
.RI "struct \fBs_sim_wire\fP"
.br
.ti -1c
.RI "struct \fBs_sim_wires\fP"
.br
.ti -1c
.RI "struct \fBs_element\fP"
.br
.ti -1c
.RI "struct \fBs_elements\fP"
.br
.ti -1c
.RI "struct \fBs_components_list\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBenum\fP \fBI_O\fP \fBe_IO_type\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBI_O\fP { \fBINPUT\fP, \fBOUTPUT\fP, \fBUNDEFINED\fP }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBenum\fP \fBI_O\fP \fBe_IO_type\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "\fBenum\fP \fBI_O\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIINPUT \fP\fP
Input type\&. 
.TP
\fB\fIOUTPUT \fP\fP
Output type\&. 
.TP
\fB\fIUNDEFINED \fP\fP
Undefined type\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
