.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/compaq_cxx.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/compaq_cxx.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/packages/boost/config/compiler/common_edg\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_COMPILER\fP   'Dec \fBAlpha\fP \fBTrue64\fP ' SC_BOOST_STRINGIZE(\fB__DECCXX_VER\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_COMPILER   'Dec \fBAlpha\fP \fBTrue64\fP ' SC_BOOST_STRINGIZE(\fB__DECCXX_VER\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
