.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <sysc/packages/boost/config/select_compiler_config\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/config/select_stdlib_config\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/config/select_platform_config\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/config/suffix\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_USER_CONFIG\fP   <\fBsysc\fP/\fBpackages\fP/\fBboost\fP/\fBconfig\fP/\fBuser\&.hpp\fP>"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_USER_CONFIG   <\fBsysc\fP/\fBpackages\fP/\fBboost\fP/\fBconfig\fP/\fBuser\&.hpp\fP>"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
