.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_utils/convenience_socket_bases.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_utils/convenience_socket_bases.h
.SH SYNOPSIS
.br
.PP
\fR#include <sysc/kernel/sc_cmnhdr\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtlm_utils::convenience_socket_base\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::simple_socket_base\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::passthrough_socket_base\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::multi_socket_base\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::convenience_socket_cb_holder\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.ti -1c
.RI "namespace \fBtlm_utils\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBSC_API\fP \fBsc_core::sc_object\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
