.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/debugwindow.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/debugwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMouseEvent>\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QScrollBar>\fP
.br
\fC#include <QWidget>\fP
.br
\fC#include <QTextEdit>\fP
.br
\fC#include <QCheckBox>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QTextStream>\fP
.br
\fC#include <QAction>\fP
.br
\fC#include <QMutex>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDebugWindow\fP"
.br
.RI "The \fBDebugWindow\fP class provides a widget for displaying debug messages\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
