.TH "debug_object" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
debug_object
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_debug_object\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdebug_object\fP (\fBsc_object\fP *\fBo\fP)"
.br
.ti -1c
.RI "std::string \fBreport_value\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBisModule\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBisAdaptor\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBisPort\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBisSignal\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBisHierarchy\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBisTraceable\fP ()"
.br
.ti -1c
.RI "std::string \fBname\fP ()"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "enum \fBobj_kind_e\fP { \fBOBJ_KIND_ADAPTOR\fP = 0, \fBOBJ_KIND_MODULE\fP, \fBOBJ_KIND_CLOCK\fP, \fBOBJ_KIND_PORT\fP, \fBOBJ_KIND_SIGNAL\fP, \fBOBJ_KIND_OTHER\fP }"
.br
.ti -1c
.RI "\fBtypedef\fP \fBenum\fP \fBdebug_object::obj_kind_e\fP \fBobj_kind_t\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBsc_object\fP * \fBobj\fP"
.br
.ti -1c
.RI "\fBobj_kind_t\fP \fBsc_kind\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBenum\fP \fBdebug_object::obj_kind_e\fP \fBdebug_object::obj_kind_t\fP\fR [private]\fP"

.SH "Member Enumeration Documentation"
.PP 
.SS "\fBenum\fP \fBdebug_object::obj_kind_e\fP\fR [private]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOBJ_KIND_ADAPTOR \fP\fP
.TP
\fB\fIOBJ_KIND_MODULE \fP\fP
.TP
\fB\fIOBJ_KIND_CLOCK \fP\fP
.TP
\fB\fIOBJ_KIND_PORT \fP\fP
.TP
\fB\fIOBJ_KIND_SIGNAL \fP\fP
.TP
\fB\fIOBJ_KIND_OTHER \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "debug_object::debug_object (\fBsc_object\fP * o)"

.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP debug_object::isAdaptor ()\fR [inline]\fP"

.SS "\fBbool\fP debug_object::isHierarchy ()\fR [inline]\fP"

.SS "\fBbool\fP debug_object::isModule ()\fR [inline]\fP"

.SS "\fBbool\fP debug_object::isPort ()\fR [inline]\fP"

.SS "\fBbool\fP debug_object::isSignal ()\fR [inline]\fP"

.SS "\fBbool\fP debug_object::isTraceable ()\fR [inline]\fP"

.SS "std::string debug_object::name ()\fR [inline]\fP"

.SS "std::string debug_object::report_value ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_object\fP* debug_object::obj\fR [private]\fP"

.SS "\fBobj_kind_t\fP debug_object::sc_kind\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
