.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/stdlib/dinkumware.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/stdlib/dinkumware.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <utility>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_MSVC_STD_ITERATOR\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_ITERATOR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_TEMPLATED_ITERATOR_CONSTRUCTORS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_ALLOCATOR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STDC_NAMESPACE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_USE_FACET\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_OUTPUT_ITERATOR_ASSIGN\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_MACRO_USE_FACET\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_MIN_MAX\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MS_INT64_NUMERIC_LIMITS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_ITERATOR_TRAITS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_DINKUMWARE_STDLIB\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_STDLIB\fP   'Dinkumware \fBstandard\fP \fBlibrary\fP \fBversion\fP 1\&.\fBx'\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_DINKUMWARE_STDLIB   1"

.SS "#\fBdefine\fP SC_BOOST_HAS_MACRO_USE_FACET"

.SS "#\fBdefine\fP SC_BOOST_MSVC_STD_ITERATOR   1"

.SS "#\fBdefine\fP SC_BOOST_NO_MS_INT64_NUMERIC_LIMITS"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_ALLOCATOR"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_ITERATOR"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_ITERATOR_TRAITS"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_MIN_MAX"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_OUTPUT_ITERATOR_ASSIGN"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_USE_FACET"

.SS "#\fBdefine\fP SC_BOOST_NO_STDC_NAMESPACE"

.SS "#\fBdefine\fP SC_BOOST_NO_TEMPLATED_ITERATOR_CONSTRUCTORS"

.SS "#\fBdefine\fP SC_BOOST_STDLIB   'Dinkumware \fBstandard\fP \fBlibrary\fP \fBversion\fP 1\&.\fBx'\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
