.TH "ElementsDisplay" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ElementsDisplay
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <elementsdisplay\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBElementsDisplay\fP (\fBQTreeWidget\fP *\fBtreeWidget\fP, QWidget *\fBparent\fP=\fBnullptr\fP)"
.br
.ti -1c
.RI "\fB~ElementsDisplay\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBloadTree\fP (\fBconst\fP \fBs_components_list\fP &\fBcomponents\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBclearTree\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBaddStateIcon\fP (\fBQTreeWidgetItem\fP *\fBitem\fP, \fBbool\fP error)"
.br
.ti -1c
.RI "\fBvoid\fP \fBaddProperty\fP (\fBQTreeWidgetItem\fP *\fBparent\fP, \fBconst\fP \fBQString\fP &\fBproperty\fP, \fBconst\fP \fBQString\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpopulateTree\fP (\fBconst\fP \fBs_components_list\fP &\fBcomponents\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBaddElements\fP (\fBQTreeWidgetItem\fP *\fBparent\fP, \fBconst\fP \fBs_elements\fP &elements)"
.br
.ti -1c
.RI "\fBvoid\fP \fBidleUi\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBaddSimulationIOs\fP (\fBQTreeWidgetItem\fP *\fBparent\fP, \fBconst\fP \fBs_sim_I_Os\fP &\fBsimIOs\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBaddSimulationWires\fP (\fBQTreeWidgetItem\fP *\fBparent\fP, \fBconst\fP \fBs_sim_wires\fP &wires)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetTextColor\fP (\fBQTreeWidgetItem\fP *\fBitem\fP, \fBconst\fP \fBQColor\fP &\fBcolor\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBs_components_list\fP * \fBcomponents\fP"
.br
.ti -1c
.RI "\fBQVBoxLayout\fP * \fBmainLayout\fP"
.br
.ti -1c
.RI "\fBQTreeView\fP * \fBplace\fP"
.br
.ti -1c
.RI "\fBQTreeWidget\fP * \fBtreeWidget\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ElementsDisplay::ElementsDisplay (\fBQTreeWidget\fP * treeWidget, QWidget * parent = \fR\fBnullptr\fP\fP)\fR [explicit]\fP"

.SS "ElementsDisplay::~ElementsDisplay ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP ElementsDisplay::addElements (\fBQTreeWidgetItem\fP * parent, \fBconst\fP \fBs_elements\fP & elements)\fR [private]\fP"

.SS "\fBvoid\fP ElementsDisplay::addProperty (\fBQTreeWidgetItem\fP * parent, \fBconst\fP \fBQString\fP & property, \fBconst\fP \fBQString\fP & value)\fR [private]\fP"

.SS "\fBvoid\fP ElementsDisplay::addSimulationIOs (\fBQTreeWidgetItem\fP * parent, \fBconst\fP \fBs_sim_I_Os\fP & simIOs)\fR [private]\fP"

.SS "\fBvoid\fP ElementsDisplay::addSimulationWires (\fBQTreeWidgetItem\fP * parent, \fBconst\fP \fBs_sim_wires\fP & wires)\fR [private]\fP"

.SS "\fBvoid\fP ElementsDisplay::addStateIcon (\fBQTreeWidgetItem\fP * item, \fBbool\fP error)\fR [private]\fP"

.SS "\fBvoid\fP ElementsDisplay::clearTree ()"

.SS "\fBvoid\fP ElementsDisplay::idleUi ()\fR [private]\fP"

.SS "\fBvoid\fP ElementsDisplay::loadTree (\fBconst\fP \fBs_components_list\fP & components)"

.SS "\fBvoid\fP ElementsDisplay::populateTree (\fBconst\fP \fBs_components_list\fP & components)\fR [private]\fP"

.SS "\fBvoid\fP ElementsDisplay::setTextColor (\fBQTreeWidgetItem\fP * item, \fBconst\fP \fBQColor\fP & color)\fR [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBs_components_list\fP* ElementsDisplay::components\fR [private]\fP"

.SS "\fBQVBoxLayout\fP* ElementsDisplay::mainLayout\fR [private]\fP"

.SS "\fBQTreeView\fP* ElementsDisplay::place\fR [private]\fP"

.SS "\fBQTreeWidget\fP* ElementsDisplay::treeWidget\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
