.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/elementsdisplay.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/elementsdisplay.h
.SH SYNOPSIS
.br
.PP
\fR#include <QWidget>\fP
.br
\fR#include <QVBoxLayout>\fP
.br
\fR#include <QTreeWidget>\fP
.br
\fR#include <QTreeWidgetItem>\fP
.br
\fR#include 'ComponentsStruct\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementsDisplay\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
