.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/elementsdisplay.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/elementsdisplay.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QVBoxLayout>\fP
.br
\fC#include <QTreeWidget>\fP
.br
\fC#include <QTreeWidgetItem>\fP
.br
\fC#include 'ComponentsStruct\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBElementsDisplay\fP"
.br
.RI "A widget that displays parsed information from an SVG file in a tree structure\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
