.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/system/eventfilter.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/system/eventfilter.h
.SH SYNOPSIS
.br
.PP
\fR#include <QWidget>\fP
.br
\fR#include <QDebug>\fP
.br
\fR#include <QEvent>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEventFilter\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
