.TH "FilesTreeView" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FilesTreeView \- The \fBFilesTreeView\fP class provides functionality to manage files in a tree view\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <filestreeview\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBsearchFolder\fP ()"
.br
.RI "Slot to handle clicking on the folder button to search for a folder\&. "
.ti -1c
.RI "\fBvoid\fP \fBhandleFileDoubleClicked\fP (\fBconst\fP \fBQModelIndex\fP &\fBindex\fP)"
.br
.RI "Slot to handle double-clicking on a file in the tree view\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilesTreeView\fP (\fBQPushButton\fP *\fBfolderButton\fP, \fBQTreeView\fP *\fBtreeView\fP, \fBSvgHandler\fP *\fBsvgHandler\fP, \fBSimulationState\fP *\fBsimulationState\fP, QWidget *\fBparent\fP=\fBnullptr\fP)"
.br
.RI "Constructs a \fBFilesTreeView\fP object\&. "
.ti -1c
.RI "\fB~FilesTreeView\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBQPushButton\fP * \fBfolderButton\fP"
.br
.ti -1c
.RI "\fBQTreeView\fP * \fBtreeView\fP"
.br
.ti -1c
.RI "\fBSvgWidget\fP * \fBsvgWidget\fP"
.br
.ti -1c
.RI "\fBQFileSystemModel\fP * \fBfileSystemModel\fP"
.br
.ti -1c
.RI "\fBSimulationState\fP * \fBsimulationState\fP"
.br
.ti -1c
.RI "\fBSvgHandler\fP * \fBsvgHandler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBFilesTreeView\fP class provides functionality to manage files in a tree view\&. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FilesTreeView::FilesTreeView (\fBQPushButton\fP * folderButton, \fBQTreeView\fP * treeView, \fBSvgHandler\fP * svgHandler, \fBSimulationState\fP * simulationState, QWidget * parent = \fR\fBnullptr\fP\fP)\fR [explicit]\fP"

.PP
Constructs a \fBFilesTreeView\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIfolderButton\fP The QPushButton used to open a folder\&. 
.br
\fItreeView\fP The QTreeView for displaying files\&. 
.br
\fIsvgWidget\fP The \fBSvgWidget\fP for displaying SVG files\&. 
.br
\fIsimulationState\fP The \fBSimulationState\fP object for managing the state of the application\&. 
.br
\fIparent\fP The parent widget\&. 
.RE
.PP

.SS "FilesTreeView::~FilesTreeView ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP FilesTreeView::handleFileDoubleClicked (\fBconst\fP \fBQModelIndex\fP & index)\fR [slot]\fP"

.PP
Slot to handle double-clicking on a file in the tree view\&. 
.PP
\fBParameters\fP
.RS 4
\fIindex\fP The index of the double-clicked file\&. 
.RE
.PP

.SS "\fBvoid\fP FilesTreeView::searchFolder ()\fR [slot]\fP"

.PP
Slot to handle clicking on the folder button to search for a folder\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBQFileSystemModel\fP* FilesTreeView::fileSystemModel\fR [private]\fP"
The file model used by the TreeView 
.SS "\fBQPushButton\fP* FilesTreeView::folderButton\fR [private]\fP"
The QPushButton used to open a folder\&. 
.SS "\fBSimulationState\fP* FilesTreeView::simulationState\fR [private]\fP"
The \fBSimulationState\fP object for managing the state of the application 
.SS "\fBSvgHandler\fP* FilesTreeView::svgHandler\fR [private]\fP"
The SvgHandling object for handling SVG files 
.SS "\fBSvgWidget\fP* FilesTreeView::svgWidget\fR [private]\fP"
The \fBSvgWidget\fP for displaying SVG files\&. 
.SS "\fBQTreeView\fP* FilesTreeView::treeView\fR [private]\fP"
The QTreeView for displaying files\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
