.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/filestreeview.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/filestreeview.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'filestreeview\&.h'\fP
.br
\fC#include <QPushButton>\fP
.br
\fC#include <QFileDialog>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
