.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/filestreeview.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/filestreeview.h
.SH SYNOPSIS
.br
.PP
\fR#include <QWidget>\fP
.br
\fR#include <QPushButton>\fP
.br
\fR#include <QTreeView>\fP
.br
\fR#include <QFileSystemModel>\fP
.br
\fR#include 'svghandler\&.h'\fP
.br
\fR#include 'svgwidget\&.h'\fP
.br
\fR#include 'simulationstate\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFilesTreeView\fP"
.br
.RI "The \fBFilesTreeView\fP class provides functionality to manage files in a tree view\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
