.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/fx.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/fx.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/datatypes/fx/sc_fixed\&.h'\fP
.br
\fR#include 'sysc/datatypes/fx/sc_fxcast_switch\&.h'\fP
.br
\fR#include 'sysc/datatypes/fx/sc_fxtype_params\&.h'\fP
.br
\fR#include 'sysc/datatypes/fx/sc_ufixed\&.h'\fP
.br
\fR#include 'sysc/datatypes/fx/scfx_other_defs\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
