.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/get_pointer.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/get_pointer.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <memory>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_boost\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBT\fP * \fBsc_boost::get_pointer\fP (\fBT\fP *p)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBT\fP * \fBsc_boost::get_pointer\fP (std::auto_ptr< \fBT\fP > \fBconst\fP &p)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
