.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/hp_acc.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/hp_acc.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INTEGRAL_INT64_T\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_OPERATORS_IN_NAMESPACE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_LOCALE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STRINGSTREAM\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MEMBER_TEMPLATES\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_DEPENDENT_NESTED_DERIVATIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_USING_DECLARATION_OVERLOADS_FROM_TYPENAME_BASE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_UNREACHABLE_RETURN_DETECTION\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_TEMPLATE_TEMPLATES\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_SWPRINTF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_DEPENDENT_TYPES_IN_TEMPLATE_VALUE_PARAMETERS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_IS_ABSTRACT\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MEMBER_TEMPLATE_KEYWORD\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MEMBER_TEMPLATE_FRIENDS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_COMPILER\fP   'HP \fBaCC\fP \fBversion\fP ' SC_BOOST_STRINGIZE(\fB__HP_aCC\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_COMPILER   'HP \fBaCC\fP \fBversion\fP ' SC_BOOST_STRINGIZE(\fB__HP_aCC\fP)"

.SS "#\fBdefine\fP SC_BOOST_NO_DEPENDENT_NESTED_DERIVATIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_DEPENDENT_TYPES_IN_TEMPLATE_VALUE_PARAMETERS"

.SS "#\fBdefine\fP SC_BOOST_NO_INTEGRAL_INT64_T"

.SS "#\fBdefine\fP SC_BOOST_NO_IS_ABSTRACT"

.SS "#\fBdefine\fP SC_BOOST_NO_MEMBER_TEMPLATE_FRIENDS"

.SS "#\fBdefine\fP SC_BOOST_NO_MEMBER_TEMPLATE_KEYWORD"

.SS "#\fBdefine\fP SC_BOOST_NO_MEMBER_TEMPLATES"

.SS "#\fBdefine\fP SC_BOOST_NO_OPERATORS_IN_NAMESPACE"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_LOCALE"

.SS "#\fBdefine\fP SC_BOOST_NO_STRINGSTREAM"

.SS "#\fBdefine\fP SC_BOOST_NO_SWPRINTF"

.SS "#\fBdefine\fP SC_BOOST_NO_TEMPLATE_TEMPLATES"

.SS "#\fBdefine\fP SC_BOOST_NO_UNREACHABLE_RETURN_DETECTION"

.SS "#\fBdefine\fP SC_BOOST_NO_USING_DECLARATION_OVERLOADS_FROM_TYPENAME_BASE"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
