.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/platform/hpux.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/platform/hpux.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <sysc/packages/boost/config/posix_features\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_PLATFORM\fP   'HP\-\fBUX'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_SWPRINTF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_CWCTYPE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_UNISTD_H\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_GETTIMEOFDAY\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_SCHED_YIELD\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_PTHREAD_MUTEXATTR_SETTYPE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_NL_TYPES_H\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_NANOSLEEP\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_DIRENT_H\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_CLOCK_GETTIME\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_SIGACTION\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_HAS_CLOCK_GETTIME"

.SS "#\fBdefine\fP SC_BOOST_HAS_DIRENT_H"

.SS "#\fBdefine\fP SC_BOOST_HAS_GETTIMEOFDAY"

.SS "#\fBdefine\fP SC_BOOST_HAS_NANOSLEEP"

.SS "#\fBdefine\fP SC_BOOST_HAS_NL_TYPES_H"

.SS "#\fBdefine\fP SC_BOOST_HAS_PTHREAD_MUTEXATTR_SETTYPE"

.SS "#\fBdefine\fP SC_BOOST_HAS_SCHED_YIELD"

.SS "#\fBdefine\fP SC_BOOST_HAS_SIGACTION"

.SS "#\fBdefine\fP SC_BOOST_HAS_UNISTD_H"

.SS "#\fBdefine\fP SC_BOOST_NO_CWCTYPE"

.SS "#\fBdefine\fP SC_BOOST_NO_SWPRINTF"

.SS "#\fBdefine\fP SC_BOOST_PLATFORM   'HP\-\fBUX'\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
