.TH "integral_c_tag" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
integral_c_tag
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <integral_c_tag\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSC_BOOST_STATIC_CONSTANT\fP (int, \fBvalue\fP=0)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "integral_c_tag::SC_BOOST_STATIC_CONSTANT (int, \fBvalue\fP = \fR0\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
