.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/kai.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/kai.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/packages/boost/config/compiler/common_edg\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STDC_NAMESPACE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_EXCEPTIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_COMPILER\fP   'Kai \fBC\fP++ \fBversion\fP ' SC_BOOST_STRINGIZE(\fB__KCC_VERSION\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_COMPILER   'Kai \fBC\fP++ \fBversion\fP ' SC_BOOST_STRINGIZE(\fB__KCC_VERSION\fP)"

.SS "#\fBdefine\fP SC_BOOST_NO_EXCEPTIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_STDC_NAMESPACE"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
