.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/qt/md/ksr1.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/qt/md/ksr1.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_STKALIGN\fP   128"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_GROW_DOWN\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_STKBASE\fP   \fBQUICKTHREADS_STKALIGN\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VSTKBASE\fP   \fBQUICKTHREADS_STKBASE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ARGS_MD\fP(\fBsp\fP)   (\fBQUICKTHREADS_SPUT\fP (\fBsp\fP, 1, ((\fBqt_word_t\fP *)\fBqt_start\fP)[0]))"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ONLY_INDEX\fP   (5)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_USER_INDEX\fP   (4)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ARGT_INDEX\fP   (3)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ARGU_INDEX\fP   (2)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGS_DEFAULT\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGS\fP(\fBsp\fP,  \fBnb\fP,  \fBvargs\fP,  \fBpt\fP,  \fBstartup\fP,  \fBvuserf\fP,  \fBcleanup\fP)         (\fBqt_vargs\fP (\fBsp\fP, \fBnbytes\fP, &\fBvargs\fP, \fBpt\fP, \fBstartup\fP, \fBvuserf\fP, \fBcleanup\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGS_MD0\fP(\fBsp\fP,  \fBvabytes\fP)     ((\fBqt_t\fP *)(((\fBchar\fP *)(\fBsp\fP)) \- 4*8 \- \fBQUICKTHREADS_STKROUNDUP\fP(\fBvabytes\fP)))"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGS_MD1\fP(\fBsp\fP)   (\fBQUICKTHREADS_SPUT\fP (\fBsp\fP, 0, ((\fBqt_word_t\fP *)\fBqt_vstart\fP)[0]))"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VCLEANUP_INDEX\fP   (4)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VUSERF_INDEX\fP   (3)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VSTARTUP_INDEX\fP   (2)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGT_INDEX\fP   (1)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBunsigned\fP \fBlong\fP \fBqt_word_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBqt_start\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBqt_vstart\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP QUICKTHREADS_ARGS_MD(\fBsp\fP)   (\fBQUICKTHREADS_SPUT\fP (\fBsp\fP, 1, ((\fBqt_word_t\fP *)\fBqt_start\fP)[0]))"

.SS "#\fBdefine\fP QUICKTHREADS_ARGT_INDEX   (3)"

.SS "#\fBdefine\fP QUICKTHREADS_ARGU_INDEX   (2)"

.SS "#\fBdefine\fP QUICKTHREADS_GROW_DOWN"

.SS "#\fBdefine\fP QUICKTHREADS_ONLY_INDEX   (5)"

.SS "#\fBdefine\fP QUICKTHREADS_STKALIGN   128"

.SS "#\fBdefine\fP QUICKTHREADS_STKBASE   \fBQUICKTHREADS_STKALIGN\fP"

.SS "#\fBdefine\fP QUICKTHREADS_USER_INDEX   (4)"

.SS "#\fBdefine\fP QUICKTHREADS_VARGS(\fBsp\fP, \fBnb\fP, \fBvargs\fP, \fBpt\fP, \fBstartup\fP, \fBvuserf\fP, \fBcleanup\fP)         (\fBqt_vargs\fP (\fBsp\fP, \fBnbytes\fP, &\fBvargs\fP, \fBpt\fP, \fBstartup\fP, \fBvuserf\fP, \fBcleanup\fP))"

.SS "#\fBdefine\fP QUICKTHREADS_VARGS_DEFAULT"

.SS "#\fBdefine\fP QUICKTHREADS_VARGS_MD0(\fBsp\fP, \fBvabytes\fP)     ((\fBqt_t\fP *)(((\fBchar\fP *)(\fBsp\fP)) \- 4*8 \- \fBQUICKTHREADS_STKROUNDUP\fP(\fBvabytes\fP)))"

.SS "#\fBdefine\fP QUICKTHREADS_VARGS_MD1(\fBsp\fP)   (\fBQUICKTHREADS_SPUT\fP (\fBsp\fP, 0, ((\fBqt_word_t\fP *)\fBqt_vstart\fP)[0]))"

.SS "#\fBdefine\fP QUICKTHREADS_VARGT_INDEX   (1)"

.SS "#\fBdefine\fP QUICKTHREADS_VCLEANUP_INDEX   (4)"

.SS "#\fBdefine\fP QUICKTHREADS_VSTARTUP_INDEX   (2)"

.SS "#\fBdefine\fP QUICKTHREADS_VSTKBASE   \fBQUICKTHREADS_STKBASE\fP"

.SS "#\fBdefine\fP QUICKTHREADS_VUSERF_INDEX   (3)"

.SH "Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBunsigned\fP \fBlong\fP \fBqt_word_t\fP"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP qt_start (\fBvoid\fP)\fR [extern]\fP"

.SS "\fBvoid\fP qt_vstart (\fBvoid\fP)\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
