.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/stdlib/libstdcpp3.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/stdlib/libstdcpp3.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_STDLIB\fP   'GNU \fBlibstdc\fP++ \fBversion\fP ' SC_BOOST_STRINGIZE(\fB__GLIBCPP__\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_CWCHAR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_CWCTYPE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_WSTRING\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_WSTREAMBUF\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_NO_CWCHAR"

.SS "#\fBdefine\fP SC_BOOST_NO_CWCTYPE"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_WSTREAMBUF"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_WSTRING"

.SS "#\fBdefine\fP SC_BOOST_STDLIB   'GNU \fBlibstdc\fP++ \fBversion\fP ' SC_BOOST_STRINGIZE(\fB__GLIBCPP__\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
