.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/platform/linux.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/platform/linux.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <cstdlib>\fP
.br
\fR#include <sysc/packages/boost/config/posix_features\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_PLATFORM\fP   'linux'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_SWPRINTF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_UNISTD_H\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__extension__\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__const__\fP   \fBconst\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__volatile__\fP   \fBvolatile\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__signed__\fP   \fBsigned\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__typeof__\fP   \fBtypeof\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__inline__\fP   \fBinline\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP __const__   \fBconst\fP"

.SS "#\fBdefine\fP __extension__"

.SS "#\fBdefine\fP __inline__   \fBinline\fP"

.SS "#\fBdefine\fP __signed__   \fBsigned\fP"

.SS "#\fBdefine\fP __typeof__   \fBtypeof\fP"

.SS "#\fBdefine\fP __volatile__   \fBvolatile\fP"

.SS "#\fBdefine\fP SC_BOOST_HAS_UNISTD_H"

.SS "#\fBdefine\fP SC_BOOST_NO_SWPRINTF"

.SS "#\fBdefine\fP SC_BOOST_PLATFORM   'linux'"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
