.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/qt/md/m88k.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/qt/md/m88k.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_GROW_DOWN\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_STKALIGN\fP   (16)	/* \fBDoubleword\fP aligned\&. */"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_STKBASE\fP   (16*4 + 8*4)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VSTKBASE\fP   (8*4 + 8*4)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_1\fP   (8+2)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_14\fP   (8+3)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_15\fP   (8+4)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_16\fP   (8+5)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_17\fP   (8+6)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_30\fP   (8+15)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ARGS_MD\fP(\fBsp\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGS\fP(\fBsp\fP,  \fBnbytes\fP,  \fBvargs\fP,  \fBpt\fP,  \fBstartup\fP,  \fBvuserf\fP,  \fBcleanup\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ONLY_INDEX\fP   (\fBQUICKTHREADS_17\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_USER_INDEX\fP   (\fBQUICKTHREADS_16\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ARGT_INDEX\fP   (\fBQUICKTHREADS_15\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ARGU_INDEX\fP   (\fBQUICKTHREADS_14\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VCLEANUP_INDEX\fP   (\fBQUICKTHREADS_14\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VUSERF_INDEX\fP   (\fBQUICKTHREADS_16\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VSTARTUP_INDEX\fP   (\fBQUICKTHREADS_17\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGT_INDEX\fP   (\fBQUICKTHREADS_15\fP)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBunsigned\fP \fBlong\fP \fBqt_word_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBvoid\fP \fBqt_function_t\fP(\fBvoid\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBqt_start\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBstruct\fP \fBqt_t\fP * \fBqt_vargs\fP (\fBstruct\fP \fBqt_t\fP *\fBsp\fP, int \fBnbytes\fP, \fBvoid\fP *\fBvargs\fP, \fBvoid\fP *\fBpt\fP, \fBqt_function_t\fP *\fBstartup\fP, \fBqt_function_t\fP *\fBvuserf\fP, \fBqt_function_t\fP *\fBcleanup\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP QUICKTHREADS_1   (8+2)"

.SS "#\fBdefine\fP QUICKTHREADS_14   (8+3)"

.SS "#\fBdefine\fP QUICKTHREADS_15   (8+4)"

.SS "#\fBdefine\fP QUICKTHREADS_16   (8+5)"

.SS "#\fBdefine\fP QUICKTHREADS_17   (8+6)"

.SS "#\fBdefine\fP QUICKTHREADS_30   (8+15)"

.SS "#\fBdefine\fP QUICKTHREADS_ARGS_MD(\fBsp\fP)"
\fBValue:\fP.PP
.nf
  (QUICKTHREADS_SPUT (sp, QUICKTHREADS_1, qt_start), \\
   QUICKTHREADS_SPUT (sp, QUICKTHREADS_30, 0))
.fi

.SS "#\fBdefine\fP QUICKTHREADS_ARGT_INDEX   (\fBQUICKTHREADS_15\fP)"

.SS "#\fBdefine\fP QUICKTHREADS_ARGU_INDEX   (\fBQUICKTHREADS_14\fP)"

.SS "#\fBdefine\fP QUICKTHREADS_GROW_DOWN"

.SS "#\fBdefine\fP QUICKTHREADS_ONLY_INDEX   (\fBQUICKTHREADS_17\fP)"

.SS "#\fBdefine\fP QUICKTHREADS_STKALIGN   (16)	/* \fBDoubleword\fP aligned\&. */"

.SS "#\fBdefine\fP QUICKTHREADS_STKBASE   (16*4 + 8*4)"

.SS "#\fBdefine\fP QUICKTHREADS_USER_INDEX   (\fBQUICKTHREADS_16\fP)"

.SS "#\fBdefine\fP QUICKTHREADS_VARGS(\fBsp\fP, \fBnbytes\fP, \fBvargs\fP, \fBpt\fP, \fBstartup\fP, \fBvuserf\fP, \fBcleanup\fP)"
\fBValue:\fP.PP
.nf
  (qt_vargs (sp, nbytes, &(vargs), pt, (qt_function_t *)startup, \\
         (qt_function_t *)vuserf, (qt_function_t *)cleanup))
.fi

.SS "#\fBdefine\fP QUICKTHREADS_VARGT_INDEX   (\fBQUICKTHREADS_15\fP)"

.SS "#\fBdefine\fP QUICKTHREADS_VCLEANUP_INDEX   (\fBQUICKTHREADS_14\fP)"

.SS "#\fBdefine\fP QUICKTHREADS_VSTARTUP_INDEX   (\fBQUICKTHREADS_17\fP)"

.SS "#\fBdefine\fP QUICKTHREADS_VSTKBASE   (8*4 + 8*4)"

.SS "#\fBdefine\fP QUICKTHREADS_VUSERF_INDEX   (\fBQUICKTHREADS_16\fP)"

.SH "Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBvoid\fP qt_function_t(\fBvoid\fP)"

.SS "\fBtypedef\fP \fBunsigned\fP \fBlong\fP \fBqt_word_t\fP"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP qt_start (\fBvoid\fP)\fR [extern]\fP"

.SS "\fBstruct\fP \fBqt_t\fP * qt_vargs (\fBstruct\fP \fBqt_t\fP * sp, int nbytes, \fBvoid\fP * vargs, \fBvoid\fP * pt, \fBqt_function_t\fP * startup, \fBqt_function_t\fP * vuserf, \fBqt_function_t\fP * cleanup)\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
