.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/main.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/main.cpp \- Main entry point for the application\&.  

.SH SYNOPSIS
.br
.PP
\fR#include 'mainwindow\&.h'\fP
.br
\fR#include <QApplication>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBGRAPHICAL\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBmain\fP (\fBint\fP \fBargc\fP, \fBchar\fP *\fBargv\fP[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Main entry point for the application\&. 

This file is the main entry point for the application\&. It is responsible for launching the graphical interface which will then start the simulation\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP GRAPHICAL"

.SH "Function Documentation"
.PP 
.SS "\fBint\fP main (\fBint\fP argc, \fBchar\fP * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
