.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/old_ui_project/qt/mainwindow.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/old_ui_project/qt/mainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'mainwindow\&.h'\fP
.br
\fR#include 'qapplication\&.h'\fP
.br
\fR#include <QVBoxLayout>\fP
.br
\fR#include <QHBoxLayout>\fP
.br
\fR#include <QSplitter>\fP
.br
\fR#include <QPushButton>\fP
.br
\fR#include <systemc\&.h>\fP
.br
\fR#include <pthread\&.h>\fP
.br
\fR#include <QList>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include 'scqt_worker\&.h'\fP
.br
\fR#include <QEventLoop>\fP
.br
\fR#include <QTimer>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBdelay\fP (int \fBmillisecondsWait\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP delay (int millisecondsWait)\fR [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
