.TH "main.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <QCoreApplication>\fP
.br
\fR#include <QFile>\fP
.br
\fR#include <QXmlStreamReader>\fP
.br
\fR#include <QDebug>\fP
.br
\fR#include <QResource>\fP
.br
\fR#include <QtSvg>\fP
.br
\fR#include 'SystemcLinker\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int \fBargc\fP, \fBchar\fP *\fBargv\fP[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, \fBchar\fP * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
