.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/mainwindow.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/mainwindow.h
.SH SYNOPSIS
.br
.PP
\fC#include <QMainWindow>\fP
.br
\fC#include <QSvgWidget>\fP
.br
\fC#include <system/simulationmanager\&.h>\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include 'svgwidget\&.h'\fP
.br
\fC#include 'filestreeview\&.h'\fP
.br
\fC#include 'simulationstate\&.h'\fP
.br
\fC#include 'svghandler\&.h'\fP
.br
\fC#include 'debugwindow\&.h'\fP
.br
\fC#include 'multitypeschrono\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
