.TH "MainWindow" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mainwindow\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *\fBparent\fP=\fBnullptr\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBloadSvgFileFromPath\fP (\fBQString\fP \fBpath\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBshowDebugWindow\fP ()"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBon_stop_clicked\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_minus_clicked\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBcloseSvg\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBupdateStateLabel\fP (\fBSimulationState::State\fP state)"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_pushButton_clicked\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_pushButton_2_clicked\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBsetSplitterToLeft\fP (\fBQSplitter\fP *\fBsplitter\fP, \fBint\fP \fBleftSize\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBUi::MainWindow\fP * \fBui\fP"
.br
.ti -1c
.RI "\fBSvgWidget\fP * \fBsvgWidget\fP"
.br
.ti -1c
.RI "\fBFilesTreeView\fP * \fBfilesTreeView\fP"
.br
.ti -1c
.RI "\fBSimulationState\fP * \fBsimulationState\fP"
.br
.ti -1c
.RI "\fBQLabel\fP * \fBstateLabel\fP"
.br
.ti -1c
.RI "\fBSvgHandler\fP * \fBsvgHandler\fP"
.br
.ti -1c
.RI "\fBDebugWindow\fP * \fBdebugWindow\fP"
.br
.ti -1c
.RI "\fBElementsDisplay\fP * \fBelementsTreeView\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (QWidget * parent = \fR\fBnullptr\fP\fP)"

.SS "MainWindow::~MainWindow ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP MainWindow::closeSvg ()\fR [private]\fP, \fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::loadSvgFileFromPath (\fBQString\fP path)"

.SS "\fBvoid\fP MainWindow::on_minus_clicked ()\fR [private]\fP, \fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::on_pushButton_2_clicked ()\fR [private]\fP, \fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::on_pushButton_clicked ()\fR [private]\fP, \fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::on_stop_clicked ()\fR [private]\fP, \fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::setSplitterToLeft (\fBQSplitter\fP * splitter, \fBint\fP leftSize)\fR [private]\fP"

.SS "\fBvoid\fP MainWindow::showDebugWindow ()"

.SS "\fBvoid\fP MainWindow::updateStateLabel (\fBSimulationState::State\fP state)\fR [private]\fP, \fR [slot]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBDebugWindow\fP* MainWindow::debugWindow\fR [private]\fP"

.SS "\fBElementsDisplay\fP* MainWindow::elementsTreeView\fR [private]\fP"

.SS "\fBFilesTreeView\fP* MainWindow::filesTreeView\fR [private]\fP"

.SS "\fBSimulationState\fP* MainWindow::simulationState\fR [private]\fP"

.SS "\fBQLabel\fP* MainWindow::stateLabel\fR [private]\fP"

.SS "\fBSvgHandler\fP* MainWindow::svgHandler\fR [private]\fP"

.SS "\fBSvgWidget\fP* MainWindow::svgWidget\fR [private]\fP"

.SS "\fBUi::MainWindow\fP* MainWindow::ui\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
