.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/mainwindow.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/mainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'multitypeschrono\&.h'\fP
.br
\fC#include 'params\&.h'\fP
.br
\fC#include 'system/eventfilter\&.h'\fP
.br
\fC#include 'system/simulationmanager\&.h'\fP
.br
\fC#include <QThread>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
