.TH "MainWindow" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mainwindow\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBonMessage\fP (\fBQString\fP \fBconst\fP &\fBmsg_origin\fP, \fBQString\fP \fBconst\fP &\fBmsg_level\fP, \fBQString\fP \fBconst\fP &msg)"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_pushButton_3_clicked\fP (\fBbool\fP \fBchecked\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_pushButton_clicked\fP (\fBbool\fP \fBchecked\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_pushButton_2_clicked\fP (\fBbool\fP \fBchecked\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnewHierarchy\fP (\fBQStringList\fP \fBhier\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnewReport\fP (\fBQStringList\fP rep)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBMessage\fP (\fBQString\fP \fBconst\fP &\fBmsg_origin\fP, \fBQString\fP \fBconst\fP &\fBmsg_level\fP, \fBQString\fP \fBconst\fP &msg)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetNewState\fP (int \fBnewState\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBrequestHierarchy\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBrequestReport\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetTraceList\fP (\fBQStringList\fP \fBtl\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBgetItem\fP ()"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBgetItem1\fP ()"
.br
.ti -1c
.RI "\fBUi::MainWindow\fP * \fBgetUi\fP ()"
.br
.ti -1c
.RI "\fBMainWindow\fP (\fBQWidget\fP *parent=\fBnullptr\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBRefresh\fP ()"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBon_checkBox_clicked\fP (\fBbool\fP \fBchecked\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_actionExit_triggered\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_actionOpen_source_triggered\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fB_sendMessage\fP (\fBQString\fP \fBconst\fP &\fBmsg_level\fP, \fBQString\fP \fBconst\fP &msg)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetupUi\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetupSim\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "QThread * \fBm_scqtThread\fP"
.br
.ti -1c
.RI "\fBscQtWorker\fP * \fBm_scqtWorker\fP"
.br
.ti -1c
.RI "\fBsc_thread_config_t\fP \fBm_ConfigParams\fP"
.br
.ti -1c
.RI "\fBUi::MainWindow\fP * \fBui\fP"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBitem\fP"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBitem1\fP"
.br
.ti -1c
.RI "\fBSVG_Viewer\fP * \fBSVGs\fP"
.br
.ti -1c
.RI "\fBQFileDialog\fP \fBWinSelectFile\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (\fBQWidget\fP * parent = \fR\fBnullptr\fP\fP)"

.SS "MainWindow::~MainWindow ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP MainWindow::_sendMessage (\fBQString\fP \fBconst\fP & msg_level, \fBQString\fP \fBconst\fP & msg)\fR [private]\fP"

.SS "\fBQGraphicsSvgItem\fP * MainWindow::getItem ()"

.SS "\fBQGraphicsSvgItem\fP * MainWindow::getItem1 ()"

.SS "\fBUi::MainWindow\fP * MainWindow::getUi ()"

.SS "\fBvoid\fP MainWindow::Message (\fBQString\fP \fBconst\fP & msg_origin, \fBQString\fP \fBconst\fP & msg_level, \fBQString\fP \fBconst\fP & msg)\fR [signal]\fP"

.SS "\fBvoid\fP MainWindow::newHierarchy (\fBQStringList\fP hier)\fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::newReport (\fBQStringList\fP rep)\fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::on_actionExit_triggered ()\fR [private]\fP, \fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::on_actionOpen_source_triggered ()\fR [private]\fP, \fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::on_checkBox_clicked (\fBbool\fP checked)\fR [private]\fP, \fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::on_pushButton_2_clicked (\fBbool\fP checked = \fR\fBfalse\fP\fP)\fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::on_pushButton_3_clicked (\fBbool\fP checked)\fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::on_pushButton_clicked (\fBbool\fP checked)\fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::onMessage (\fBQString\fP \fBconst\fP & msg_origin, \fBQString\fP \fBconst\fP & msg_level, \fBQString\fP \fBconst\fP & msg)\fR [slot]\fP"

.SS "\fBvoid\fP MainWindow::Refresh ()"

.SS "\fBvoid\fP MainWindow::requestHierarchy ()\fR [signal]\fP"

.SS "\fBvoid\fP MainWindow::requestReport ()\fR [signal]\fP"

.SS "\fBvoid\fP MainWindow::setNewState (int newState)\fR [signal]\fP"

.SS "\fBvoid\fP MainWindow::setTraceList (\fBQStringList\fP tl)\fR [signal]\fP"

.SS "\fBvoid\fP MainWindow::setupSim ()\fR [private]\fP"

.SS "\fBvoid\fP MainWindow::setupUi ()\fR [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBQGraphicsSvgItem\fP* MainWindow::item\fR [private]\fP"

.SS "\fBQGraphicsSvgItem\fP* MainWindow::item1\fR [private]\fP"

.SS "\fBsc_thread_config_t\fP MainWindow::m_ConfigParams\fR [private]\fP"

.SS "QThread* MainWindow::m_scqtThread\fR [private]\fP"

.SS "\fBscQtWorker\fP* MainWindow::m_scqtWorker\fR [private]\fP"

.SS "\fBSVG_Viewer\fP* MainWindow::SVGs\fR [private]\fP"

.SS "\fBUi::MainWindow\fP* MainWindow::ui\fR [private]\fP"

.SS "\fBQFileDialog\fP MainWindow::WinSelectFile\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
