.TH "MainWindow" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mainwindow\&.h>\fP
.PP
Inherits QMainWindow\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMainWindow\fP (QWidget *\fBparent\fP=\fBnullptr\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBloadSvgFileFromPath\fP (\fBQString\fP \fBpath\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBshowDebugWindow\fP ()"
.br
.ti -1c
.RI "\fB~MainWindow\fP ()"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBcloseSvg\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBloadNormal_clicked\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBloadError_clicked\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_pushButton_clicked\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBsetSplitterToLeft\fP (\fBQSplitter\fP *\fBsplitter\fP, \fBint\fP \fBleftSize\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBupdateGui\fP (\fBconst\fP \fBQString\fP &\fBmessage\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBstartSimulation\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBstopSimulation\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "Ui::MainWindow * \fBui\fP"
.br
.ti -1c
.RI "\fBSvgWidget\fP * \fBsvgWidget\fP"
.br
.ti -1c
.RI "\fBFilesTreeView\fP * \fBfilesTreeView\fP"
.br
.ti -1c
.RI "\fBSimulationState\fP * \fBstate\fP"
.br
.ti -1c
.RI "\fBQLabel\fP * \fBstateLabel\fP"
.br
.ti -1c
.RI "\fBSvgHandler\fP * \fBsvgHandler\fP"
.br
.ti -1c
.RI "\fBDebugWindow\fP * \fBdebugWindow\fP"
.br
.ti -1c
.RI "\fBMultiTypesChrono\fP * \fBchronoWidgetSine\fP"
.br
.ti -1c
.RI "\fBMultiTypesChrono\fP * \fBchronoWidgetRamp\fP"
.br
.ti -1c
.RI "\fBMultiTypesChrono\fP * \fBchronoWidgetBool\fP"
.br
.ti -1c
.RI "\fBMultiTypesChrono\fP * \fBchronoWidgetSum\fP"
.br
.ti -1c
.RI "\fBSimulationManager\fP * \fBsimManager\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MainWindow::MainWindow (QWidget * parent = \fC\fBnullptr\fP\fP)"

.SS "MainWindow::~MainWindow ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP MainWindow::closeSvg ()\fC [private]\fP, \fC [slot]\fP"

.SS "\fBvoid\fP MainWindow::loadError_clicked ()\fC [private]\fP, \fC [slot]\fP"

.SS "\fBvoid\fP MainWindow::loadNormal_clicked ()\fC [private]\fP, \fC [slot]\fP"

.SS "\fBvoid\fP MainWindow::loadSvgFileFromPath (\fBQString\fP path)"

.SS "\fBvoid\fP MainWindow::on_pushButton_clicked ()\fC [private]\fP, \fC [slot]\fP"

.SS "\fBvoid\fP MainWindow::setSplitterToLeft (\fBQSplitter\fP * splitter, \fBint\fP leftSize)\fC [private]\fP"

.SS "\fBvoid\fP MainWindow::showDebugWindow ()"

.SS "\fBvoid\fP MainWindow::startSimulation ()\fC [private]\fP"

.SS "\fBvoid\fP MainWindow::stopSimulation ()\fC [private]\fP"

.SS "\fBvoid\fP MainWindow::updateGui (\fBconst\fP \fBQString\fP & message)\fC [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBMultiTypesChrono\fP* MainWindow::chronoWidgetBool\fC [private]\fP"

.SS "\fBMultiTypesChrono\fP* MainWindow::chronoWidgetRamp\fC [private]\fP"

.SS "\fBMultiTypesChrono\fP* MainWindow::chronoWidgetSine\fC [private]\fP"

.SS "\fBMultiTypesChrono\fP* MainWindow::chronoWidgetSum\fC [private]\fP"

.SS "\fBDebugWindow\fP* MainWindow::debugWindow\fC [private]\fP"

.SS "\fBFilesTreeView\fP* MainWindow::filesTreeView\fC [private]\fP"

.SS "\fBSimulationManager\fP* MainWindow::simManager\fC [private]\fP"

.SS "\fBSimulationState\fP* MainWindow::state\fC [private]\fP"

.SS "\fBQLabel\fP* MainWindow::stateLabel\fC [private]\fP"

.SS "\fBSvgHandler\fP* MainWindow::svgHandler\fC [private]\fP"

.SS "\fBSvgWidget\fP* MainWindow::svgWidget\fC [private]\fP"

.SS "Ui::MainWindow* MainWindow::ui\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
