.TH "md__c_1_2_users_2_b_j_r_o_d_i_e_r_2_documents_2_q_t___r_e_p_o_2_q_t___v_h_d_l__simulator_2code_2_qt___v_h_d_l___s_v_g__proj_2_t_o_d_os" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c_1_2_users_2_b_j_r_o_d_i_e_r_2_documents_2_q_t___r_e_p_o_2_q_t___v_h_d_l__simulator_2code_2_qt___v_h_d_l___s_v_g__proj_2_t_o_d_os \- TODOs 
.PP

.IP "\(bu" 2
Rename sys c modules class 
.PP

