.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/metrowerks.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/metrowerks.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_FUNCTION_TEMPLATE_ORDERING\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_POINTER_TO_MEMBER_CONST\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_DEPENDENT_TYPES_IN_TEMPLATE_VALUE_PARAMETERS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MEMBER_TEMPLATE_KEYWORD\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MEMBER_FUNCTION_SPECIALIZATIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_UNREACHABLE_RETURN_DETECTION\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_SFINAE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MEMBER_TEMPLATE_FRIENDS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_IS_ABSTRACT\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INTRINSIC_WCHAR_T\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_EXCEPTIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_COMPILER_VERSION\fP   \fB__MWERKS__\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_COMPILER\fP   'Metrowerks \fBCodeWarrior\fP \fBC\fP++ \fBversion\fP ' SC_BOOST_STRINGIZE(\fBSC_BOOST_COMPILER_VERSION\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_COMPILER   'Metrowerks \fBCodeWarrior\fP \fBC\fP++ \fBversion\fP ' SC_BOOST_STRINGIZE(\fBSC_BOOST_COMPILER_VERSION\fP)"

.SS "#\fBdefine\fP SC_BOOST_COMPILER_VERSION   \fB__MWERKS__\fP"

.SS "#\fBdefine\fP SC_BOOST_NO_DEPENDENT_TYPES_IN_TEMPLATE_VALUE_PARAMETERS"

.SS "#\fBdefine\fP SC_BOOST_NO_EXCEPTIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_FUNCTION_TEMPLATE_ORDERING"

.SS "#\fBdefine\fP SC_BOOST_NO_INTRINSIC_WCHAR_T"

.SS "#\fBdefine\fP SC_BOOST_NO_IS_ABSTRACT"

.SS "#\fBdefine\fP SC_BOOST_NO_MEMBER_FUNCTION_SPECIALIZATIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_MEMBER_TEMPLATE_FRIENDS"

.SS "#\fBdefine\fP SC_BOOST_NO_MEMBER_TEMPLATE_KEYWORD"

.SS "#\fBdefine\fP SC_BOOST_NO_POINTER_TO_MEMBER_CONST"

.SS "#\fBdefine\fP SC_BOOST_NO_SFINAE"

.SS "#\fBdefine\fP SC_BOOST_NO_UNREACHABLE_RETURN_DETECTION"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
