.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/build/debug/moc_predefs.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/build/debug/moc_predefs.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_MIN_EXP__\fP   (\-1021)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_attributes\fP   200809\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_nontype_template_parameter_auto\fP   201606\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_LEAST16_MAX__\fP   0xffff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__ATOMIC_ACQUIRE\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_MAX_10_EXP__\fP   4932"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_MIN__\fP   1\&.17549435082228750796873653722224568\fBe\fP\-38\fBF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_IEC_559_COMPLEX\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_aggregate_nsdmi\fP   201304\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_LEAST8_TYPE__\fP   \fBunsigned\fP \fBchar\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_FLOAT80__\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INTMAX_C\fP(\fBc\fP)   \fBc\fP ## \fBLL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__CHAR_BIT__\fP   8"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__MINGW32__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT8_MAX__\fP   0xff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SCHAR_WIDTH__\fP   8"
.br
.ti -1c
.RI "#\fBdefine\fP \fB_WIN64\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WINT_MAX__\fP   0xffff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_MIN_EXP__\fP   (\-125)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_static_assert\fP   201411\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__ORDER_LITTLE_ENDIAN__\fP   1234"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZE_MAX__\fP   0xffffffffffffffffULL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WCHAR_MAX__\fP   0xffff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_HAVE_SYNC_COMPARE_AND_SWAP_1\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_HAVE_SYNC_COMPARE_AND_SWAP_2\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_HAVE_SYNC_COMPARE_AND_SWAP_4\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_DENORM_MIN__\fP   \fBdouble\fP(4\&.94065645841246544176568792868221372\fBe\fP\-324\fBL\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_HAVE_SYNC_COMPARE_AND_SWAP_8\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_ATOMIC_CHAR_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_IEC_559\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_DECIMAL_DIG__\fP   17"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_EVAL_METHOD__\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_binary_literals\fP   201304\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_DECIMAL_DIG__\fP   17"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_noexcept_function_type\fP   201510L"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_ATOMIC_CHAR32_T_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_variadic_templates\fP   200704\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_FAST64_MAX__\fP   0xffffffffffffffffULL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIG_ATOMIC_TYPE__\fP   \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_MIN_10_EXP__\fP   (\-307)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FINITE_MATH_ONLY__\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_variable_templates\fP   201304\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_MAX_EXP__\fP   1024"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_FAST8_MAX__\fP   0xff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_rvalue_reference\fP   200610L"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_nested_namespace_definitions\fP   201411\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB_stdcall\fP   \fB__attribute__\fP((\fB__stdcall__\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC64_MAX_EXP__\fP   385"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT8_C\fP(\fBc\fP)   \fBc\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_LEAST8_WIDTH__\fP   8"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_variadic_using\fP   201611\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_LEAST64_MAX__\fP   0xffffffffffffffffULL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_LEAST8_MAX__\fP   0x7f"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_capture_star_this\fP   201603\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SHRT_MAX__\fP   0x7fff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_MAX__\fP   1\&.18973149535723176502126385303097021\fBe\fP+4932\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_MAX_10_EXP__\fP   4932"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_if_constexpr\fP   201606\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_IS_IEC_60559__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_LEAST8_MAX__\fP   0xff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_ATOMIC_BOOL_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_DENORM_MIN__\fP   6\&.47517511943802511092443895822764655\fBe\fP\-4966\fBF128\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINTMAX_TYPE__\fP   \fBlong\fP \fBlong\fP \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC32_EPSILON__\fP   1\fBE\fP\-6\fBDF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_EVAL_METHOD_TS_18661_3__\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT32_MAX__\fP   0xffffffffU"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GXX_EXPERIMENTAL_CXX0X__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_MIN_EXP__\fP   (\-16381)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WINT_MIN__\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_MIN_10_EXP__\fP   (\-4931)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_IS_IEC_60559__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_LEAST16_WIDTH__\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SCHAR_MAX__\fP   0x7f"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_MANT_DIG__\fP   113"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WCHAR_MIN__\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT64_C\fP(\fBc\fP)   \fBc\fP ## \fBLL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_ATOMIC_POINTER_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_MANT_DIG__\fP   53"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_ATOMIC_CHAR16_T_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_aligned_new\fP   201606\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__USER_LABEL_PREFIX__\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_MAX_10_EXP__\fP   38"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_EPSILON__\fP   1\&.08420217248550443400745280086994171\fBe\fP\-19\fBF64x\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__STDC_HOSTED__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC64_MIN_EXP__\fP   (\-382)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WIN64\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_decltype_auto\fP   201304\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_DIG__\fP   15"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_DIG__\fP   6"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_EPSILON__\fP   1\&.19209289550781250000000000000000000e\-7\fBF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GXX_WEAK__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SHRT_WIDTH__\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_IS_IEC_60559__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_MIN__\fP   3\&.36210314311209350626267781732175260e\-4932\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_IS_IEC_60559__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC32_MAX__\fP   9\&.999999\fBE96DF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_threadsafe_static_init\fP   200806\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_enumerator_attributes\fP   201411\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_DENORM_MIN__\fP   3\&.64519953188247460252840593361941982\fBe\fP\-4951\fBF64x\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT32_MAX__\fP   0x7fffffff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_WIDTH__\fP   32"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_LONG__\fP   4"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT16_C\fP(\fBc\fP)   \fBc\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DECIMAL_DIG__\fP   21"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_EPSILON__\fP   2\&.22044604925031308084726333618164062\fBe\fP\-16\fBF64\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT16_MAX__\fP   0x7fff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_MIN_EXP__\fP   (\-1021)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_MIN_10_EXP__\fP   (\-4931)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_MANT_DIG__\fP   53"
.br
.ti -1c
.RI "#\fBdefine\fP \fB_REENTRANT\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_MANT_DIG__\fP   64"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GNUC__\fP   11"
.br
.ti -1c
.RI "#\fBdefine\fP \fB_cdecl\fP   \fB__attribute__\fP((\fB__cdecl__\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GXX_RTTI\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__MMX__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_LONG_DOUBLE__\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__BIGGEST_ALIGNMENT__\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__STDC_UTF_16__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_MAX_10_EXP__\fP   308"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_delegating_constructors\fP   200604\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_MAX__\fP   \fBdouble\fP(1\&.79769313486231570814527423731704357\fBe\fP+308\fBL\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB_thiscall\fP   \fB__attribute__\fP((\fB__thiscall__\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_raw_strings\fP   200710L"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_FAST32_MAX__\fP   0x7fffffff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WINNT\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_FLOAT__\fP   4"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WINNT__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__HAVE_SPECULATION_SAFE_VALUE\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_fold_expressions\fP   201603\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC32_MIN_EXP__\fP   (\-94)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INTPTR_WIDTH__\fP   64"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_LEAST32_MAX__\fP   0xffffffffU"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_FAST16_TYPE__\fP   \fBshort\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__MMX_WITH_SSE__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB_fastcall\fP   \fB__attribute__\fP((\fB__fastcall__\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cplusplus\fP   201703\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_ref_qualifiers\fP   200710L"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC32_MIN__\fP   1\fBE\fP\-95\fBDF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEPRECATED\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_rvalue_references\fP   200610L"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_MAX_EXP__\fP   1024"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WCHAR_WIDTH__\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_MAX__\fP   3\&.40282346638528859811704183484516925\fBe\fP+38\fBF32\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC128_EPSILON__\fP   1\fBE\fP\-33\fBDL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SSE2_MATH__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__ATOMIC_HLE_RELEASE\fP   131072"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WIN32__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__PTRDIFF_MAX__\fP   0x7fffffffffffffffLL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__amd64\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__tune_core2__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__ATOMIC_HLE_ACQUIRE\fP   65536"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GNUG__\fP   11"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LONG_LONG_MAX__\fP   0x7fffffffffffffffLL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_SIZE_T__\fP   8"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_nsdmi\fP   200809\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_MIN_EXP__\fP   (\-16381)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_WINT_T__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LONG_LONG_WIDTH__\fP   64"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_initializer_lists\fP   200806\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_MAX_EXP__\fP   128"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_hex_float\fP   201603\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GXX_ABI_VERSION\fP   1016"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_MIN_EXP__\fP   (\-125)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_HAVE_DWARF2_CFI_ASM\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__x86_64\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_lambdas\fP   200907\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_FAST64_TYPE__\fP   \fBlong\fP \fBlong\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_DENORM_MIN__\fP   4\&.94065645841246544176568792868221372\fBe\fP\-324\fBF64\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_template_auto\fP   201606\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_MIN__\fP   \fBdouble\fP(2\&.22507385850720138309023271733240406\fBe\fP\-308\fBL\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_EPSILON__\fP   1\&.92592994438723585305597794258492732\fBe\fP\-34\fBF128\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_NORM_MAX__\fP   1\&.18973149535723176502126385303097021\fBe\fP+4932\fBF64x\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_POINTER__\fP   8"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZE_TYPE__\fP   \fBlong\fP \fBlong\fP \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_EPSILON__\fP   2\&.22044604925031308084726333618164062\fBe\fP\-16\fBF32x\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DECIMAL_BID_FORMAT__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GXX_TYPEINFO_EQUALITY_INLINE\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_MIN_10_EXP__\fP   (\-307)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_DECIMAL_DIG__\fP   21"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC128_MIN__\fP   1\fBE\fP\-6143\fBDL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__REGISTER_PREFIX__\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT16_MAX__\fP   0xffff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cdecl\fP   \fB__attribute__\fP((\fB__cdecl__\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_MIN__\fP   1\&.17549435082228750796873653722224568\fBe\fP\-38\fBF32\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT8_TYPE__\fP   \fBunsigned\fP \fBchar\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_DIG__\fP   6"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__NO_INLINE__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC_EVAL_METHOD__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC128_MAX__\fP   9\&.999999999999999999999999999999999\fBE6144DL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_MANT_DIG__\fP   24"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_DECIMAL_DIG__\fP   21"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__VERSION__\fP   '11\&.2\&.0'"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT64_C\fP(\fBc\fP)   \fBc\fP ## \fBULL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_unicode_characters\fP   201411\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB_WIN32\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SEH__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_LEAST32_MAX__\fP   0x7fffffff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_ATOMIC_INT_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_MAX_EXP__\fP   16384"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_MANT_DIG__\fP   24"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLOAT_WORD_ORDER__\fP   \fB__ORDER_LITTLE_ENDIAN__\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_aggregate_bases\fP   201603\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_DECIMAL_DIG__\fP   9"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_DIG__\fP   33"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT32_C\fP(\fBc\fP)   \fBc\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC64_EPSILON__\fP   1\fBE\fP\-15\fBDD\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__ORDER_PDP_ENDIAN__\fP   3412"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC128_MIN_EXP__\fP   (\-6142)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_FAST32_TYPE__\fP   \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_LEAST16_TYPE__\fP   \fBshort\fP \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_rtti\fP   199711\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT64_MAX__\fP   0xffffffffffffffffULL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_IS_IEC_60559__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GNUC_WIDE_EXECUTION_CHARSET_NAME\fP   'UTF\-16\fBLE'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_DIG__\fP   18"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT8_TYPE__\fP   \fBsigned\fP \fBchar\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_digit_separators\fP   201309\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_ASM_FLAG_OUTPUTS__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT32_TYPE__\fP   \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_RADIX__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_LEAST16_TYPE__\fP   \fBshort\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_EPSILON__\fP   1\&.08420217248550443400745280086994171\fBe\fP\-19\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINTMAX_C\fP(\fBc\fP)   \fBc\fP ## \fBULL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GLIBCXX_BITSIZE_INT_N_0\fP   128"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_MIN__\fP   2\&.22507385850720138309023271733240406\fBe\fP\-308\fBF32x\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIG_ATOMIC_MAX__\fP   0x7fffffff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_ATOMIC_WCHAR_T_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_PTRDIFF_T__\fP   8"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_DIG__\fP   18"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_IS_IEC_60559__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__x86_64__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_MIN_EXP__\fP   (\-1021)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC32_SUBNORMAL_MIN__\fP   0\&.000001\fBE\fP\-95\fBDF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__MSVCRT__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_FAST16_MAX__\fP   0x7fff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_DIG__\fP   15"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_FAST32_MAX__\fP   0xffffffffU"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_LEAST64_TYPE__\fP   \fBlong\fP \fBlong\fP \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_MAX_10_EXP__\fP   38"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LONG_MAX__\fP   0x7fffffffL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC128_SUBNORMAL_MIN__\fP   0\&.000000000000000000000000000000001\fBE\fP\-6143\fBDL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GNUC_EXECUTION_CHARSET_NAME\fP   'UTF\-8'"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_unicode_literals\fP   200710L"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_FAST16_TYPE__\fP   \fBshort\fP \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC64_MAX__\fP   9\&.999999999999999\fBE384DD\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_FAST32_WIDTH__\fP   32"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__CHAR16_TYPE__\fP   \fBshort\fP \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__PRAGMA_REDEFINE_EXTNAME\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZE_WIDTH__\fP   64"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SEG_FS\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_LEAST16_MAX__\fP   0x7fff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC64_MANT_DIG__\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT64_MAX__\fP   0x7fffffffffffffffLL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SEG_GS\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_DENORM_MIN__\fP   1\&.40129846432481707092372958328991613\fBe\fP\-45\fBF32\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIG_ATOMIC_WIDTH__\fP   32"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_LEAST64_TYPE__\fP   \fBlong\fP \fBlong\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT16_TYPE__\fP   \fBshort\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_LEAST8_TYPE__\fP   \fBsigned\fP \fBchar\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__nocona__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_structured_bindings\fP   201606\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_INT__\fP   4"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC32_MAX_EXP__\fP   97"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_FAST8_MAX__\fP   0x7f"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_MAX__\fP   1\&.18973149535723176508575932662800702\fBe\fP+4932\fBF128\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INTPTR_MAX__\fP   0x7fffffffffffffffLL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_sized_deallocation\fP   201309\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_guaranteed_copy_elision\fP   201606\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__stdcall\fP   \fB__attribute__\fP((\fB__stdcall__\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_MIN_10_EXP__\fP   (\-37)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__EXCEPTIONS\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GXX_MERGED_TYPEINFO_NAMES\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__PTRDIFF_WIDTH__\fP   64"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_MANT_DIG__\fP   64"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_range_based_for\fP   201603\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_HAS_INFINITY__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_MAX__\fP   1\&.18973149535723176502126385303097021\fBe\fP+4932\fBF64x\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__STDCPP_DEFAULT_NEW_ALIGNMENT__\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIG_ATOMIC_MIN__\fP   (\-\fB__SIG_ATOMIC_MAX__\fP \- 1)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_ATOMIC_LONG_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_nontype_template_args\fP   201411\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC32_MANT_DIG__\fP   7"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_return_type_deduction\fP   201304\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INTPTR_TYPE__\fP   \fBlong\fP \fBlong\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT16_TYPE__\fP   \fBshort\fP \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WCHAR_TYPE__\fP   \fBshort\fP \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__pic__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINTPTR_MAX__\fP   0xffffffffffffffffULL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_FAST64_WIDTH__\fP   64"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_decltype\fP   200707\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_FAST64_MAX__\fP   0x7fffffffffffffffLL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_ATOMIC_TEST_AND_SET_TRUEVAL\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_NORM_MAX__\fP   3\&.40282346638528859811704183484516925\fBe\fP+38\fBF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_MAX_EXP__\fP   16384"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_FAST64_TYPE__\fP   \fBlong\fP \fBlong\fP \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_inline_variables\fP   201606\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_MAX__\fP   0x7fffffff"
.br
.ti -1c
.RI "#\fBdefine\fP \fBWIN32\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__nocona\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__code_model_medium__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT64_TYPE__\fP   \fBlong\fP \fBlong\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_MAX_EXP__\fP   128"
.br
.ti -1c
.RI "#\fBdefine\fP \fBWIN64\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__ORDER_BIG_ENDIAN__\fP   4321"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_MANT_DIG__\fP   53"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_inheriting_constructors\fP   201511\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_FLOAT128__\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_LEAST64_MAX__\fP   0x7fffffffffffffffLL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC64_MIN__\fP   1\fBE\fP\-383\fBDD\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WINT_TYPE__\fP   \fBshort\fP \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_LEAST32_TYPE__\fP   \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_SHORT__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_NORM_MAX__\fP   3\&.40282346638528859811704183484516925\fBe\fP+38\fBF32\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SSE__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_MIN_EXP__\fP   (\-16381)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_MAX__\fP   1\&.79769313486231570814527423731704357\fBe\fP+308\fBF64\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__amd64__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WINT_WIDTH__\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_LEAST64_WIDTH__\fP   64"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_MAX_EXP__\fP   16384"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_MAX_10_EXP__\fP   308"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WIN32\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_INT128__\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_IS_IEC_60559__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WCHAR_UNSIGNED__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_MAX_10_EXP__\fP   4932"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__ATOMIC_RELAXED\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_EPSILON__\fP   \fBdouble\fP(2\&.22044604925031308084726333618164062\fBe\fP\-16\fBL\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__thiscall\fP   \fB__attribute__\fP((\fB__thiscall__\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_MIN__\fP   3\&.36210314311209350626267781732175260e\-4932\fBF128\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT8_C\fP(\fBc\fP)   \fBc\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_MAX_EXP__\fP   1024"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_LEAST32_TYPE__\fP   \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_WCHAR_T__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GNUC_PATCHLEVEL__\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_NORM_MAX__\fP   1\&.18973149535723176508575932662800702\fBe\fP+4932\fBF128\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_NORM_MAX__\fP   1\&.79769313486231570814527423731704357\fBe\fP+308\fBF64\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INTMAX_MAX__\fP   0x7fffffffffffffffLL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SSE3__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_FAST8_TYPE__\fP   \fBsigned\fP \fBchar\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__fastcall\fP   \fB__attribute__\fP((\fB__fastcall__\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_namespace_attributes\fP   201411\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64X_MIN__\fP   3\&.36210314311209350626267781732175260e\-4932\fBF64x\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__STDCPP_THREADS__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GNUC_STDC_INLINE__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_HAS_DENORM__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_EPSILON__\fP   1\&.19209289550781250000000000000000000e\-7\fBF32\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_DECIMAL_DIG__\fP   17"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__STDC_UTF_32__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_FAST8_WIDTH__\fP   8"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FXSR__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_MAX__\fP   1\&.79769313486231570814527423731704357\fBe\fP+308\fBF32x\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_NORM_MAX__\fP   \fBdouble\fP(1\&.79769313486231570814527423731704357\fBe\fP+308\fBL\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__BYTE_ORDER__\fP   \fB__ORDER_LITTLE_ENDIAN__\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__MINGW64__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INTMAX_WIDTH__\fP   64"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_runtime_arrays\fP   198712\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT64_TYPE__\fP   \fBlong\fP \fBlong\fP \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT32_C\fP(\fBc\fP)   \fBc\fP ## \fBU\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_alias_templates\fP   200704\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBWINNT\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_DENORM_MIN__\fP   1\&.40129846432481707092372958328991613\fBe\fP\-45\fBF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_IS_IEC_60559__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT8_MAX__\fP   0x7f"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LONG_WIDTH__\fP   32"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__PIC__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_FAST32_TYPE__\fP   \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_NORM_MAX__\fP   1\&.79769313486231570814527423731704357\fBe\fP+308\fBF32x\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__CHAR32_TYPE__\fP   \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_MAX__\fP   3\&.40282346638528859811704183484516925\fBe\fP+38\fBF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_constexpr\fP   201603\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SSE2__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_deduction_guides\fP   201703\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT32_TYPE__\fP   \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_DOUBLE__\fP   8"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_exceptions\fP   199711\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_MIN_10_EXP__\fP   (\-37)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT64_MIN__\fP   2\&.22507385850720138309023271733240406\fBe\fP\-308\fBF64\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_LEAST32_WIDTH__\fP   32"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INTMAX_TYPE__\fP   \fBlong\fP \fBlong\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB_INTEGRAL_MAX_BITS\fP   64"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC128_MAX_EXP__\fP   6145"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__ATOMIC_CONSUME\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GNUC_MINOR__\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GLIBCXX_TYPE_INT_N_0\fP   \fB__int128\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT_FAST16_WIDTH__\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINTMAX_MAX__\fP   0xffffffffffffffffULL"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_DENORM_MIN__\fP   4\&.94065645841246544176568792868221372\fBe\fP\-324\fBF32x\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_template_template_args\fP   201611\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DBL_MAX_10_EXP__\fP   308"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_DENORM_MIN__\fP   3\&.64519953188247460252840593361941982\fBe\fP\-4951\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__INT16_C\fP(\fBc\fP)   \fBc\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__STDC__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_DIG__\fP   15"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__PTRDIFF_TYPE__\fP   \fBlong\fP \fBlong\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__ATOMIC_SEQ_CST\fP   5"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_HAVE_SYNC_COMPARE_AND_SWAP_16\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32X_MIN_10_EXP__\fP   (\-307)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINTPTR_TYPE__\fP   \fBlong\fP \fBlong\fP \fBunsigned\fP \fBint\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC64_SUBNORMAL_MIN__\fP   0\&.000000000000001\fBE\fP\-383\fBDD\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__DEC128_MANT_DIG__\fP   34"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_MIN_10_EXP__\fP   (\-4931)"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_generic_lambdas\fP   201304\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SSE_MATH__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__SIZEOF_LONG_LONG__\fP   8"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_user_defined_literals\fP   200809\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT128_DECIMAL_DIG__\fP   36"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_ATOMIC_LLONG_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT32_HAS_QUIET_NAN__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__FLT_DECIMAL_DIG__\fP   9"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_FAST16_MAX__\fP   0xffff"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__LDBL_NORM_MAX__\fP   1\&.18973149535723176502126385303097021\fBe\fP+4932\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__GCC_ATOMIC_SHORT_LOCK_FREE\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__UINT_FAST8_TYPE__\fP   \fBunsigned\fP \fBchar\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__WIN64__\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__cpp_init_captures\fP   201304\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__ATOMIC_ACQ_REL\fP   4"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__ATOMIC_RELEASE\fP   3"
.br
.ti -1c
.RI "#\fBdefine\fP \fB__declspec\fP(\fBx\fP)   \fB__attribute__\fP((\fBx\fP))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP __amd64   1"

.SS "#\fBdefine\fP __amd64__   1"

.SS "#\fBdefine\fP __ATOMIC_ACQ_REL   4"

.SS "#\fBdefine\fP __ATOMIC_ACQUIRE   2"

.SS "#\fBdefine\fP __ATOMIC_CONSUME   1"

.SS "#\fBdefine\fP __ATOMIC_HLE_ACQUIRE   65536"

.SS "#\fBdefine\fP __ATOMIC_HLE_RELEASE   131072"

.SS "#\fBdefine\fP __ATOMIC_RELAXED   0"

.SS "#\fBdefine\fP __ATOMIC_RELEASE   3"

.SS "#\fBdefine\fP __ATOMIC_SEQ_CST   5"

.SS "#\fBdefine\fP __BIGGEST_ALIGNMENT__   16"

.SS "#\fBdefine\fP __BYTE_ORDER__   \fB__ORDER_LITTLE_ENDIAN__\fP"

.SS "#\fBdefine\fP __cdecl   \fB__attribute__\fP((\fB__cdecl__\fP))"

.SS "#\fBdefine\fP __CHAR16_TYPE__   \fBshort\fP \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __CHAR32_TYPE__   \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __CHAR_BIT__   8"

.SS "#\fBdefine\fP __code_model_medium__   1"

.SS "#\fBdefine\fP __cplusplus   201703\fBL\fP"

.SS "#\fBdefine\fP __cpp_aggregate_bases   201603\fBL\fP"

.SS "#\fBdefine\fP __cpp_aggregate_nsdmi   201304\fBL\fP"

.SS "#\fBdefine\fP __cpp_alias_templates   200704\fBL\fP"

.SS "#\fBdefine\fP __cpp_aligned_new   201606\fBL\fP"

.SS "#\fBdefine\fP __cpp_attributes   200809\fBL\fP"

.SS "#\fBdefine\fP __cpp_binary_literals   201304\fBL\fP"

.SS "#\fBdefine\fP __cpp_capture_star_this   201603\fBL\fP"

.SS "#\fBdefine\fP __cpp_constexpr   201603\fBL\fP"

.SS "#\fBdefine\fP __cpp_decltype   200707\fBL\fP"

.SS "#\fBdefine\fP __cpp_decltype_auto   201304\fBL\fP"

.SS "#\fBdefine\fP __cpp_deduction_guides   201703\fBL\fP"

.SS "#\fBdefine\fP __cpp_delegating_constructors   200604\fBL\fP"

.SS "#\fBdefine\fP __cpp_digit_separators   201309\fBL\fP"

.SS "#\fBdefine\fP __cpp_enumerator_attributes   201411\fBL\fP"

.SS "#\fBdefine\fP __cpp_exceptions   199711\fBL\fP"

.SS "#\fBdefine\fP __cpp_fold_expressions   201603\fBL\fP"

.SS "#\fBdefine\fP __cpp_generic_lambdas   201304\fBL\fP"

.SS "#\fBdefine\fP __cpp_guaranteed_copy_elision   201606\fBL\fP"

.SS "#\fBdefine\fP __cpp_hex_float   201603\fBL\fP"

.SS "#\fBdefine\fP __cpp_if_constexpr   201606\fBL\fP"

.SS "#\fBdefine\fP __cpp_inheriting_constructors   201511\fBL\fP"

.SS "#\fBdefine\fP __cpp_init_captures   201304\fBL\fP"

.SS "#\fBdefine\fP __cpp_initializer_lists   200806\fBL\fP"

.SS "#\fBdefine\fP __cpp_inline_variables   201606\fBL\fP"

.SS "#\fBdefine\fP __cpp_lambdas   200907\fBL\fP"

.SS "#\fBdefine\fP __cpp_namespace_attributes   201411\fBL\fP"

.SS "#\fBdefine\fP __cpp_nested_namespace_definitions   201411\fBL\fP"

.SS "#\fBdefine\fP __cpp_noexcept_function_type   201510L"

.SS "#\fBdefine\fP __cpp_nontype_template_args   201411\fBL\fP"

.SS "#\fBdefine\fP __cpp_nontype_template_parameter_auto   201606\fBL\fP"

.SS "#\fBdefine\fP __cpp_nsdmi   200809\fBL\fP"

.SS "#\fBdefine\fP __cpp_range_based_for   201603\fBL\fP"

.SS "#\fBdefine\fP __cpp_raw_strings   200710L"

.SS "#\fBdefine\fP __cpp_ref_qualifiers   200710L"

.SS "#\fBdefine\fP __cpp_return_type_deduction   201304\fBL\fP"

.SS "#\fBdefine\fP __cpp_rtti   199711\fBL\fP"

.SS "#\fBdefine\fP __cpp_runtime_arrays   198712\fBL\fP"

.SS "#\fBdefine\fP __cpp_rvalue_reference   200610L"

.SS "#\fBdefine\fP __cpp_rvalue_references   200610L"

.SS "#\fBdefine\fP __cpp_sized_deallocation   201309\fBL\fP"

.SS "#\fBdefine\fP __cpp_static_assert   201411\fBL\fP"

.SS "#\fBdefine\fP __cpp_structured_bindings   201606\fBL\fP"

.SS "#\fBdefine\fP __cpp_template_auto   201606\fBL\fP"

.SS "#\fBdefine\fP __cpp_template_template_args   201611\fBL\fP"

.SS "#\fBdefine\fP __cpp_threadsafe_static_init   200806\fBL\fP"

.SS "#\fBdefine\fP __cpp_unicode_characters   201411\fBL\fP"

.SS "#\fBdefine\fP __cpp_unicode_literals   200710L"

.SS "#\fBdefine\fP __cpp_user_defined_literals   200809\fBL\fP"

.SS "#\fBdefine\fP __cpp_variable_templates   201304\fBL\fP"

.SS "#\fBdefine\fP __cpp_variadic_templates   200704\fBL\fP"

.SS "#\fBdefine\fP __cpp_variadic_using   201611\fBL\fP"

.SS "#\fBdefine\fP __DBL_DECIMAL_DIG__   17"

.SS "#\fBdefine\fP __DBL_DENORM_MIN__   \fBdouble\fP(4\&.94065645841246544176568792868221372\fBe\fP\-324\fBL\fP)"

.SS "#\fBdefine\fP __DBL_DIG__   15"

.SS "#\fBdefine\fP __DBL_EPSILON__   \fBdouble\fP(2\&.22044604925031308084726333618164062\fBe\fP\-16\fBL\fP)"

.SS "#\fBdefine\fP __DBL_HAS_DENORM__   1"

.SS "#\fBdefine\fP __DBL_HAS_INFINITY__   1"

.SS "#\fBdefine\fP __DBL_HAS_QUIET_NAN__   1"

.SS "#\fBdefine\fP __DBL_IS_IEC_60559__   2"

.SS "#\fBdefine\fP __DBL_MANT_DIG__   53"

.SS "#\fBdefine\fP __DBL_MAX_10_EXP__   308"

.SS "#\fBdefine\fP __DBL_MAX__   \fBdouble\fP(1\&.79769313486231570814527423731704357\fBe\fP+308\fBL\fP)"

.SS "#\fBdefine\fP __DBL_MAX_EXP__   1024"

.SS "#\fBdefine\fP __DBL_MIN_10_EXP__   (\-307)"

.SS "#\fBdefine\fP __DBL_MIN__   \fBdouble\fP(2\&.22507385850720138309023271733240406\fBe\fP\-308\fBL\fP)"

.SS "#\fBdefine\fP __DBL_MIN_EXP__   (\-1021)"

.SS "#\fBdefine\fP __DBL_NORM_MAX__   \fBdouble\fP(1\&.79769313486231570814527423731704357\fBe\fP+308\fBL\fP)"

.SS "#\fBdefine\fP __DEC128_EPSILON__   1\fBE\fP\-33\fBDL\fP"

.SS "#\fBdefine\fP __DEC128_MANT_DIG__   34"

.SS "#\fBdefine\fP __DEC128_MAX__   9\&.999999999999999999999999999999999\fBE6144DL\fP"

.SS "#\fBdefine\fP __DEC128_MAX_EXP__   6145"

.SS "#\fBdefine\fP __DEC128_MIN__   1\fBE\fP\-6143\fBDL\fP"

.SS "#\fBdefine\fP __DEC128_MIN_EXP__   (\-6142)"

.SS "#\fBdefine\fP __DEC128_SUBNORMAL_MIN__   0\&.000000000000000000000000000000001\fBE\fP\-6143\fBDL\fP"

.SS "#\fBdefine\fP __DEC32_EPSILON__   1\fBE\fP\-6\fBDF\fP"

.SS "#\fBdefine\fP __DEC32_MANT_DIG__   7"

.SS "#\fBdefine\fP __DEC32_MAX__   9\&.999999\fBE96DF\fP"

.SS "#\fBdefine\fP __DEC32_MAX_EXP__   97"

.SS "#\fBdefine\fP __DEC32_MIN__   1\fBE\fP\-95\fBDF\fP"

.SS "#\fBdefine\fP __DEC32_MIN_EXP__   (\-94)"

.SS "#\fBdefine\fP __DEC32_SUBNORMAL_MIN__   0\&.000001\fBE\fP\-95\fBDF\fP"

.SS "#\fBdefine\fP __DEC64_EPSILON__   1\fBE\fP\-15\fBDD\fP"

.SS "#\fBdefine\fP __DEC64_MANT_DIG__   16"

.SS "#\fBdefine\fP __DEC64_MAX__   9\&.999999999999999\fBE384DD\fP"

.SS "#\fBdefine\fP __DEC64_MAX_EXP__   385"

.SS "#\fBdefine\fP __DEC64_MIN__   1\fBE\fP\-383\fBDD\fP"

.SS "#\fBdefine\fP __DEC64_MIN_EXP__   (\-382)"

.SS "#\fBdefine\fP __DEC64_SUBNORMAL_MIN__   0\&.000000000000001\fBE\fP\-383\fBDD\fP"

.SS "#\fBdefine\fP __DEC_EVAL_METHOD__   2"

.SS "#\fBdefine\fP __DECIMAL_BID_FORMAT__   1"

.SS "#\fBdefine\fP __DECIMAL_DIG__   21"

.SS "#\fBdefine\fP __declspec(\fBx\fP)   \fB__attribute__\fP((\fBx\fP))"

.SS "#\fBdefine\fP __DEPRECATED   1"

.SS "#\fBdefine\fP __EXCEPTIONS   1"

.SS "#\fBdefine\fP __fastcall   \fB__attribute__\fP((\fB__fastcall__\fP))"

.SS "#\fBdefine\fP __FINITE_MATH_ONLY__   0"

.SS "#\fBdefine\fP __FLOAT_WORD_ORDER__   \fB__ORDER_LITTLE_ENDIAN__\fP"

.SS "#\fBdefine\fP __FLT128_DECIMAL_DIG__   36"

.SS "#\fBdefine\fP __FLT128_DENORM_MIN__   6\&.47517511943802511092443895822764655\fBe\fP\-4966\fBF128\fP"

.SS "#\fBdefine\fP __FLT128_DIG__   33"

.SS "#\fBdefine\fP __FLT128_EPSILON__   1\&.92592994438723585305597794258492732\fBe\fP\-34\fBF128\fP"

.SS "#\fBdefine\fP __FLT128_HAS_DENORM__   1"

.SS "#\fBdefine\fP __FLT128_HAS_INFINITY__   1"

.SS "#\fBdefine\fP __FLT128_HAS_QUIET_NAN__   1"

.SS "#\fBdefine\fP __FLT128_IS_IEC_60559__   2"

.SS "#\fBdefine\fP __FLT128_MANT_DIG__   113"

.SS "#\fBdefine\fP __FLT128_MAX_10_EXP__   4932"

.SS "#\fBdefine\fP __FLT128_MAX__   1\&.18973149535723176508575932662800702\fBe\fP+4932\fBF128\fP"

.SS "#\fBdefine\fP __FLT128_MAX_EXP__   16384"

.SS "#\fBdefine\fP __FLT128_MIN_10_EXP__   (\-4931)"

.SS "#\fBdefine\fP __FLT128_MIN__   3\&.36210314311209350626267781732175260e\-4932\fBF128\fP"

.SS "#\fBdefine\fP __FLT128_MIN_EXP__   (\-16381)"

.SS "#\fBdefine\fP __FLT128_NORM_MAX__   1\&.18973149535723176508575932662800702\fBe\fP+4932\fBF128\fP"

.SS "#\fBdefine\fP __FLT32_DECIMAL_DIG__   9"

.SS "#\fBdefine\fP __FLT32_DENORM_MIN__   1\&.40129846432481707092372958328991613\fBe\fP\-45\fBF32\fP"

.SS "#\fBdefine\fP __FLT32_DIG__   6"

.SS "#\fBdefine\fP __FLT32_EPSILON__   1\&.19209289550781250000000000000000000e\-7\fBF32\fP"

.SS "#\fBdefine\fP __FLT32_HAS_DENORM__   1"

.SS "#\fBdefine\fP __FLT32_HAS_INFINITY__   1"

.SS "#\fBdefine\fP __FLT32_HAS_QUIET_NAN__   1"

.SS "#\fBdefine\fP __FLT32_IS_IEC_60559__   2"

.SS "#\fBdefine\fP __FLT32_MANT_DIG__   24"

.SS "#\fBdefine\fP __FLT32_MAX_10_EXP__   38"

.SS "#\fBdefine\fP __FLT32_MAX__   3\&.40282346638528859811704183484516925\fBe\fP+38\fBF32\fP"

.SS "#\fBdefine\fP __FLT32_MAX_EXP__   128"

.SS "#\fBdefine\fP __FLT32_MIN_10_EXP__   (\-37)"

.SS "#\fBdefine\fP __FLT32_MIN__   1\&.17549435082228750796873653722224568\fBe\fP\-38\fBF32\fP"

.SS "#\fBdefine\fP __FLT32_MIN_EXP__   (\-125)"

.SS "#\fBdefine\fP __FLT32_NORM_MAX__   3\&.40282346638528859811704183484516925\fBe\fP+38\fBF32\fP"

.SS "#\fBdefine\fP __FLT32X_DECIMAL_DIG__   17"

.SS "#\fBdefine\fP __FLT32X_DENORM_MIN__   4\&.94065645841246544176568792868221372\fBe\fP\-324\fBF32x\fP"

.SS "#\fBdefine\fP __FLT32X_DIG__   15"

.SS "#\fBdefine\fP __FLT32X_EPSILON__   2\&.22044604925031308084726333618164062\fBe\fP\-16\fBF32x\fP"

.SS "#\fBdefine\fP __FLT32X_HAS_DENORM__   1"

.SS "#\fBdefine\fP __FLT32X_HAS_INFINITY__   1"

.SS "#\fBdefine\fP __FLT32X_HAS_QUIET_NAN__   1"

.SS "#\fBdefine\fP __FLT32X_IS_IEC_60559__   2"

.SS "#\fBdefine\fP __FLT32X_MANT_DIG__   53"

.SS "#\fBdefine\fP __FLT32X_MAX_10_EXP__   308"

.SS "#\fBdefine\fP __FLT32X_MAX__   1\&.79769313486231570814527423731704357\fBe\fP+308\fBF32x\fP"

.SS "#\fBdefine\fP __FLT32X_MAX_EXP__   1024"

.SS "#\fBdefine\fP __FLT32X_MIN_10_EXP__   (\-307)"

.SS "#\fBdefine\fP __FLT32X_MIN__   2\&.22507385850720138309023271733240406\fBe\fP\-308\fBF32x\fP"

.SS "#\fBdefine\fP __FLT32X_MIN_EXP__   (\-1021)"

.SS "#\fBdefine\fP __FLT32X_NORM_MAX__   1\&.79769313486231570814527423731704357\fBe\fP+308\fBF32x\fP"

.SS "#\fBdefine\fP __FLT64_DECIMAL_DIG__   17"

.SS "#\fBdefine\fP __FLT64_DENORM_MIN__   4\&.94065645841246544176568792868221372\fBe\fP\-324\fBF64\fP"

.SS "#\fBdefine\fP __FLT64_DIG__   15"

.SS "#\fBdefine\fP __FLT64_EPSILON__   2\&.22044604925031308084726333618164062\fBe\fP\-16\fBF64\fP"

.SS "#\fBdefine\fP __FLT64_HAS_DENORM__   1"

.SS "#\fBdefine\fP __FLT64_HAS_INFINITY__   1"

.SS "#\fBdefine\fP __FLT64_HAS_QUIET_NAN__   1"

.SS "#\fBdefine\fP __FLT64_IS_IEC_60559__   2"

.SS "#\fBdefine\fP __FLT64_MANT_DIG__   53"

.SS "#\fBdefine\fP __FLT64_MAX_10_EXP__   308"

.SS "#\fBdefine\fP __FLT64_MAX__   1\&.79769313486231570814527423731704357\fBe\fP+308\fBF64\fP"

.SS "#\fBdefine\fP __FLT64_MAX_EXP__   1024"

.SS "#\fBdefine\fP __FLT64_MIN_10_EXP__   (\-307)"

.SS "#\fBdefine\fP __FLT64_MIN__   2\&.22507385850720138309023271733240406\fBe\fP\-308\fBF64\fP"

.SS "#\fBdefine\fP __FLT64_MIN_EXP__   (\-1021)"

.SS "#\fBdefine\fP __FLT64_NORM_MAX__   1\&.79769313486231570814527423731704357\fBe\fP+308\fBF64\fP"

.SS "#\fBdefine\fP __FLT64X_DECIMAL_DIG__   21"

.SS "#\fBdefine\fP __FLT64X_DENORM_MIN__   3\&.64519953188247460252840593361941982\fBe\fP\-4951\fBF64x\fP"

.SS "#\fBdefine\fP __FLT64X_DIG__   18"

.SS "#\fBdefine\fP __FLT64X_EPSILON__   1\&.08420217248550443400745280086994171\fBe\fP\-19\fBF64x\fP"

.SS "#\fBdefine\fP __FLT64X_HAS_DENORM__   1"

.SS "#\fBdefine\fP __FLT64X_HAS_INFINITY__   1"

.SS "#\fBdefine\fP __FLT64X_HAS_QUIET_NAN__   1"

.SS "#\fBdefine\fP __FLT64X_IS_IEC_60559__   2"

.SS "#\fBdefine\fP __FLT64X_MANT_DIG__   64"

.SS "#\fBdefine\fP __FLT64X_MAX_10_EXP__   4932"

.SS "#\fBdefine\fP __FLT64X_MAX__   1\&.18973149535723176502126385303097021\fBe\fP+4932\fBF64x\fP"

.SS "#\fBdefine\fP __FLT64X_MAX_EXP__   16384"

.SS "#\fBdefine\fP __FLT64X_MIN_10_EXP__   (\-4931)"

.SS "#\fBdefine\fP __FLT64X_MIN__   3\&.36210314311209350626267781732175260e\-4932\fBF64x\fP"

.SS "#\fBdefine\fP __FLT64X_MIN_EXP__   (\-16381)"

.SS "#\fBdefine\fP __FLT64X_NORM_MAX__   1\&.18973149535723176502126385303097021\fBe\fP+4932\fBF64x\fP"

.SS "#\fBdefine\fP __FLT_DECIMAL_DIG__   9"

.SS "#\fBdefine\fP __FLT_DENORM_MIN__   1\&.40129846432481707092372958328991613\fBe\fP\-45\fBF\fP"

.SS "#\fBdefine\fP __FLT_DIG__   6"

.SS "#\fBdefine\fP __FLT_EPSILON__   1\&.19209289550781250000000000000000000e\-7\fBF\fP"

.SS "#\fBdefine\fP __FLT_EVAL_METHOD__   0"

.SS "#\fBdefine\fP __FLT_EVAL_METHOD_TS_18661_3__   0"

.SS "#\fBdefine\fP __FLT_HAS_DENORM__   1"

.SS "#\fBdefine\fP __FLT_HAS_INFINITY__   1"

.SS "#\fBdefine\fP __FLT_HAS_QUIET_NAN__   1"

.SS "#\fBdefine\fP __FLT_IS_IEC_60559__   2"

.SS "#\fBdefine\fP __FLT_MANT_DIG__   24"

.SS "#\fBdefine\fP __FLT_MAX_10_EXP__   38"

.SS "#\fBdefine\fP __FLT_MAX__   3\&.40282346638528859811704183484516925\fBe\fP+38\fBF\fP"

.SS "#\fBdefine\fP __FLT_MAX_EXP__   128"

.SS "#\fBdefine\fP __FLT_MIN_10_EXP__   (\-37)"

.SS "#\fBdefine\fP __FLT_MIN__   1\&.17549435082228750796873653722224568\fBe\fP\-38\fBF\fP"

.SS "#\fBdefine\fP __FLT_MIN_EXP__   (\-125)"

.SS "#\fBdefine\fP __FLT_NORM_MAX__   3\&.40282346638528859811704183484516925\fBe\fP+38\fBF\fP"

.SS "#\fBdefine\fP __FLT_RADIX__   2"

.SS "#\fBdefine\fP __FXSR__   1"

.SS "#\fBdefine\fP __GCC_ASM_FLAG_OUTPUTS__   1"

.SS "#\fBdefine\fP __GCC_ATOMIC_BOOL_LOCK_FREE   2"

.SS "#\fBdefine\fP __GCC_ATOMIC_CHAR16_T_LOCK_FREE   2"

.SS "#\fBdefine\fP __GCC_ATOMIC_CHAR32_T_LOCK_FREE   2"

.SS "#\fBdefine\fP __GCC_ATOMIC_CHAR_LOCK_FREE   2"

.SS "#\fBdefine\fP __GCC_ATOMIC_INT_LOCK_FREE   2"

.SS "#\fBdefine\fP __GCC_ATOMIC_LLONG_LOCK_FREE   2"

.SS "#\fBdefine\fP __GCC_ATOMIC_LONG_LOCK_FREE   2"

.SS "#\fBdefine\fP __GCC_ATOMIC_POINTER_LOCK_FREE   2"

.SS "#\fBdefine\fP __GCC_ATOMIC_SHORT_LOCK_FREE   2"

.SS "#\fBdefine\fP __GCC_ATOMIC_TEST_AND_SET_TRUEVAL   1"

.SS "#\fBdefine\fP __GCC_ATOMIC_WCHAR_T_LOCK_FREE   2"

.SS "#\fBdefine\fP __GCC_HAVE_DWARF2_CFI_ASM   1"

.SS "#\fBdefine\fP __GCC_HAVE_SYNC_COMPARE_AND_SWAP_1   1"

.SS "#\fBdefine\fP __GCC_HAVE_SYNC_COMPARE_AND_SWAP_16   1"

.SS "#\fBdefine\fP __GCC_HAVE_SYNC_COMPARE_AND_SWAP_2   1"

.SS "#\fBdefine\fP __GCC_HAVE_SYNC_COMPARE_AND_SWAP_4   1"

.SS "#\fBdefine\fP __GCC_HAVE_SYNC_COMPARE_AND_SWAP_8   1"

.SS "#\fBdefine\fP __GCC_IEC_559   2"

.SS "#\fBdefine\fP __GCC_IEC_559_COMPLEX   2"

.SS "#\fBdefine\fP __GLIBCXX_BITSIZE_INT_N_0   128"

.SS "#\fBdefine\fP __GLIBCXX_TYPE_INT_N_0   \fB__int128\fP"

.SS "#\fBdefine\fP __GNUC__   11"

.SS "#\fBdefine\fP __GNUC_EXECUTION_CHARSET_NAME   'UTF\-8'"

.SS "#\fBdefine\fP __GNUC_MINOR__   2"

.SS "#\fBdefine\fP __GNUC_PATCHLEVEL__   0"

.SS "#\fBdefine\fP __GNUC_STDC_INLINE__   1"

.SS "#\fBdefine\fP __GNUC_WIDE_EXECUTION_CHARSET_NAME   'UTF\-16\fBLE'\fP"

.SS "#\fBdefine\fP __GNUG__   11"

.SS "#\fBdefine\fP __GXX_ABI_VERSION   1016"

.SS "#\fBdefine\fP __GXX_EXPERIMENTAL_CXX0X__   1"

.SS "#\fBdefine\fP __GXX_MERGED_TYPEINFO_NAMES   0"

.SS "#\fBdefine\fP __GXX_RTTI   1"

.SS "#\fBdefine\fP __GXX_TYPEINFO_EQUALITY_INLINE   0"

.SS "#\fBdefine\fP __GXX_WEAK__   1"

.SS "#\fBdefine\fP __HAVE_SPECULATION_SAFE_VALUE   1"

.SS "#\fBdefine\fP __INT16_C(\fBc\fP)   \fBc\fP"

.SS "#\fBdefine\fP __INT16_MAX__   0x7fff"

.SS "#\fBdefine\fP __INT16_TYPE__   \fBshort\fP \fBint\fP"

.SS "#\fBdefine\fP __INT32_C(\fBc\fP)   \fBc\fP"

.SS "#\fBdefine\fP __INT32_MAX__   0x7fffffff"

.SS "#\fBdefine\fP __INT32_TYPE__   \fBint\fP"

.SS "#\fBdefine\fP __INT64_C(\fBc\fP)   \fBc\fP ## \fBLL\fP"

.SS "#\fBdefine\fP __INT64_MAX__   0x7fffffffffffffffLL"

.SS "#\fBdefine\fP __INT64_TYPE__   \fBlong\fP \fBlong\fP \fBint\fP"

.SS "#\fBdefine\fP __INT8_C(\fBc\fP)   \fBc\fP"

.SS "#\fBdefine\fP __INT8_MAX__   0x7f"

.SS "#\fBdefine\fP __INT8_TYPE__   \fBsigned\fP \fBchar\fP"

.SS "#\fBdefine\fP __INT_FAST16_MAX__   0x7fff"

.SS "#\fBdefine\fP __INT_FAST16_TYPE__   \fBshort\fP \fBint\fP"

.SS "#\fBdefine\fP __INT_FAST16_WIDTH__   16"

.SS "#\fBdefine\fP __INT_FAST32_MAX__   0x7fffffff"

.SS "#\fBdefine\fP __INT_FAST32_TYPE__   \fBint\fP"

.SS "#\fBdefine\fP __INT_FAST32_WIDTH__   32"

.SS "#\fBdefine\fP __INT_FAST64_MAX__   0x7fffffffffffffffLL"

.SS "#\fBdefine\fP __INT_FAST64_TYPE__   \fBlong\fP \fBlong\fP \fBint\fP"

.SS "#\fBdefine\fP __INT_FAST64_WIDTH__   64"

.SS "#\fBdefine\fP __INT_FAST8_MAX__   0x7f"

.SS "#\fBdefine\fP __INT_FAST8_TYPE__   \fBsigned\fP \fBchar\fP"

.SS "#\fBdefine\fP __INT_FAST8_WIDTH__   8"

.SS "#\fBdefine\fP __INT_LEAST16_MAX__   0x7fff"

.SS "#\fBdefine\fP __INT_LEAST16_TYPE__   \fBshort\fP \fBint\fP"

.SS "#\fBdefine\fP __INT_LEAST16_WIDTH__   16"

.SS "#\fBdefine\fP __INT_LEAST32_MAX__   0x7fffffff"

.SS "#\fBdefine\fP __INT_LEAST32_TYPE__   \fBint\fP"

.SS "#\fBdefine\fP __INT_LEAST32_WIDTH__   32"

.SS "#\fBdefine\fP __INT_LEAST64_MAX__   0x7fffffffffffffffLL"

.SS "#\fBdefine\fP __INT_LEAST64_TYPE__   \fBlong\fP \fBlong\fP \fBint\fP"

.SS "#\fBdefine\fP __INT_LEAST64_WIDTH__   64"

.SS "#\fBdefine\fP __INT_LEAST8_MAX__   0x7f"

.SS "#\fBdefine\fP __INT_LEAST8_TYPE__   \fBsigned\fP \fBchar\fP"

.SS "#\fBdefine\fP __INT_LEAST8_WIDTH__   8"

.SS "#\fBdefine\fP __INT_MAX__   0x7fffffff"

.SS "#\fBdefine\fP __INT_WIDTH__   32"

.SS "#\fBdefine\fP __INTMAX_C(\fBc\fP)   \fBc\fP ## \fBLL\fP"

.SS "#\fBdefine\fP __INTMAX_MAX__   0x7fffffffffffffffLL"

.SS "#\fBdefine\fP __INTMAX_TYPE__   \fBlong\fP \fBlong\fP \fBint\fP"

.SS "#\fBdefine\fP __INTMAX_WIDTH__   64"

.SS "#\fBdefine\fP __INTPTR_MAX__   0x7fffffffffffffffLL"

.SS "#\fBdefine\fP __INTPTR_TYPE__   \fBlong\fP \fBlong\fP \fBint\fP"

.SS "#\fBdefine\fP __INTPTR_WIDTH__   64"

.SS "#\fBdefine\fP __LDBL_DECIMAL_DIG__   21"

.SS "#\fBdefine\fP __LDBL_DENORM_MIN__   3\&.64519953188247460252840593361941982\fBe\fP\-4951\fBL\fP"

.SS "#\fBdefine\fP __LDBL_DIG__   18"

.SS "#\fBdefine\fP __LDBL_EPSILON__   1\&.08420217248550443400745280086994171\fBe\fP\-19\fBL\fP"

.SS "#\fBdefine\fP __LDBL_HAS_DENORM__   1"

.SS "#\fBdefine\fP __LDBL_HAS_INFINITY__   1"

.SS "#\fBdefine\fP __LDBL_HAS_QUIET_NAN__   1"

.SS "#\fBdefine\fP __LDBL_IS_IEC_60559__   2"

.SS "#\fBdefine\fP __LDBL_MANT_DIG__   64"

.SS "#\fBdefine\fP __LDBL_MAX_10_EXP__   4932"

.SS "#\fBdefine\fP __LDBL_MAX__   1\&.18973149535723176502126385303097021\fBe\fP+4932\fBL\fP"

.SS "#\fBdefine\fP __LDBL_MAX_EXP__   16384"

.SS "#\fBdefine\fP __LDBL_MIN_10_EXP__   (\-4931)"

.SS "#\fBdefine\fP __LDBL_MIN__   3\&.36210314311209350626267781732175260e\-4932\fBL\fP"

.SS "#\fBdefine\fP __LDBL_MIN_EXP__   (\-16381)"

.SS "#\fBdefine\fP __LDBL_NORM_MAX__   1\&.18973149535723176502126385303097021\fBe\fP+4932\fBL\fP"

.SS "#\fBdefine\fP __LONG_LONG_MAX__   0x7fffffffffffffffLL"

.SS "#\fBdefine\fP __LONG_LONG_WIDTH__   64"

.SS "#\fBdefine\fP __LONG_MAX__   0x7fffffffL"

.SS "#\fBdefine\fP __LONG_WIDTH__   32"

.SS "#\fBdefine\fP __MINGW32__   1"

.SS "#\fBdefine\fP __MINGW64__   1"

.SS "#\fBdefine\fP __MMX__   1"

.SS "#\fBdefine\fP __MMX_WITH_SSE__   1"

.SS "#\fBdefine\fP __MSVCRT__   1"

.SS "#\fBdefine\fP __NO_INLINE__   1"

.SS "#\fBdefine\fP __nocona   1"

.SS "#\fBdefine\fP __nocona__   1"

.SS "#\fBdefine\fP __ORDER_BIG_ENDIAN__   4321"

.SS "#\fBdefine\fP __ORDER_LITTLE_ENDIAN__   1234"

.SS "#\fBdefine\fP __ORDER_PDP_ENDIAN__   3412"

.SS "#\fBdefine\fP __pic__   1"

.SS "#\fBdefine\fP __PIC__   1"

.SS "#\fBdefine\fP __PRAGMA_REDEFINE_EXTNAME   1"

.SS "#\fBdefine\fP __PTRDIFF_MAX__   0x7fffffffffffffffLL"

.SS "#\fBdefine\fP __PTRDIFF_TYPE__   \fBlong\fP \fBlong\fP \fBint\fP"

.SS "#\fBdefine\fP __PTRDIFF_WIDTH__   64"

.SS "#\fBdefine\fP __REGISTER_PREFIX__"

.SS "#\fBdefine\fP __SCHAR_MAX__   0x7f"

.SS "#\fBdefine\fP __SCHAR_WIDTH__   8"

.SS "#\fBdefine\fP __SEG_FS   1"

.SS "#\fBdefine\fP __SEG_GS   1"

.SS "#\fBdefine\fP __SEH__   1"

.SS "#\fBdefine\fP __SHRT_MAX__   0x7fff"

.SS "#\fBdefine\fP __SHRT_WIDTH__   16"

.SS "#\fBdefine\fP __SIG_ATOMIC_MAX__   0x7fffffff"

.SS "#\fBdefine\fP __SIG_ATOMIC_MIN__   (\-\fB__SIG_ATOMIC_MAX__\fP \- 1)"

.SS "#\fBdefine\fP __SIG_ATOMIC_TYPE__   \fBint\fP"

.SS "#\fBdefine\fP __SIG_ATOMIC_WIDTH__   32"

.SS "#\fBdefine\fP __SIZE_MAX__   0xffffffffffffffffULL"

.SS "#\fBdefine\fP __SIZE_TYPE__   \fBlong\fP \fBlong\fP \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __SIZE_WIDTH__   64"

.SS "#\fBdefine\fP __SIZEOF_DOUBLE__   8"

.SS "#\fBdefine\fP __SIZEOF_FLOAT128__   16"

.SS "#\fBdefine\fP __SIZEOF_FLOAT80__   16"

.SS "#\fBdefine\fP __SIZEOF_FLOAT__   4"

.SS "#\fBdefine\fP __SIZEOF_INT128__   16"

.SS "#\fBdefine\fP __SIZEOF_INT__   4"

.SS "#\fBdefine\fP __SIZEOF_LONG__   4"

.SS "#\fBdefine\fP __SIZEOF_LONG_DOUBLE__   16"

.SS "#\fBdefine\fP __SIZEOF_LONG_LONG__   8"

.SS "#\fBdefine\fP __SIZEOF_POINTER__   8"

.SS "#\fBdefine\fP __SIZEOF_PTRDIFF_T__   8"

.SS "#\fBdefine\fP __SIZEOF_SHORT__   2"

.SS "#\fBdefine\fP __SIZEOF_SIZE_T__   8"

.SS "#\fBdefine\fP __SIZEOF_WCHAR_T__   2"

.SS "#\fBdefine\fP __SIZEOF_WINT_T__   2"

.SS "#\fBdefine\fP __SSE2__   1"

.SS "#\fBdefine\fP __SSE2_MATH__   1"

.SS "#\fBdefine\fP __SSE3__   1"

.SS "#\fBdefine\fP __SSE__   1"

.SS "#\fBdefine\fP __SSE_MATH__   1"

.SS "#\fBdefine\fP __STDC__   1"

.SS "#\fBdefine\fP __STDC_HOSTED__   1"

.SS "#\fBdefine\fP __STDC_UTF_16__   1"

.SS "#\fBdefine\fP __STDC_UTF_32__   1"

.SS "#\fBdefine\fP __stdcall   \fB__attribute__\fP((\fB__stdcall__\fP))"

.SS "#\fBdefine\fP __STDCPP_DEFAULT_NEW_ALIGNMENT__   16"

.SS "#\fBdefine\fP __STDCPP_THREADS__   1"

.SS "#\fBdefine\fP __thiscall   \fB__attribute__\fP((\fB__thiscall__\fP))"

.SS "#\fBdefine\fP __tune_core2__   1"

.SS "#\fBdefine\fP __UINT16_C(\fBc\fP)   \fBc\fP"

.SS "#\fBdefine\fP __UINT16_MAX__   0xffff"

.SS "#\fBdefine\fP __UINT16_TYPE__   \fBshort\fP \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __UINT32_C(\fBc\fP)   \fBc\fP ## \fBU\fP"

.SS "#\fBdefine\fP __UINT32_MAX__   0xffffffffU"

.SS "#\fBdefine\fP __UINT32_TYPE__   \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __UINT64_C(\fBc\fP)   \fBc\fP ## \fBULL\fP"

.SS "#\fBdefine\fP __UINT64_MAX__   0xffffffffffffffffULL"

.SS "#\fBdefine\fP __UINT64_TYPE__   \fBlong\fP \fBlong\fP \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __UINT8_C(\fBc\fP)   \fBc\fP"

.SS "#\fBdefine\fP __UINT8_MAX__   0xff"

.SS "#\fBdefine\fP __UINT8_TYPE__   \fBunsigned\fP \fBchar\fP"

.SS "#\fBdefine\fP __UINT_FAST16_MAX__   0xffff"

.SS "#\fBdefine\fP __UINT_FAST16_TYPE__   \fBshort\fP \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __UINT_FAST32_MAX__   0xffffffffU"

.SS "#\fBdefine\fP __UINT_FAST32_TYPE__   \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __UINT_FAST64_MAX__   0xffffffffffffffffULL"

.SS "#\fBdefine\fP __UINT_FAST64_TYPE__   \fBlong\fP \fBlong\fP \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __UINT_FAST8_MAX__   0xff"

.SS "#\fBdefine\fP __UINT_FAST8_TYPE__   \fBunsigned\fP \fBchar\fP"

.SS "#\fBdefine\fP __UINT_LEAST16_MAX__   0xffff"

.SS "#\fBdefine\fP __UINT_LEAST16_TYPE__   \fBshort\fP \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __UINT_LEAST32_MAX__   0xffffffffU"

.SS "#\fBdefine\fP __UINT_LEAST32_TYPE__   \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __UINT_LEAST64_MAX__   0xffffffffffffffffULL"

.SS "#\fBdefine\fP __UINT_LEAST64_TYPE__   \fBlong\fP \fBlong\fP \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __UINT_LEAST8_MAX__   0xff"

.SS "#\fBdefine\fP __UINT_LEAST8_TYPE__   \fBunsigned\fP \fBchar\fP"

.SS "#\fBdefine\fP __UINTMAX_C(\fBc\fP)   \fBc\fP ## \fBULL\fP"

.SS "#\fBdefine\fP __UINTMAX_MAX__   0xffffffffffffffffULL"

.SS "#\fBdefine\fP __UINTMAX_TYPE__   \fBlong\fP \fBlong\fP \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __UINTPTR_MAX__   0xffffffffffffffffULL"

.SS "#\fBdefine\fP __UINTPTR_TYPE__   \fBlong\fP \fBlong\fP \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __USER_LABEL_PREFIX__"

.SS "#\fBdefine\fP __VERSION__   '11\&.2\&.0'"

.SS "#\fBdefine\fP __WCHAR_MAX__   0xffff"

.SS "#\fBdefine\fP __WCHAR_MIN__   0"

.SS "#\fBdefine\fP __WCHAR_TYPE__   \fBshort\fP \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __WCHAR_UNSIGNED__   1"

.SS "#\fBdefine\fP __WCHAR_WIDTH__   16"

.SS "#\fBdefine\fP __WIN32   1"

.SS "#\fBdefine\fP __WIN32__   1"

.SS "#\fBdefine\fP __WIN64   1"

.SS "#\fBdefine\fP __WIN64__   1"

.SS "#\fBdefine\fP __WINNT   1"

.SS "#\fBdefine\fP __WINNT__   1"

.SS "#\fBdefine\fP __WINT_MAX__   0xffff"

.SS "#\fBdefine\fP __WINT_MIN__   0"

.SS "#\fBdefine\fP __WINT_TYPE__   \fBshort\fP \fBunsigned\fP \fBint\fP"

.SS "#\fBdefine\fP __WINT_WIDTH__   16"

.SS "#\fBdefine\fP __x86_64   1"

.SS "#\fBdefine\fP __x86_64__   1"

.SS "#\fBdefine\fP _cdecl   \fB__attribute__\fP((\fB__cdecl__\fP))"

.SS "#\fBdefine\fP _fastcall   \fB__attribute__\fP((\fB__fastcall__\fP))"

.SS "#\fBdefine\fP _INTEGRAL_MAX_BITS   64"

.SS "#\fBdefine\fP _REENTRANT   1"

.SS "#\fBdefine\fP _stdcall   \fB__attribute__\fP((\fB__stdcall__\fP))"

.SS "#\fBdefine\fP _thiscall   \fB__attribute__\fP((\fB__thiscall__\fP))"

.SS "#\fBdefine\fP _WIN32   1"

.SS "#\fBdefine\fP _WIN64   1"

.SS "#\fBdefine\fP WIN32   1"

.SS "#\fBdefine\fP WIN64   1"

.SS "#\fBdefine\fP WINNT   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
