.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/stdlib/modena.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/stdlib/modena.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <utility>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_MESSAGES\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_WSTRING\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_STDLIB\fP   'Modena \fBC\fP++ \fBstandard\fP \fBlibrary'\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_NO_STD_MESSAGES"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_WSTRING"

.SS "#\fBdefine\fP SC_BOOST_STDLIB   'Modena \fBC\fP++ \fBstandard\fP \fBlibrary'\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
