.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/mpw.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/mpw.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_CV_SPECIALIZATIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_DEPENDENT_NESTED_DERIVATIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_DEPENDENT_TYPES_IN_TEMPLATE_VALUE_PARAMETERS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INCLASS_MEMBER_INITIALIZATION\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INTRINSIC_WCHAR_T\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_TEMPLATE_PARTIAL_SPECIALIZATION\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_USING_TEMPLATE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_CWCHAR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_LIMITS_COMPILE_TIME_CONSTANTS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_ALLOCATOR\fP   /* \fBactually\fP \fBa\fP \fBbug\fP \fBwith\fP \fBconst\fP reference \fBoverloading\fP */"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_NO_CV_SPECIALIZATIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_CWCHAR"

.SS "#\fBdefine\fP SC_BOOST_NO_DEPENDENT_NESTED_DERIVATIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_DEPENDENT_TYPES_IN_TEMPLATE_VALUE_PARAMETERS"

.SS "#\fBdefine\fP SC_BOOST_NO_INCLASS_MEMBER_INITIALIZATION"

.SS "#\fBdefine\fP SC_BOOST_NO_INTRINSIC_WCHAR_T"

.SS "#\fBdefine\fP SC_BOOST_NO_LIMITS_COMPILE_TIME_CONSTANTS"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_ALLOCATOR   /* \fBactually\fP \fBa\fP \fBbug\fP \fBwith\fP \fBconst\fP reference \fBoverloading\fP */"

.SS "#\fBdefine\fP SC_BOOST_NO_TEMPLATE_PARTIAL_SPECIALIZATION"

.SS "#\fBdefine\fP SC_BOOST_NO_USING_TEMPLATE"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
