.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_utils/multi_socket_bases.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_utils/multi_socket_bases.h
.SH SYNOPSIS
.br
.PP
\fR#include <tlm>\fP
.br
\fR#include 'tlm_utils/convenience_socket_bases\&.h'\fP
.br
\fR#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBtlm_utils::fn_container< signature >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::callback_binder_fw< TYPES >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::callback_binder_bw< TYPES >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::multi_init_base_if< TYPES >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::multi_init_base< BUSWIDTH, TYPES, N, POL >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::multi_target_base_if< TYPES >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::multi_target_base< BUSWIDTH, TYPES, N, POL >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::multi_to_multi_bind_base< TYPES >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtlm_utils\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBTLM_DEFINE_FUNCTOR\fP(name)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_RET_VAL\fP   \fBtlm::tlm_sync_enum\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_FULL_ARG_LIST\fP   \fBtypename\fP TRAITS::tlm_payload_type& \fBtxn\fP, \fBtypename\fP TRAITS::tlm_phase_type& \fBph\fP, \fBsc_core::sc_time\fP& t"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_ARG_LIST_WITHOUT_TYPES\fP   \fBtxn\fP,\fBph\fP,t"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_RET_VAL\fP   \fBvoid\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_FULL_ARG_LIST\fP   \fBtypename\fP TRAITS::tlm_payload_type& \fBtxn\fP, \fBsc_core::sc_time\fP& t"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_ARG_LIST_WITHOUT_TYPES\fP   \fBtxn\fP,t"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_RET_VAL\fP   \fBunsigned\fP int"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_FULL_ARG_LIST\fP   \fBtypename\fP TRAITS::tlm_payload_type& \fBtxn\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_ARG_LIST_WITHOUT_TYPES\fP   \fBtxn\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_RET_VAL\fP   \fBbool\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_FULL_ARG_LIST\fP   \fBtypename\fP TRAITS::tlm_payload_type& \fBtxn\fP, \fBtlm::tlm_dmi\fP& \fBdmi\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_ARG_LIST_WITHOUT_TYPES\fP   \fBtxn\fP,\fBdmi\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_RET_VAL\fP   \fBvoid\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_FULL_ARG_LIST\fP   \fBsc_dt::uint64\fP \fBl\fP, \fBsc_dt::uint64\fP \fBu\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_ARG_LIST_WITHOUT_TYPES\fP   \fBl\fP,\fBu\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBtlm_utils::TLM_DEFINE_FUNCTOR\fP (\fBnb_transport\fP)"
.br
.ti -1c
.RI "\fBtlm_utils::TLM_DEFINE_FUNCTOR\fP (b_transport)"
.br
.ti -1c
.RI "\fBtlm_utils::TLM_DEFINE_FUNCTOR\fP (\fBdebug_transport\fP)"
.br
.ti -1c
.RI "\fBtlm_utils::TLM_DEFINE_FUNCTOR\fP (get_dmi_ptr)"
.br
.ti -1c
.RI "\fBtlm_utils::TLM_DEFINE_FUNCTOR\fP (\fBinvalidate_dmi\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP TLM_ARG_LIST_WITHOUT_TYPES   \fBtxn\fP,\fBph\fP,t"

.SS "#\fBdefine\fP TLM_ARG_LIST_WITHOUT_TYPES   \fBtxn\fP,t"

.SS "#\fBdefine\fP TLM_ARG_LIST_WITHOUT_TYPES   \fBtxn\fP"

.SS "#\fBdefine\fP TLM_ARG_LIST_WITHOUT_TYPES   \fBtxn\fP,\fBdmi\fP"

.SS "#\fBdefine\fP TLM_ARG_LIST_WITHOUT_TYPES   \fBl\fP,\fBu\fP"

.SS "#\fBdefine\fP TLM_DEFINE_FUNCTOR(name)"

.SS "#\fBdefine\fP TLM_FULL_ARG_LIST   \fBtypename\fP TRAITS::tlm_payload_type& \fBtxn\fP, \fBtypename\fP TRAITS::tlm_phase_type& \fBph\fP, \fBsc_core::sc_time\fP& t"

.SS "#\fBdefine\fP TLM_FULL_ARG_LIST   \fBtypename\fP TRAITS::tlm_payload_type& \fBtxn\fP, \fBsc_core::sc_time\fP& t"

.SS "#\fBdefine\fP TLM_FULL_ARG_LIST   \fBtypename\fP TRAITS::tlm_payload_type& \fBtxn\fP"

.SS "#\fBdefine\fP TLM_FULL_ARG_LIST   \fBtypename\fP TRAITS::tlm_payload_type& \fBtxn\fP, \fBtlm::tlm_dmi\fP& \fBdmi\fP"

.SS "#\fBdefine\fP TLM_FULL_ARG_LIST   \fBsc_dt::uint64\fP \fBl\fP, \fBsc_dt::uint64\fP \fBu\fP"

.SS "#\fBdefine\fP TLM_RET_VAL   \fBtlm::tlm_sync_enum\fP"

.SS "#\fBdefine\fP TLM_RET_VAL   \fBvoid\fP"

.SS "#\fBdefine\fP TLM_RET_VAL   \fBunsigned\fP int"

.SS "#\fBdefine\fP TLM_RET_VAL   \fBbool\fP"

.SS "#\fBdefine\fP TLM_RET_VAL   \fBvoid\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
