.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_utils/multi_passthrough_target_socket.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_utils/multi_passthrough_target_socket.h
.SH SYNOPSIS
.br
.PP
\fR#include 'tlm_utils/multi_socket_bases\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtlm_utils::multi_passthrough_target_socket< MODULE, BUSWIDTH, TYPES, N, POL >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::multi_passthrough_target_socket_optional< MODULE, BUSWIDTH, TYPES, N >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtlm_utils\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
