.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/params.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/params.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBDEBUG\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBMAX_DEBUG_MESSAGES_NB\fP   200"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTEMP_SVG_PATH\fP   ':/svg/\fBmux_symp\&.svg'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTEMP_SVG_ER_PATH\fP   ':/svg/\fBmux_symp_er\&.svg'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTEMP_SVG_PATH2\fP   ':/svg/\fBmux\&.svg'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTEMP_SVG_PATH3\fP   ':/svg/\fBSchematic_Paco\&.svg'\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP DEBUG"

.SS "#\fBdefine\fP MAX_DEBUG_MESSAGES_NB   200"

.SS "#\fBdefine\fP TEMP_SVG_ER_PATH   ':/svg/\fBmux_symp_er\&.svg'\fP"

.SS "#\fBdefine\fP TEMP_SVG_PATH   ':/svg/\fBmux_symp\&.svg'\fP"

.SS "#\fBdefine\fP TEMP_SVG_PATH2   ':/svg/\fBmux\&.svg'\fP"

.SS "#\fBdefine\fP TEMP_SVG_PATH3   ':/svg/\fBSchematic_Paco\&.svg'\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
