.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/qt/md/powerpc_sys5.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/qt/md/powerpc_sys5.h
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBPPC_STACK_INCR\fP   16"
.br
.ti -1c
.RI "#\fBdefine\fP \fBPPC_ROUND_STACK\fP(length)   	(((length)+\fBPPC_STACK_INCR\fP\-1) & ~(\fBPPC_STACK_INCR\fP\-1))"
.br
.ti -1c
.RI "#\fBdefine\fP \fBPPC_LINKAGE_AREA\fP   8"
.br
.ti -1c
.RI "#\fBdefine\fP \fBPPC_LR_SAVE\fP   4"
.br
.ti -1c
.RI "#\fBdefine\fP \fBPPC_PARAM_AREA\fP(\fBn\fP)   (4*(\fBn\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fBPPC_GPR_SAVE_AREA\fP   (4*19)		/* \fBGPR13\fP\-\fBGPR31\fP \fBmust\fP \fBbe\fP \fBsaved\fP */"
.br
.ti -1c
.RI "#\fBdefine\fP \fBPPC_FPR_SAVE_AREA\fP   (8*18)		/* \fBFPR14\fP\-\fBFPR31\fP \fBmust\fP \fBbe\fP \fBsaved\fP */"
.br
.ti -1c
.RI "#\fBdefine\fP \fBPPC_PAR\fP(\fBi\fP)   (\fBPPC_LINKAGE_AREA\fP+(\fBi\fP)*4)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_BLOCKI_FRAME_SIZE\fP   	\fBPPC_ROUND_STACK\fP(\fBPPC_LINKAGE_AREA\fP+4+\fBPPC_GPR_SAVE_AREA\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_BLOCKI_CR_SAVE\fP   8"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_BLOCKI_GPR_SAVE\fP(\fBi\fP)   (\fBQUICKTHREADS_BLOCKI_FRAME_SIZE\fP\-4+(\fBi\fP\-31)*4)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_BLOCK_FRAME_SIZE\fP   	\fBPPC_ROUND_STACK\fP(\fBPPC_LINKAGE_AREA\fP+\fBPPC_FPR_SAVE_AREA\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_BLOCK_FPR_SAVE\fP(\fBi\fP)   (\fBQUICKTHREADS_BLOCK_FRAME_SIZE\fP\-8+(\fBi\fP\-31)*8)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_START_FRAME_SIZE\fP   \fBPPC_ROUND_STACK\fP(\fBPPC_LINKAGE_AREA\fP+\fBPPC_PARAM_AREA\fP(4))"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGS_LOCAL_AREA\fP   (4*4)		/* \fBlocal\fP \fBvariable\fP \fBarea\fP */"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGS_BKOFF\fP   \fBPPC_PARAM_AREA\fP(4+8)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VSTART_FRAME_SIZE\fP(\fBvarbytes\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VSTART_LIST_BASE\fP   (\fBPPC_LINKAGE_AREA\fP+\fBPPC_PARAM_AREA\fP(4))"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_RETURN_INDEX\fP   ((\fBQUICKTHREADS_BLOCKI_FRAME_SIZE\fP+\fBPPC_LR_SAVE\fP)/\fBsizeof\fP(\fBPPC_W\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ARG_INDEX\fP(\fBi\fP)   ((\fBQUICKTHREADS_BLOCKI_FRAME_SIZE\fP+\fBPPC_PAR\fP(\fBi\fP))/\fBsizeof\fP(\fBPPC_W\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_GROW_DOWN\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_STKALIGN\fP   \fBPPC_STACK_INCR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ARGS_MD\fP(\fBsp\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGS_MD0\fP(\fBsp\fP,  \fBvarbytes\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGS_MD1\fP(\fBsp\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGS_DEFAULT\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGS\fP(\fBsp\fP,  \fBnbytes\fP,  \fBvargs\fP,  \fBpt\fP,  \fBstartup\fP,  \fBvuserf\fP,  \fBcleanup\fP)         ((\fBqt_t\fP *)\fBqt_vargs_stdarg\fP (\fBsp\fP, \fBnbytes\fP, \fBvargs\fP, \fBpt\fP, \fBstartup\fP, \fBvuserf\fP, \fBcleanup\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_STKBASE\fP   	(\fBQUICKTHREADS_BLOCKI_FRAME_SIZE\fP+\fBQUICKTHREADS_START_FRAME_SIZE\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VSTKBASE\fP   (\fBQUICKTHREADS_BLOCKI_FRAME_SIZE\fP+\fBQUICKTHREADS_VSTART_LIST_BASE\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ARGU_INDEX\fP   \fBQUICKTHREADS_ARG_INDEX\fP(0)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ARGT_INDEX\fP   \fBQUICKTHREADS_ARG_INDEX\fP(1)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_USER_INDEX\fP   \fBQUICKTHREADS_ARG_INDEX\fP(2)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_ONLY_INDEX\fP   \fBQUICKTHREADS_ARG_INDEX\fP(3)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VARGT_INDEX\fP   \fBQUICKTHREADS_ARG_INDEX\fP(0)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VSTARTUP_INDEX\fP   \fBQUICKTHREADS_ARG_INDEX\fP(1)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VUSERF_INDEX\fP   \fBQUICKTHREADS_ARG_INDEX\fP(2)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBQUICKTHREADS_VCLEANUP_INDEX\fP   \fBQUICKTHREADS_ARG_INDEX\fP(3)"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBunsigned\fP \fBlong\fP \fBPPC_W\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBPPC_W\fP \fBqt_word_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBqt_start\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBqt_vstart\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP PPC_FPR_SAVE_AREA   (8*18)		/* \fBFPR14\fP\-\fBFPR31\fP \fBmust\fP \fBbe\fP \fBsaved\fP */"

.SS "#\fBdefine\fP PPC_GPR_SAVE_AREA   (4*19)		/* \fBGPR13\fP\-\fBGPR31\fP \fBmust\fP \fBbe\fP \fBsaved\fP */"

.SS "#\fBdefine\fP PPC_LINKAGE_AREA   8"

.SS "#\fBdefine\fP PPC_LR_SAVE   4"

.SS "#\fBdefine\fP PPC_PAR(\fBi\fP)   (\fBPPC_LINKAGE_AREA\fP+(\fBi\fP)*4)"

.SS "#\fBdefine\fP PPC_PARAM_AREA(\fBn\fP)   (4*(\fBn\fP))"

.SS "#\fBdefine\fP PPC_ROUND_STACK(length)   	(((length)+\fBPPC_STACK_INCR\fP\-1) & ~(\fBPPC_STACK_INCR\fP\-1))"

.SS "#\fBdefine\fP PPC_STACK_INCR   16"

.SS "#\fBdefine\fP QUICKTHREADS_ARG_INDEX(\fBi\fP)   ((\fBQUICKTHREADS_BLOCKI_FRAME_SIZE\fP+\fBPPC_PAR\fP(\fBi\fP))/\fBsizeof\fP(\fBPPC_W\fP))"

.SS "#\fBdefine\fP QUICKTHREADS_ARGS_MD(\fBsp\fP)"
\fBValue:\fP.PP
.nf
    (QUICKTHREADS_SPUT (sp, QUICKTHREADS_RETURN_INDEX, qt_start), \\
	QUICKTHREADS_SPUT (sp, 0, sp+QUICKTHREADS_BLOCKI_FRAME_SIZE), \\
	QUICKTHREADS_SPUT (sp, QUICKTHREADS_BLOCKI_FRAME_SIZE/sizeof(PPC_W), \\
        sp+QUICKTHREADS_BLOCKI_FRAME_SIZE+QUICKTHREADS_START_FRAME_SIZE))
.fi

.SS "#\fBdefine\fP QUICKTHREADS_ARGT_INDEX   \fBQUICKTHREADS_ARG_INDEX\fP(1)"

.SS "#\fBdefine\fP QUICKTHREADS_ARGU_INDEX   \fBQUICKTHREADS_ARG_INDEX\fP(0)"

.SS "#\fBdefine\fP QUICKTHREADS_BLOCK_FPR_SAVE(\fBi\fP)   (\fBQUICKTHREADS_BLOCK_FRAME_SIZE\fP\-8+(\fBi\fP\-31)*8)"

.SS "#\fBdefine\fP QUICKTHREADS_BLOCK_FRAME_SIZE   	\fBPPC_ROUND_STACK\fP(\fBPPC_LINKAGE_AREA\fP+\fBPPC_FPR_SAVE_AREA\fP)"

.SS "#\fBdefine\fP QUICKTHREADS_BLOCKI_CR_SAVE   8"

.SS "#\fBdefine\fP QUICKTHREADS_BLOCKI_FRAME_SIZE   	\fBPPC_ROUND_STACK\fP(\fBPPC_LINKAGE_AREA\fP+4+\fBPPC_GPR_SAVE_AREA\fP)"

.SS "#\fBdefine\fP QUICKTHREADS_BLOCKI_GPR_SAVE(\fBi\fP)   (\fBQUICKTHREADS_BLOCKI_FRAME_SIZE\fP\-4+(\fBi\fP\-31)*4)"

.SS "#\fBdefine\fP QUICKTHREADS_GROW_DOWN"

.SS "#\fBdefine\fP QUICKTHREADS_ONLY_INDEX   \fBQUICKTHREADS_ARG_INDEX\fP(3)"

.SS "#\fBdefine\fP QUICKTHREADS_RETURN_INDEX   ((\fBQUICKTHREADS_BLOCKI_FRAME_SIZE\fP+\fBPPC_LR_SAVE\fP)/\fBsizeof\fP(\fBPPC_W\fP))"

.SS "#\fBdefine\fP QUICKTHREADS_START_FRAME_SIZE   \fBPPC_ROUND_STACK\fP(\fBPPC_LINKAGE_AREA\fP+\fBPPC_PARAM_AREA\fP(4))"

.SS "#\fBdefine\fP QUICKTHREADS_STKALIGN   \fBPPC_STACK_INCR\fP"

.SS "#\fBdefine\fP QUICKTHREADS_STKBASE   	(\fBQUICKTHREADS_BLOCKI_FRAME_SIZE\fP+\fBQUICKTHREADS_START_FRAME_SIZE\fP)"

.SS "#\fBdefine\fP QUICKTHREADS_USER_INDEX   \fBQUICKTHREADS_ARG_INDEX\fP(2)"

.SS "#\fBdefine\fP QUICKTHREADS_VARGS(\fBsp\fP, \fBnbytes\fP, \fBvargs\fP, \fBpt\fP, \fBstartup\fP, \fBvuserf\fP, \fBcleanup\fP)         ((\fBqt_t\fP *)\fBqt_vargs_stdarg\fP (\fBsp\fP, \fBnbytes\fP, \fBvargs\fP, \fBpt\fP, \fBstartup\fP, \fBvuserf\fP, \fBcleanup\fP))"

.SS "#\fBdefine\fP QUICKTHREADS_VARGS_BKOFF   \fBPPC_PARAM_AREA\fP(4+8)"

.SS "#\fBdefine\fP QUICKTHREADS_VARGS_DEFAULT"

.SS "#\fBdefine\fP QUICKTHREADS_VARGS_LOCAL_AREA   (4*4)		/* \fBlocal\fP \fBvariable\fP \fBarea\fP */"

.SS "#\fBdefine\fP QUICKTHREADS_VARGS_MD0(\fBsp\fP, \fBvarbytes\fP)"
\fBValue:\fP.PP
.nf
  ((qt_sp_bottom_save = sp), \\
  ((qt_t *)(((char *)(sp)) \- \\
        (QUICKTHREADS_VSTART_FRAME_SIZE(varbytes)\-QUICKTHREADS_VSTART_LIST_BASE))))
.fi

.SS "#\fBdefine\fP QUICKTHREADS_VARGS_MD1(\fBsp\fP)"
\fBValue:\fP.PP
.nf
    (QUICKTHREADS_SPUT (sp, QUICKTHREADS_RETURN_INDEX, qt_vstart), \\
	QUICKTHREADS_SPUT (sp, 0, sp+QUICKTHREADS_BLOCKI_FRAME_SIZE), \\
	QUICKTHREADS_SPUT (sp, (QUICKTHREADS_BLOCKI_FRAME_SIZE)/sizeof(PPC_W), \\
        qt_sp_bottom_save))
.fi

.SS "#\fBdefine\fP QUICKTHREADS_VARGT_INDEX   \fBQUICKTHREADS_ARG_INDEX\fP(0)"

.SS "#\fBdefine\fP QUICKTHREADS_VCLEANUP_INDEX   \fBQUICKTHREADS_ARG_INDEX\fP(3)"

.SS "#\fBdefine\fP QUICKTHREADS_VSTART_FRAME_SIZE(\fBvarbytes\fP)"
\fBValue:\fP.PP
.nf
    PPC_ROUND_STACK(PPC_LINKAGE_AREA+QUICKTHREADS_VARGS_BKOFF+(varbytes)+ \\
        QUICKTHREADS_VARGS_LOCAL_AREA)
.fi

.SS "#\fBdefine\fP QUICKTHREADS_VSTART_LIST_BASE   (\fBPPC_LINKAGE_AREA\fP+\fBPPC_PARAM_AREA\fP(4))"

.SS "#\fBdefine\fP QUICKTHREADS_VSTARTUP_INDEX   \fBQUICKTHREADS_ARG_INDEX\fP(1)"

.SS "#\fBdefine\fP QUICKTHREADS_VSTKBASE   (\fBQUICKTHREADS_BLOCKI_FRAME_SIZE\fP+\fBQUICKTHREADS_VSTART_LIST_BASE\fP)"

.SS "#\fBdefine\fP QUICKTHREADS_VUSERF_INDEX   \fBQUICKTHREADS_ARG_INDEX\fP(2)"

.SH "Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBunsigned\fP \fBlong\fP \fBPPC_W\fP"

.SS "\fBtypedef\fP \fBPPC_W\fP \fBqt_word_t\fP"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP qt_start (\fBvoid\fP)\fR [extern]\fP"

.SS "\fBvoid\fP qt_vstart (\fBvoid\fP)\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
