.TH "qt_meta_stringdata_EventFilter_t" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qt_meta_stringdata_EventFilter_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const uint \fBoffsetsAndSize\fP [2]"
.br
.ti -1c
.RI "char \fBstringdata0\fP [12]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "const uint qt_meta_stringdata_EventFilter_t::offsetsAndSize[2]"

.SS "char qt_meta_stringdata_EventFilter_t::stringdata0[12]"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
