.TH "qt_t" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
qt_t
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <qt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchar\fP \fBdummy\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBchar\fP qt_t::dummy"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
