.TH "QT_WARNING_DISABLE_DEPRECATED::qt_meta_stringdata_CLASSElementsDisplayENDCLASS_t" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QT_WARNING_DISABLE_DEPRECATED::qt_meta_stringdata_CLASSElementsDisplayENDCLASS_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint\fP \fBoffsetsAndSizes\fP [2]"
.br
.ti -1c
.RI "\fBchar\fP \fBstringdata0\fP [16]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuint\fP QT_WARNING_DISABLE_DEPRECATED::qt_meta_stringdata_CLASSElementsDisplayENDCLASS_t::offsetsAndSizes[2]"

.SS "\fBchar\fP QT_WARNING_DISABLE_DEPRECATED::qt_meta_stringdata_CLASSElementsDisplayENDCLASS_t::stringdata0[16]"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
