.TH "QT_WARNING_DISABLE_DEPRECATED::qt_meta_stringdata_CLASSSvgWidgetENDCLASS_t" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QT_WARNING_DISABLE_DEPRECATED::qt_meta_stringdata_CLASSSvgWidgetENDCLASS_t
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint\fP \fBoffsetsAndSizes\fP [8]"
.br
.ti -1c
.RI "\fBchar\fP \fBstringdata0\fP [10]"
.br
.ti -1c
.RI "\fBchar\fP \fBstringdata1\fP [12]"
.br
.ti -1c
.RI "\fBchar\fP \fBstringdata2\fP [1]"
.br
.ti -1c
.RI "\fBchar\fP \fBstringdata3\fP [6]"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuint\fP QT_WARNING_DISABLE_DEPRECATED::qt_meta_stringdata_CLASSSvgWidgetENDCLASS_t::offsetsAndSizes[8]"

.SS "\fBchar\fP QT_WARNING_DISABLE_DEPRECATED::qt_meta_stringdata_CLASSSvgWidgetENDCLASS_t::stringdata0[10]"

.SS "\fBchar\fP QT_WARNING_DISABLE_DEPRECATED::qt_meta_stringdata_CLASSSvgWidgetENDCLASS_t::stringdata1[12]"

.SS "\fBchar\fP QT_WARNING_DISABLE_DEPRECATED::qt_meta_stringdata_CLASSSvgWidgetENDCLASS_t::stringdata2[1]"

.SS "\fBchar\fP QT_WARNING_DISABLE_DEPRECATED::qt_meta_stringdata_CLASSSvgWidgetENDCLASS_t::stringdata3[6]"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
