.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/ref.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/ref.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <sysc/packages/boost/config\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/utility/addressof\&.hpp>\fP
.br
\fR#include <sysc/packages/boost/mpl/bool\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_boost::reference_wrapper< T >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::is_reference_wrapper< T >\fP"
.br
.ti -1c
.RI "class \fBsc_boost::unwrap_reference< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_boost\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_REF_CONST\fP   \fBconst\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_AUX_REFERENCE_WRAPPER_METAFUNCTIONS_DEF\fP(X)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBreference_wrapper\fP< \fBT\fP > \fBSC_BOOST_REF_CONST\fP \fBsc_boost::ref\fP (\fBT\fP &t)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBreference_wrapper\fP< \fBT\fP \fBconst\fP > \fBSC_BOOST_REF_CONST\fP \fBsc_boost::cref\fP (\fBT\fP \fBconst\fP &t)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_AUX_REFERENCE_WRAPPER_METAFUNCTIONS_DEF(X)"
\fBValue:\fP.PP
.nf
template<typename T> \\
class is_reference_wrapper< X > \\
    : public mpl::true_ \\
{ \\
}; \\
\\
template<typename T> \\
class unwrap_reference< X > \\
{ \\
 public: \\
    typedef T type; \\
}; \\
.fi

.SS "#\fBdefine\fP SC_BOOST_REF_CONST   \fBconst\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
