.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/stdlib/roguewave.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/stdlib/roguewave.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <utility>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_RWSTD_VER\fP   0x010000"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_STDLIB\fP   'Rogue \fBWave\fP \fBstandard\fP \fBlibrary\fP \fBversion\fP (\fBUnknown\fP \fBversion\fP)'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_LIMITS_COMPILE_TIME_CONSTANTS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_LONG_LONG_NUMERIC_LIMITS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_ITERATOR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_AUTO_PTR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STRINGSTREAM\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_ALLOCATOR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_LOCALE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_ALLOCATOR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_DISTANCE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_OUTPUT_ITERATOR_ASSIGN\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_NO_AUTO_PTR"

.SS "#\fBdefine\fP SC_BOOST_NO_LIMITS_COMPILE_TIME_CONSTANTS"

.SS "#\fBdefine\fP SC_BOOST_NO_LONG_LONG_NUMERIC_LIMITS"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_ALLOCATOR"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_ALLOCATOR"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_DISTANCE"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_ITERATOR"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_LOCALE"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_OUTPUT_ITERATOR_ASSIGN"

.SS "#\fBdefine\fP SC_BOOST_NO_STRINGSTREAM"

.SS "#\fBdefine\fP SC_BOOST_RWSTD_VER   0x010000"

.SS "#\fBdefine\fP SC_BOOST_STDLIB   'Rogue \fBWave\fP \fBstandard\fP \fBlibrary\fP \fBversion\fP (\fBUnknown\fP \fBversion\fP)'"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
