.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemC Directory Reference" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemC Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBsystemc_modules\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBnotmain\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsc_t_gates\&.h\fP"
.br
.ti -1c
.RI "file \fBsystemcbuilder\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsystemcbuilder\&.h\fP"
.br
.in -1c
