.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/build/Desktop_Qt_6_2_2_MinGW_64_bit-Debug Directory Reference" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/build/Desktop_Qt_6_2_2_MinGW_64_bit-Debug Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBdebug\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBui_mainwindow\&.h\fP"
.br
.in -1c
