.TH "s_element_io" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_element_io
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ComponentsStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQString\fP \fBname\fP"
.br
.RI "Name of the I/O\&. "
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.RI "Width of the I/O\&. "
.ti -1c
.RI "\fBQString\fP \fBconnected_to\fP"
.br
.RI "Connected to\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBQString\fP s_element_io::connected_to"

.PP
Connected to\&. 
.SS "\fBQString\fP s_element_io::name"

.PP
Name of the I/O\&. 
.SS "\fBint\fP s_element_io::width"

.PP
Width of the I/O\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
