.TH "s_elements" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_elements
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ComponentsStruct\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBisEmpty\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQList\fP< \fBs_element\fP > \fBelements_list\fP"
.br
.RI "List of elements\&. "
.ti -1c
.RI "\fBs_parse_error\fP \fBerror\fP"
.br
.RI "Error\&. "
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP s_elements::isEmpty () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBQList\fP<\fBs_element\fP> s_elements::elements_list"

.PP
List of elements\&. 
.SS "\fBs_parse_error\fP s_elements::error"

.PP
Error\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
