.TH "s_element" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_element
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ComponentsStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQString\fP \fBname\fP"
.br
.RI "Name of the element\&. "
.ti -1c
.RI "\fBQString\fP \fBdevice\fP"
.br
.RI "Device of the element\&. "
.ti -1c
.RI "\fBQString\fP \fBlabel\fP"
.br
.RI "Label of the element\&. "
.ti -1c
.RI "\fBQList\fP< \fBs_element_io\fP > \fBinputs\fP"
.br
.RI "List of inputs\&. "
.ti -1c
.RI "\fBQList\fP< \fBs_element_io\fP > \fBoutputs\fP"
.br
.RI "List of outputs\&. "
.ti -1c
.RI "\fBint\fP \fBinputs_number\fP"
.br
.RI "Number of inputs\&. "
.ti -1c
.RI "\fBint\fP \fBoutputs_number\fP"
.br
.RI "Number of outputs\&. "
.ti -1c
.RI "\fBs_parse_error\fP \fBerror\fP"
.br
.RI "Error\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBQString\fP s_element::device"

.PP
Device of the element\&. 
.SS "\fBs_parse_error\fP s_element::error"

.PP
Error\&. 
.SS "\fBQList\fP<\fBs_element_io\fP> s_element::inputs"

.PP
List of inputs\&. 
.SS "\fBint\fP s_element::inputs_number"

.PP
Number of inputs\&. 
.SS "\fBQString\fP s_element::label"

.PP
Label of the element\&. 
.SS "\fBQString\fP s_element::name"

.PP
Name of the element\&. 
.SS "\fBQList\fP<\fBs_element_io\fP> s_element::outputs"

.PP
List of outputs\&. 
.SS "\fBint\fP s_element::outputs_number"

.PP
Number of outputs\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
