.TH "s_parse_error" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_parse_error
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ComponentsStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBis_parse_error\fP"
.br
.RI "Flag indicating parsing error\&. "
.ti -1c
.RI "\fBQList\fP< \fBQString\fP > \fBerror_messages\fP"
.br
.RI "Error messages\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBQList\fP<\fBQString\fP> s_parse_error::error_messages"

.PP
Error messages\&. 
.SS "\fBbool\fP s_parse_error::is_parse_error"

.PP
Flag indicating parsing error\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
