.TH "s_sim_wire" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_sim_wire
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ComponentsStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQString\fP \fBname\fP"
.br
.RI "Wire name\&. "
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.RI "Wire width\&. "
.ti -1c
.RI "\fBQString\fP \fBconnected_to\fP"
.br
.RI "Connected to\&. "
.ti -1c
.RI "\fBs_parse_error\fP \fBerror\fP"
.br
.RI "Error\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBQString\fP s_sim_wire::connected_to"

.PP
Connected to\&. 
.SS "\fBs_parse_error\fP s_sim_wire::error"

.PP
Error\&. 
.SS "\fBQString\fP s_sim_wire::name"

.PP
Wire name\&. 
.SS "\fBint\fP s_sim_wire::width"

.PP
Wire width\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
