.TH "s_sim_I_O" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_sim_I_O
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ComponentsStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQString\fP \fBname\fP"
.br
.RI "Name of the component\&. "
.ti -1c
.RI "\fBint\fP \fBwidth\fP"
.br
.RI "Width of the component\&. "
.ti -1c
.RI "\fBe_IO_type\fP \fBtype\fP"
.br
.RI "Type of the I/O\&. "
.ti -1c
.RI "\fBQString\fP \fBconnected_to\fP"
.br
.RI "Connected to (if output)\&. "
.ti -1c
.RI "\fBs_parse_error\fP \fBerror\fP"
.br
.RI "Error\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBQString\fP s_sim_I_O::connected_to"

.PP
Connected to (if output)\&. 
.SS "\fBs_parse_error\fP s_sim_I_O::error"

.PP
Error\&. 
.SS "\fBQString\fP s_sim_I_O::name"

.PP
Name of the component\&. 
.SS "\fBe_IO_type\fP s_sim_I_O::type"

.PP
Type of the I/O\&. 
.SS "\fBint\fP s_sim_I_O::width"

.PP
Width of the component\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
