.TH "s_sim_wires" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_sim_wires
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ComponentsStruct\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQList\fP< \fBs_sim_wire\fP > \fBwires\fP"
.br
.RI "List of wires\&. "
.ti -1c
.RI "\fBs_parse_error\fP \fBerror\fP"
.br
.RI "Error\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBs_parse_error\fP s_sim_wires::error"

.PP
Error\&. 
.SS "\fBQList\fP<\fBs_sim_wire\fP> s_sim_wires::wires"

.PP
List of wires\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
