.TH "s_style" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
s_style \- Represents a style with default and 'on' states\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Represents a style with default and 'on' states\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
