.TH "systemc_modules/sc_arith.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
systemc_modules/sc_arith.h
.SH SYNOPSIS
.br
.PP
\fR#include <systemc\&.h>\fP
.br
\fR#include 'sc_gates\&.h'\fP
.br
\fR#include 'sc_gates_pv\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSyscAdd< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscAdd_pv< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscSub< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscSub_pv< N, W >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
