.TH "sc_boost::detail" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::detail
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBstring_view_traits_eq\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBclass\fP \fBcharT\fP , \fBclass\fP \fBtraits\fP > \fBvoid\fP \fBsv_insert_fill_chars\fP (std::basic_ostream< \fBcharT\fP, \fBtraits\fP > &\fBos\fP, std::size_t \fBn\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBcharT\fP , \fBclass\fP \fBtraits\fP > \fBvoid\fP \fBsv_insert_aligned\fP (std::basic_ostream< \fBcharT\fP, \fBtraits\fP > &\fBos\fP, \fBconst\fP \fBbasic_string_view\fP< \fBcharT\fP, \fBtraits\fP > &\fBstr\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBcharT\fP , \fBclass\fP \fBtraits\fP > \fBvoid\fP sc_boost::detail::sv_insert_aligned (std::basic_ostream< \fBcharT\fP, \fBtraits\fP > & os, \fBconst\fP \fBbasic_string_view\fP< \fBcharT\fP, \fBtraits\fP > & str)"

.SS "template<\fBclass\fP \fBcharT\fP , \fBclass\fP \fBtraits\fP > \fBvoid\fP sc_boost::detail::sv_insert_fill_chars (std::basic_ostream< \fBcharT\fP, \fBtraits\fP > & os, std::size_t n)\fR [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
