.TH "sc_boost::_bi::add_value< value< T > >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::_bi::add_value< value< T > >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bind\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fB_bi::value\fP< \fBT\fP > \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fB_bi::value\fP<\fBT\fP> \fBsc_boost::_bi::add_value\fP< \fBvalue\fP< \fBT\fP > >::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
