.TH "sc_boost::disable_if_c< B, T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::disable_if_c< B, T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <enable_if\&.hpp>\fP
.PP
Inherited by \fBsc_boost::disable_if< Cond, T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBT\fP \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBbool\fP B, \fBclass\fP \fBT\fP  = void> \fBtypedef\fP \fBT\fP \fBsc_boost::disable_if_c\fP< \fBB\fP, \fBT\fP >::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
