.TH "sc_boost::_bi::bind_t< R, F, L >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::_bi::bind_t< R, F, L >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bind\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBbind_t\fP \fBthis_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbind_t\fP (F f, \fBL\fP \fBconst\fP &\fBl\fP)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBL\fP > \fBtypedef\fP \fBbind_t\fP \fBsc_boost::_bi::bind_t\fP< \fBR\fP, F, \fBL\fP >::this_type"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBL\fP > \fBsc_boost::_bi::bind_t\fP< \fBR\fP, F, \fBL\fP >::bind_t (F f, \fBL\fP \fBconst\fP & l)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
