.TH "sc_boost::_bi::value< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::_bi::value< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bind\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvalue\fP (\fBT\fP \fBconst\fP &t)"
.br
.ti -1c
.RI "\fBT\fP & \fBget\fP ()"
.br
.ti -1c
.RI "\fBT\fP \fBconst\fP & \fBget\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBvalue\fP \fBconst\fP &\fBrhs\fP) \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP \fBt_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_boost::_bi::value\fP< \fBT\fP >::value (\fBT\fP \fBconst\fP & t)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBT\fP & \fBsc_boost::_bi::value\fP< \fBT\fP >::get ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBconst\fP  & \fBsc_boost::_bi::value\fP< \fBT\fP >::get () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBbool\fP \fBsc_boost::_bi::value\fP< \fBT\fP >\fB::operator\fP== (\fBvalue\fP< \fBT\fP > \fBconst\fP & rhs) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBsc_boost::_bi::value\fP< \fBT\fP >::t_\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
