.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/bit/sc_bit_ids.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/bit/sc_bit_ids.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/utils/sc_report\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_DEFINE_MESSAGE\fP(id,  \fBunused1\fP,  \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_LENGTH_MISMATCH_\fP, 200, 'length \fBmismatch\fP \fBin\fP bit/\fBlogic\fP vector \fBassignment'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_INCOMPATIBLE_TYPES_\fP"
.br
.ti -1c
.RI "\fBincompatible\fP \fBtypes\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_CANNOT_CONVERT_\fP, 202, 'cannot \fBperform\fP \fBconversion'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_INCOMPATIBLE_VECTORS_\fP"
.br
.ti -1c
.RI "\fBincompatible\fP \fBtypes\fP \fBincompatible\fP \fBvectors\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_VALUE_NOT_VALID_\fP, 204, 'value \fBis\fP \fBnot\fP \fBvalid'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_ZERO_LENGTH_\fP"
.br
.ti -1c
.RI "\fBincompatible\fP \fBtypes\fP \fBincompatible\fP \fBvectors\fP \fBzero\fP length \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_VECTOR_CONTAINS_LOGIC_VALUE_\fP, 206, 'vector contains 4\-\fBvalue\fP \fBlogic'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_SC_BV_CANNOT_CONTAIN_X_AND_Z_\fP"
.br
.ti -1c
.RI "\fBincompatible\fP \fBtypes\fP \fBincompatible\fP \fBvectors\fP \fBzero\fP length sc_bv \fBcannot\fP \fBcontain\fP \fBvalues\fP X \fBand\fP \fBZ\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_VECTOR_TOO_LONG_\fP, 208, 'vector \fBis\fP \fBtoo\fP \fBlong:\fP \fBtruncated'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_VECTOR_TOO_SHORT_\fP"
.br
.ti -1c
.RI "\fBincompatible\fP \fBtypes\fP \fBincompatible\fP \fBvectors\fP \fBzero\fP length sc_bv \fBcannot\fP \fBcontain\fP \fBvalues\fP X \fBand\fP \fBZ\fP vector \fBis\fP \fBtoo\fP \fBwrong\fP \fBvalue\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_LOGIC_Z_TO_BOOL_\fP, 211, 'sc_logic \fBvalue\fP '\fBZ\fP' \fBcannot\fP \fBbe\fP \fBconverted\fP \fBto\fP \fBbool'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_LOGIC_X_TO_BOOL_\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBincompatible\fP \fBtypes\fP \fBincompatible\fP \fBvectors\fP \fBzero\fP length sc_bv \fBcannot\fP \fBcontain\fP \fBvalues\fP X \fBand\fP \fBZ\fP vector \fBis\fP \fBtoo\fP \fBshort\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_DEFINE_MESSAGE(id, \fBunused1\fP, \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"

.SH "Function Documentation"
.PP 
.SS "\fBincompatible\fP \fBtypes\fP SC_DEFINE_MESSAGE (\fBSC_ID_CANNOT_CONVERT_\fP, 202, 'cannot \fBperform\fP \fBconversion'\fP)"

.SS "SC_DEFINE_MESSAGE (\fBSC_ID_LENGTH_MISMATCH_\fP, 200, 'length \fBmismatch\fP \fBin\fP bit/\fBlogic\fP vector \fBassignment'\fP)"

.SS "\fBincompatible\fP \fBtypes\fP \fBincompatible\fP \fBvectors\fP \fBzero\fP length sc_bv \fBcannot\fP \fBcontain\fP \fBvalues\fP X \fBand\fP \fBZ\fP vector \fBis\fP \fBtoo\fP \fBwrong\fP \fBvalue\fP SC_DEFINE_MESSAGE (\fBSC_ID_LOGIC_Z_TO_BOOL_\fP, 211, 'sc_logic \fBvalue\fP '\fBZ\fP' \fBcannot\fP \fBbe\fP \fBconverted\fP \fBto\fP \fBbool'\fP)"

.SS "\fBincompatible\fP \fBtypes\fP \fBincompatible\fP \fBvectors\fP SC_DEFINE_MESSAGE (\fBSC_ID_VALUE_NOT_VALID_\fP, 204, 'value \fBis\fP \fBnot\fP \fBvalid'\fP)"

.SS "\fBincompatible\fP \fBtypes\fP \fBincompatible\fP \fBvectors\fP \fBzero\fP length SC_DEFINE_MESSAGE (\fBSC_ID_VECTOR_CONTAINS_LOGIC_VALUE_\fP, 206, 'vector contains 4\-\fBvalue\fP \fBlogic'\fP)"

.SS "\fBincompatible\fP \fBtypes\fP \fBincompatible\fP \fBvectors\fP \fBzero\fP length sc_bv \fBcannot\fP \fBcontain\fP \fBvalues\fP X \fBand\fP \fBZ\fP SC_DEFINE_MESSAGE (\fBSC_ID_VECTOR_TOO_LONG_\fP, 208, 'vector \fBis\fP \fBtoo\fP \fBlong:\fP \fBtruncated'\fP)"

.SH "Variable Documentation"
.PP 
.SS "\fBincompatible\fP \fBtypes\fP \fBincompatible\fP \fBvectors\fP \fBzero\fP length sc_bv \fBcannot\fP \fBcontain\fP \fBvalues\fP X \fBand\fP \fBZ\fP vector \fBis\fP \fBtoo\fP short"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
