.TH "sc_boost::reference_wrapper< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::reference_wrapper< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ref\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBT\fP \fBtype\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBreference_wrapper\fP (\fBT\fP &t)"
.br
.ti -1c
.RI "\fBoperator T&\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBT\fP & \fBget\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBT\fP * \fBget_pointer\fP () \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP * \fBt_\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fBT\fP \fBsc_boost::reference_wrapper\fP< \fBT\fP >::type"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_boost::reference_wrapper\fP< \fBT\fP >::reference_wrapper (\fBT\fP & t)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBT\fP & \fBsc_boost::reference_wrapper\fP< \fBT\fP >::get () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP * \fBsc_boost::reference_wrapper\fP< \fBT\fP >::get_pointer () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_boost::reference_wrapper\fP< \fBT\fP >\fB::operator\fP \fBT\fP& () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBT\fP* \fBsc_boost::reference_wrapper\fP< \fBT\fP >::t_\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
