.TH "sc_boost::_mfi::dm< R, T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::_mfi::dm< R, T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <mem_fn\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBR\fP \fBconst\fP  & \fBresult_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBT\fP \fBconst\fP  * \fBargument_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdm\fP (\fBF\fP f)"
.br
.ti -1c
.RI "\fBR\fP & \fBoperator()\fP (\fBT\fP *p) \fBconst\fP"
.br
.ti -1c
.RI "\fBR\fP \fBconst\fP & \fBoperator()\fP (\fBT\fP \fBconst\fP *p) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP \fBU\fP > \fBR\fP \fBconst\fP & \fBoperator()\fP (\fBU\fP &\fBu\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBR\fP & \fBoperator()\fP (\fBT\fP &t) \fBconst\fP"
.br
.ti -1c
.RI "\fBR\fP \fBconst\fP & \fBoperator()\fP (\fBT\fP \fBconst\fP &t) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBdm\fP \fBconst\fP &\fBrhs\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBdm\fP \fBconst\fP &\fBrhs\fP) \fBconst\fP"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP RT::* \fBF\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "template<\fBclass\fP \fBU\fP > \fBR\fP \fBconst\fP & \fBcall\fP (\fBU\fP &\fBu\fP, \fBT\fP \fBconst\fP *) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP \fBU\fP > \fBR\fP & \fBcall\fP (\fBU\fP &\fBu\fP, \fBT\fP *) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP \fBU\fP > \fBR\fP \fBconst\fP & \fBcall\fP (\fBU\fP &\fBu\fP, \fBvoid\fP \fBconst\fP *) \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBF\fP \fBf_\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fBtypedef\fP \fBT\fP \fBconst\fP* \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >::argument_type"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fBtypedef\fP RT::* \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >::F\fR [private]\fP"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fBtypedef\fP \fBR\fP \fBconst\fP& \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >\fB::result_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >::dm (\fBF\fP f)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > template<\fBclass\fP \fBU\fP > \fBR\fP & \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >::call (\fBU\fP & u, \fBT\fP *) const\fR [inline]\fP, \fR [private]\fP"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > template<\fBclass\fP \fBU\fP > \fBR\fP \fBconst\fP  & \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >::call (\fBU\fP & u, \fBT\fP \fBconst\fP *) const\fR [inline]\fP, \fR [private]\fP"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > template<\fBclass\fP \fBU\fP > \fBR\fP \fBconst\fP  & \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >::call (\fBU\fP & u, \fBvoid\fP \fBconst\fP *) const\fR [inline]\fP, \fR [private]\fP"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fBbool\fP \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >::operator!= (\fBdm\fP< \fBR\fP, \fBT\fP > \fBconst\fP & rhs) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fBR\fP & \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >\fB::operator\fP() (\fBT\fP & t) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fBR\fP & \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >\fB::operator\fP() (\fBT\fP * p) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fBR\fP \fBconst\fP  & \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >\fB::operator\fP() (\fBT\fP \fBconst\fP & t) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fBR\fP \fBconst\fP  & \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >\fB::operator\fP() (\fBT\fP \fBconst\fP * p) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > template<\fBclass\fP \fBU\fP > \fBR\fP \fBconst\fP  & \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >\fB::operator\fP() (\fBU\fP & u) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fBbool\fP \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >\fB::operator\fP== (\fBdm\fP< \fBR\fP, \fBT\fP > \fBconst\fP & rhs) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBT\fP > \fBF\fP \fBsc_boost::_mfi::dm\fP< \fBR\fP, \fBT\fP >::f_\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
