.TH "sc_boost::unwrap_reference< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::unwrap_reference< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ref\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBT\fP \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBtypedef\fP \fBT\fP \fBsc_boost::unwrap_reference\fP< \fBT\fP >::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
