.TH "sc_boost::_bi::add_value< arg< I >(*)() >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::_bi::add_value< arg< I >(*)() >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bind\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_boost::arg\fP< \fBI\fP >(* \fBtype\fP) ()"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<int I> \fBtypedef\fP \fBsc_boost::arg\fP< \fBI\fP >(* \fBsc_boost::_bi::add_value\fP< \fBarg\fP< \fBI\fP >(*)() >::type) ()"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
