.TH "sc_boost::_bi::af0< R, F >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::_bi::af0< R, F >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <make_adaptable\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBR\fP \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaf0\fP (F f)"
.br
.ti -1c
.RI "\fBresult_type\fP \fBoperator()\fP ()"
.br
.ti -1c
.RI "\fBresult_type\fP \fBoperator()\fP () \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "F \fBf_\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP F > \fBtypedef\fP \fBR\fP \fBsc_boost::_bi::af0\fP< \fBR\fP, F >\fB::result_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP F > \fBsc_boost::_bi::af0\fP< \fBR\fP, F >::af0 (F f)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP F > \fBresult_type\fP \fBsc_boost::_bi::af0\fP< \fBR\fP, F >\fB::operator\fP() ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP F > \fBresult_type\fP \fBsc_boost::_bi::af0\fP< \fBR\fP, F >\fB::operator\fP() () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP F > F \fBsc_boost::_bi::af0\fP< \fBR\fP, F >::f_\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
