.TH "sc_boost::_bi::add_value< bind_t< R, F, L > >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::_bi::add_value< bind_t< R, F, L > >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bind\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBbind_t\fP< \fBR\fP, F, \fBL\fP > \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBL\fP > \fBtypedef\fP \fBbind_t\fP<\fBR\fP, F, \fBL\fP> \fBsc_boost::_bi::add_value\fP< \fBbind_t\fP< \fBR\fP, F, \fBL\fP > >::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
