.TH "sc_boost::is_reference_wrapper< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::is_reference_wrapper< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ref\&.hpp>\fP
.PP
Inherits mpl::false_\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
