.TH "sc_boost::apply< R >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::apply< R >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <apply\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBR\fP \fBresult_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<\fBclass\fP F > \fBresult_type\fP \fBoperator()\fP (F &f) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP > \fBresult_type\fP \fBoperator()\fP (F &f, \fBA1\fP &a1) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP > \fBresult_type\fP \fBoperator()\fP (F &f, \fBA1\fP &a1, \fBA2\fP &\fBa2\fP) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP > \fBresult_type\fP \fBoperator()\fP (F &f, \fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBresult_type\fP \fBoperator()\fP (F &f, \fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP, \fBA4\fP &\fBa4\fP) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP > \fBresult_type\fP \fBoperator()\fP (F &f, \fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP, \fBA4\fP &\fBa4\fP, \fBA5\fP &\fBa5\fP) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP > \fBresult_type\fP \fBoperator()\fP (F &f, \fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP, \fBA4\fP &\fBa4\fP, \fBA5\fP &\fBa5\fP, \fBA6\fP &\fBa6\fP) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP > \fBresult_type\fP \fBoperator()\fP (F &f, \fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP, \fBA4\fP &\fBa4\fP, \fBA5\fP &\fBa5\fP, \fBA6\fP &\fBa6\fP, \fBA7\fP &\fBa7\fP) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP > \fBresult_type\fP \fBoperator()\fP (F &f, \fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP, \fBA4\fP &\fBa4\fP, \fBA5\fP &\fBa5\fP, \fBA6\fP &\fBa6\fP, \fBA7\fP &\fBa7\fP, \fBA8\fP &\fBa8\fP) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP , \fBclass\fP \fBA9\fP > \fBresult_type\fP \fBoperator()\fP (F &f, \fBA1\fP &a1, \fBA2\fP &\fBa2\fP, \fBA3\fP &\fBa3\fP, \fBA4\fP &\fBa4\fP, \fBA5\fP &\fBa5\fP, \fBA6\fP &\fBa6\fP, \fBA7\fP &\fBa7\fP, \fBA8\fP &\fBa8\fP, \fBA9\fP &\fBa9\fP) \fBconst\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP > \fBtypedef\fP \fBR\fP \fBsc_boost::apply\fP< \fBR\fP >\fB::result_type\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP > template<\fBclass\fP F > \fBresult_type\fP \fBsc_boost::apply\fP< \fBR\fP >\fB::operator\fP() (F & f) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP > template<\fBclass\fP F , \fBclass\fP \fBA1\fP > \fBresult_type\fP \fBsc_boost::apply\fP< \fBR\fP >\fB::operator\fP() (F & f, \fBA1\fP & a1) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP > template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP > \fBresult_type\fP \fBsc_boost::apply\fP< \fBR\fP >\fB::operator\fP() (F & f, \fBA1\fP & a1, \fBA2\fP & a2) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP > template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP > \fBresult_type\fP \fBsc_boost::apply\fP< \fBR\fP >\fB::operator\fP() (F & f, \fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP > template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBresult_type\fP \fBsc_boost::apply\fP< \fBR\fP >\fB::operator\fP() (F & f, \fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3, \fBA4\fP & a4) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP > template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP > \fBresult_type\fP \fBsc_boost::apply\fP< \fBR\fP >\fB::operator\fP() (F & f, \fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3, \fBA4\fP & a4, \fBA5\fP & a5) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP > template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP > \fBresult_type\fP \fBsc_boost::apply\fP< \fBR\fP >\fB::operator\fP() (F & f, \fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3, \fBA4\fP & a4, \fBA5\fP & a5, \fBA6\fP & a6) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP > template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP > \fBresult_type\fP \fBsc_boost::apply\fP< \fBR\fP >\fB::operator\fP() (F & f, \fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3, \fBA4\fP & a4, \fBA5\fP & a5, \fBA6\fP & a6, \fBA7\fP & a7) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP > template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP > \fBresult_type\fP \fBsc_boost::apply\fP< \fBR\fP >\fB::operator\fP() (F & f, \fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3, \fBA4\fP & a4, \fBA5\fP & a5, \fBA6\fP & a6, \fBA7\fP & a7, \fBA8\fP & a8) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP > template<\fBclass\fP F , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP , \fBclass\fP \fBA5\fP , \fBclass\fP \fBA6\fP , \fBclass\fP \fBA7\fP , \fBclass\fP \fBA8\fP , \fBclass\fP \fBA9\fP > \fBresult_type\fP \fBsc_boost::apply\fP< \fBR\fP >\fB::operator\fP() (F & f, \fBA1\fP & a1, \fBA2\fP & a2, \fBA3\fP & a3, \fBA4\fP & a4, \fBA5\fP & a5, \fBA6\fP & a6, \fBA7\fP & a7, \fBA8\fP & a8, \fBA9\fP & a9) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
