.TH "sc_boost::detail::string_view_traits_eq< charT, traits >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::detail::string_view_traits_eq< charT, traits >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <string_view\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstring_view_traits_eq\fP (\fBcharT\fP \fBch\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator()\fP (\fBcharT\fP \fBval\fP) \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcharT\fP \fBch_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBcharT\fP , \fBtypename\fP \fBtraits\fP > \fBsc_boost::detail::string_view_traits_eq\fP< \fBcharT\fP, \fBtraits\fP >::string_view_traits_eq (\fBcharT\fP ch)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBcharT\fP , \fBtypename\fP \fBtraits\fP > \fBbool\fP \fBsc_boost::detail::string_view_traits_eq\fP< \fBcharT\fP, \fBtraits\fP >\fB::operator\fP() (\fBcharT\fP val) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBcharT\fP , \fBtypename\fP \fBtraits\fP > \fBcharT\fP \fBsc_boost::detail::string_view_traits_eq\fP< \fBcharT\fP, \fBtraits\fP >::ch_"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
