.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/bit/sc_bit_proxies.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/bit/sc_bit_proxies.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/datatypes/bit/sc_bit_ids\&.h'\fP
.br
\fR#include 'sysc/datatypes/bit/sc_proxy\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_dt::sc_bitref_conv_r< T, Traits >\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_bitref_conv_r< T, sc_proxy_traits< sc_bv_base > >\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_bitref_r< T >\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_bitref< X >\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_subref_r< X >\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_subref< X >\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_concref_r< X, Y >\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_concref< X, Y >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_dt\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_logic\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_bitref_r\fP< \fBT1\fP > &\fBa\fP, \fBconst\fP \fBsc_bitref_r\fP< \fBT2\fP > &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_logic\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_bitref_r\fP< \fBT1\fP > &\fBa\fP, \fBconst\fP \fBsc_bitref_r\fP< \fBT2\fP > &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_logic\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_bitref_r\fP< \fBT1\fP > &\fBa\fP, \fBconst\fP \fBsc_bitref_r\fP< \fBT2\fP > &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_bitref_r\fP< \fBT1\fP > &\fBa\fP, \fBconst\fP \fBsc_bitref_r\fP< \fBT2\fP > &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_bitref_r\fP< \fBT1\fP > &\fBa\fP, \fBconst\fP \fBsc_bitref_r\fP< \fBT2\fP > &\fBb\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT1\fP >, \fBsc_bitref_r\fP< \fBT2\fP > > \fBsc_dt::operator,\fP (\fBsc_bitref_r\fP< \fBT1\fP >, \fBsc_bitref_r\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT1\fP >, \fBsc_subref_r\fP< \fBT2\fP > > \fBsc_dt::operator,\fP (\fBsc_bitref_r\fP< \fBT1\fP >, \fBsc_subref_r\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT1\fP >, \fBsc_concref_r\fP< \fBT2\fP, \fBT3\fP > > \fBsc_dt::operator,\fP (\fBsc_bitref_r\fP< \fBT1\fP >, \fBsc_concref_r\fP< \fBT2\fP, \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT1\fP >, \fBT2\fP > \fBsc_dt::operator,\fP (\fBsc_bitref_r\fP< \fBT1\fP >, \fBconst\fP \fBsc_proxy\fP< \fBT2\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT\fP >, \fBsc_lv_base\fP > \fBsc_dt::operator,\fP (\fBsc_bitref_r\fP< \fBT\fP >, \fBconst\fP \fBchar\fP *)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_bitref_r\fP< \fBT\fP > > \fBsc_dt::operator,\fP (\fBconst\fP \fBchar\fP *, \fBsc_bitref_r\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT\fP >, \fBsc_lv_base\fP > \fBsc_dt::operator,\fP (\fBsc_bitref_r\fP< \fBT\fP >, \fBconst\fP \fBsc_logic\fP &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_bitref_r\fP< \fBT\fP > > \fBsc_dt::operator,\fP (\fBconst\fP \fBsc_logic\fP &, \fBsc_bitref_r\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT\fP >, \fBsc_lv_base\fP > \fBsc_dt::operator,\fP (\fBsc_bitref_r\fP< \fBT\fP >, \fBbool\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_bitref_r\fP< \fBT\fP > > \fBsc_dt::operator,\fP (\fBbool\fP, \fBsc_bitref_r\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT1\fP >, \fBsc_bitref_r\fP< \fBT2\fP > > \fBsc_dt::concat\fP (\fBsc_bitref_r\fP< \fBT1\fP >, \fBsc_bitref_r\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT1\fP >, \fBsc_subref_r\fP< \fBT2\fP > > \fBsc_dt::concat\fP (\fBsc_bitref_r\fP< \fBT1\fP >, \fBsc_subref_r\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT1\fP >, \fBsc_concref_r\fP< \fBT2\fP, \fBT3\fP > > \fBsc_dt::concat\fP (\fBsc_bitref_r\fP< \fBT1\fP >, \fBsc_concref_r\fP< \fBT2\fP, \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT1\fP >, \fBT2\fP > \fBsc_dt::concat\fP (\fBsc_bitref_r\fP< \fBT1\fP >, \fBconst\fP \fBsc_proxy\fP< \fBT2\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT\fP >, \fBsc_lv_base\fP > \fBsc_dt::concat\fP (\fBsc_bitref_r\fP< \fBT\fP >, \fBconst\fP \fBchar\fP *)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_bitref_r\fP< \fBT\fP > > \fBsc_dt::concat\fP (\fBconst\fP \fBchar\fP *, \fBsc_bitref_r\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT\fP >, \fBsc_lv_base\fP > \fBsc_dt::concat\fP (\fBsc_bitref_r\fP< \fBT\fP >, \fBconst\fP \fBsc_logic\fP &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_bitref_r\fP< \fBT\fP > > \fBsc_dt::concat\fP (\fBconst\fP \fBsc_logic\fP &, \fBsc_bitref_r\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_bitref_r\fP< \fBT\fP >, \fBsc_lv_base\fP > \fBsc_dt::concat\fP (\fBsc_bitref_r\fP< \fBT\fP >, \fBbool\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_bitref_r\fP< \fBT\fP > > \fBsc_dt::concat\fP (\fBbool\fP, \fBsc_bitref_r\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBsc_bitref\fP< \fBT1\fP >, \fBsc_bitref\fP< \fBT2\fP > > \fBsc_dt::operator,\fP (\fBsc_bitref\fP< \fBT1\fP >, \fBsc_bitref\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBsc_bitref\fP< \fBT1\fP >, \fBsc_subref\fP< \fBT2\fP > > \fBsc_dt::operator,\fP (\fBsc_bitref\fP< \fBT1\fP >, \fBsc_subref\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref\fP< \fBsc_bitref\fP< \fBT1\fP >, \fBsc_concref\fP< \fBT2\fP, \fBT3\fP > > \fBsc_dt::operator,\fP (\fBsc_bitref\fP< \fBT1\fP >, \fBsc_concref\fP< \fBT2\fP, \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBsc_bitref\fP< \fBT1\fP >, \fBT2\fP > \fBsc_dt::operator,\fP (\fBsc_bitref\fP< \fBT1\fP >, \fBsc_proxy\fP< \fBT2\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBsc_bitref\fP< \fBT1\fP >, \fBsc_bitref\fP< \fBT2\fP > > \fBsc_dt::concat\fP (\fBsc_bitref\fP< \fBT1\fP >, \fBsc_bitref\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBsc_bitref\fP< \fBT1\fP >, \fBsc_subref\fP< \fBT2\fP > > \fBsc_dt::concat\fP (\fBsc_bitref\fP< \fBT1\fP >, \fBsc_subref\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref\fP< \fBsc_bitref\fP< \fBT1\fP >, \fBsc_concref\fP< \fBT2\fP, \fBT3\fP > > \fBsc_dt::concat\fP (\fBsc_bitref\fP< \fBT1\fP >, \fBsc_concref\fP< \fBT2\fP, \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBsc_bitref\fP< \fBT1\fP >, \fBT2\fP > \fBsc_dt::concat\fP (\fBsc_bitref\fP< \fBT1\fP >, \fBsc_proxy\fP< \fBT2\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > ::std::istream & \fBsc_dt::operator>>\fP (::std::istream &, \fBsc_bitref\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT1\fP >, \fBsc_bitref_r\fP< \fBT2\fP > > \fBsc_dt::operator,\fP (\fBsc_subref_r\fP< \fBT1\fP >, \fBsc_bitref_r\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT1\fP >, \fBsc_subref_r\fP< \fBT2\fP > > \fBsc_dt::operator,\fP (\fBsc_subref_r\fP< \fBT1\fP >, \fBsc_subref_r\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT1\fP >, \fBsc_concref_r\fP< \fBT2\fP, \fBT3\fP > > \fBsc_dt::operator,\fP (\fBsc_subref_r\fP< \fBT1\fP >, \fBsc_concref_r\fP< \fBT2\fP, \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT1\fP >, \fBT2\fP > \fBsc_dt::operator,\fP (\fBsc_subref_r\fP< \fBT1\fP >, \fBconst\fP \fBsc_proxy\fP< \fBT2\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT\fP >, \fBsc_lv_base\fP > \fBsc_dt::operator,\fP (\fBsc_subref_r\fP< \fBT\fP >, \fBconst\fP \fBchar\fP *)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_subref_r\fP< \fBT\fP > > \fBsc_dt::operator,\fP (\fBconst\fP \fBchar\fP *, \fBsc_subref_r\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT\fP >, \fBsc_lv_base\fP > \fBsc_dt::operator,\fP (\fBsc_subref_r\fP< \fBT\fP >, \fBconst\fP \fBsc_logic\fP &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_subref_r\fP< \fBT\fP > > \fBsc_dt::operator,\fP (\fBconst\fP \fBsc_logic\fP &, \fBsc_subref_r\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT\fP >, \fBsc_bv_base\fP > \fBsc_dt::operator,\fP (\fBsc_subref_r\fP< \fBT\fP >, \fBbool\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_bv_base\fP, \fBsc_subref_r\fP< \fBT\fP > > \fBsc_dt::operator,\fP (\fBbool\fP, \fBsc_subref_r\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT1\fP >, \fBsc_bitref_r\fP< \fBT2\fP > > \fBsc_dt::concat\fP (\fBsc_subref_r\fP< \fBT1\fP >, \fBsc_bitref_r\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT1\fP >, \fBsc_subref_r\fP< \fBT2\fP > > \fBsc_dt::concat\fP (\fBsc_subref_r\fP< \fBT1\fP >, \fBsc_subref_r\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT1\fP >, \fBsc_concref_r\fP< \fBT2\fP, \fBT3\fP > > \fBsc_dt::concat\fP (\fBsc_subref_r\fP< \fBT1\fP >, \fBsc_concref_r\fP< \fBT2\fP, \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT1\fP >, \fBT2\fP > \fBsc_dt::concat\fP (\fBsc_subref_r\fP< \fBT1\fP >, \fBconst\fP \fBsc_proxy\fP< \fBT2\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT\fP >, \fBsc_lv_base\fP > \fBsc_dt::concat\fP (\fBsc_subref_r\fP< \fBT\fP >, \fBconst\fP \fBchar\fP *)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_subref_r\fP< \fBT\fP > > \fBsc_dt::concat\fP (\fBconst\fP \fBchar\fP *, \fBsc_subref_r\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT\fP >, \fBsc_lv_base\fP > \fBsc_dt::concat\fP (\fBsc_subref_r\fP< \fBT\fP >, \fBconst\fP \fBsc_logic\fP &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_subref_r\fP< \fBT\fP > > \fBsc_dt::concat\fP (\fBconst\fP \fBsc_logic\fP &, \fBsc_subref_r\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_subref_r\fP< \fBT\fP >, \fBsc_bv_base\fP > \fBsc_dt::concat\fP (\fBsc_subref_r\fP< \fBT\fP >, \fBbool\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_bv_base\fP, \fBsc_subref_r\fP< \fBT\fP > > \fBsc_dt::concat\fP (\fBbool\fP, \fBsc_subref_r\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBsc_subref\fP< \fBT1\fP >, \fBsc_bitref\fP< \fBT2\fP > > \fBsc_dt::operator,\fP (\fBsc_subref\fP< \fBT1\fP >, \fBsc_bitref\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBsc_subref\fP< \fBT1\fP >, \fBsc_subref\fP< \fBT2\fP > > \fBsc_dt::operator,\fP (\fBsc_subref\fP< \fBT1\fP >, \fBsc_subref\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref\fP< \fBsc_subref\fP< \fBT1\fP >, \fBsc_concref\fP< \fBT2\fP, \fBT3\fP > > \fBsc_dt::operator,\fP (\fBsc_subref\fP< \fBT1\fP >, \fBsc_concref\fP< \fBT2\fP, \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBsc_subref\fP< \fBT1\fP >, \fBT2\fP > \fBsc_dt::operator,\fP (\fBsc_subref\fP< \fBT1\fP >, \fBsc_proxy\fP< \fBT2\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBsc_subref\fP< \fBT1\fP >, \fBsc_bitref\fP< \fBT2\fP > > \fBsc_dt::concat\fP (\fBsc_subref\fP< \fBT1\fP >, \fBsc_bitref\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBsc_subref\fP< \fBT1\fP >, \fBsc_subref\fP< \fBT2\fP > > \fBsc_dt::concat\fP (\fBsc_subref\fP< \fBT1\fP >, \fBsc_subref\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref\fP< \fBsc_subref\fP< \fBT1\fP >, \fBsc_concref\fP< \fBT2\fP, \fBT3\fP > > \fBsc_dt::concat\fP (\fBsc_subref\fP< \fBT1\fP >, \fBsc_concref\fP< \fBT2\fP, \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBsc_subref\fP< \fBT1\fP >, \fBT2\fP > \fBsc_dt::concat\fP (\fBsc_subref\fP< \fBT1\fP >, \fBsc_proxy\fP< \fBT2\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > inline::std::istream & \fBsc_dt::operator>>\fP (::std::istream &, \fBsc_subref\fP< \fBT\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_bitref_r\fP< \fBT3\fP > > \fBsc_dt::operator,\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_bitref_r\fP< \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_subref_r\fP< \fBT3\fP > > \fBsc_dt::operator,\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_subref_r\fP< \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP , \fBclass\fP \fBT4\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_concref_r\fP< \fBT3\fP, \fBT4\fP > > \fBsc_dt::operator,\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_concref_r\fP< \fBT3\fP, \fBT4\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBT3\fP > \fBsc_dt::operator,\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBconst\fP \fBsc_proxy\fP< \fBT3\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_lv_base\fP > \fBsc_dt::operator,\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBconst\fP \fBchar\fP *)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP > > \fBsc_dt::operator,\fP (\fBconst\fP \fBchar\fP *, \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_lv_base\fP > \fBsc_dt::operator,\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBconst\fP \fBsc_logic\fP &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP > > \fBsc_dt::operator,\fP (\fBconst\fP \fBsc_logic\fP &, \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_bv_base\fP > \fBsc_dt::operator,\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBbool\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_bv_base\fP, \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP > > \fBsc_dt::operator,\fP (\fBbool\fP, \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_bitref_r\fP< \fBT3\fP > > \fBsc_dt::concat\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_bitref_r\fP< \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_subref_r\fP< \fBT3\fP > > \fBsc_dt::concat\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_subref_r\fP< \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP , \fBclass\fP \fBT4\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_concref_r\fP< \fBT3\fP, \fBT4\fP > > \fBsc_dt::concat\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_concref_r\fP< \fBT3\fP, \fBT4\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBT3\fP > \fBsc_dt::concat\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBconst\fP \fBsc_proxy\fP< \fBT3\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_lv_base\fP > \fBsc_dt::concat\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBconst\fP \fBchar\fP *)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP > > \fBsc_dt::concat\fP (\fBconst\fP \fBchar\fP *, \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_lv_base\fP > \fBsc_dt::concat\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBconst\fP \fBsc_logic\fP &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP > > \fBsc_dt::concat\fP (\fBconst\fP \fBsc_logic\fP &, \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBsc_bv_base\fP > \fBsc_dt::concat\fP (\fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >, \fBbool\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBsc_bv_base\fP, \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP > > \fBsc_dt::concat\fP (\fBbool\fP, \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref\fP< \fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_bitref\fP< \fBT3\fP > > \fBsc_dt::operator,\fP (\fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_bitref\fP< \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref\fP< \fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_subref\fP< \fBT3\fP > > \fBsc_dt::operator,\fP (\fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_subref\fP< \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP , \fBclass\fP \fBT4\fP > \fBsc_concref\fP< \fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_concref\fP< \fBT3\fP, \fBT4\fP > > \fBsc_dt::operator,\fP (\fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_concref\fP< \fBT3\fP, \fBT4\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref\fP< \fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBT3\fP > \fBsc_dt::operator,\fP (\fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_proxy\fP< \fBT3\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref\fP< \fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_bitref\fP< \fBT3\fP > > \fBsc_dt::concat\fP (\fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_bitref\fP< \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref\fP< \fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_subref\fP< \fBT3\fP > > \fBsc_dt::concat\fP (\fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_subref\fP< \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP , \fBclass\fP \fBT4\fP > \fBsc_concref\fP< \fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_concref\fP< \fBT3\fP, \fBT4\fP > > \fBsc_dt::concat\fP (\fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_concref\fP< \fBT3\fP, \fBT4\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref\fP< \fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBT3\fP > \fBsc_dt::concat\fP (\fBsc_concref\fP< \fBT1\fP, \fBT2\fP >, \fBsc_proxy\fP< \fBT3\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > inline::std::istream & \fBsc_dt::operator>>\fP (::std::istream &, \fBsc_concref\fP< \fBT1\fP, \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBT1\fP, \fBsc_bitref_r\fP< \fBT2\fP > > \fBsc_dt::operator,\fP (\fBconst\fP \fBsc_proxy\fP< \fBT1\fP > &, \fBsc_bitref_r\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBT1\fP, \fBsc_subref_r\fP< \fBT2\fP > > \fBsc_dt::operator,\fP (\fBconst\fP \fBsc_proxy\fP< \fBT1\fP > &, \fBsc_subref_r\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref_r\fP< \fBT1\fP, \fBsc_concref_r\fP< \fBT2\fP, \fBT3\fP > > \fBsc_dt::operator,\fP (\fBconst\fP \fBsc_proxy\fP< \fBT1\fP > &, \fBsc_concref_r\fP< \fBT2\fP, \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP > \fBsc_dt::operator,\fP (\fBconst\fP \fBsc_proxy\fP< \fBT1\fP > &, \fBconst\fP \fBsc_proxy\fP< \fBT2\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBT\fP, \fBsc_lv_base\fP > \fBsc_dt::operator,\fP (\fBconst\fP \fBsc_proxy\fP< \fBT\fP > &, \fBconst\fP \fBchar\fP *)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBT\fP > \fBsc_dt::operator,\fP (\fBconst\fP \fBchar\fP *, \fBconst\fP \fBsc_proxy\fP< \fBT\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBT\fP, \fBsc_lv_base\fP > \fBsc_dt::operator,\fP (\fBconst\fP \fBsc_proxy\fP< \fBT\fP > &, \fBconst\fP \fBsc_logic\fP &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBT\fP > \fBsc_dt::operator,\fP (\fBconst\fP \fBsc_logic\fP &, \fBconst\fP \fBsc_proxy\fP< \fBT\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBT\fP, \fBsc_bv_base\fP > \fBsc_dt::operator,\fP (\fBconst\fP \fBsc_proxy\fP< \fBT\fP > &, \fBbool\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_bv_base\fP, \fBT\fP > \fBsc_dt::operator,\fP (\fBbool\fP, \fBconst\fP \fBsc_proxy\fP< \fBT\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBT1\fP, \fBsc_bitref_r\fP< \fBT2\fP > > \fBsc_dt::concat\fP (\fBconst\fP \fBsc_proxy\fP< \fBT1\fP > &, \fBsc_bitref_r\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBT1\fP, \fBsc_subref_r\fP< \fBT2\fP > > \fBsc_dt::concat\fP (\fBconst\fP \fBsc_proxy\fP< \fBT1\fP > &, \fBsc_subref_r\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref_r\fP< \fBT1\fP, \fBsc_concref_r\fP< \fBT2\fP, \fBT3\fP > > \fBsc_dt::concat\fP (\fBconst\fP \fBsc_proxy\fP< \fBT1\fP > &, \fBsc_concref_r\fP< \fBT2\fP, \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref_r\fP< \fBT1\fP, \fBT2\fP > \fBsc_dt::concat\fP (\fBconst\fP \fBsc_proxy\fP< \fBT1\fP > &, \fBconst\fP \fBsc_proxy\fP< \fBT2\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBT\fP, \fBsc_lv_base\fP > \fBsc_dt::concat\fP (\fBconst\fP \fBsc_proxy\fP< \fBT\fP > &, \fBconst\fP \fBchar\fP *)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBT\fP > \fBsc_dt::concat\fP (\fBconst\fP \fBchar\fP *, \fBconst\fP \fBsc_proxy\fP< \fBT\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBT\fP, \fBsc_lv_base\fP > \fBsc_dt::concat\fP (\fBconst\fP \fBsc_proxy\fP< \fBT\fP > &, \fBconst\fP \fBsc_logic\fP &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_lv_base\fP, \fBT\fP > \fBsc_dt::concat\fP (\fBconst\fP \fBsc_logic\fP &, \fBconst\fP \fBsc_proxy\fP< \fBT\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBT\fP, \fBsc_bv_base\fP > \fBsc_dt::concat\fP (\fBconst\fP \fBsc_proxy\fP< \fBT\fP > &, \fBbool\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_concref_r\fP< \fBsc_bv_base\fP, \fBT\fP > \fBsc_dt::concat\fP (\fBbool\fP, \fBconst\fP \fBsc_proxy\fP< \fBT\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBT1\fP, \fBsc_bitref\fP< \fBT2\fP > > \fBsc_dt::operator,\fP (\fBsc_proxy\fP< \fBT1\fP > &, \fBsc_bitref\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBT1\fP, \fBsc_subref\fP< \fBT2\fP > > \fBsc_dt::operator,\fP (\fBsc_proxy\fP< \fBT1\fP > &, \fBsc_subref\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref\fP< \fBT1\fP, \fBsc_concref\fP< \fBT2\fP, \fBT3\fP > > \fBsc_dt::operator,\fP (\fBsc_proxy\fP< \fBT1\fP > &, \fBsc_concref\fP< \fBT2\fP, \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBT1\fP, \fBT2\fP > \fBsc_dt::operator,\fP (\fBsc_proxy\fP< \fBT1\fP > &, \fBsc_proxy\fP< \fBT2\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBT1\fP, \fBsc_bitref\fP< \fBT2\fP > > \fBsc_dt::concat\fP (\fBsc_proxy\fP< \fBT1\fP > &, \fBsc_bitref\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBT1\fP, \fBsc_subref\fP< \fBT2\fP > > \fBsc_dt::concat\fP (\fBsc_proxy\fP< \fBT1\fP > &, \fBsc_subref\fP< \fBT2\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP , \fBclass\fP \fBT3\fP > \fBsc_concref\fP< \fBT1\fP, \fBsc_concref\fP< \fBT2\fP, \fBT3\fP > > \fBsc_dt::concat\fP (\fBsc_proxy\fP< \fBT1\fP > &, \fBsc_concref\fP< \fBT2\fP, \fBT3\fP >)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT1\fP , \fBclass\fP \fBT2\fP > \fBsc_concref\fP< \fBT1\fP, \fBT2\fP > \fBsc_dt::concat\fP (\fBsc_proxy\fP< \fBT1\fP > &, \fBsc_proxy\fP< \fBT2\fP > &)"
.br
.ti -1c
.RI "template<\fBclass\fP X > inline::std::istream & \fBsc_dt::operator>>\fP (::std::istream &\fBis\fP, \fBsc_bitref\fP< X > \fBa\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP X > inline::std::istream & \fBsc_dt::operator>>\fP (::std::istream &\fBis\fP, \fBsc_subref\fP< X > \fBa\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP X , \fBclass\fP \fBY\fP > inline::std::istream & \fBsc_dt::operator>>\fP (::std::istream &\fBis\fP, \fBsc_concref\fP< X, \fBY\fP > \fBa\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
