.TH "sc_boost::_bi::list4< A1, A2, A3, A4 >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::_bi::list4< A1, A2, A3, A4 >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bind\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBlist4\fP (\fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP, \fBA4\fP \fBa4\fP)"
.br
.ti -1c
.RI "\fBA1\fP \fBoperator[]\fP (\fBsc_boost::arg\fP< 1 >) \fBconst\fP"
.br
.ti -1c
.RI "\fBA2\fP \fBoperator[]\fP (\fBsc_boost::arg\fP< 2 >) \fBconst\fP"
.br
.ti -1c
.RI "\fBA3\fP \fBoperator[]\fP (\fBsc_boost::arg\fP< 3 >) \fBconst\fP"
.br
.ti -1c
.RI "\fBA4\fP \fBoperator[]\fP (\fBsc_boost::arg\fP< 4 >) \fBconst\fP"
.br
.ti -1c
.RI "\fBA1\fP \fBoperator[]\fP (\fBsc_boost::arg\fP< 1 >(*)()) \fBconst\fP"
.br
.ti -1c
.RI "\fBA2\fP \fBoperator[]\fP (\fBsc_boost::arg\fP< 2 >(*)()) \fBconst\fP"
.br
.ti -1c
.RI "\fBA3\fP \fBoperator[]\fP (\fBsc_boost::arg\fP< 3 >(*)()) \fBconst\fP"
.br
.ti -1c
.RI "\fBA4\fP \fBoperator[]\fP (\fBsc_boost::arg\fP< 4 >(*)()) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBT\fP & \fBoperator[]\fP (\fB_bi::value\fP< \fBT\fP > &v) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBT\fP \fBconst\fP & \fBoperator[]\fP (\fB_bi::value\fP< \fBT\fP > \fBconst\fP &v) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBT\fP & \fBoperator[]\fP (\fBreference_wrapper\fP< \fBT\fP > \fBconst\fP &v) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBL\fP > \fBresult_traits\fP< \fBR\fP, F >::type \fBoperator[]\fP (\fBbind_t\fP< \fBR\fP, F, \fBL\fP > &b) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBL\fP > \fBresult_traits\fP< \fBR\fP, F >::type \fBoperator[]\fP (\fBbind_t\fP< \fBR\fP, F, \fBL\fP > \fBconst\fP &b) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA\fP > \fBR\fP \fBoperator()\fP (\fBtype\fP< \fBR\fP >, F &f, \fBA\fP &\fBa\fP, \fBlong\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA\fP > \fBR\fP \fBoperator()\fP (\fBtype\fP< \fBR\fP >, F \fBconst\fP &f, \fBA\fP &\fBa\fP, \fBlong\fP) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA\fP > \fBvoid\fP \fBoperator()\fP (\fBtype\fP< \fBvoid\fP >, F &f, \fBA\fP &\fBa\fP, int)"
.br
.ti -1c
.RI "template<\fBclass\fP F , \fBclass\fP \fBA\fP > \fBvoid\fP \fBoperator()\fP (\fBtype\fP< \fBvoid\fP >, F \fBconst\fP &f, \fBA\fP &\fBa\fP, int) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBclass\fP \fBV\fP > \fBvoid\fP \fBaccept\fP (\fBV\fP &v) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBlist4\fP \fBconst\fP &\fBrhs\fP) \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBA1\fP \fBa1_\fP"
.br
.ti -1c
.RI "\fBA2\fP \fBa2_\fP"
.br
.ti -1c
.RI "\fBA3\fP \fBa3_\fP"
.br
.ti -1c
.RI "\fBA4\fP \fBa4_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >::list4 (\fBA1\fP a1, \fBA2\fP a2, \fBA3\fP a3, \fBA4\fP a4)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > template<\fBclass\fP \fBV\fP > \fBvoid\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >::accept (\fBV\fP & v) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA\fP > \fBR\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP() (\fBtype\fP< \fBR\fP >, F & f, \fBA\fP & a, \fBlong\fP)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBA\fP > \fBR\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP() (\fBtype\fP< \fBR\fP >, F \fBconst\fP & f, \fBA\fP & a, \fBlong\fP) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > template<\fBclass\fP F , \fBclass\fP \fBA\fP > \fBvoid\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP() (\fBtype\fP< \fBvoid\fP >, F & f, \fBA\fP & a, int)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > template<\fBclass\fP F , \fBclass\fP \fBA\fP > \fBvoid\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP() (\fBtype\fP< \fBvoid\fP >, F \fBconst\fP & f, \fBA\fP & a, int) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBbool\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP== (\fBlist4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP > \fBconst\fP & rhs) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > template<\fBclass\fP \fBT\fP > \fBT\fP & \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fB_bi::value\fP< \fBT\fP > & v) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > template<\fBclass\fP \fBT\fP > \fBT\fP \fBconst\fP  & \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fB_bi::value\fP< \fBT\fP > \fBconst\fP & v) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBL\fP > \fBresult_traits\fP< \fBR\fP, F >::type \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fBbind_t\fP< \fBR\fP, F, \fBL\fP > & b) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > template<\fBclass\fP \fBR\fP , \fBclass\fP F , \fBclass\fP \fBL\fP > \fBresult_traits\fP< \fBR\fP, F >::type \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fBbind_t\fP< \fBR\fP, F, \fBL\fP > \fBconst\fP & b) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > template<\fBclass\fP \fBT\fP > \fBT\fP & \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fBreference_wrapper\fP< \fBT\fP > \fBconst\fP & v) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBA1\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fBsc_boost::arg\fP< 1 >*)() const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBA1\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fBsc_boost::arg\fP< 1 >) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBA2\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fBsc_boost::arg\fP< 2 >*)() const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBA2\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fBsc_boost::arg\fP< 2 >) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBA3\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fBsc_boost::arg\fP< 3 >*)() const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBA3\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fBsc_boost::arg\fP< 3 >) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBA4\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fBsc_boost::arg\fP< 4 >*)() const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBA4\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >\fB::operator\fP[] (\fBsc_boost::arg\fP< 4 >) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBA1\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >::a1_\fR [private]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBA2\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >::a2_\fR [private]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBA3\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >::a3_\fR [private]\fP"

.SS "template<\fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP \fBA4\fP > \fBA4\fP \fBsc_boost::_bi::list4\fP< \fBA1\fP, \fBA2\fP, \fBA3\fP, \fBA4\fP >::a4_\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
