.TH "sc_boost::_bi::logical_not" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::_bi::logical_not
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <bind\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "template<\fBclass\fP \fBV\fP > \fBbool\fP \fBoperator()\fP (\fBV\fP \fBconst\fP &v) \fBconst\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBV\fP > \fBbool\fP sc_boost::_bi::logical_not::operator() (\fBV\fP \fBconst\fP & v) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
