.TH "sc_boost::_bi::af3< R, A1, A2, A3, F >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_boost::_bi::af3< R, A1, A2, A3, F >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <make_adaptable\&.hpp>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBR\fP \fBresult_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBA1\fP \fBarg1_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBA2\fP \fBarg2_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBA3\fP \fBarg3_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBaf3\fP (F f)"
.br
.ti -1c
.RI "\fBresult_type\fP \fBoperator()\fP (\fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP)"
.br
.ti -1c
.RI "\fBresult_type\fP \fBoperator()\fP (\fBA1\fP a1, \fBA2\fP \fBa2\fP, \fBA3\fP \fBa3\fP) \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "F \fBf_\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP F > \fBtypedef\fP \fBA1\fP \fBsc_boost::_bi::af3\fP< \fBR\fP, \fBA1\fP, \fBA2\fP, \fBA3\fP, F >::arg1_type"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP F > \fBtypedef\fP \fBA2\fP \fBsc_boost::_bi::af3\fP< \fBR\fP, \fBA1\fP, \fBA2\fP, \fBA3\fP, F >::arg2_type"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP F > \fBtypedef\fP \fBA3\fP \fBsc_boost::_bi::af3\fP< \fBR\fP, \fBA1\fP, \fBA2\fP, \fBA3\fP, F >::arg3_type"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP F > \fBtypedef\fP \fBR\fP \fBsc_boost::_bi::af3\fP< \fBR\fP, \fBA1\fP, \fBA2\fP, \fBA3\fP, F >\fB::result_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP F > \fBsc_boost::_bi::af3\fP< \fBR\fP, \fBA1\fP, \fBA2\fP, \fBA3\fP, F >::af3 (F f)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP F > \fBresult_type\fP \fBsc_boost::_bi::af3\fP< \fBR\fP, \fBA1\fP, \fBA2\fP, \fBA3\fP, F >\fB::operator\fP() (\fBA1\fP a1, \fBA2\fP a2, \fBA3\fP a3)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP F > \fBresult_type\fP \fBsc_boost::_bi::af3\fP< \fBR\fP, \fBA1\fP, \fBA2\fP, \fBA3\fP, F >\fB::operator\fP() (\fBA1\fP a1, \fBA2\fP a2, \fBA3\fP a3) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBR\fP , \fBclass\fP \fBA1\fP , \fBclass\fP \fBA2\fP , \fBclass\fP \fBA3\fP , \fBclass\fP F > F \fBsc_boost::_bi::af3\fP< \fBR\fP, \fBA1\fP, \fBA2\fP, \fBA3\fP, F >::f_\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
