.TH "sc_core::sc_plist_base_iter" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_plist_base_iter
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_list\&.h>\fP
.PP
Inherited by \fBsc_core::sc_plist_iter< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_plist_elem\fP * \fBhandle_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_plist_base_iter\fP (\fBsc_plist_base\fP *\fBl\fP, \fBbool\fP \fBfrom_tail\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fB~sc_plist_base_iter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP (\fBsc_plist_base\fP *\fBl\fP, \fBbool\fP \fBfrom_tail\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBempty\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBget\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset\fP (\fBvoid\fP *d)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove\fP (int \fBdirection\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_handle\fP (\fBhandle_t\fP \fBh\fP)"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBget_handle\fP () \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBsc_plist_base\fP * \fBlst\fP"
.br
.ti -1c
.RI "\fBsc_plist_elem\fP * \fBptr\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBsc_plist_elem\fP* \fBsc_core::sc_plist_base_iter::handle_t\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_plist_base_iter::sc_plist_base_iter (\fBsc_plist_base\fP * l, \fBbool\fP from_tail = \fR\fBfalse\fP\fP)"

.SS "sc_core::sc_plist_base_iter::~sc_plist_base_iter ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP sc_core::sc_plist_base_iter::empty () const"

.SS "\fBvoid\fP * sc_core::sc_plist_base_iter::get () const"

.SS "\fBhandle_t\fP sc_core::sc_plist_base_iter::get_handle () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_core::sc_plist_base_iter::operator++ (int)"

.SS "\fBvoid\fP sc_core::sc_plist_base_iter::operator\-\- (int)"

.SS "\fBvoid\fP sc_core::sc_plist_base_iter::remove ()"

.SS "\fBvoid\fP sc_core::sc_plist_base_iter::remove (int direction)"

.SS "\fBvoid\fP sc_core::sc_plist_base_iter::reset (\fBsc_plist_base\fP * l, \fBbool\fP from_tail = \fR\fBfalse\fP\fP)"

.SS "\fBvoid\fP sc_core::sc_plist_base_iter::set (\fBvoid\fP * d)"

.SS "\fBvoid\fP sc_core::sc_plist_base_iter::set_handle (\fBhandle_t\fP h)"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_plist_base\fP* sc_core::sc_plist_base_iter::lst\fR [private]\fP"

.SS "\fBsc_plist_elem\fP* sc_core::sc_plist_base_iter::ptr\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
