.TH "sc_core::sc_trace_file" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_trace_file
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_trace\&.h>\fP
.PP
Inherited by \fBsc_core::sc_trace_file_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_trace_file\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBtrace\fP (\fBconst\fP \fBunsigned\fP int &\fBobject\fP, \fBconst\fP std::string &name, \fBconst\fP \fBchar\fP **\fBenum_literals\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBwrite_comment\fP (\fBconst\fP std::string &\fBcomment\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBspace\fP (int \fBn\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBdelta_cycles\fP (\fBbool\fP \fBflag\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBset_time_unit\fP (\fBdouble\fP v, \fBsc_time_unit\fP \fBtu\fP)=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBcycle\fP (\fBbool\fP \fBdelta_cycle\fP)=0"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_dt::uint64\fP & \fBevent_trigger_stamp\fP (\fBconst\fP \fBsc_event\fP &event) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_trace_file\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_simcontext\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_trace_file::sc_trace_file ()"

.SS "\fBvirtual\fP sc_core::sc_trace_file::~sc_trace_file ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_trace_file::cycle (\fBbool\fP delta_cycle)\fR [protected]\fP, \fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::vcd_trace_file\fP, and \fBsc_core::wif_trace_file\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_trace_file::delta_cycles (\fBbool\fP flag)\fR [virtual]\fP"

.PP
Reimplemented in \fBsc_core::sc_trace_file_base\fP\&.
.SS "\fBconst\fP \fBsc_dt::uint64\fP & sc_core::sc_trace_file::event_trigger_stamp (\fBconst\fP \fBsc_event\fP & event) const\fR [protected]\fP"

.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_trace_file::set_time_unit (\fBdouble\fP v, \fBsc_time_unit\fP tu)\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_trace_file_base\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_trace_file::space (int n)\fR [virtual]\fP"

.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_trace_file::trace (\fBconst\fP \fBunsigned\fP int & object, \fBconst\fP std::string & name, \fBconst\fP \fBchar\fP ** enum_literals)\fR [pure virtual]\fP"

.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_trace_file::write_comment (\fBconst\fP std::string & comment)\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::vcd_trace_file\fP, and \fBsc_core::wif_trace_file\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_simcontext\fP\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
