.TH "sc_core::sc_process_host" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_process_host
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_process\&.h>\fP
.PP
Inherited by \fBsc_core::sc_module\fP, \fBsc_core::sc_spawn_object< T >\fP, and \fBsc_core::sc_spawn_object_v< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_process_host\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_process_host\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBdefunct\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_process_host::sc_process_host ()\fR [inline]\fP"

.SS "\fBvirtual\fP sc_core::sc_process_host::~sc_process_host ()\fR [inline]\fP, \fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP sc_core::sc_process_host::defunct ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
