.TH "sc_core::sc_meta::is_more_const< CT, T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_meta::is_more_const< CT, T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_vector\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSC_STATIC_CONSTANT_\fP (\fBbool\fP, \fBvalue\fP=(\fBis_same\fP< \fBtypename\fP \fBremove_const\fP< \fBCT\fP >::type, \fBtypename\fP \fBremove_const\fP< \fBT\fP >::type >\fB::value\fP &&(\fBis_const\fP< \fBCT\fP >\fB::value\fP >=\fBis_const\fP< \fBT\fP >\fB::value\fP)))"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBCT\fP , \fBtypename\fP \fBT\fP > \fBsc_core::sc_meta::is_more_const\fP< \fBCT\fP, \fBT\fP >::SC_STATIC_CONSTANT_ (\fBbool\fP, \fBvalue\fP = \fR(\fBis_same\fP< \fBtypename\fP \fBremove_const\fP< \fBCT\fP >::type, \fBtypename\fP \fBremove_const\fP< \fBT\fP >::type >\fB::value\fP &&(\fBis_const\fP< \fBCT\fP >\fB::value\fP >=\fBis_const\fP< \fBT\fP >\fB::value\fP))\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
