.TH "sc_core::sc_object_manager::table_entry" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_object_manager::table_entry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_object_manager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtable_entry\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBm_element_p\fP"
.br
.ti -1c
.RI "\fBsc_name_origin\fP \fBm_name_origin\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_object_manager::table_entry::table_entry ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBvoid\fP* sc_core::sc_object_manager::table_entry::m_element_p"

.SS "\fBsc_name_origin\fP sc_core::sc_object_manager::table_entry::m_name_origin"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
