.TH "sc_core::sc_type_index" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_type_index
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_typeindex\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_type_index\fP (\fBconst\fP std::type_info &\fBti\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP \fBsc_type_index\fP &\fBrhs\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBconst\fP \fBsc_type_index\fP &\fBrhs\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator<\fP (\fBconst\fP \fBsc_type_index\fP &\fBrhs\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator<=\fP (\fBconst\fP \fBsc_type_index\fP &\fBrhs\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator>\fP (\fBconst\fP \fBsc_type_index\fP &\fBrhs\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator>=\fP (\fBconst\fP \fBsc_type_index\fP &\fBrhs\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBname\fP () \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::type_info \fBconst\fP  * \fBinfo_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_type_index::sc_type_index (\fBconst\fP std::type_info & ti)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBconst\fP \fBchar\fP * sc_core::sc_type_index::name () const\fR [inline]\fP"

.SS "\fBbool\fP sc_core::sc_type_index::operator!= (\fBconst\fP \fBsc_type_index\fP & rhs) const\fR [inline]\fP"

.SS "\fBbool\fP sc_core::sc_type_index::operator< (\fBconst\fP \fBsc_type_index\fP & rhs) const\fR [inline]\fP"

.SS "\fBbool\fP sc_core::sc_type_index::operator<= (\fBconst\fP \fBsc_type_index\fP & rhs) const\fR [inline]\fP"

.SS "\fBbool\fP sc_core::sc_type_index::operator== (\fBconst\fP \fBsc_type_index\fP & rhs) const\fR [inline]\fP"

.SS "\fBbool\fP sc_core::sc_type_index::operator> (\fBconst\fP \fBsc_type_index\fP & rhs) const\fR [inline]\fP"

.SS "\fBbool\fP sc_core::sc_type_index::operator>= (\fBconst\fP \fBsc_type_index\fP & rhs) const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::type_info \fBconst\fP* sc_core::sc_type_index::info_\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
