.TH "sc_core::sc_vector_base::context_scope" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_vector_base::context_scope
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_vector\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcontext_scope\fP (\fBsc_vector_base\fP *\fBowner\fP)"
.br
.ti -1c
.RI "\fB~context_scope\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBsc_vector_base\fP * \fBowner_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_vector_base::context_scope::context_scope (\fBsc_vector_base\fP * owner)\fR [explicit]\fP"

.SS "sc_core::sc_vector_base::context_scope::~context_scope ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_vector_base\fP* sc_core::sc_vector_base::context_scope::owner_\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
