.TH "sc_core::sc_attr_cltn" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_attr_cltn
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_attribute\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_attr_base\fP * \fBelem_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP std::vector< \fBelem_type\fP >::iterator \fBiterator\fP"
.br
.ti -1c
.RI "\fBtypedef\fP std::vector< \fBelem_type\fP >::const_iterator \fBconst_iterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_attr_cltn\fP ()"
.br
.ti -1c
.RI "\fBsc_attr_cltn\fP (\fBconst\fP \fBsc_attr_cltn\fP &)"
.br
.ti -1c
.RI "\fB~sc_attr_cltn\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBpush_back\fP (\fBsc_attr_base\fP *)"
.br
.ti -1c
.RI "\fBsc_attr_base\fP * \fBoperator[]\fP (\fBconst\fP std::string &\fBname_\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_attr_base\fP * \fBoperator[]\fP (\fBconst\fP std::string &\fBname_\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_attr_base\fP * \fBremove\fP (\fBconst\fP std::string &\fBname_\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove_all\fP ()"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBbegin\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP ()"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBend\fP () \fBconst\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_attr_cltn\fP & \fBoperator=\fP (\fBconst\fP \fBsc_attr_cltn\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBsc_attr_base\fP * > \fBm_cltn\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "\fBtypedef\fP std::vector<\fBelem_type\fP>::const_iterator \fBsc_core::sc_attr_cltn::const_iterator\fP"

.SS "\fBtypedef\fP \fBsc_attr_base\fP* \fBsc_core::sc_attr_cltn::elem_type\fP"

.SS "\fBtypedef\fP std::vector<\fBelem_type\fP>::iterator \fBsc_core::sc_attr_cltn::iterator\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_attr_cltn::sc_attr_cltn ()"

.SS "sc_core::sc_attr_cltn::sc_attr_cltn (\fBconst\fP \fBsc_attr_cltn\fP &)"

.SS "sc_core::sc_attr_cltn::~sc_attr_cltn ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBiterator\fP sc_core::sc_attr_cltn::begin ()\fR [inline]\fP"

.SS "\fBconst_iterator\fP sc_core::sc_attr_cltn::begin () const\fR [inline]\fP"

.SS "\fBiterator\fP sc_core::sc_attr_cltn::end ()\fR [inline]\fP"

.SS "\fBconst_iterator\fP sc_core::sc_attr_cltn::end () const\fR [inline]\fP"

.SS "\fBsc_attr_cltn\fP & sc_core::sc_attr_cltn::operator= (\fBconst\fP \fBsc_attr_cltn\fP &)\fR [private]\fP"

.SS "\fBsc_attr_base\fP * sc_core::sc_attr_cltn::operator[] (\fBconst\fP std::string & name_)"

.SS "\fBconst\fP \fBsc_attr_base\fP * sc_core::sc_attr_cltn::operator[] (\fBconst\fP std::string & name_) const"

.SS "\fBbool\fP sc_core::sc_attr_cltn::push_back (\fBsc_attr_base\fP *)"

.SS "\fBsc_attr_base\fP * sc_core::sc_attr_cltn::remove (\fBconst\fP std::string & name_)"

.SS "\fBvoid\fP sc_core::sc_attr_cltn::remove_all ()"

.SS "int sc_core::sc_attr_cltn::size () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBsc_attr_base\fP*> sc_core::sc_attr_cltn::m_cltn\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
