.TH "sc_core::sc_writer_policy_check_port" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_writer_policy_check_port
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_writer_policy\&.h>\fP
.PP
Inherited by \fBsc_core::sc_writer_policy_check< SC_ONE_WRITER >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBcheck_port\fP (\fBsc_object\fP *target, \fBsc_port_base\fP *port, \fBbool\fP \fBis_output\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_writer_policy_check_port\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBsc_port_base\fP * \fBm_output\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_writer_policy_check_port::sc_writer_policy_check_port ()\fR [inline]\fP, \fR [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP sc_core::sc_writer_policy_check_port::check_port (\fBsc_object\fP * target, \fBsc_port_base\fP * port, \fBbool\fP is_output)"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_port_base\fP* sc_core::sc_writer_policy_check_port::m_output\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
