.TH "sc_core::sc_event_queue_if" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_event_queue_if
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_event_queue\&.h>\fP
.PP
Inherits \fBsc_core::sc_interface\fP\&.
.PP
Inherited by \fBsc_core::sc_event_queue\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBnotify\fP (\fBdouble\fP \fBwhen\fP, \fBsc_time_unit\fP \fBbase\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBnotify\fP (\fBconst\fP \fBsc_time\fP &\fBwhen\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBcancel_all\fP ()=0"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBregister_port\fP (\fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBchar\fP *\fBif_typename_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_interface\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBsc_interface\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_event_queue_if::cancel_all ()\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_event_queue\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_event_queue_if::notify (\fBconst\fP \fBsc_time\fP & when)\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_event_queue\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_event_queue_if::notify (\fBdouble\fP when, \fBsc_time_unit\fP base)\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_event_queue\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
