.TH "sc_core::sc_phase_callback_registry::entry" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_phase_callback_registry::entry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_phase_callback_registry\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcb_type\fP * \fBtarget\fP"
.br
.ti -1c
.RI "\fBmask_type\fP \fBmask\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBmask_type\fP sc_core::sc_phase_callback_registry::entry::mask"

.SS "\fBcb_type\fP* sc_core::sc_phase_callback_registry::entry::target"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
