.TH "sc_core::sc_join" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_join
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_join\&.h>\fP
.PP
Inherits \fBsc_core::sc_process_monitor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_join\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd_process\fP (\fBsc_process_handle\fP \fBprocess_h\fP)"
.br
.ti -1c
.RI "int \fBprocess_count\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBsignal\fP (\fBsc_thread_handle\fP \fBthread_p\fP, int type)"
.br
.ti -1c
.RI "\fBvoid\fP \fBwait\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBwait_clocked\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_process_monitor\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~sc_process_monitor\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBadd_process\fP (\fBsc_process_b\fP *\fBprocess_p\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBsc_event\fP \fBm_join_event\fP"
.br
.ti -1c
.RI "int \fBm_threads_n\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_join\fP (\fBconst\fP \fBsc_join\fP &)"
.br
.ti -1c
.RI "\fBsc_join\fP & \fBoperator=\fP (\fBconst\fP \fBsc_join\fP &)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_process_b\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_process_handle\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBsc_core::sc_process_monitor\fP
.in +1c
.ti -1c
.RI "enum { \fBspm_exit\fP = 0 }"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_join::sc_join ()"

.SS "sc_core::sc_join::sc_join (\fBconst\fP \fBsc_join\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP sc_core::sc_join::add_process (\fBsc_process_b\fP * process_p)\fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_join::add_process (\fBsc_process_handle\fP process_h)"

.SS "\fBsc_join\fP & sc_core::sc_join::operator= (\fBconst\fP \fBsc_join\fP &)\fR [private]\fP"

.SS "int sc_core::sc_join::process_count ()\fR [inline]\fP"

.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_join::signal (\fBsc_thread_handle\fP thread_p, int type)\fR [virtual]\fP"

.PP
Reimplemented from \fBsc_core::sc_process_monitor\fP\&.
.SS "\fBvoid\fP sc_core::sc_join::wait ()\fR [inline]\fP"

.SS "\fBvoid\fP sc_core::sc_join::wait_clocked ()\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_process_b\fP\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_process_handle\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_event\fP sc_core::sc_join::m_join_event\fR [protected]\fP"

.SS "int sc_core::sc_join::m_threads_n\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
