.TH "sc_core::sc_bind_proxy" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_bind_proxy
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_module\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_bind_proxy\fP ()"
.br
.ti -1c
.RI "\fBsc_bind_proxy\fP (\fBsc_interface\fP &)"
.br
.ti -1c
.RI "\fBsc_bind_proxy\fP (\fBsc_port_base\fP &)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsc_interface\fP * \fBiface\fP"
.br
.ti -1c
.RI "\fBsc_port_base\fP * \fBport\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_bind_proxy::sc_bind_proxy ()"

.SS "sc_core::sc_bind_proxy::sc_bind_proxy (\fBsc_interface\fP &)"

.SS "sc_core::sc_bind_proxy::sc_bind_proxy (\fBsc_port_base\fP &)"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_interface\fP* sc_core::sc_bind_proxy::iface"

.SS "\fBsc_port_base\fP* sc_core::sc_bind_proxy::port"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
