.TH "sc_core::sc_meta::is_const< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_meta::is_const< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_vector\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSC_BOOST_STATIC_CONSTANT\fP (\fBbool\fP, \fBvalue\fP=\fBfalse\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBsc_core::sc_meta::is_const\fP< \fBT\fP >::SC_BOOST_STATIC_CONSTANT (\fBbool\fP, \fBvalue\fP = \fR\fBfalse\fP\fP)"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
