.TH "sc_core::sc_pvector< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_pvector< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_pvector\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBconst\fP \fBT\fP * \fBconst_iterator\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBT\fP * \fBiterator\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_pvector\fP (int \fBalloc_n\fP=0)"
.br
.ti -1c
.RI "\fBsc_pvector\fP (\fBconst\fP \fBsc_pvector\fP< \fBT\fP > &\fBrhs\fP)"
.br
.ti -1c
.RI "\fB~sc_pvector\fP ()"
.br
.ti -1c
.RI "std::size_t \fBsize\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBbegin\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBiterator\fP \fBend\fP ()"
.br
.ti -1c
.RI "\fBconst_iterator\fP \fBend\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_pvector\fP< \fBT\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_pvector\fP< \fBT\fP > &\fBrhs\fP)"
.br
.ti -1c
.RI "\fBT\fP & \fBoperator[]\fP (\fBunsigned\fP int \fBi\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBT\fP & \fBoperator[]\fP (\fBunsigned\fP int \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBT\fP & \fBfetch\fP (int \fBi\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBT\fP & \fBfetch\fP (int \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBT\fP * \fBraw_data\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBT\fP * \fBraw_data\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBoperator const ::std::vector< T > &\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBpush_back\fP (\fBT\fP item)"
.br
.ti -1c
.RI "\fBvoid\fP \fBerase_all\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsort\fP (\fBCFT\fP \fBcompar\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBput\fP (\fBT\fP item, int \fBi\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdecr_count\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBdecr_count\fP (int \fBk\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBmutable\fP ::std::vector< \fBT\fP > \fBm_vector\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fBconst\fP \fBT\fP* \fBsc_core::sc_pvector\fP< \fBT\fP >::const_iterator"

.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fBT\fP* \fBsc_core::sc_pvector\fP< \fBT\fP >::iterator"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_pvector\fP< \fBT\fP >::sc_pvector (int alloc_n = \fR0\fP)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_pvector\fP< \fBT\fP >::sc_pvector (\fBconst\fP \fBsc_pvector\fP< \fBT\fP > & rhs)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_pvector\fP< \fBT\fP >::~\fBsc_pvector\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBiterator\fP \fBsc_core::sc_pvector\fP< \fBT\fP >::begin ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst_iterator\fP \fBsc_core::sc_pvector\fP< \fBT\fP >::begin () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_pvector\fP< \fBT\fP >::decr_count ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_pvector\fP< \fBT\fP >::decr_count (int k)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBiterator\fP \fBsc_core::sc_pvector\fP< \fBT\fP >::end ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst_iterator\fP \fBsc_core::sc_pvector\fP< \fBT\fP >::end () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_pvector\fP< \fBT\fP >::erase_all ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP & \fBsc_core::sc_pvector\fP< \fBT\fP >::fetch (int i)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBT\fP & \fBsc_core::sc_pvector\fP< \fBT\fP >::fetch (int i) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_pvector\fP< \fBT\fP >\fB::operator\fP \fBconst\fP ::std::vector< \fBT\fP > & () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_pvector\fP< \fBT\fP > & \fBsc_core::sc_pvector\fP< \fBT\fP >\fB::operator\fP= (\fBconst\fP \fBsc_pvector\fP< \fBT\fP > & rhs)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP & \fBsc_core::sc_pvector\fP< \fBT\fP >\fB::operator\fP[] (\fBunsigned\fP int i)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBT\fP & \fBsc_core::sc_pvector\fP< \fBT\fP >\fB::operator\fP[] (\fBunsigned\fP int i) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_pvector\fP< \fBT\fP >::push_back (\fBT\fP item)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_pvector\fP< \fBT\fP >::put (\fBT\fP item, int i)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP * \fBsc_core::sc_pvector\fP< \fBT\fP >::raw_data ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBT\fP * \fBsc_core::sc_pvector\fP< \fBT\fP >::raw_data () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > std::size_t \fBsc_core::sc_pvector\fP< \fBT\fP >::size () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_pvector\fP< \fBT\fP >::sort (\fBCFT\fP compar)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBmutable\fP ::std::vector<\fBT\fP> \fBsc_core::sc_pvector\fP< \fBT\fP >::m_vector\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
