.TH "sc_core::sc_plist< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_plist< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_list\&.h>\fP
.PP
Inherits \fBsc_core::sc_plist_base\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_plist_iter\fP< \fBT\fP > \fBiterator\fP"
.br
.in -1c

Public Types inherited from \fBsc_core::sc_plist_base\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_plist_elem\fP * \fBhandle_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_plist\fP ()"
.br
.ti -1c
.RI "\fB~sc_plist\fP ()"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBpush_back\fP (\fBT\fP d)"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBpush_front\fP (\fBT\fP d)"
.br
.ti -1c
.RI "\fBT\fP \fBpop_back\fP ()"
.br
.ti -1c
.RI "\fBT\fP \fBpop_front\fP ()"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBinsert_before\fP (\fBhandle_t\fP \fBh\fP, \fBT\fP d)"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBinsert_after\fP (\fBhandle_t\fP \fBh\fP, \fBT\fP d)"
.br
.ti -1c
.RI "\fBT\fP \fBremove\fP (\fBhandle_t\fP \fBh\fP)"
.br
.ti -1c
.RI "\fBT\fP \fBget\fP (\fBhandle_t\fP \fBh\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset\fP (\fBhandle_t\fP \fBh\fP, \fBT\fP d)"
.br
.ti -1c
.RI "\fBT\fP \fBfront\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBT\fP \fBback\fP () \fBconst\fP"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_plist_base\fP
.in +1c
.ti -1c
.RI "\fBsc_plist_base\fP ()"
.br
.ti -1c
.RI "\fB~sc_plist_base\fP ()"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBpush_back\fP (\fBvoid\fP *d)"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBpush_front\fP (\fBvoid\fP *d)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBpop_back\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP * \fBpop_front\fP ()"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBinsert_before\fP (\fBhandle_t\fP \fBh\fP, \fBvoid\fP *d)"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBinsert_after\fP (\fBhandle_t\fP \fBh\fP, \fBvoid\fP *d)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBremove\fP (\fBhandle_t\fP \fBh\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBget\fP (\fBhandle_t\fP \fBh\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset\fP (\fBhandle_t\fP \fBh\fP, \fBvoid\fP *d)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmapcar\fP (\fBsc_plist_map_fn\fP f, \fBvoid\fP *arg)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBfront\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBback\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBerase_all\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBempty\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_plist_iter< T >\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fBsc_plist_iter\fP<\fBT\fP> \fBsc_core::sc_plist\fP< \fBT\fP >::iterator"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_plist\fP< \fBT\fP >::sc_plist ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_plist\fP< \fBT\fP >::~\fBsc_plist\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBsc_core::sc_plist\fP< \fBT\fP >::back () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBsc_core::sc_plist\fP< \fBT\fP >::front () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBsc_core::sc_plist\fP< \fBT\fP >::get (\fBhandle_t\fP h) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBhandle_t\fP \fBsc_core::sc_plist\fP< \fBT\fP >::insert_after (\fBhandle_t\fP h, \fBT\fP d)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBhandle_t\fP \fBsc_core::sc_plist\fP< \fBT\fP >::insert_before (\fBhandle_t\fP h, \fBT\fP d)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBsc_core::sc_plist\fP< \fBT\fP >::pop_back ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBsc_core::sc_plist\fP< \fBT\fP >::pop_front ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBhandle_t\fP \fBsc_core::sc_plist\fP< \fBT\fP >::push_back (\fBT\fP d)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBhandle_t\fP \fBsc_core::sc_plist\fP< \fBT\fP >::push_front (\fBT\fP d)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBsc_core::sc_plist\fP< \fBT\fP >::remove (\fBhandle_t\fP h)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_plist\fP< \fBT\fP >::set (\fBhandle_t\fP h, \fBT\fP d)\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBfriend\fP \fBclass\fP \fBsc_plist_iter\fP< \fBT\fP >\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
