.TH "sc_core::sc_clock_negedge_callback" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_clock_negedge_callback
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_clock\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_clock_negedge_callback\fP (\fBsc_clock\fP *\fBtarget_p\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator()\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBsc_clock\fP * \fBm_target_p\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_clock_negedge_callback::sc_clock_negedge_callback (\fBsc_clock\fP * target_p)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP sc_core::sc_clock_negedge_callback::operator() ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_clock\fP* sc_core::sc_clock_negedge_callback::m_target_p\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
