.TH "sc_core::sc_byte_heap" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_byte_heap
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_temporary\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBchar\fP * \fBallocate\fP (std::size_t \fBbytes_n\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBinitialize\fP (std::size_t \fBheap_size\fP=0x100000)"
.br
.ti -1c
.RI "std::size_t \fBlength\fP ()"
.br
.ti -1c
.RI "\fBsc_byte_heap\fP ()"
.br
.ti -1c
.RI "\fBsc_byte_heap\fP (std::size_t \fBheap_size\fP)"
.br
.ti -1c
.RI "\fB~sc_byte_heap\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBchar\fP * \fBm_bgn_p\fP"
.br
.ti -1c
.RI "\fBchar\fP * \fBm_end_p\fP"
.br
.ti -1c
.RI "\fBchar\fP * \fBm_next_p\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_byte_heap::sc_byte_heap ()\fR [inline]\fP"

.SS "sc_core::sc_byte_heap::sc_byte_heap (std::size_t heap_size)\fR [inline]\fP"

.SS "sc_core::sc_byte_heap::~sc_byte_heap ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBchar\fP * sc_core::sc_byte_heap::allocate (std::size_t bytes_n)\fR [inline]\fP"

.SS "\fBvoid\fP sc_core::sc_byte_heap::initialize (std::size_t heap_size = \fR0x100000\fP)\fR [inline]\fP"

.SS "std::size_t sc_core::sc_byte_heap::length ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBchar\fP* sc_core::sc_byte_heap::m_bgn_p"

.SS "\fBchar\fP* sc_core::sc_byte_heap::m_end_p"

.SS "\fBchar\fP* sc_core::sc_byte_heap::m_next_p"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
