.TH "sc_core::sc_cor_pkg" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_cor_pkg
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_cor\&.h>\fP
.PP
Inherited by \fBsc_core::sc_cor_pkg_qt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_cor_pkg\fP (\fBsc_simcontext\fP *\fBsimc\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_cor_pkg\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBsc_cor\fP * \fBcreate\fP (std::size_t \fBstack_size\fP, \fBsc_cor_fn\fP *\fBfn\fP, \fBvoid\fP *arg)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fByield\fP (\fBsc_cor\fP *next_cor)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBabort\fP (\fBsc_cor\fP *next_cor)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBsc_cor\fP * \fBget_main\fP ()=0"
.br
.ti -1c
.RI "\fBsc_simcontext\fP * \fBsimcontext\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_cor_pkg\fP ()"
.br
.ti -1c
.RI "\fBsc_cor_pkg\fP (\fBconst\fP \fBsc_cor_pkg\fP &)"
.br
.ti -1c
.RI "\fBsc_cor_pkg\fP & \fBoperator=\fP (\fBconst\fP \fBsc_cor_pkg\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBsc_simcontext\fP * \fBm_simc\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_cor_pkg::sc_cor_pkg (\fBsc_simcontext\fP * simc)\fR [inline]\fP"

.SS "\fBvirtual\fP sc_core::sc_cor_pkg::~sc_cor_pkg ()\fR [inline]\fP, \fR [virtual]\fP"

.SS "sc_core::sc_cor_pkg::sc_cor_pkg ()\fR [private]\fP"

.SS "sc_core::sc_cor_pkg::sc_cor_pkg (\fBconst\fP \fBsc_cor_pkg\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_cor_pkg::abort (\fBsc_cor\fP * next_cor)\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_cor_pkg_qt\fP\&.
.SS "\fBvirtual\fP \fBsc_cor\fP * sc_core::sc_cor_pkg::create (std::size_t stack_size, \fBsc_cor_fn\fP * fn, \fBvoid\fP * arg)\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_cor_pkg_qt\fP\&.
.SS "\fBvirtual\fP \fBsc_cor\fP * sc_core::sc_cor_pkg::get_main ()\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_cor_pkg_qt\fP\&.
.SS "\fBsc_cor_pkg\fP & sc_core::sc_cor_pkg::operator= (\fBconst\fP \fBsc_cor_pkg\fP &)\fR [private]\fP"

.SS "\fBsc_simcontext\fP * sc_core::sc_cor_pkg::simcontext ()\fR [inline]\fP"

.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_cor_pkg::yield (\fBsc_cor\fP * next_cor)\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_cor_pkg_qt\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsc_simcontext\fP* sc_core::sc_cor_pkg::m_simc\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
