.TH "sc_core::sc_zstring_view" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_zstring_view \- non-owning, const-ref to null-terminated string (implementation-defined)  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_string_view\&.h>\fP
.PP
Inherits sc_string_view\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_zstring_view\fP ()"
.br
.ti -1c
.RI "\fBsc_zstring_view\fP (\fBconst\fP \fBchar\fP *s)"
.br
.ti -1c
.RI "\fBsc_zstring_view\fP (\fBconst\fP std::string &s)"
.br
.ti -1c
.RI "\fBvoid\fP \fBswap\fP (\fBsc_zstring_view\fP &s)"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBc_str\fP () \fBconst\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
non-owning, const-ref to null-terminated string (implementation-defined) 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_zstring_view::sc_zstring_view ()\fR [inline]\fP"

.SS "sc_core::sc_zstring_view::sc_zstring_view (\fBconst\fP \fBchar\fP * s)\fR [inline]\fP"

.SS "sc_core::sc_zstring_view::sc_zstring_view (\fBconst\fP std::string & s)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBconst\fP \fBchar\fP * sc_core::sc_zstring_view::c_str () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_core::sc_zstring_view::swap (\fBsc_zstring_view\fP & s)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
