.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemc_modules/sc_counter.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemc_modules/sc_counter.h
.SH SYNOPSIS
.br
.PP
\fR#include <systemc\&.h>\fP
.br
\fR#include 'sc_config\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_MODULE\fP (\fBscCounter\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SC_MODULE (\fBscCounter\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
