.TH "sc_core::sc_trace_params" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_trace_params
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_signal_ports\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_trace_params\fP (\fBsc_trace_file\fP *\fBtf_\fP, \fBconst\fP std::string &\fBname_\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsc_trace_file\fP * \fBtf\fP"
.br
.ti -1c
.RI "std::string \fBname\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_trace_params::sc_trace_params (\fBsc_trace_file\fP * tf_, \fBconst\fP std::string & name_)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string sc_core::sc_trace_params::name"

.SS "\fBsc_trace_file\fP* sc_core::sc_trace_params::tf"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
