.TH "sc_core::sc_writer_policy_nocheck_port" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_writer_policy_nocheck_port
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_writer_policy\&.h>\fP
.PP
Inherited by \fBsc_core::sc_writer_policy_check< SC_MANY_WRITERS >\fP, and \fBsc_core::sc_writer_policy_check< SC_UNCHECKED_WRITERS >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBcheck_port\fP (\fBsc_object\fP *, \fBsc_port_base\fP *, \fBbool\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP sc_core::sc_writer_policy_nocheck_port::check_port (\fBsc_object\fP *, \fBsc_port_base\fP *, \fBbool\fP)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
