.TH "sc_core::sc_time_tuple" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_time_tuple
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_time\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_time_tuple\fP ()"
.br
.ti -1c
.RI "\fBsc_time_tuple\fP (\fBconst\fP \fBsc_time\fP &t)"
.br
.ti -1c
.RI "\fBbool\fP \fBhas_value\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvalue_type\fP \fBvalue\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_time_unit\fP \fBunit\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBunit_symbol\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBoperator sc_time\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBdouble\fP \fBto_double\fP () \fBconst\fP"
.br
.ti -1c
.RI "std::string \fBto_string\fP () \fBconst\fP"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_time::value_type\fP \fBvalue_type\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_time_tuple\fP (\fBvalue_type\fP v)"
.br
.ti -1c
.RI "\fBvoid\fP \fBinit\fP (\fBvalue_type\fP v)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBvalue_type\fP \fBm_value\fP"
.br
.ti -1c
.RI "\fBsc_time_unit\fP \fBm_unit\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBm_offset\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_time\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBsc_time::value_type\fP \fBsc_core::sc_time_tuple::value_type\fP\fR [private]\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_time_tuple::sc_time_tuple (\fBvalue_type\fP v)\fR [inline]\fP, \fR [explicit]\fP, \fR [private]\fP"

.SS "sc_core::sc_time_tuple::sc_time_tuple ()\fR [inline]\fP"

.SS "sc_core::sc_time_tuple::sc_time_tuple (\fBconst\fP \fBsc_time\fP & t)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP sc_core::sc_time_tuple::has_value () const"

.SS "\fBvoid\fP sc_core::sc_time_tuple::init (\fBvalue_type\fP v)\fR [private]\fP"

.SS "sc_core::sc_time_tuple::operator \fBsc_time\fP () const\fR [inline]\fP"

.SS "\fBdouble\fP sc_core::sc_time_tuple::to_double () const\fR [inline]\fP"

.SS "std::string sc_core::sc_time_tuple::to_string () const"

.SS "\fBsc_time_unit\fP sc_core::sc_time_tuple::unit () const\fR [inline]\fP"

.SS "\fBconst\fP \fBchar\fP * sc_core::sc_time_tuple::unit_symbol () const"

.SS "\fBvalue_type\fP sc_core::sc_time_tuple::value () const"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_time\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBunsigned\fP sc_core::sc_time_tuple::m_offset\fR [private]\fP"

.SS "\fBsc_time_unit\fP sc_core::sc_time_tuple::m_unit\fR [private]\fP"

.SS "\fBvalue_type\fP sc_core::sc_time_tuple::m_value\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
