.TH "sc_core::sc_cor_qt" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_cor_qt
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_cor_qt\&.h>\fP
.PP
Inherits \fBsc_core::sc_cor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_cor_qt\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_cor_qt\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBstack_protect\fP (\fBbool\fP enable)"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_cor\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~sc_cor\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::size_t \fBm_stack_size\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBm_stack\fP"
.br
.ti -1c
.RI "\fBqt_t\fP * \fBm_sp\fP"
.br
.ti -1c
.RI "\fBsc_cor_pkg_qt\fP * \fBm_pkg\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_cor_qt\fP (\fBconst\fP \fBsc_cor_qt\fP &)"
.br
.ti -1c
.RI "\fBsc_cor_qt\fP & \fBoperator=\fP (\fBconst\fP \fBsc_cor_qt\fP &)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBsc_core::sc_cor\fP
.in +1c
.ti -1c
.RI "\fBsc_cor\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_cor_qt::sc_cor_qt ()\fR [inline]\fP"

.SS "\fBvirtual\fP sc_core::sc_cor_qt::~sc_cor_qt ()\fR [inline]\fP, \fR [virtual]\fP"

.SS "sc_core::sc_cor_qt::sc_cor_qt (\fBconst\fP \fBsc_cor_qt\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBsc_cor_qt\fP & sc_core::sc_cor_qt::operator= (\fBconst\fP \fBsc_cor_qt\fP &)\fR [private]\fP"

.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_cor_qt::stack_protect (\fBbool\fP enable)\fR [virtual]\fP"

.PP
Reimplemented from \fBsc_core::sc_cor\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsc_cor_pkg_qt\fP* sc_core::sc_cor_qt::m_pkg"

.SS "\fBqt_t\fP* sc_core::sc_cor_qt::m_sp"

.SS "\fBvoid\fP* sc_core::sc_cor_qt::m_stack"

.SS "std::size_t sc_core::sc_cor_qt::m_stack_size"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
