.TH "sc_core::sc_writer_policy_check_delta" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_writer_policy_check_delta
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_writer_policy\&.h>\fP
.PP
Inherits \fBsc_core::sc_writer_policy_check_write\fP\&.
.PP
Inherited by \fBsc_core::sc_writer_policy_check< SC_MANY_WRITERS >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBneeds_update\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBupdate\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_writer_policy_check_write\fP
.in +1c
.ti -1c
.RI "\fBbool\fP \fBcheck_write\fP (\fBsc_object\fP *target, \fBbool\fP value_changed)"
.br
.ti -1c
.RI "\fBbool\fP \fBneeds_update\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBupdate\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_writer_policy_check_delta\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_writer_policy_check_write\fP
.in +1c
.ti -1c
.RI "\fBsc_writer_policy_check_write\fP (\fBbool\fP \fBdelta_only\fP=\fBonly_delta\fP())"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBsc_core::sc_writer_policy_check_write\fP
.in +1c
.ti -1c
.RI "\fBconst\fP \fBbool\fP \fBm_delta_only\fP"
.br
.ti -1c
.RI "\fBsc_process_handle\fP \fBm_writer_p\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_writer_policy_check_delta::sc_writer_policy_check_delta ()\fR [inline]\fP, \fR [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP sc_core::sc_writer_policy_check_delta::needs_update () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_core::sc_writer_policy_check_delta::update ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
