.TH "sc_core::sc_mutex_if" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_mutex_if
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_mutex_if\&.h>\fP
.PP
Inherits \fBsc_core::sc_interface\fP\&.
.PP
Inherited by \fBsc_core::sc_host_mutex\fP, and \fBsc_core::sc_mutex\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP int \fBlock\fP ()=0"
.br
.ti -1c
.RI "\fBvirtual\fP int \fBtrylock\fP ()=0"
.br
.ti -1c
.RI "\fBvirtual\fP int \fBunlock\fP ()=0"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBregister_port\fP (\fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBchar\fP *\fBif_typename_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_interface\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_mutex_if\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBsc_interface\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_mutex_if\fP (\fBconst\fP \fBsc_mutex_if\fP &)"
.br
.ti -1c
.RI "\fBsc_mutex_if\fP & \fBoperator=\fP (\fBconst\fP \fBsc_mutex_if\fP &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_mutex_if::sc_mutex_if ()\fR [inline]\fP, \fR [protected]\fP"

.SS "sc_core::sc_mutex_if::sc_mutex_if (\fBconst\fP \fBsc_mutex_if\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP int sc_core::sc_mutex_if::lock ()\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_host_mutex\fP, and \fBsc_core::sc_mutex\fP\&.
.SS "\fBsc_mutex_if\fP & sc_core::sc_mutex_if::operator= (\fBconst\fP \fBsc_mutex_if\fP &)\fR [private]\fP"

.SS "\fBvirtual\fP int sc_core::sc_mutex_if::trylock ()\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_host_mutex\fP, and \fBsc_core::sc_mutex\fP\&.
.SS "\fBvirtual\fP int sc_core::sc_mutex_if::unlock ()\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_host_mutex\fP, and \fBsc_core::sc_mutex\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
