.TH "sc_core::sc_reset_target" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_reset_target
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_reset\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBm_async\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_level\fP"
.br
.ti -1c
.RI "\fBsc_process_b\fP * \fBm_process_p\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP sc_core::sc_reset_target::m_async"

.SS "\fBbool\fP sc_core::sc_reset_target::m_level"

.SS "\fBsc_process_b\fP* sc_core::sc_reset_target::m_process_p"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
