.TH "sc_core::sc_object::hierarchy_scope" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_object::hierarchy_scope
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_object_int\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBhierarchy_scope\fP (\fBsc_object\fP *obj)"
.br
.ti -1c
.RI "\fBhierarchy_scope\fP (\fBsc_module\fP *\fBmod\fP)"
.br
.ti -1c
.RI "\fB~hierarchy_scope\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBhierarchy_scope\fP (\fBhierarchy_scope\fP \fBconst\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBhierarchy_scope\fP & \fBoperator=\fP (\fBhierarchy_scope\fP \fBconst\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBsc_module\fP * \fBscope_\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_object::hierarchy_scope::hierarchy_scope (\fBsc_object\fP * obj)\fR [inline]\fP, \fR [explicit]\fP"

.SS "sc_core::sc_object::hierarchy_scope::hierarchy_scope (\fBsc_module\fP * mod)\fR [inline]\fP, \fR [explicit]\fP"

.SS "sc_core::sc_object::hierarchy_scope::~hierarchy_scope ()\fR [inline]\fP"

.SS "sc_core::sc_object::hierarchy_scope::hierarchy_scope (\fBhierarchy_scope\fP \fBconst\fP & other)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBhierarchy_scope\fP & sc_core::sc_object::hierarchy_scope::operator= (\fBhierarchy_scope\fP \fBconst\fP &)\fR [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_module\fP* sc_core::sc_object::hierarchy_scope::scope_\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
