.TH "sc_core::sc_plist_base" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_plist_base
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_list\&.h>\fP
.PP
Inherited by \fBsc_core::sc_plist< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_plist_elem\fP * \fBhandle_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_plist_base\fP ()"
.br
.ti -1c
.RI "\fB~sc_plist_base\fP ()"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBpush_back\fP (\fBvoid\fP *d)"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBpush_front\fP (\fBvoid\fP *d)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBpop_back\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP * \fBpop_front\fP ()"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBinsert_before\fP (\fBhandle_t\fP \fBh\fP, \fBvoid\fP *d)"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBinsert_after\fP (\fBhandle_t\fP \fBh\fP, \fBvoid\fP *d)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBremove\fP (\fBhandle_t\fP \fBh\fP)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBget\fP (\fBhandle_t\fP \fBh\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset\fP (\fBhandle_t\fP \fBh\fP, \fBvoid\fP *d)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmapcar\fP (\fBsc_plist_map_fn\fP f, \fBvoid\fP *arg)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBfront\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBback\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBerase_all\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBempty\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBhandle_t\fP \fBhead\fP"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBtail\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_plist_base_iter\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBsc_plist_elem\fP* \fBsc_core::sc_plist_base::handle_t\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_plist_base::sc_plist_base ()"

.SS "sc_core::sc_plist_base::~sc_plist_base ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP * sc_core::sc_plist_base::back () const"

.SS "\fBbool\fP sc_core::sc_plist_base::empty () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_core::sc_plist_base::erase_all ()"

.SS "\fBvoid\fP * sc_core::sc_plist_base::front () const"

.SS "\fBvoid\fP * sc_core::sc_plist_base::get (\fBhandle_t\fP h) const"

.SS "\fBhandle_t\fP sc_core::sc_plist_base::insert_after (\fBhandle_t\fP h, \fBvoid\fP * d)"

.SS "\fBhandle_t\fP sc_core::sc_plist_base::insert_before (\fBhandle_t\fP h, \fBvoid\fP * d)"

.SS "\fBvoid\fP sc_core::sc_plist_base::mapcar (\fBsc_plist_map_fn\fP f, \fBvoid\fP * arg)"

.SS "\fBvoid\fP * sc_core::sc_plist_base::pop_back ()"

.SS "\fBvoid\fP * sc_core::sc_plist_base::pop_front ()"

.SS "\fBhandle_t\fP sc_core::sc_plist_base::push_back (\fBvoid\fP * d)"

.SS "\fBhandle_t\fP sc_core::sc_plist_base::push_front (\fBvoid\fP * d)"

.SS "\fBvoid\fP * sc_core::sc_plist_base::remove (\fBhandle_t\fP h)"

.SS "\fBvoid\fP sc_core::sc_plist_base::set (\fBhandle_t\fP h, \fBvoid\fP * d)"

.SS "int sc_core::sc_plist_base::size () const"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_plist_base_iter\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBhandle_t\fP sc_core::sc_plist_base::head\fR [private]\fP"

.SS "\fBhandle_t\fP sc_core::sc_plist_base::tail\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
