.TH "sc_core::sc_strhash_iter< C >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_strhash_iter< C >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_hash\&.h>\fP
.PP
Inherits \fBsc_core::sc_phash_base_iter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_strhash_iter\fP (\fBsc_strhash\fP< \fBC\fP > *t)"
.br
.ti -1c
.RI "\fBsc_strhash_iter\fP (\fBsc_strhash\fP< \fBC\fP > &t)"
.br
.ti -1c
.RI "\fB~sc_strhash_iter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP (\fBsc_strhash\fP< \fBC\fP > *t)"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP (\fBsc_strhash\fP< \fBC\fP > &t)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBkey\fP ()"
.br
.ti -1c
.RI "\fBC\fP \fBcontents\fP ()"
.br
.ti -1c
.RI "\fBC\fP \fBset_contents\fP (\fBC\fP \fBc\fP)"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_phash_base_iter\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBreset\fP (\fBsc_phash_base\fP *t)"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP (\fBsc_phash_base\fP &t)"
.br
.ti -1c
.RI "\fBsc_phash_base_iter\fP (\fBsc_phash_base\fP *t)"
.br
.ti -1c
.RI "\fBsc_phash_base_iter\fP (\fBsc_phash_base\fP &t)"
.br
.ti -1c
.RI "\fB~sc_phash_base_iter\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBempty\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBstep\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove\fP (\fBvoid\fP(*kfree)(\fBvoid\fP *))"
.br
.ti -1c
.RI "\fBvoid\fP * \fBkey\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBcontents\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBset_contents\fP (\fBvoid\fP *\fBc\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBsc_core::sc_phash_base_iter\fP
.in +1c
.ti -1c
.RI "\fBsc_phash_base\fP * \fBtable\fP"
.br
.ti -1c
.RI "\fBsc_phash_elem\fP * \fBentry\fP"
.br
.ti -1c
.RI "\fBsc_phash_elem\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBsc_phash_elem\fP ** \fBlast\fP"
.br
.ti -1c
.RI "int \fBindex\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBC\fP > \fBsc_core::sc_strhash_iter\fP< \fBC\fP >::sc_strhash_iter (\fBsc_strhash\fP< \fBC\fP > * t)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBC\fP > \fBsc_core::sc_strhash_iter\fP< \fBC\fP >::sc_strhash_iter (\fBsc_strhash\fP< \fBC\fP > & t)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBC\fP > \fBsc_core::sc_strhash_iter\fP< \fBC\fP >::~\fBsc_strhash_iter\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBC\fP > \fBC\fP \fBsc_core::sc_strhash_iter\fP< \fBC\fP >::contents ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBC\fP > \fBconst\fP \fBchar\fP * \fBsc_core::sc_strhash_iter\fP< \fBC\fP >::key ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBC\fP > \fBvoid\fP \fBsc_core::sc_strhash_iter\fP< \fBC\fP >::remove ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBC\fP > \fBvoid\fP \fBsc_core::sc_strhash_iter\fP< \fBC\fP >::reset (\fBsc_strhash\fP< \fBC\fP > & t)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBC\fP > \fBvoid\fP \fBsc_core::sc_strhash_iter\fP< \fBC\fP >::reset (\fBsc_strhash\fP< \fBC\fP > * t)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBC\fP > \fBC\fP \fBsc_core::sc_strhash_iter\fP< \fBC\fP >::set_contents (\fBC\fP c)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
