.TH "sc_core::sc_cor_pkg_qt" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_cor_pkg_qt
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_cor_qt\&.h>\fP
.PP
Inherits \fBsc_core::sc_cor_pkg\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_cor_pkg_qt\fP (\fBsc_simcontext\fP *\fBsimc\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_cor_pkg_qt\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBsc_cor\fP * \fBcreate\fP (std::size_t \fBstack_size\fP, \fBsc_cor_fn\fP *\fBfn\fP, \fBvoid\fP *arg)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fByield\fP (\fBsc_cor\fP *next_cor)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBabort\fP (\fBsc_cor\fP *next_cor)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBsc_cor\fP * \fBget_main\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_cor_pkg\fP
.in +1c
.ti -1c
.RI "\fBsc_cor_pkg\fP (\fBsc_simcontext\fP *\fBsimc\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_cor_pkg\fP ()"
.br
.ti -1c
.RI "\fBsc_simcontext\fP * \fBsimcontext\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_cor_pkg_qt\fP ()"
.br
.ti -1c
.RI "\fBsc_cor_pkg_qt\fP (\fBconst\fP \fBsc_cor_pkg_qt\fP &)"
.br
.ti -1c
.RI "\fBsc_cor_pkg_qt\fP & \fBoperator=\fP (\fBconst\fP \fBsc_cor_pkg_qt\fP &)"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP int \fBinstance_count\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_cor_pkg_qt::sc_cor_pkg_qt (\fBsc_simcontext\fP * simc)"

.SS "\fBvirtual\fP sc_core::sc_cor_pkg_qt::~sc_cor_pkg_qt ()\fR [virtual]\fP"

.SS "sc_core::sc_cor_pkg_qt::sc_cor_pkg_qt ()\fR [private]\fP"

.SS "sc_core::sc_cor_pkg_qt::sc_cor_pkg_qt (\fBconst\fP \fBsc_cor_pkg_qt\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_cor_pkg_qt::abort (\fBsc_cor\fP * next_cor)\fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_cor_pkg\fP\&.
.SS "\fBvirtual\fP \fBsc_cor\fP * sc_core::sc_cor_pkg_qt::create (std::size_t stack_size, \fBsc_cor_fn\fP * fn, \fBvoid\fP * arg)\fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_cor_pkg\fP\&.
.SS "\fBvirtual\fP \fBsc_cor\fP * sc_core::sc_cor_pkg_qt::get_main ()\fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_cor_pkg\fP\&.
.SS "\fBsc_cor_pkg_qt\fP & sc_core::sc_cor_pkg_qt::operator= (\fBconst\fP \fBsc_cor_pkg_qt\fP &)\fR [private]\fP"

.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_cor_pkg_qt::yield (\fBsc_cor\fP * next_cor)\fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_cor_pkg\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int sc_core::sc_cor_pkg_qt::instance_count\fR [static]\fP, \fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
