.TH "sc_core::sc_mempool" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_mempool
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_mempool\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP * \fBallocate\fP (std::size_t \fBsz\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBrelease\fP (\fBvoid\fP *p, std::size_t \fBsz\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBdisplay_statistics\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBstatic\fP \fBvoid\fP * sc_core::sc_mempool::allocate (std::size_t sz)\fR [static]\fP"

.SS "\fBstatic\fP \fBvoid\fP sc_core::sc_mempool::display_statistics ()\fR [static]\fP"

.SS "\fBstatic\fP \fBvoid\fP sc_core::sc_mempool::release (\fBvoid\fP * p, std::size_t sz)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
