.TH "sc_core::SC_API_VERSION_STRING" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::SC_API_VERSION_STRING
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_ver\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSC_API_VERSION_STRING\fP (\fBsc_writer_policy\fP \fBdefault_writer_policy\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::SC_API_VERSION_STRING::SC_API_VERSION_STRING (\fBsc_writer_policy\fP default_writer_policy)"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
