.TH "sc_core::sc_event_timed" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_event_timed
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_event\&.h>\fP
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_event_timed\fP (\fBsc_event\fP *\fBe\fP, \fBconst\fP \fBsc_time\fP &t)"
.br
.ti -1c
.RI "\fB~sc_event_timed\fP ()"
.br
.ti -1c
.RI "\fBsc_event\fP * \fBevent\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_time\fP & \fBnotify_time\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_event_timed\fP ()"
.br
.ti -1c
.RI "\fBsc_event_timed\fP (\fBconst\fP \fBsc_event_timed\fP &)"
.br
.ti -1c
.RI "\fBsc_event_timed\fP & \fBoperator=\fP (\fBconst\fP \fBsc_event_timed\fP &)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP * \fBoperator new\fP (std::size_t)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *p, std::size_t)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP * \fBallocate\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBdeallocate\fP (\fBvoid\fP *)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBsc_event\fP * \fBm_event\fP"
.br
.ti -1c
.RI "\fBsc_time\fP \fBm_notify_time\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_event\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_simcontext\fP"
.br
.ti -1c
.RI "\fBSC_API\fP int \fBsc_notify_time_compare\fP (\fBconst\fP \fBvoid\fP *, \fBconst\fP \fBvoid\fP *)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_event_timed::sc_event_timed (\fBsc_event\fP * e, \fBconst\fP \fBsc_time\fP & t)\fR [inline]\fP, \fR [private]\fP"

.SS "sc_core::sc_event_timed::~sc_event_timed ()\fR [inline]\fP, \fR [private]\fP"

.SS "sc_core::sc_event_timed::sc_event_timed ()\fR [private]\fP"

.SS "sc_core::sc_event_timed::sc_event_timed (\fBconst\fP \fBsc_event_timed\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBstatic\fP \fBvoid\fP * sc_core::sc_event_timed::allocate ()\fR [static]\fP, \fR [private]\fP"

.SS "\fBstatic\fP \fBvoid\fP sc_core::sc_event_timed::deallocate (\fBvoid\fP *)\fR [static]\fP, \fR [private]\fP"

.SS "\fBsc_event\fP * sc_core::sc_event_timed::event () const\fR [inline]\fP, \fR [private]\fP"

.SS "\fBconst\fP \fBsc_time\fP & sc_core::sc_event_timed::notify_time () const\fR [inline]\fP, \fR [private]\fP"

.SS "\fBstatic\fP \fBvoid\fP sc_core::sc_event_timed::operator \fBdelete\fP (\fBvoid\fP * p, std::size_t)\fR [inline]\fP, \fR [static]\fP, \fR [private]\fP"

.SS "\fBstatic\fP \fBvoid\fP * sc_core::sc_event_timed::operator \fBnew\fP (std::size_t)\fR [inline]\fP, \fR [static]\fP, \fR [private]\fP"

.SS "\fBsc_event_timed\fP & sc_core::sc_event_timed::operator= (\fBconst\fP \fBsc_event_timed\fP &)\fR [private]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_event\fP\fR [friend]\fP"

.SS "\fBSC_API\fP int sc_notify_time_compare (\fBconst\fP \fBvoid\fP *, \fBconst\fP \fBvoid\fP *)\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_simcontext\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_event\fP* sc_core::sc_event_timed::m_event\fR [private]\fP"

.SS "\fBsc_time\fP sc_core::sc_event_timed::m_notify_time\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
