.TH "sc_core::sc_curr_proc_info" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_curr_proc_info
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_simcontext\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_curr_proc_info\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsc_process_b\fP * \fBprocess_handle\fP"
.br
.ti -1c
.RI "\fBsc_curr_proc_kind\fP \fBkind\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_curr_proc_info::sc_curr_proc_info ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_curr_proc_kind\fP sc_core::sc_curr_proc_info::kind"

.SS "\fBsc_process_b\fP* sc_core::sc_curr_proc_info::process_handle"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
