.TH "sc_core::sc_direct_access< ElementType >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_direct_access< ElementType >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_vector\&.h>\fP
.PP
Inherited by \fBsc_core::sc_vector_iter< ElementType, AccessPolicy >\fP\fR [private]\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBElementType\fP \fBelement_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBelement_type\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_meta::remove_const\fP< \fBtype\fP >\fB::type\fP \fBplain_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_direct_access\fP< \fBtype\fP > \fBpolicy\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_direct_access\fP< \fBplain_type\fP > \fBnon_const_policy\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_direct_access\fP< \fBconst\fP \fBplain_type\fP > \fBconst_policy\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_direct_access\fP ()"
.br
.ti -1c
.RI "\fBsc_direct_access\fP (\fBconst\fP \fBnon_const_policy\fP &)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBU\fP > \fBsc_direct_access\fP (\fBconst\fP \fBU\fP &, \fBSC_ENABLE_IF_\fP((\fBsc_meta::is_more_const\fP< \fBtype\fP, \fBtypename\fP U::policy::element_type >)))"
.br
.ti -1c
.RI "\fBtype\fP * \fBget\fP (\fBtype\fP *\fBthis_\fP) \fBconst\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBtypename\fP \fBElementType\fP > \fBtypedef\fP \fBsc_direct_access\fP< \fBconst\fP \fBplain_type\fP > \fBsc_core::sc_direct_access\fP< \fBElementType\fP >::const_policy"

.SS "template<\fBtypename\fP \fBElementType\fP > \fBtypedef\fP \fBElementType\fP \fBsc_core::sc_direct_access\fP< \fBElementType\fP >::element_type"

.SS "template<\fBtypename\fP \fBElementType\fP > \fBtypedef\fP \fBsc_direct_access\fP< \fBplain_type\fP > \fBsc_core::sc_direct_access\fP< \fBElementType\fP >::non_const_policy"

.SS "template<\fBtypename\fP \fBElementType\fP > \fBtypedef\fP \fBsc_meta::remove_const\fP<\fBtype\fP>\fB::type\fP \fBsc_core::sc_direct_access\fP< \fBElementType\fP >::plain_type"

.SS "template<\fBtypename\fP \fBElementType\fP > \fBtypedef\fP \fBsc_direct_access\fP< \fBtype\fP > \fBsc_core::sc_direct_access\fP< \fBElementType\fP >::policy"

.SS "template<\fBtypename\fP \fBElementType\fP > \fBtypedef\fP \fBelement_type\fP \fBsc_core::sc_direct_access\fP< \fBElementType\fP >::type"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBElementType\fP > \fBsc_core::sc_direct_access\fP< \fBElementType\fP >::sc_direct_access ()\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBElementType\fP > \fBsc_core::sc_direct_access\fP< \fBElementType\fP >::sc_direct_access (\fBconst\fP \fBnon_const_policy\fP &)\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBElementType\fP > template<\fBtypename\fP \fBU\fP > \fBsc_core::sc_direct_access\fP< \fBElementType\fP >::sc_direct_access (\fBconst\fP \fBU\fP &, \fBSC_ENABLE_IF_\fP(( \fBsc_meta::is_more_const\fP< \fBtype\fP, \fBtypename\fP U::policy::element_type >)))\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBElementType\fP > \fBtype\fP * \fBsc_core::sc_direct_access\fP< \fBElementType\fP >::get (\fBtype\fP * this_) const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
