.TH "sc_core::sc_module_name" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_module_name
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_module_name\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_module_name\fP (\fBconst\fP \fBchar\fP *)"
.br
.ti -1c
.RI "\fBsc_module_name\fP (\fBconst\fP \fBsc_module_name\fP &)"
.br
.ti -1c
.RI "\fB~sc_module_name\fP ()"
.br
.ti -1c
.RI "\fBoperator const char *\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBclear_module\fP (\fBsc_module\fP *\fBmodule_p\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_module\fP (\fBsc_module\fP *\fBmodule_p\fP)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_module_name\fP ()"
.br
.ti -1c
.RI "\fBsc_module_name\fP & \fBoperator=\fP (\fBconst\fP \fBsc_module_name\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBm_name\fP"
.br
.ti -1c
.RI "\fBsc_module\fP * \fBm_module_p\fP"
.br
.ti -1c
.RI "\fBsc_module_name\fP * \fBm_next\fP"
.br
.ti -1c
.RI "\fBsc_simcontext\fP * \fBm_simc\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_pushed\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_module\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_object_manager\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_module_name::sc_module_name (\fBconst\fP \fBchar\fP *)"

.SS "sc_core::sc_module_name::sc_module_name (\fBconst\fP \fBsc_module_name\fP &)"

.SS "sc_core::sc_module_name::~sc_module_name ()"

.SS "sc_core::sc_module_name::sc_module_name ()\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP sc_core::sc_module_name::clear_module (\fBsc_module\fP * module_p)\fR [inline]\fP, \fR [protected]\fP"

.SS "sc_core::sc_module_name::operator \fBconst\fP \fBchar\fP * () const"

.SS "\fBsc_module_name\fP & sc_core::sc_module_name::operator= (\fBconst\fP \fBsc_module_name\fP &)\fR [private]\fP"

.SS "\fBvoid\fP sc_core::sc_module_name::set_module (\fBsc_module\fP * module_p)\fR [inline]\fP, \fR [protected]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_module\fP\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_object_manager\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_module\fP* sc_core::sc_module_name::m_module_p\fR [private]\fP"

.SS "\fBconst\fP \fBchar\fP* sc_core::sc_module_name::m_name\fR [private]\fP"

.SS "\fBsc_module_name\fP* sc_core::sc_module_name::m_next\fR [private]\fP"

.SS "\fBbool\fP sc_core::sc_module_name::m_pushed\fR [private]\fP"

.SS "\fBsc_simcontext\fP* sc_core::sc_module_name::m_simc\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
