.TH "sc_core::sc_writer_policy_nocheck_write" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_writer_policy_nocheck_write
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_writer_policy\&.h>\fP
.PP
Inherited by \fBsc_core::sc_writer_policy_check< SC_UNCHECKED_WRITERS >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBcheck_write\fP (\fBsc_object\fP *, \fBbool\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBneeds_update\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBupdate\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP sc_core::sc_writer_policy_nocheck_write::check_write (\fBsc_object\fP *, \fBbool\fP)\fR [inline]\fP"

.SS "\fBbool\fP sc_core::sc_writer_policy_nocheck_write::needs_update () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_core::sc_writer_policy_nocheck_write::update ()\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
