.TH "sc_core::sc_name_gen" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_name_gen
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_name_gen\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_name_gen\fP ()"
.br
.ti -1c
.RI "\fB~sc_name_gen\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBgen_unique_name\fP (\fBconst\fP \fBchar\fP *\fBbasename_\fP, \fBbool\fP \fBpreserve_first\fP=\fBfalse\fP)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_name_gen\fP (\fBconst\fP \fBsc_name_gen\fP &)"
.br
.ti -1c
.RI "\fBsc_name_gen\fP & \fBoperator=\fP (\fBconst\fP \fBsc_name_gen\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBsc_strhash\fP< int * > \fBm_unique_name_map\fP"
.br
.ti -1c
.RI "std::string \fBm_unique_name\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_name_gen::sc_name_gen ()"

.SS "sc_core::sc_name_gen::~sc_name_gen ()"

.SS "sc_core::sc_name_gen::sc_name_gen (\fBconst\fP \fBsc_name_gen\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBconst\fP \fBchar\fP * sc_core::sc_name_gen::gen_unique_name (\fBconst\fP \fBchar\fP * basename_, \fBbool\fP preserve_first = \fR\fBfalse\fP\fP)"

.SS "\fBsc_name_gen\fP & sc_core::sc_name_gen::operator= (\fBconst\fP \fBsc_name_gen\fP &)\fR [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string sc_core::sc_name_gen::m_unique_name\fR [private]\fP"

.SS "\fBsc_strhash\fP<int*> sc_core::sc_name_gen::m_unique_name_map\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
