.TH "sc_core::sc_throw_it< EXCEPT >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_throw_it< EXCEPT >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_process\&.h>\fP
.PP
Inherits \fBsc_core::sc_throw_it_helper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_throw_it\fP (\fBconst\fP \fBEXCEPT\fP &\fBvalue\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_throw_it\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBthis_type\fP * \fBclone\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBthrow_it\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_throw_it_helper\fP
.in +1c
.ti -1c
.RI "\fBsc_throw_it_helper\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_throw_it_helper\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBEXCEPT\fP \fBm_value\fP"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_throw_it\fP< \fBEXCEPT\fP > \fBthis_type\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBtypename\fP \fBEXCEPT\fP > \fBtypedef\fP \fBsc_throw_it\fP<\fBEXCEPT\fP> \fBsc_core::sc_throw_it\fP< \fBEXCEPT\fP >::this_type\fR [private]\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBEXCEPT\fP > \fBsc_core::sc_throw_it\fP< \fBEXCEPT\fP >::sc_throw_it (\fBconst\fP \fBEXCEPT\fP & value)\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBEXCEPT\fP > \fBvirtual\fP \fBsc_core::sc_throw_it\fP< \fBEXCEPT\fP >::~\fBsc_throw_it\fP ()\fR [inline]\fP, \fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBEXCEPT\fP > \fBvirtual\fP \fBthis_type\fP * \fBsc_core::sc_throw_it\fP< \fBEXCEPT\fP >::clone () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_throw_it_helper\fP\&.
.SS "template<\fBtypename\fP \fBEXCEPT\fP > \fBvirtual\fP \fBvoid\fP \fBsc_core::sc_throw_it\fP< \fBEXCEPT\fP >::throw_it ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_throw_it_helper\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBEXCEPT\fP > \fBEXCEPT\fP \fBsc_core::sc_throw_it\fP< \fBEXCEPT\fP >::m_value\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
