.TH "sc_core::sc_throw_it_helper" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_throw_it_helper
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_process\&.h>\fP
.PP
Inherited by \fBsc_core::sc_throw_it< EXCEPT >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBsc_throw_it_helper\fP * \fBclone\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBthrow_it\fP ()=0"
.br
.ti -1c
.RI "\fBsc_throw_it_helper\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_throw_it_helper\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_throw_it_helper::sc_throw_it_helper ()\fR [inline]\fP"

.SS "\fBvirtual\fP sc_core::sc_throw_it_helper::~sc_throw_it_helper ()\fR [inline]\fP, \fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBsc_throw_it_helper\fP * sc_core::sc_throw_it_helper::clone () const\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_throw_it< EXCEPT >\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_throw_it_helper::throw_it ()\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_throw_it< EXCEPT >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
