.TH "sc_core::sc_writer_policy_check_write" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_writer_policy_check_write
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_writer_policy\&.h>\fP
.PP
Inherited by \fBsc_core::sc_writer_policy_check< SC_ONE_WRITER >\fP, and \fBsc_core::sc_writer_policy_check_delta\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBcheck_write\fP (\fBsc_object\fP *target, \fBbool\fP value_changed)"
.br
.ti -1c
.RI "\fBbool\fP \fBneeds_update\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBupdate\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_writer_policy_check_write\fP (\fBbool\fP \fBdelta_only\fP=\fBonly_delta\fP())"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBbool\fP \fBm_delta_only\fP"
.br
.ti -1c
.RI "\fBsc_process_handle\fP \fBm_writer_p\fP"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBonly_delta\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_writer_policy_check_write::sc_writer_policy_check_write (\fBbool\fP delta_only = \fR\fBonly_delta\fP()\fP)\fR [inline]\fP, \fR [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP sc_core::sc_writer_policy_check_write::check_write (\fBsc_object\fP * target, \fBbool\fP value_changed)\fR [inline]\fP"

.SS "\fBbool\fP sc_core::sc_writer_policy_check_write::needs_update () const\fR [inline]\fP"

.SS "\fBstatic\fP \fBbool\fP sc_core::sc_writer_policy_check_write::only_delta ()\fR [static]\fP, \fR [private]\fP"

.SS "\fBvoid\fP sc_core::sc_writer_policy_check_write::update ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBconst\fP \fBbool\fP sc_core::sc_writer_policy_check_write::m_delta_only\fR [protected]\fP"

.SS "\fBsc_process_handle\fP sc_core::sc_writer_policy_check_write::m_writer_p\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
