.TH "sc_core::sc_inout< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_inout< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_signal_ports\&.h>\fP
.PP
Inherits \fBsc_core::sc_port< sc_signal_inout_if< T >, 1, SC_ONE_OR_MORE_BOUND >\fP\&.
.PP
Inherited by \fBsc_core::sc_out< sc_dt::sc_lv >\fP, \fBsc_core::sc_out< typename sc_dt::sc_lv >\fP, \fBsc_core::sc_out< bool >\fP, and \fBsc_core::sc_out< T >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBT\fP \fBdata_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_signal_inout_if\fP< \fBdata_type\fP > \fBif_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_port\fP< \fBif_type\fP, 1, \fBSC_ONE_OR_MORE_BOUND\fP > \fBbase_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_inout\fP< \fBdata_type\fP > \fBthis_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_signal_in_if\fP< \fBdata_type\fP > \fBin_if_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_port\fP< \fBin_if_type\fP, 1, \fBSC_ONE_OR_MORE_BOUND\fP > \fBin_port_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBif_type\fP \fBinout_if_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBbase_type\fP \fBinout_port_type\fP"
.br
.in -1c

Public Types inherited from \fBsc_core::sc_port_b< IF >\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_port_base\fP \fBbase_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_port_b\fP< \fBIF\fP > \fBthis_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBthis_type\fP \fBport_type\fP"
.br
.in -1c

Public Types inherited from \fBsc_core::sc_port_base\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_port_base\fP \fBthis_type\fP"
.br
.in -1c

Public Types inherited from \fBsc_core::sc_object\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBunsigned\fP \fBphase_cb_mask\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_inout\fP ()"
.br
.ti -1c
.RI "\fBsc_inout\fP (\fBconst\fP \fBchar\fP *\fBname_\fP)"
.br
.ti -1c
.RI "\fBsc_inout\fP (\fBinout_if_type\fP &\fBinterface_\fP)"
.br
.ti -1c
.RI "\fBsc_inout\fP (\fBconst\fP \fBchar\fP *\fBname_\fP, \fBinout_if_type\fP &\fBinterface_\fP)"
.br
.ti -1c
.RI "\fBsc_inout\fP (\fBinout_port_type\fP &\fBparent_\fP)"
.br
.ti -1c
.RI "\fBsc_inout\fP (\fBconst\fP \fBchar\fP *\fBname_\fP, \fBinout_port_type\fP &\fBparent_\fP)"
.br
.ti -1c
.RI "\fBsc_inout\fP (\fBthis_type\fP &\fBparent_\fP)"
.br
.ti -1c
.RI "\fBsc_inout\fP (\fBconst\fP \fBchar\fP *\fBname_\fP, \fBthis_type\fP &\fBparent_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_inout\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_event\fP & \fBvalue_changed_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBdata_type\fP & \fBread\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBoperator const data_type &\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBevent\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBwrite\fP (\fBconst\fP \fBdata_type\fP &\fBvalue_\fP)"
.br
.ti -1c
.RI "\fBthis_type\fP & \fBoperator=\fP (\fBconst\fP \fBdata_type\fP &\fBvalue_\fP)"
.br
.ti -1c
.RI "\fBthis_type\fP & \fBoperator=\fP (\fBconst\fP \fBin_if_type\fP &\fBinterface_\fP)"
.br
.ti -1c
.RI "\fBthis_type\fP & \fBoperator=\fP (\fBconst\fP \fBin_port_type\fP &\fBport_\fP)"
.br
.ti -1c
.RI "\fBthis_type\fP & \fBoperator=\fP (\fBconst\fP \fBinout_port_type\fP &\fBport_\fP)"
.br
.ti -1c
.RI "\fBthis_type\fP & \fBoperator=\fP (\fBconst\fP \fBthis_type\fP &\fBport_\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBinitialize\fP (\fBconst\fP \fBdata_type\fP &\fBvalue_\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBinitialize\fP (\fBconst\fP \fBin_if_type\fP &\fBinterface_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBend_of_elaboration\fP ()"
.br
.ti -1c
.RI "\fBsc_event_finder\fP & \fBvalue_changed\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBchar\fP * \fBkind\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd_trace_internal\fP (\fBsc_trace_file\fP *, \fBconst\fP std::string &) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd_trace\fP (\fBsc_trace_file\fP *, \fBconst\fP std::string &) \fBconst\fP"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_port< sc_signal_inout_if< T >, 1, SC_ONE_OR_MORE_BOUND >\fP
.in +1c
.ti -1c
.RI "\fBsc_port\fP ()"
.br
.ti -1c
.RI "\fBsc_port\fP (\fBconst\fP \fBchar\fP *\fBname_\fP)"
.br
.ti -1c
.RI "\fBsc_port\fP (\fBsc_signal_inout_if\fP< \fBT\fP > &\fBinterface_\fP)"
.br
.ti -1c
.RI "\fBsc_port\fP (\fBconst\fP \fBchar\fP *\fBname_\fP, \fBsc_signal_inout_if\fP< \fBT\fP > &\fBinterface_\fP)"
.br
.ti -1c
.RI "\fBsc_port\fP (\fBbase_type\fP &\fBparent_\fP)"
.br
.ti -1c
.RI "\fBsc_port\fP (\fBconst\fP \fBchar\fP *\fBname_\fP, \fBbase_type\fP &\fBparent_\fP)"
.br
.ti -1c
.RI "\fBsc_port\fP (\fBthis_type\fP &\fBparent_\fP)"
.br
.ti -1c
.RI "\fBsc_port\fP (\fBconst\fP \fBchar\fP *\fBname_\fP, \fBthis_type\fP &\fBparent_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_port\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_port_b< IF >\fP
.in +1c
.ti -1c
.RI "\fBSC_VIRTUAL_\fP \fBvoid\fP \fBbind\fP (\fBIF\fP &\fBinterface_\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator()\fP (\fBIF\fP &\fBinterface_\fP)"
.br
.ti -1c
.RI "\fBSC_VIRTUAL_\fP \fBvoid\fP \fBbind\fP (\fBport_type\fP &\fBparent_\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator()\fP (\fBport_type\fP &\fBparent_\fP)"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBIF\fP * \fBoperator\->\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBIF\fP * \fBoperator\->\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBIF\fP * \fBget_interface\fP (int \fBiface_i\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBIF\fP * \fBget_interface\fP (int \fBiface_i\fP)"
.br
.ti -1c
.RI "\fBIF\fP * \fBoperator[]\fP (int \fBindex_\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBIF\fP * \fBoperator[]\fP (int \fBindex_\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBsc_interface\fP * \fBget_interface\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_interface\fP * \fBget_interface\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBsc_type_index\fP \fBget_interface_type\fP () \fBconst\fP"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_port_base\fP
.in +1c
.ti -1c
.RI "int \fBbind_count\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_object\fP
.in +1c
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBbasename\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBprint\fP (::std::ostream &\fBos\fP=::std::cout) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBdump\fP (::std::ostream &\fBos\fP=::std::cout) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBtrace\fP (\fBsc_trace_file\fP *tf) \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_simcontext\fP * \fBsimcontext\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBadd_attribute\fP (\fBsc_attr_base\fP &)"
.br
.ti -1c
.RI "\fBsc_attr_base\fP * \fBget_attribute\fP (\fBconst\fP std::string &\fBname_\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_attr_base\fP * \fBget_attribute\fP (\fBconst\fP std::string &\fBname_\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_attr_base\fP * \fBremove_attribute\fP (\fBconst\fP std::string &\fBname_\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove_all_attributes\fP ()"
.br
.ti -1c
.RI "int \fBnum_attributes\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_attr_cltn\fP & \fBattr_cltn\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_attr_cltn\fP & \fBattr_cltn\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP std::vector< \fBsc_event\fP * > & \fBget_child_events\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP std::vector< \fBsc_object\fP * > & \fBget_child_objects\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_object\fP * \fBget_parent\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_object\fP * \fBget_parent_object\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBremove_traces\fP () \fBconst\fP"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_port_b< IF >\fP
.in +1c
.ti -1c
.RI "\fBsc_port_b\fP (int \fBmax_size_\fP, \fBsc_port_policy\fP policy=\fBSC_ONE_OR_MORE_BOUND\fP)"
.br
.ti -1c
.RI "\fBsc_port_b\fP (\fBconst\fP \fBchar\fP *\fBname_\fP, int \fBmax_size_\fP, \fBsc_port_policy\fP policy=\fBSC_ONE_OR_MORE_BOUND\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_port_b\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP int \fBvbind\fP (\fBsc_interface\fP &)"
.br
.ti -1c
.RI "\fBvirtual\fP int \fBvbind\fP (\fBsc_port_base\fP &)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBmake_sensitive\fP (\fBsc_thread_handle\fP, \fBsc_event_finder\fP *=0) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBmake_sensitive\fP (\fBsc_method_handle\fP, \fBsc_event_finder\fP *=0) \fBconst\fP"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_port_base\fP
.in +1c
.ti -1c
.RI "\fBsc_port_base\fP (int \fBmax_size_\fP, \fBsc_port_policy\fP policy=\fBSC_ONE_OR_MORE_BOUND\fP)"
.br
.ti -1c
.RI "\fBsc_port_base\fP (\fBconst\fP \fBchar\fP *\fBname_\fP, int \fBmax_size_\fP, \fBsc_port_policy\fP policy=\fBSC_ONE_OR_MORE_BOUND\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_port_base\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBbind\fP (\fBsc_interface\fP &\fBinterface_\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBbind\fP (\fBthis_type\fP &\fBparent_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBbefore_end_of_elaboration\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBstart_of_simulation\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBend_of_simulation\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBreport_error\fP (\fBconst\fP \fBchar\fP *id, \fBconst\fP \fBchar\fP *\fBadd_msg\fP=0) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd_static_event\fP (\fBsc_method_handle\fP \fBprocess_p\fP, \fBconst\fP \fBsc_event\fP &event) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd_static_event\fP (\fBsc_thread_handle\fP \fBprocess_p\fP, \fBconst\fP \fBsc_event\fP &event) \fBconst\fP"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_object\fP
.in +1c
.ti -1c
.RI "\fBsc_object\fP ()"
.br
.ti -1c
.RI "\fBsc_object\fP (\fBconst\fP \fBchar\fP *\fBnm\fP)"
.br
.ti -1c
.RI "\fBsc_object\fP (\fBconst\fP \fBsc_object\fP &)"
.br
.ti -1c
.RI "\fBsc_object\fP & \fBoperator=\fP (\fBconst\fP \fBsc_object\fP &)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_object\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBadd_child_event\fP (\fBsc_event\fP *\fBevent_p\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBadd_child_object\fP (\fBsc_object\fP *\fBobject_p\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBremove_child_event\fP (\fBsc_event\fP *\fBevent_p\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBremove_child_object\fP (\fBsc_object\fP *\fBobject_p\fP)"
.br
.ti -1c
.RI "\fBphase_cb_mask\fP \fBregister_simulation_phase_callback\fP (\fBphase_cb_mask\fP)"
.br
.ti -1c
.RI "\fBphase_cb_mask\fP \fBunregister_simulation_phase_callback\fP (\fBphase_cb_mask\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBdata_type\fP * \fBm_init_val\fP"
.br
.ti -1c
.RI "\fBsc_trace_params_vec\fP * \fBm_traces\fP"
.br
.in -1c

Protected Attributes inherited from \fBsc_core::sc_port_base\fP
.in +1c
.ti -1c
.RI "\fBsc_bind_info\fP * \fBm_bind_info\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_inout\fP (\fBconst\fP \fBthis_type\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBsc_event_finder\fP * \fBm_change_finder_p\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fBsc_port\fP<\fBif_type\fP,1,\fBSC_ONE_OR_MORE_BOUND\fP> \fBsc_core::sc_inout\fP< \fBT\fP >::base_type"

.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fBT\fP \fBsc_core::sc_inout\fP< \fBT\fP >::data_type"

.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fBsc_signal_inout_if\fP<\fBdata_type\fP> \fBsc_core::sc_inout\fP< \fBT\fP >::if_type"

.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fBsc_signal_in_if\fP<\fBdata_type\fP> \fBsc_core::sc_inout\fP< \fBT\fP >::in_if_type"

.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fBsc_port\fP<\fBin_if_type\fP,1,\fBSC_ONE_OR_MORE_BOUND\fP> \fBsc_core::sc_inout\fP< \fBT\fP >::in_port_type"

.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fBif_type\fP \fBsc_core::sc_inout\fP< \fBT\fP >::inout_if_type"

.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fBbase_type\fP \fBsc_core::sc_inout\fP< \fBT\fP >::inout_port_type"

.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP \fBsc_inout\fP<\fBdata_type\fP> \fBsc_core::sc_inout\fP< \fBT\fP >::this_type"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_inout\fP< \fBT\fP >::sc_inout ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_inout\fP< \fBT\fP >::sc_inout (\fBconst\fP \fBchar\fP * name_)\fR [inline]\fP, \fR [explicit]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_inout\fP< \fBT\fP >::sc_inout (\fBinout_if_type\fP & interface_)\fR [inline]\fP, \fR [explicit]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_inout\fP< \fBT\fP >::sc_inout (\fBconst\fP \fBchar\fP * name_, \fBinout_if_type\fP & interface_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_inout\fP< \fBT\fP >::sc_inout (\fBinout_port_type\fP & parent_)\fR [inline]\fP, \fR [explicit]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_inout\fP< \fBT\fP >::sc_inout (\fBconst\fP \fBchar\fP * name_, \fBinout_port_type\fP & parent_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_inout\fP< \fBT\fP >::sc_inout (\fBthis_type\fP & parent_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_inout\fP< \fBT\fP >::sc_inout (\fBconst\fP \fBchar\fP * name_, \fBthis_type\fP & parent_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_inout\fP< \fBT\fP >::~\fBsc_inout\fP ()\fR [inline]\fP, \fR [virtual]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_inout\fP< \fBT\fP >::sc_inout (\fBconst\fP \fBthis_type\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_inout\fP< \fBT\fP >::add_trace (\fBsc_trace_file\fP * tf_, \fBconst\fP std::string & name_) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_inout\fP< \fBT\fP >::add_trace_internal (\fBsc_trace_file\fP * tf_, \fBconst\fP std::string & name_) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBsc_event\fP & \fBsc_core::sc_inout\fP< \fBT\fP >::default_event () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_inout\fP< \fBT\fP >::end_of_elaboration ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBsc_core::sc_port_base\fP\&.
.PP
Reimplemented in \fBsc_core::sc_inout_rv< W >\fP\&.
.SS "template<\fBclass\fP \fBT\fP > \fBbool\fP \fBsc_core::sc_inout\fP< \fBT\fP >::event () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_inout\fP< \fBT\fP >::initialize (\fBconst\fP \fBdata_type\fP & value_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_inout\fP< \fBT\fP >::initialize (\fBconst\fP \fBin_if_type\fP & interface_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvirtual\fP \fBconst\fP \fBchar\fP * \fBsc_core::sc_inout\fP< \fBT\fP >::kind () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBsc_core::sc_port< sc_signal_inout_if< T >, 1, SC_ONE_OR_MORE_BOUND >\fP\&.
.PP
Reimplemented in \fBsc_core::sc_out< T >\fP, \fBsc_core::sc_out< bool >\fP, \fBsc_core::sc_out< sc_dt::sc_lv >\fP, \fBsc_core::sc_out< typename sc_dt::sc_lv >\fP, \fBsc_core::sc_inout_rv< W >\fP, and \fBsc_core::sc_out_rv< W >\fP\&.
.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_inout\fP< \fBT\fP >\fB::operator\fP \fBconst\fP \fBdata_type\fP & () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBthis_type\fP & \fBsc_core::sc_inout\fP< \fBT\fP >\fB::operator\fP= (\fBconst\fP \fBdata_type\fP & value_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBthis_type\fP & \fBsc_core::sc_inout\fP< \fBT\fP >\fB::operator\fP= (\fBconst\fP \fBin_if_type\fP & interface_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBthis_type\fP & \fBsc_core::sc_inout\fP< \fBT\fP >\fB::operator\fP= (\fBconst\fP \fBin_port_type\fP & port_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBthis_type\fP & \fBsc_core::sc_inout\fP< \fBT\fP >\fB::operator\fP= (\fBconst\fP \fBinout_port_type\fP & port_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBthis_type\fP & \fBsc_core::sc_inout\fP< \fBT\fP >\fB::operator\fP= (\fBconst\fP \fBthis_type\fP & port_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBdata_type\fP & \fBsc_core::sc_inout\fP< \fBT\fP >::read () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_inout\fP< \fBT\fP >::remove_traces () const\fR [inline]\fP, \fR [protected]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_event_finder\fP & \fBsc_core::sc_inout\fP< \fBT\fP >::value_changed () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBsc_event\fP & \fBsc_core::sc_inout\fP< \fBT\fP >::value_changed_event () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_inout\fP< \fBT\fP >::write (\fBconst\fP \fBdata_type\fP & value_)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_event_finder\fP* \fBsc_core::sc_inout\fP< \fBT\fP >::m_change_finder_p\fR [mutable]\fP, \fR [private]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBdata_type\fP* \fBsc_core::sc_inout\fP< \fBT\fP >::m_init_val\fR [protected]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_trace_params_vec\fP* \fBsc_core::sc_inout\fP< \fBT\fP >::m_traces\fR [mutable]\fP, \fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
