.TH "sc_core::sc_user" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_user
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_except\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_user\fP ()"
.br
.ti -1c
.RI "\fBsc_user\fP (\fBconst\fP \fBsc_user\fP &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_user::sc_user ()\fR [inline]\fP"

.SS "sc_core::sc_user::sc_user (\fBconst\fP \fBsc_user\fP &)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
