.TH "sc_core::sc_event_and_list" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_event_and_list
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_event\&.h>\fP
.PP
Inherits \fBsc_core::sc_event_list\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_event_and_list\fP ()"
.br
.ti -1c
.RI "\fBsc_event_and_list\fP (\fBconst\fP \fBsc_event\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBswap\fP (\fBsc_event_and_list\fP &)"
.br
.ti -1c
.RI "\fBsc_event_and_list\fP & \fBoperator&=\fP (\fBconst\fP \fBsc_event\fP &)"
.br
.ti -1c
.RI "\fBsc_event_and_list\fP & \fBoperator&=\fP (\fBconst\fP \fBsc_event_and_list\fP &)"
.br
.ti -1c
.RI "\fBsc_event_expr\fP< \fBsc_event_and_list\fP > \fBoperator&\fP (\fBconst\fP \fBsc_event\fP &)"
.br
.ti -1c
.RI "\fBsc_event_expr\fP< \fBsc_event_and_list\fP > \fBoperator&\fP (\fBconst\fP \fBsc_event_and_list\fP &)"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_event_list\fP
.in +1c
.ti -1c
.RI "\fBsc_event_list\fP (\fBconst\fP \fBsc_event_list\fP &)"
.br
.ti -1c
.RI "\fBsc_event_list\fP & \fBoperator=\fP (\fBconst\fP \fBsc_event_list\fP &)"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBempty\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_event_and_list\fP (\fBbool\fP \fBauto_delete_\fP)"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_event_list\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBpush_back\fP (\fBconst\fP \fBsc_event\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpush_back\fP (\fBconst\fP \fBsc_event_list\fP &)"
.br
.ti -1c
.RI "\fBsc_event_list\fP (\fBbool\fP \fBand_list_\fP, \fBbool\fP \fBauto_delete_\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBsc_event_list\fP (\fBconst\fP \fBsc_event\fP &, \fBbool\fP \fBand_list_\fP, \fBbool\fP \fBauto_delete_\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fB~sc_event_list\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBswap\fP (\fBsc_event_list\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove_from\fP (\fBconst\fP \fBsc_event_list\fP &)"
.br
.ti -1c
.RI "\fBbool\fP \fBand_list\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd_dynamic\fP (\fBsc_method_handle\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd_dynamic\fP (\fBsc_thread_handle\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove_dynamic\fP (\fBsc_method_handle\fP, \fBconst\fP \fBsc_event\fP *) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove_dynamic\fP (\fBsc_thread_handle\fP, \fBconst\fP \fBsc_event\fP *) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBbusy\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBtemporary\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBauto_delete\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBreport_premature_destruction\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBreport_invalid_modification\fP () \fBconst\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_event\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_event_expr< sc_event_and_list >\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_process_b\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_method_process\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_thread_process\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_event_and_list::sc_event_and_list (\fBbool\fP auto_delete_)\fR [inline]\fP, \fR [explicit]\fP, \fR [protected]\fP"

.SS "sc_core::sc_event_and_list::sc_event_and_list ()\fR [inline]\fP"

.SS "sc_core::sc_event_and_list::sc_event_and_list (\fBconst\fP \fBsc_event\fP & e)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBsc_event_and_expr\fP sc_core::sc_event_and_list::operator& (\fBconst\fP \fBsc_event\fP & e)\fR [inline]\fP"

.SS "\fBsc_event_and_expr\fP sc_core::sc_event_and_list::operator& (\fBconst\fP \fBsc_event_and_list\fP & el)\fR [inline]\fP"

.SS "\fBsc_event_and_list\fP & sc_core::sc_event_and_list::operator&= (\fBconst\fP \fBsc_event\fP & e)\fR [inline]\fP"

.SS "\fBsc_event_and_list\fP & sc_core::sc_event_and_list::operator&= (\fBconst\fP \fBsc_event_and_list\fP & el)\fR [inline]\fP"

.SS "\fBvoid\fP sc_core::sc_event_and_list::swap (\fBsc_event_and_list\fP & that)\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_event\fP\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_event_expr\fP< \fBsc_event_and_list\fP >\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_method_process\fP\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_process_b\fP\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_thread_process\fP\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
