.TH "sc_core::sc_port_registry" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_port_registry
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_port\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBinsert\fP (\fBsc_port_base\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove\fP (\fBsc_port_base\fP *)"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_port_registry\fP (\fBsc_simcontext\fP &\fBsimc_\fP)"
.br
.ti -1c
.RI "\fB~sc_port_registry\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBcomplete_binding\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBconstruction_done\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBelaboration_done\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBstart_simulation\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsimulation_done\fP ()"
.br
.ti -1c
.RI "\fBsc_port_registry\fP ()"
.br
.ti -1c
.RI "\fBsc_port_registry\fP (\fBconst\fP \fBsc_port_registry\fP &)"
.br
.ti -1c
.RI "\fBsc_port_registry\fP & \fBoperator=\fP (\fBconst\fP \fBsc_port_registry\fP &)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBreplace_port\fP (\fBsc_port_registry\fP *)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_construction_done\fP"
.br
.ti -1c
.RI "std::vector< \fBsc_port_base\fP * > \fBm_port_vec\fP"
.br
.ti -1c
.RI "\fBsc_simcontext\fP * \fBm_simc\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_simcontext\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_port_registry::sc_port_registry (\fBsc_simcontext\fP & simc_)\fR [explicit]\fP, \fR [private]\fP"

.SS "sc_core::sc_port_registry::~sc_port_registry ()\fR [private]\fP"

.SS "sc_core::sc_port_registry::sc_port_registry ()\fR [private]\fP"

.SS "sc_core::sc_port_registry::sc_port_registry (\fBconst\fP \fBsc_port_registry\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP sc_core::sc_port_registry::complete_binding ()\fR [private]\fP"

.SS "\fBbool\fP sc_core::sc_port_registry::construction_done ()\fR [private]\fP"

.SS "\fBvoid\fP sc_core::sc_port_registry::elaboration_done ()\fR [private]\fP"

.SS "\fBvoid\fP sc_core::sc_port_registry::insert (\fBsc_port_base\fP *)"

.SS "\fBsc_port_registry\fP & sc_core::sc_port_registry::operator= (\fBconst\fP \fBsc_port_registry\fP &)\fR [private]\fP"

.SS "\fBvoid\fP sc_core::sc_port_registry::remove (\fBsc_port_base\fP *)"

.SS "\fBstatic\fP \fBvoid\fP sc_core::sc_port_registry::replace_port (\fBsc_port_registry\fP *)\fR [static]\fP, \fR [private]\fP"

.SS "\fBvoid\fP sc_core::sc_port_registry::simulation_done ()\fR [private]\fP"

.SS "int sc_core::sc_port_registry::size () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_core::sc_port_registry::start_simulation ()\fR [private]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_simcontext\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int sc_core::sc_port_registry::m_construction_done\fR [private]\fP"

.SS "std::vector<\fBsc_port_base\fP*> sc_core::sc_port_registry::m_port_vec\fR [private]\fP"

.SS "\fBsc_simcontext\fP* sc_core::sc_port_registry::m_simc\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
