.TH "sc_core::sc_lv_resolve< W >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_lv_resolve< W >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_signal_rv\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBresolve\fP (\fBsc_dt::sc_lv\fP< \fBW\fP > &, \fBconst\fP std::vector< \fBsc_dt::sc_lv\fP< \fBW\fP > * > &)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<int W> \fBvoid\fP \fBsc_core::sc_lv_resolve\fP< \fBW\fP >::resolve (\fBsc_dt::sc_lv\fP< \fBW\fP > & result_, \fBconst\fP std::vector< \fBsc_dt::sc_lv\fP< \fBW\fP > * > & values_)\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
