.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_cmnhdr.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_cmnhdr.h
.SH SYNOPSIS
.br
.PP
\fR#include <cassert>\fP
.br
\fR#include <cstdio>\fP
.br
\fR#include <cstdlib>\fP
.br
\fR#include <vector>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_LIKELY_\fP(\fBx\fP)   !!(\fBx\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_UNLIKELY_\fP(\fBx\fP)   !!(\fBx\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_CPLUSPLUS\fP   \fB__cplusplus\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_CPLUSPLUS_BASE_\fP   201103\fBL\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBIEEE_1666_CPLUSPLUS\fP   \fBSC_CPLUSPLUS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_NOEXCEPT_\fP   \fBthrow\fP()"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_NOEXCEPT_EXPR_\fP(\fBexpr\fP)   /* \fBnothing\fP */"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_TPLEXTERN_\fP   \fBextern\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_API\fP   /* \fBnothing\fP */"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_API_TEMPLATE_DECL_\fP   \fBSC_TPLEXTERN_\fP \fBtemplate\fP \fBclass\fP \fBSC_API\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP IEEE_1666_CPLUSPLUS   \fBSC_CPLUSPLUS\fP"

.SS "#\fBdefine\fP SC_API   /* \fBnothing\fP */"

.SS "#\fBdefine\fP SC_API_TEMPLATE_DECL_   \fBSC_TPLEXTERN_\fP \fBtemplate\fP \fBclass\fP \fBSC_API\fP"

.SS "#\fBdefine\fP SC_CPLUSPLUS   \fB__cplusplus\fP"

.SS "#\fBdefine\fP SC_CPLUSPLUS_BASE_   201103\fBL\fP"

.SS "#\fBdefine\fP SC_LIKELY_(\fBx\fP)   !!(\fBx\fP)"

.SS "#\fBdefine\fP SC_NOEXCEPT_   \fBthrow\fP()"

.SS "#\fBdefine\fP SC_NOEXCEPT_EXPR_(\fBexpr\fP)   /* \fBnothing\fP */"

.SS "#\fBdefine\fP SC_TPLEXTERN_   \fBextern\fP"

.SS "#\fBdefine\fP SC_UNLIKELY_(\fBx\fP)   !!(\fBx\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
