.TH "sc_core::sc_event_expr< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_event_expr< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_event\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_event_expr\fP (\fBsc_event_expr\fP \fBconst\fP &\fBe\fP)"
.br
.ti -1c
.RI "\fBT\fP \fBconst\fP & \fBrelease\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBpush_back\fP (\fBsc_event\fP \fBconst\fP &\fBe\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBpush_back\fP (\fBtype\fP \fBconst\fP &\fBel\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBoperator T const &\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fB~sc_event_expr\fP ()"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBT\fP \fBtype\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_event_expr\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator=\fP (\fBsc_event_expr\fP \fBconst\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBtype\fP * \fBm_expr\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_event\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_event_and_list\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_event_or_list\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBtypedef\fP \fBT\fP \fBsc_core::sc_event_expr\fP< \fBT\fP >::type\fR [private]\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBsc_core::sc_event_expr\fP< \fBT\fP >::sc_event_expr ()\fR [inline]\fP, \fR [private]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBsc_core::sc_event_expr\fP< \fBT\fP >::sc_event_expr (\fBsc_event_expr\fP< \fBT\fP > \fBconst\fP & e)\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBsc_core::sc_event_expr\fP< \fBT\fP >::~\fBsc_event_expr\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBsc_core::sc_event_expr\fP< \fBT\fP >\fB::operator\fP \fBT\fP \fBconst\fP & () const\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_event_expr\fP< \fBT\fP >\fB::operator\fP= (\fBsc_event_expr\fP< \fBT\fP > \fBconst\fP &)\fR [private]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_event_expr\fP< \fBT\fP >::push_back (\fBsc_event\fP \fBconst\fP & e) const\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_event_expr\fP< \fBT\fP >::push_back (\fBtype\fP \fBconst\fP & el) const\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBT\fP \fBconst\fP  & \fBsc_core::sc_event_expr\fP< \fBT\fP >::release () const\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBfriend\fP \fBclass\fP \fBsc_event\fP\fR [friend]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBfriend\fP \fBclass\fP \fBsc_event_and_list\fP\fR [friend]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBfriend\fP \fBclass\fP \fBsc_event_or_list\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBtype\fP* \fBsc_core::sc_event_expr\fP< \fBT\fP >::m_expr\fR [mutable]\fP, \fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
