.TH "sc_core::sc_host_semaphore" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_host_semaphore
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_host_semaphore\&.h>\fP
.PP
Inherits \fBsc_core::sc_semaphore_if\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_host_semaphore\fP (int init=0)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_host_semaphore\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP int \fBwait\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP int \fBtrywait\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP int \fBpost\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP int \fBget_value\fP () \fBconst\fP"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBregister_port\fP (\fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBchar\fP *\fBif_typename_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_interface\fP ()"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsem_t\fP \fBunderlying_type\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBdo_init\fP (int init)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdo_wait\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBdo_trywait\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBdo_post\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBdo_destroy\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBunderlying_type\fP \fBm_sem\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBsc_core::sc_semaphore_if\fP
.in +1c
.ti -1c
.RI "\fBsc_semaphore_if\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBsc_interface\fP ()"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBsem_t\fP \fBsc_core::sc_host_semaphore::underlying_type\fP\fR [private]\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_host_semaphore::sc_host_semaphore (int init = \fR0\fP)\fR [inline]\fP, \fR [explicit]\fP"

.SS "\fBvirtual\fP sc_core::sc_host_semaphore::~sc_host_semaphore ()\fR [inline]\fP, \fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP sc_core::sc_host_semaphore::do_destroy ()\fR [inline]\fP, \fR [private]\fP"

.SS "\fBvoid\fP sc_core::sc_host_semaphore::do_init (int init)\fR [inline]\fP, \fR [private]\fP"

.SS "\fBvoid\fP sc_core::sc_host_semaphore::do_post ()\fR [inline]\fP, \fR [private]\fP"

.SS "\fBbool\fP sc_core::sc_host_semaphore::do_trywait ()\fR [inline]\fP, \fR [private]\fP"

.SS "\fBvoid\fP sc_core::sc_host_semaphore::do_wait ()\fR [inline]\fP, \fR [private]\fP"

.SS "\fBvirtual\fP int sc_core::sc_host_semaphore::get_value () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_semaphore_if\fP\&.
.SS "\fBvirtual\fP int sc_core::sc_host_semaphore::post ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_semaphore_if\fP\&.
.SS "\fBvirtual\fP int sc_core::sc_host_semaphore::trywait ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_semaphore_if\fP\&.
.SS "\fBvirtual\fP int sc_core::sc_host_semaphore::wait ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_semaphore_if\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBunderlying_type\fP sc_core::sc_host_semaphore::m_sem\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
