.TH "sc_core::sc_meta::remove_special_fptr< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_meta::remove_special_fptr< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_vector\&.h>\fP

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
