.TH "sc_core::sc_spawn_object_v< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_spawn_object_v< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_spawn\&.h>\fP
.PP
Inherits \fBsc_core::sc_process_host\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_spawn_object_v\fP (\fBtypename\fP T::result_type *\fBr_p\fP, \fBT\fP \fBobject\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBsemantics\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_process_host\fP
.in +1c
.ti -1c
.RI "\fBsc_process_host\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_process_host\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBdefunct\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP \fBm_object\fP"
.br
.ti -1c
.RI "T::result_type * \fBm_result_p\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBsc_core::sc_spawn_object_v\fP< \fBT\fP >::sc_spawn_object_v (\fBtypename\fP T::result_type * r_p, \fBT\fP object)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBvirtual\fP \fBvoid\fP \fBsc_core::sc_spawn_object_v\fP< \fBT\fP >::semantics ()\fR [inline]\fP, \fR [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBT\fP \fBsc_core::sc_spawn_object_v\fP< \fBT\fP >::m_object\fR [protected]\fP"

.SS "template<\fBtypename\fP \fBT\fP > T::result_type* \fBsc_core::sc_spawn_object_v\fP< \fBT\fP >::m_result_p\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
