.TH "sc_core::sc_reset_finder" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_reset_finder
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_reset\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_reset_finder\fP (\fBbool\fP \fBasync\fP, \fBconst\fP \fBsc_in\fP< \fBbool\fP > *\fBport_p\fP, \fBbool\fP level, \fBsc_process_b\fP *\fBtarget_p\fP)"
.br
.ti -1c
.RI "\fBsc_reset_finder\fP (\fBbool\fP \fBasync\fP, \fBconst\fP \fBsc_inout\fP< \fBbool\fP > *\fBport_p\fP, \fBbool\fP level, \fBsc_process_b\fP *\fBtarget_p\fP)"
.br
.ti -1c
.RI "\fBsc_reset_finder\fP (\fBbool\fP \fBasync\fP, \fBconst\fP \fBsc_out\fP< \fBbool\fP > *\fBport_p\fP, \fBbool\fP level, \fBsc_process_b\fP *\fBtarget_p\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBm_async\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_level\fP"
.br
.ti -1c
.RI "\fBsc_reset_finder\fP * \fBm_next_p\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_in\fP< \fBbool\fP > * \fBm_in_p\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_inout\fP< \fBbool\fP > * \fBm_inout_p\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_out\fP< \fBbool\fP > * \fBm_out_p\fP"
.br
.ti -1c
.RI "\fBsc_process_b\fP * \fBm_target_p\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_reset_finder\fP (\fBconst\fP \fBsc_reset_finder\fP &)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_reset_finder\fP & \fBoperator=\fP (\fBconst\fP \fBsc_reset_finder\fP &)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_reset\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_simcontext\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_reset_finder::sc_reset_finder (\fBbool\fP async, \fBconst\fP \fBsc_in\fP< \fBbool\fP > * port_p, \fBbool\fP level, \fBsc_process_b\fP * target_p)"

.SS "sc_core::sc_reset_finder::sc_reset_finder (\fBbool\fP async, \fBconst\fP \fBsc_inout\fP< \fBbool\fP > * port_p, \fBbool\fP level, \fBsc_process_b\fP * target_p)"

.SS "sc_core::sc_reset_finder::sc_reset_finder (\fBbool\fP async, \fBconst\fP \fBsc_out\fP< \fBbool\fP > * port_p, \fBbool\fP level, \fBsc_process_b\fP * target_p)"

.SS "sc_core::sc_reset_finder::sc_reset_finder (\fBconst\fP \fBsc_reset_finder\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBconst\fP \fBsc_reset_finder\fP & sc_core::sc_reset_finder::operator= (\fBconst\fP \fBsc_reset_finder\fP &)\fR [private]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_reset\fP\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_simcontext\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP sc_core::sc_reset_finder::m_async\fR [protected]\fP"

.SS "\fBconst\fP \fBsc_in\fP<\fBbool\fP>* sc_core::sc_reset_finder::m_in_p\fR [protected]\fP"

.SS "\fBconst\fP \fBsc_inout\fP<\fBbool\fP>* sc_core::sc_reset_finder::m_inout_p\fR [protected]\fP"

.SS "\fBbool\fP sc_core::sc_reset_finder::m_level\fR [protected]\fP"

.SS "\fBsc_reset_finder\fP* sc_core::sc_reset_finder::m_next_p\fR [protected]\fP"

.SS "\fBconst\fP \fBsc_out\fP<\fBbool\fP>* sc_core::sc_reset_finder::m_out_p\fR [protected]\fP"

.SS "\fBsc_process_b\fP* sc_core::sc_reset_finder::m_target_p\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
