.TH "sc_core::sc_signal_in_if< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_signal_in_if< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_signal_ifs\&.h>\fP
.PP
Inherits \fBsc_core::sc_interface\fP\&.
.PP
Inherited by \fBsc_core::sc_signal_inout_if< sc_dt::sc_lv >\fP, \fBsc_core::sc_signal_inout_if< bool >\fP, \fBsc_core::sc_signal_inout_if< sc_dt::sc_logic >\fP, \fBsc_core::sc_signal_inout_if< sc_dt::sc_lv< W > >\fP, \fBsc_core::sc_signal_inout_if< typename sc_dt::sc_lv >\fP, \fBsc_core::sc_signal_inout_if< sc_dt::sc_lv< 32 > >\fP, and \fBsc_core::sc_signal_inout_if< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBvalue_changed_event\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBT\fP & \fBread\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBT\fP & \fBget_data_ref\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBevent\fP () \fBconst\fP =0"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBregister_port\fP (\fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBchar\fP *\fBif_typename_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_interface\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_signal_in_if\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBsc_interface\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_signal_in_if\fP (\fBconst\fP \fBsc_signal_in_if\fP< \fBT\fP > &)"
.br
.ti -1c
.RI "\fBsc_signal_in_if\fP< \fBT\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_signal_in_if\fP< \fBT\fP > &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_signal_in_if\fP< \fBT\fP >::sc_signal_in_if ()\fR [inline]\fP, \fR [protected]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_signal_in_if\fP< \fBT\fP >::sc_signal_in_if (\fBconst\fP \fBsc_signal_in_if\fP< \fBT\fP > &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBvirtual\fP \fBbool\fP \fBsc_core::sc_signal_in_if\fP< \fBT\fP >::event () const\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_signal_t< T, POL >\fP, \fBsc_core::sc_signal_t< bool, POL >\fP, \fBsc_core::sc_signal_t< sc_dt::sc_logic, POL >\fP, \fBsc_core::sc_signal_t< sc_dt::sc_lv, POL >\fP, \fBsc_core::sc_signal_t< sc_dt::sc_lv< 32 >, POL >\fP, and \fBsc_core::sc_signal_t< sc_dt::sc_lv< W >, POL >\fP\&.
.SS "template<\fBclass\fP \fBT\fP > \fBvirtual\fP \fBconst\fP \fBT\fP & \fBsc_core::sc_signal_in_if\fP< \fBT\fP >::get_data_ref () const\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_signal_t< T, POL >\fP, \fBsc_core::sc_signal_t< bool, POL >\fP, \fBsc_core::sc_signal_t< sc_dt::sc_logic, POL >\fP, \fBsc_core::sc_signal_t< sc_dt::sc_lv, POL >\fP, \fBsc_core::sc_signal_t< sc_dt::sc_lv< 32 >, POL >\fP, and \fBsc_core::sc_signal_t< sc_dt::sc_lv< W >, POL >\fP\&.
.SS "template<\fBclass\fP \fBT\fP > \fBsc_signal_in_if\fP< \fBT\fP > & \fBsc_core::sc_signal_in_if\fP< \fBT\fP >\fB::operator\fP= (\fBconst\fP \fBsc_signal_in_if\fP< \fBT\fP > &)\fR [private]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvirtual\fP \fBconst\fP \fBT\fP & \fBsc_core::sc_signal_in_if\fP< \fBT\fP >::read () const\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_signal_t< T, POL >\fP, \fBsc_core::sc_signal_t< bool, POL >\fP, \fBsc_core::sc_signal_t< sc_dt::sc_logic, POL >\fP, \fBsc_core::sc_signal_t< sc_dt::sc_lv, POL >\fP, \fBsc_core::sc_signal_t< sc_dt::sc_lv< 32 >, POL >\fP, and \fBsc_core::sc_signal_t< sc_dt::sc_lv< W >, POL >\fP\&.
.SS "template<\fBclass\fP \fBT\fP > \fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBsc_core::sc_signal_in_if\fP< \fBT\fP >::value_changed_event () const\fR [pure virtual]\fP"

.PP
Implemented in \fBsc_core::sc_signal_t< T, POL >\fP, \fBsc_core::sc_signal_t< bool, POL >\fP, \fBsc_core::sc_signal_t< sc_dt::sc_logic, POL >\fP, \fBsc_core::sc_signal_t< sc_dt::sc_lv, POL >\fP, \fBsc_core::sc_signal_t< sc_dt::sc_lv< 32 >, POL >\fP, and \fBsc_core::sc_signal_t< sc_dt::sc_lv< W >, POL >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
