.TH "sc_core::sc_plist_iter< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_plist_iter< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_list\&.h>\fP
.PP
Inherits \fBsc_core::sc_plist_base_iter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_plist_iter\fP (\fBsc_plist\fP< \fBT\fP > *\fBl\fP, \fBbool\fP \fBfrom_tail\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBsc_plist_iter\fP (\fBsc_plist\fP< \fBT\fP > &\fBl\fP, \fBbool\fP \fBfrom_tail\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fB~sc_plist_iter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP (\fBsc_plist\fP< \fBT\fP > *\fBl\fP, \fBbool\fP \fBfrom_tail\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP (\fBsc_plist\fP< \fBT\fP > &\fBl\fP, \fBbool\fP \fBfrom_tail\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBT\fP \fBoperator*\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBT\fP \fBget\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset\fP (\fBT\fP d)"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_plist_base_iter\fP
.in +1c
.ti -1c
.RI "\fBsc_plist_base_iter\fP (\fBsc_plist_base\fP *\fBl\fP, \fBbool\fP \fBfrom_tail\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fB~sc_plist_base_iter\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP (\fBsc_plist_base\fP *\fBl\fP, \fBbool\fP \fBfrom_tail\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBempty\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBget\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset\fP (\fBvoid\fP *d)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove\fP (int \fBdirection\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_handle\fP (\fBhandle_t\fP \fBh\fP)"
.br
.ti -1c
.RI "\fBhandle_t\fP \fBget_handle\fP () \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBsc_core::sc_plist_base_iter\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_plist_elem\fP * \fBhandle_t\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_plist_iter\fP< \fBT\fP >::sc_plist_iter (\fBsc_plist\fP< \fBT\fP > * l, \fBbool\fP from_tail = \fR\fBfalse\fP\fP)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_plist_iter\fP< \fBT\fP >::sc_plist_iter (\fBsc_plist\fP< \fBT\fP > & l, \fBbool\fP from_tail = \fR\fBfalse\fP\fP)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_plist_iter\fP< \fBT\fP >::~\fBsc_plist_iter\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBsc_core::sc_plist_iter\fP< \fBT\fP >::get () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBsc_core::sc_plist_iter\fP< \fBT\fP >\fB::operator\fP* () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_plist_iter\fP< \fBT\fP >::reset (\fBsc_plist\fP< \fBT\fP > & l, \fBbool\fP from_tail = \fR\fBfalse\fP\fP)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_plist_iter\fP< \fBT\fP >::reset (\fBsc_plist\fP< \fBT\fP > * l, \fBbool\fP from_tail = \fR\fBfalse\fP\fP)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_plist_iter\fP< \fBT\fP >::set (\fBT\fP d)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
