.TH "sc_core::sc_mpobject" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_mpobject
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_mempool\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP * \fBoperator new\fP (std::size_t \fBsz\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *p, std::size_t \fBsz\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP * \fBoperator new[]\fP (std::size_t \fBsz\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBoperator delete[]\fP (\fBvoid\fP *p, std::size_t \fBsz\fP)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBstatic\fP \fBvoid\fP sc_core::sc_mpobject::operator \fBdelete\fP (\fBvoid\fP * p, std::size_t sz)\fR [inline]\fP, \fR [static]\fP"

.SS "\fBstatic\fP \fBvoid\fP sc_core::sc_mpobject::operator \fBdelete\fP[] (\fBvoid\fP * p, std::size_t sz)\fR [inline]\fP, \fR [static]\fP"

.SS "\fBstatic\fP \fBvoid\fP * sc_core::sc_mpobject::operator \fBnew\fP (std::size_t sz)\fR [inline]\fP, \fR [static]\fP"

.SS "\fBstatic\fP \fBvoid\fP * sc_core::sc_mpobject::operator \fBnew\fP[] (std::size_t sz)\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
