.TH "sc_core::sc_vector_iter< ElementType, AccessPolicy >::select_iter< U >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_vector_iter< ElementType, AccessPolicy >::select_iter< U >
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP storage_type::iterator \fBtype\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessPolicy\fP  = sc_direct_access<ElementType>> template<\fBtypename\fP \fBU\fP > \fBtypedef\fP storage_type::iterator \fBsc_core::sc_vector_iter\fP< \fBElementType\fP, \fBAccessPolicy\fP >::select_iter< \fBU\fP >::type"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
