.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_communication_ids.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_communication_ids.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/utils/sc_report\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_DEFINE_MESSAGE\fP(id,  \fBunused1\fP,  \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_PORT_OUTSIDE_MODULE_\fP, 100, 'port \fBspecified\fP \fBoutside\fP \fBof\fP \fBmodule'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_CLOCK_PERIOD_ZERO_\fP"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_CLOCK_HIGH_TIME_ZERO_\fP, 102, 'sc_clock \fBhigh\fP \fBtime\fP \fBis\fP \fBzero'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_CLOCK_LOW_TIME_ZERO_\fP"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_MORE_THAN_ONE_FIFO_READER_\fP, 104, 'sc_fifo<\fBT\fP> \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBreader'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_MORE_THAN_ONE_FIFO_WRITER_\fP"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_INVALID_FIFO_SIZE_\fP, 106, 'sc_fifo<\fBT\fP> \fBmust\fP \fBhave\fP \fBa\fP size \fBof\fP at \fBleast\fP 1') SC_DEFINE_MESSAGE(\fBSC_ID_BIND_IF_TO_PORT_\fP"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_BIND_PORT_TO_PORT_\fP, 108, 'bind parent port \fBto\fP port \fBfailed'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_COMPLETE_BINDING_\fP"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_INSERT_PORT_\fP, 110, 'insert port \fBfailed'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_REMOVE_PORT_\fP"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_GET_IF_\fP, 112, 'get \fBinterface\fP \fBfailed'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_INSERT_PRIM_CHANNEL_\fP"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_REMOVE_PRIM_CHANNEL_\fP, 114, 'remove \fBprimitive\fP \fBchannel\fP \fBfailed'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_MORE_THAN_ONE_SIGNAL_DRIVER_\fP"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP sc_signal< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBdriver\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_NO_DEFAULT_EVENT_\fP, 116, 'channel \fBdoesn\fP't \fBhave\fP \fBa\fP \fBdefault\fP \fBevent'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_RESOLVED_PORT_NOT_BOUND_\fP"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP sc_signal< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBdriver\fP \fBresolved\fP port \fBnot\fP \fBbound\fP \fBto\fP \fBresolved\fP signal \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_FIND_EVENT_\fP, 118, 'find event \fBfailed'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_INVALID_SEMAPHORE_VALUE_\fP"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP sc_signal< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBdriver\fP \fBresolved\fP port \fBnot\fP \fBbound\fP \fBto\fP \fBresolved\fP signal sc_semaphore \fBinitial\fP sc_export \fBnot\fP \fBregistered\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_SC_EXPORT_NOT_BOUND_AFTER_CONSTRUCTION_\fP, 124, 'sc_export instance \fBnot\fP \fBbound\fP \fBto\fP \fBinterface\fP at end \fBof\fP \fBconstruction'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_ATTEMPT_TO_WRITE_TO_CLOCK_\fP"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP sc_signal< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBdriver\fP \fBresolved\fP port \fBnot\fP \fBbound\fP \fBto\fP \fBresolved\fP signal sc_semaphore \fBinitial\fP sc_export \fBnot\fP \fBregistered\fP \fBattempt\fP \fBto\fP write \fBthe\fP \fBvalue\fP \fBof\fP \fBan\fP sc_clock instance \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_SC_EXPORT_ALREADY_BOUND_\fP, 126, 'sc_export instance \fBalready\fP \fBbound'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_OPERATION_ON_NON_SPECIALIZED_SIGNAL_\fP"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP sc_signal< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBdriver\fP \fBresolved\fP port \fBnot\fP \fBbound\fP \fBto\fP \fBresolved\fP signal sc_semaphore \fBinitial\fP sc_export \fBnot\fP \fBregistered\fP \fBattempt\fP \fBto\fP write \fBthe\fP \fBvalue\fP \fBof\fP \fBan\fP sc_clock instance \fBattempted\fP \fBspecalized\fP signal \fBoperation\fP \fBon\fP \fBnon\fP \fBspecialized\fP signal \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_ATTEMPT_TO_BIND_CLOCK_TO_OUTPUT_\fP, 128, 'attempted \fBto\fP bind sc_clock instance \fBto\fP sc_inout \fBor\fP \fBsc_out'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_NO_ASYNC_UPDATE_\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP \fBchar\fP \fBsc_core::SC_ID_REGISTER_ID_FAILED_\fP []"
.br
.ti -1c
.RI "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP sc_signal< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBdriver\fP \fBresolved\fP port \fBnot\fP \fBbound\fP \fBto\fP \fBresolved\fP signal sc_semaphore \fBinitial\fP \fBvalue\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_DEFINE_MESSAGE(id, \fBunused1\fP, \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"

.SH "Function Documentation"
.PP 
.SS "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP sc_signal< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBdriver\fP \fBresolved\fP port \fBnot\fP \fBbound\fP \fBto\fP \fBresolved\fP signal sc_semaphore \fBinitial\fP sc_export \fBnot\fP \fBregistered\fP \fBattempt\fP \fBto\fP write \fBthe\fP \fBvalue\fP \fBof\fP \fBan\fP sc_clock instance \fBattempted\fP \fBspecalized\fP signal \fBoperation\fP \fBon\fP \fBnon\fP \fBspecialized\fP signal SC_DEFINE_MESSAGE (\fBSC_ID_ATTEMPT_TO_BIND_CLOCK_TO_OUTPUT_\fP, 128, 'attempted \fBto\fP bind sc_clock instance \fBto\fP sc_inout \fBor\fP \fBsc_out'\fP)"

.SS "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP SC_DEFINE_MESSAGE (\fBSC_ID_BIND_PORT_TO_PORT_\fP, 108, 'bind parent port \fBto\fP port \fBfailed'\fP)"

.SS "sc_clock period \fBis\fP \fBzero\fP SC_DEFINE_MESSAGE (\fBSC_ID_CLOCK_HIGH_TIME_ZERO_\fP, 102, 'sc_clock \fBhigh\fP \fBtime\fP \fBis\fP \fBzero'\fP)"

.SS "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP sc_signal< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBdriver\fP \fBresolved\fP port \fBnot\fP \fBbound\fP \fBto\fP \fBresolved\fP signal SC_DEFINE_MESSAGE (\fBSC_ID_FIND_EVENT_\fP, 118, 'find event \fBfailed'\fP)"

.SS "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP SC_DEFINE_MESSAGE (\fBSC_ID_GET_IF_\fP, 112, 'get \fBinterface\fP \fBfailed'\fP)"

.SS "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP SC_DEFINE_MESSAGE (\fBSC_ID_INSERT_PORT_\fP, 110, 'insert port \fBfailed'\fP)"

.SS "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP SC_DEFINE_MESSAGE (\fBSC_ID_INVALID_FIFO_SIZE_\fP, 106, 'sc_fifo<\fBT\fP> \fBmust\fP \fBhave\fP \fBa\fP size \fBof\fP at \fBleast\fP 1')"

.SS "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP SC_DEFINE_MESSAGE (\fBSC_ID_MORE_THAN_ONE_FIFO_READER_\fP, 104, 'sc_fifo<\fBT\fP> \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBreader'\fP)"

.SS "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP sc_signal< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBdriver\fP SC_DEFINE_MESSAGE (\fBSC_ID_NO_DEFAULT_EVENT_\fP, 116, 'channel \fBdoesn\fP't \fBhave\fP \fBa\fP \fBdefault\fP \fBevent'\fP)"

.SS "SC_DEFINE_MESSAGE (\fBSC_ID_PORT_OUTSIDE_MODULE_\fP, 100, 'port \fBspecified\fP \fBoutside\fP \fBof\fP \fBmodule'\fP)"

.SS "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP SC_DEFINE_MESSAGE (\fBSC_ID_REMOVE_PRIM_CHANNEL_\fP, 114, 'remove \fBprimitive\fP \fBchannel\fP \fBfailed'\fP)"

.SS "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP sc_signal< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBdriver\fP \fBresolved\fP port \fBnot\fP \fBbound\fP \fBto\fP \fBresolved\fP signal sc_semaphore \fBinitial\fP sc_export \fBnot\fP \fBregistered\fP \fBattempt\fP \fBto\fP write \fBthe\fP \fBvalue\fP \fBof\fP \fBan\fP sc_clock instance SC_DEFINE_MESSAGE (\fBSC_ID_SC_EXPORT_ALREADY_BOUND_\fP, 126, 'sc_export instance \fBalready\fP \fBbound'\fP)"

.SS "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP sc_signal< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBdriver\fP \fBresolved\fP port \fBnot\fP \fBbound\fP \fBto\fP \fBresolved\fP signal sc_semaphore \fBinitial\fP sc_export \fBnot\fP \fBregistered\fP SC_DEFINE_MESSAGE (\fBSC_ID_SC_EXPORT_NOT_BOUND_AFTER_CONSTRUCTION_\fP, 124, 'sc_export instance \fBnot\fP \fBbound\fP \fBto\fP \fBinterface\fP at end \fBof\fP \fBconstruction'\fP)"

.SH "Variable Documentation"
.PP 
.SS "sc_clock period \fBis\fP \fBzero\fP sc_clock \fBlow\fP \fBtime\fP \fBis\fP \fBzero\fP sc_fifo< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBwriter\fP bind \fBinterface\fP \fBto\fP port \fBfailed\fP \fBcomplete\fP \fBbinding\fP \fBfailed\fP remove port \fBfailed\fP insert \fBprimitive\fP \fBchannel\fP \fBfailed\fP sc_signal< \fBT\fP > \fBcannot\fP \fBhave\fP \fBmore\fP \fBthan\fP \fBone\fP \fBdriver\fP \fBresolved\fP port \fBnot\fP \fBbound\fP \fBto\fP \fBresolved\fP signal sc_semaphore \fBinitial\fP value"
\fBInitial value:\fP.PP
.nf
= 0" )
SC_DEFINE_MESSAGE( SC_ID_SC_EXPORT_HAS_NO_INTERFACE_,  120,
            "sc_export instance has no interface" )
SC_DEFINE_MESSAGE( SC_ID_INSERT_EXPORT_,  121,
    "insert sc_export failed" )
SC_DEFINE_MESSAGE( SC_ID_EXPORT_OUTSIDE_MODULE_, 122,
    "sc_export specified outside of module" )
SC_DEFINE_MESSAGE( SC_ID_SC_EXPORT_NOT_REGISTERED_,  123,
    "remove sc_export failed
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
