.TH "sc_core::sc_halt" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_halt
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_except\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_halt\fP ()"
.br
.ti -1c
.RI "\fBsc_halt\fP (\fBconst\fP \fBsc_halt\fP &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_halt::sc_halt ()\fR [inline]\fP"

.SS "sc_core::sc_halt::sc_halt (\fBconst\fP \fBsc_halt\fP &)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
