.TH "sc_core::sc_ppq< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_ppq< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_pq\&.h>\fP
.PP
Inherits \fBsc_core::sc_ppq_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_ppq\fP (int \fBsz\fP, \fBcompare_fn_t\fP cmp)"
.br
.ti -1c
.RI "\fB~sc_ppq\fP ()"
.br
.ti -1c
.RI "\fBT\fP \fBtop\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBT\fP \fBextract_top\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBinsert\fP (\fBT\fP elem)"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_ppq_base\fP
.in +1c
.ti -1c
.RI "\fBsc_ppq_base\fP (int \fBsz\fP, \fBcompare_fn_t\fP cmp)"
.br
.ti -1c
.RI "\fB~sc_ppq_base\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP * \fBtop\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBextract_top\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBinsert\fP (\fBvoid\fP *elem)"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBempty\fP () \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBsc_core::sc_ppq_base\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP int(* \fBcompare_fn_t\fP) (\fBconst\fP \fBvoid\fP *, \fBconst\fP \fBvoid\fP *)"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_ppq_base\fP
.in +1c
.ti -1c
.RI "int \fBparent\fP (int \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "int \fBleft\fP (int \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "int \fBright\fP (int \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBheapify\fP (int \fBi\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_ppq\fP< \fBT\fP >::sc_ppq (int sz, \fBcompare_fn_t\fP cmp)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_ppq\fP< \fBT\fP >::~\fBsc_ppq\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBsc_core::sc_ppq\fP< \fBT\fP >::extract_top ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_ppq\fP< \fBT\fP >::insert (\fBT\fP elem)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBsc_core::sc_ppq\fP< \fBT\fP >::top () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
