.TH "sc_core::sc_attr_base" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_attr_base
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_attribute\&.h>\fP
.PP
Inherited by \fBsc_core::sc_attribute< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_attr_base\fP (\fBconst\fP std::string &\fBname_\fP)"
.br
.ti -1c
.RI "\fBsc_attr_base\fP (\fBconst\fP \fBsc_attr_base\fP &)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_attr_base\fP ()"
.br
.ti -1c
.RI "\fBconst\fP std::string & \fBname\fP () \fBconst\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_attr_base\fP ()"
.br
.ti -1c
.RI "\fBsc_attr_base\fP & \fBoperator=\fP (\fBconst\fP \fBsc_attr_base\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::string \fBm_name\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_attr_base::sc_attr_base (\fBconst\fP std::string & name_)"

.SS "sc_core::sc_attr_base::sc_attr_base (\fBconst\fP \fBsc_attr_base\fP &)"

.SS "\fBvirtual\fP sc_core::sc_attr_base::~sc_attr_base ()\fR [virtual]\fP"

.SS "sc_core::sc_attr_base::sc_attr_base ()\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBconst\fP std::string & sc_core::sc_attr_base::name () const"

.SS "\fBsc_attr_base\fP & sc_core::sc_attr_base::operator= (\fBconst\fP \fBsc_attr_base\fP &)\fR [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::string sc_core::sc_attr_base::m_name\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
