.TH "sc_core::sc_event_finder_t< IF >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_event_finder_t< IF >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_event_finder\&.h>\fP
.PP
Inherits \fBsc_core::sc_event_finder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_event_finder_t\fP (\fBconst\fP \fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBsc_event\fP &(IF::*\fBevent_method_\fP)() \fBconst\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_event_finder_t\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBfind_event\fP (\fBsc_interface\fP *\fBif_p\fP=0) \fBconst\fP"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_event_finder\fP
.in +1c
.ti -1c
.RI "\fBconst\fP \fBsc_port_base\fP & \fBport\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_event_finder\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_event_finder_t\fP ()"
.br
.ti -1c
.RI "\fBsc_event_finder_t\fP (\fBconst\fP \fBsc_event_finder_t\fP< \fBIF\fP > &)"
.br
.ti -1c
.RI "\fBsc_event_finder_t\fP< \fBIF\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_event_finder_t\fP< \fBIF\fP > &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBsc_event\fP &(IF::* \fBm_event_method\fP )() \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBsc_core::sc_event_finder\fP
.in +1c
.ti -1c
.RI "template<\fBtypename\fP \fBIF\fP > \fBstatic\fP \fBsc_event_finder\fP & \fBcached_create\fP (\fBsc_event_finder\fP *&\fBcache_p\fP, \fBconst\fP \fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBsc_event\fP &(IF::*\fBef_p\fP)() \fBconst\fP)"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_event_finder\fP
.in +1c
.ti -1c
.RI "\fBsc_event_finder\fP (\fBconst\fP \fBsc_port_base\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBreport_error\fP (\fBconst\fP \fBchar\fP *id, \fBconst\fP \fBchar\fP *\fBadd_msg\fP=0) \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBIF\fP > \fBsc_core::sc_event_finder_t\fP< \fBIF\fP >::sc_event_finder_t (\fBconst\fP \fBsc_port_base\fP & port_, \fBconst\fP \fBsc_event\fP &(IF::*)() \fBconst\fP event_method_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBIF\fP > \fBvirtual\fP \fBsc_core::sc_event_finder_t\fP< \fBIF\fP >::~\fBsc_event_finder_t\fP ()\fR [inline]\fP, \fR [virtual]\fP"

.SS "template<\fBclass\fP \fBIF\fP > \fBsc_core::sc_event_finder_t\fP< \fBIF\fP >::sc_event_finder_t ()\fR [private]\fP"

.SS "template<\fBclass\fP \fBIF\fP > \fBsc_core::sc_event_finder_t\fP< \fBIF\fP >::sc_event_finder_t (\fBconst\fP \fBsc_event_finder_t\fP< \fBIF\fP > &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBIF\fP > \fBconst\fP \fBsc_event\fP & \fBsc_core::sc_event_finder_t\fP< \fBIF\fP >::find_event (\fBsc_interface\fP * if_p = \fR0\fP) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_event_finder\fP\&.
.SS "template<\fBclass\fP \fBIF\fP > \fBsc_event_finder_t\fP< \fBIF\fP > & \fBsc_core::sc_event_finder_t\fP< \fBIF\fP >\fB::operator\fP= (\fBconst\fP \fBsc_event_finder_t\fP< \fBIF\fP > &)\fR [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBIF\fP > \fBconst\fP \fBsc_event\fP &(IF::* \fBsc_core::sc_event_finder_t\fP< \fBIF\fP >::m_event_method) () \fBconst\fP\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
