.TH "sc_core::sc_cor" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_cor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_cor\&.h>\fP
.PP
Inherited by \fBsc_core::sc_cor_qt\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~sc_cor\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBstack_protect\fP (\fBbool\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_cor\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_cor\fP (\fBconst\fP \fBsc_cor\fP &)"
.br
.ti -1c
.RI "\fBsc_cor\fP & \fBoperator=\fP (\fBconst\fP \fBsc_cor\fP &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_cor::sc_cor ()\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvirtual\fP sc_core::sc_cor::~sc_cor ()\fR [inline]\fP, \fR [virtual]\fP"

.SS "sc_core::sc_cor::sc_cor (\fBconst\fP \fBsc_cor\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBsc_cor\fP & sc_core::sc_cor::operator= (\fBconst\fP \fBsc_cor\fP &)\fR [private]\fP"

.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_cor::stack_protect (\fBbool\fP)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBsc_core::sc_cor_qt\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
