.TH "sc_core::sc_process_monitor" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_process_monitor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_process\&.h>\fP
.PP
Inherited by \fBsc_core::sc_join\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBspm_exit\fP = 0 }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~sc_process_monitor\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBsignal\fP (\fBsc_thread_handle\fP \fBthread_p\fP, int type)"
.br
.in -1c
.SH "Member Enumeration Documentation"
.PP 
.SS "\fBanonymous\fP \fBenum\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIspm_exit \fP\fP
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBvirtual\fP sc_core::sc_process_monitor::~sc_process_monitor ()\fR [inline]\fP, \fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP sc_core::sc_process_monitor::signal (\fBsc_thread_handle\fP thread_p, int type)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBsc_core::sc_join\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
