.TH "sc_core::sc_signal_in_if< bool >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_signal_in_if< bool >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_signal_ifs\&.h>\fP
.PP
Inherits \fBsc_core::sc_interface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBvalue_changed_event\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBposedge_event\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBnegedge_event\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBbool\fP & \fBread\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBbool\fP & \fBget_data_ref\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBevent\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBposedge\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnegedge\fP () \fBconst\fP =0"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBregister_port\fP (\fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBchar\fP *\fBif_typename_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_interface\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_signal_in_if\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBsc_interface\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_signal_in_if\fP (\fBconst\fP \fBsc_signal_in_if\fP< \fBbool\fP > &)"
.br
.ti -1c
.RI "\fBsc_signal_in_if\fP< \fBbool\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_signal_in_if\fP< \fBbool\fP > &)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBsc_reset\fP * \fBis_reset\fP () \fBconst\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_reset\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBsc_core::sc_signal_in_if\fP< \fBbool\fP >::sc_signal_in_if ()\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBsc_core::sc_signal_in_if\fP< \fBbool\fP >::sc_signal_in_if (\fBconst\fP \fBsc_signal_in_if\fP< \fBbool\fP > &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBbool\fP \fBsc_core::sc_signal_in_if\fP< \fBbool\fP >::event () const\fR [pure virtual]\fP"

.SS "\fBvirtual\fP \fBconst\fP \fBbool\fP & \fBsc_core::sc_signal_in_if\fP< \fBbool\fP >::get_data_ref () const\fR [pure virtual]\fP"

.SS "\fBvirtual\fP \fBsc_reset\fP * \fBsc_core::sc_signal_in_if\fP< \fBbool\fP >::is_reset () const\fR [inline]\fP, \fR [private]\fP, \fR [virtual]\fP"

.SS "\fBvirtual\fP \fBbool\fP \fBsc_core::sc_signal_in_if\fP< \fBbool\fP >::negedge () const\fR [pure virtual]\fP"

.SS "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBsc_core::sc_signal_in_if\fP< \fBbool\fP >::negedge_event () const\fR [pure virtual]\fP"

.SS "\fBsc_signal_in_if\fP< \fBbool\fP > & \fBsc_core::sc_signal_in_if\fP< \fBbool\fP >\fB::operator\fP= (\fBconst\fP \fBsc_signal_in_if\fP< \fBbool\fP > &)\fR [private]\fP"

.SS "\fBvirtual\fP \fBbool\fP \fBsc_core::sc_signal_in_if\fP< \fBbool\fP >::posedge () const\fR [pure virtual]\fP"

.SS "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBsc_core::sc_signal_in_if\fP< \fBbool\fP >::posedge_event () const\fR [pure virtual]\fP"

.SS "\fBvirtual\fP \fBconst\fP \fBbool\fP & \fBsc_core::sc_signal_in_if\fP< \fBbool\fP >::read () const\fR [pure virtual]\fP"

.SS "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBsc_core::sc_signal_in_if\fP< \fBbool\fP >::value_changed_event () const\fR [pure virtual]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_reset\fP\fR [friend]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
