.TH "sc_core::sc_report_handler::msg_def_items" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_report_handler::msg_def_items
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_report_handler\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsc_msg_def\fP * \fBmd\fP"
.br
.ti -1c
.RI "int \fBcount\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBallocated\fP"
.br
.ti -1c
.RI "\fBmsg_def_items\fP * \fBnext\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP sc_core::sc_report_handler::msg_def_items::allocated"

.SS "int sc_core::sc_report_handler::msg_def_items::count"

.SS "\fBsc_msg_def\fP* sc_core::sc_report_handler::msg_def_items::md"

.SS "\fBmsg_def_items\fP* sc_core::sc_report_handler::msg_def_items::next"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
