.TH "sc_core::sc_scoped_lock" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_scoped_lock
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_mutex_if\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_mutex_if\fP \fBlockable_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_scoped_lock\fP (\fBlockable_type\fP &\fBmtx\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBrelease\fP ()"
.br
.ti -1c
.RI "\fB~sc_scoped_lock\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_scoped_lock\fP (\fBconst\fP \fBsc_scoped_lock\fP &)"
.br
.ti -1c
.RI "\fBsc_scoped_lock\fP & \fBoperator=\fP (\fBconst\fP \fBsc_scoped_lock\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBlockable_type\fP & \fBm_ref\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_active\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBsc_mutex_if\fP \fBsc_core::sc_scoped_lock::lockable_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_scoped_lock::sc_scoped_lock (\fBlockable_type\fP & mtx)\fR [inline]\fP, \fR [explicit]\fP"

.SS "sc_core::sc_scoped_lock::~sc_scoped_lock ()\fR [inline]\fP"

.SS "sc_core::sc_scoped_lock::sc_scoped_lock (\fBconst\fP \fBsc_scoped_lock\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBsc_scoped_lock\fP & sc_core::sc_scoped_lock::operator= (\fBconst\fP \fBsc_scoped_lock\fP &)\fR [private]\fP"

.SS "\fBbool\fP sc_core::sc_scoped_lock::release ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP sc_core::sc_scoped_lock::m_active\fR [private]\fP"

.SS "\fBlockable_type\fP& sc_core::sc_scoped_lock::m_ref\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
