.TH "sc_core::sc_attribute< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_attribute< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_attribute\&.h>\fP
.PP
Inherits \fBsc_core::sc_attr_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_attribute\fP (\fBconst\fP std::string &\fBname_\fP)"
.br
.ti -1c
.RI "\fBsc_attribute\fP (\fBconst\fP std::string &\fBname_\fP, \fBconst\fP \fBT\fP &\fBvalue_\fP)"
.br
.ti -1c
.RI "\fBsc_attribute\fP (\fBconst\fP \fBsc_attribute\fP< \fBT\fP > &\fBa\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_attribute\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_attr_base\fP
.in +1c
.ti -1c
.RI "\fBsc_attr_base\fP (\fBconst\fP std::string &\fBname_\fP)"
.br
.ti -1c
.RI "\fBsc_attr_base\fP (\fBconst\fP \fBsc_attr_base\fP &)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_attr_base\fP ()"
.br
.ti -1c
.RI "\fBconst\fP std::string & \fBname\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP \fBvalue\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_attribute\fP ()"
.br
.ti -1c
.RI "\fBsc_attribute\fP< \fBT\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_attribute\fP< \fBT\fP > &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_attribute\fP< \fBT\fP >::sc_attribute (\fBconst\fP std::string & name_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_attribute\fP< \fBT\fP >::sc_attribute (\fBconst\fP std::string & name_, \fBconst\fP \fBT\fP & value_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_attribute\fP< \fBT\fP >::sc_attribute (\fBconst\fP \fBsc_attribute\fP< \fBT\fP > & a)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvirtual\fP \fBsc_core::sc_attribute\fP< \fBT\fP >::~\fBsc_attribute\fP ()\fR [inline]\fP, \fR [virtual]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_attribute\fP< \fBT\fP >::sc_attribute ()\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_attribute\fP< \fBT\fP > & \fBsc_core::sc_attribute\fP< \fBT\fP >\fB::operator\fP= (\fBconst\fP \fBsc_attribute\fP< \fBT\fP > &)\fR [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBT\fP \fBsc_core::sc_attribute\fP< \fBT\fP >::value"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
