.TH "sc_core::sc_msg_def" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_msg_def
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_report_handler\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBmsg_type\fP"
.br
.ti -1c
.RI "\fBsc_actions\fP \fBactions\fP"
.br
.ti -1c
.RI "\fBsc_actions\fP \fBsev_actions\fP [\fBSC_MAX_SEVERITY\fP]"
.br
.ti -1c
.RI "\fBunsigned\fP \fBlimit\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBsev_limit\fP [\fBSC_MAX_SEVERITY\fP]"
.br
.ti -1c
.RI "\fBunsigned\fP \fBlimit_mask\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBcall_count\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBsev_call_count\fP [\fBSC_MAX_SEVERITY\fP]"
.br
.ti -1c
.RI "\fBchar\fP * \fBmsg_type_data\fP"
.br
.ti -1c
.RI "int \fBid\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBsc_actions\fP sc_core::sc_msg_def::actions"

.SS "\fBunsigned\fP sc_core::sc_msg_def::call_count"

.SS "int sc_core::sc_msg_def::id"

.SS "\fBunsigned\fP sc_core::sc_msg_def::limit"

.SS "\fBunsigned\fP sc_core::sc_msg_def::limit_mask"

.SS "\fBconst\fP \fBchar\fP* sc_core::sc_msg_def::msg_type"

.SS "\fBchar\fP* sc_core::sc_msg_def::msg_type_data"

.SS "\fBsc_actions\fP sc_core::sc_msg_def::sev_actions[\fBSC_MAX_SEVERITY\fP]"

.SS "\fBunsigned\fP sc_core::sc_msg_def::sev_call_count[\fBSC_MAX_SEVERITY\fP]"

.SS "\fBunsigned\fP sc_core::sc_msg_def::sev_limit[\fBSC_MAX_SEVERITY\fP]"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
