.TH "sc_core::sc_member_access< ElementType, AccessType >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_member_access< ElementType, AccessType >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_vector\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBElementType\fP \fBelement_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBAccessType\fP \fBaccess_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP access_typeElementType::* \fBmember_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBaccess_type\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_meta::remove_const\fP< \fBtype\fP >\fB::type\fP \fBplain_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_meta::remove_const\fP< \fBElementType\fP >\fB::type\fP \fBplain_elem_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_member_access\fP< \fBelement_type\fP, \fBaccess_type\fP > \fBpolicy\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_member_access\fP< \fBplain_elem_type\fP, \fBplain_type\fP > \fBnon_const_policy\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_member_access\fP< \fBconst\fP \fBplain_elem_type\fP, \fBconst\fP \fBplain_type\fP > \fBconst_policy\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_member_access\fP (\fBmember_type\fP ptr)"
.br
.ti -1c
.RI "\fBsc_member_access\fP (\fBconst\fP \fBnon_const_policy\fP &\fBother\fP)"
.br
.ti -1c
.RI "\fBaccess_type\fP * \fBget\fP (\fBelement_type\fP *\fBthis_\fP) \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBmember_type\fP \fBptr_\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<\fBtypename\fP , \fBtypename\fP > \fBclass\fP \fBsc_member_access\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBtypedef\fP \fBAccessType\fP \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::access_type"

.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBtypedef\fP \fBsc_member_access\fP< \fBconst\fP \fBplain_elem_type\fP, \fBconst\fP \fBplain_type\fP > \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::const_policy"

.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBtypedef\fP \fBElementType\fP \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::element_type"

.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBtypedef\fP access_typeElementType::* \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::member_type"

.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBtypedef\fP \fBsc_member_access\fP< \fBplain_elem_type\fP, \fBplain_type\fP > \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::non_const_policy"

.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBtypedef\fP \fBsc_meta::remove_const\fP<\fBElementType\fP>\fB::type\fP \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::plain_elem_type"

.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBtypedef\fP \fBsc_meta::remove_const\fP<\fBtype\fP>\fB::type\fP \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::plain_type"

.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBtypedef\fP \fBsc_member_access\fP< \fBelement_type\fP, \fBaccess_type\fP > \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::policy"

.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBtypedef\fP \fBaccess_type\fP \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::type"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::sc_member_access (\fBmember_type\fP ptr)\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::sc_member_access (\fBconst\fP \fBnon_const_policy\fP & other)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBaccess_type\fP * \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::get (\fBelement_type\fP * this_) const\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > template<\fBtypename\fP , \fBtypename\fP > \fBfriend\fP \fBclass\fP \fBsc_member_access\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBElementType\fP , \fBtypename\fP \fBAccessType\fP > \fBmember_type\fP \fBsc_core::sc_member_access\fP< \fBElementType\fP, \fBAccessType\fP >::ptr_\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
