.TH "sc_core::sc_time_params" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_time_params
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_time\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_time_params\fP ()"
.br
.ti -1c
.RI "\fB~sc_time_params\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBdouble\fP \fBtime_resolution\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBtime_resolution_specified\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBtime_resolution_fixed\fP"
.br
.ti -1c
.RI "\fBsc_time::value_type\fP \fBdefault_time_unit\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBdefault_time_unit_specified\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_time_params::sc_time_params ()"

.SS "sc_core::sc_time_params::~sc_time_params ()"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_time::value_type\fP sc_core::sc_time_params::default_time_unit"

.SS "\fBbool\fP sc_core::sc_time_params::default_time_unit_specified"

.SS "\fBdouble\fP sc_core::sc_time_params::time_resolution"

.SS "\fBbool\fP sc_core::sc_time_params::time_resolution_fixed"

.SS "\fBbool\fP sc_core::sc_time_params::time_resolution_specified"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
