.TH "sc_core::sc_event_list" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_event_list
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_event\&.h>\fP
.PP
Inherited by \fBsc_core::sc_event_and_list\fP, and \fBsc_core::sc_event_or_list\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_event_list\fP (\fBconst\fP \fBsc_event_list\fP &)"
.br
.ti -1c
.RI "\fBsc_event_list\fP & \fBoperator=\fP (\fBconst\fP \fBsc_event_list\fP &)"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBempty\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBpush_back\fP (\fBconst\fP \fBsc_event\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBpush_back\fP (\fBconst\fP \fBsc_event_list\fP &)"
.br
.ti -1c
.RI "\fBsc_event_list\fP (\fBbool\fP \fBand_list_\fP, \fBbool\fP \fBauto_delete_\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBsc_event_list\fP (\fBconst\fP \fBsc_event\fP &, \fBbool\fP \fBand_list_\fP, \fBbool\fP \fBauto_delete_\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fB~sc_event_list\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBswap\fP (\fBsc_event_list\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBmove_from\fP (\fBconst\fP \fBsc_event_list\fP &)"
.br
.ti -1c
.RI "\fBbool\fP \fBand_list\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd_dynamic\fP (\fBsc_method_handle\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd_dynamic\fP (\fBsc_thread_handle\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove_dynamic\fP (\fBsc_method_handle\fP, \fBconst\fP \fBsc_event\fP *) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove_dynamic\fP (\fBsc_thread_handle\fP, \fBconst\fP \fBsc_event\fP *) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBbusy\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBtemporary\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBauto_delete\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBreport_premature_destruction\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBreport_invalid_modification\fP () \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBconst\fP \fBsc_event\fP * > \fBm_events\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_and_list\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_auto_delete\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBm_busy\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_process_b\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_method_process\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_thread_process\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_thread_cor_fn\fP (\fBvoid\fP *arg)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_event_list::sc_event_list (\fBconst\fP \fBsc_event_list\fP & that)\fR [inline]\fP"

.SS "sc_core::sc_event_list::sc_event_list (\fBbool\fP and_list_, \fBbool\fP auto_delete_ = \fR\fBfalse\fP\fP)\fR [inline]\fP, \fR [explicit]\fP, \fR [protected]\fP"

.SS "sc_core::sc_event_list::sc_event_list (\fBconst\fP \fBsc_event\fP & e, \fBbool\fP and_list_, \fBbool\fP auto_delete_ = \fR\fBfalse\fP\fP)\fR [inline]\fP, \fR [protected]\fP"

.SS "sc_core::sc_event_list::~sc_event_list ()\fR [inline]\fP, \fR [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP sc_core::sc_event_list::add_dynamic (\fBsc_method_handle\fP) const\fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_event_list::add_dynamic (\fBsc_thread_handle\fP) const\fR [protected]\fP"

.SS "\fBbool\fP sc_core::sc_event_list::and_list () const\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_event_list::auto_delete () const\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBbool\fP sc_core::sc_event_list::busy () const\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBbool\fP sc_core::sc_event_list::empty () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_core::sc_event_list::move_from (\fBconst\fP \fBsc_event_list\fP & that)\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBsc_event_list\fP & sc_core::sc_event_list::operator= (\fBconst\fP \fBsc_event_list\fP & that)\fR [inline]\fP"

.SS "\fBvoid\fP sc_core::sc_event_list::push_back (\fBconst\fP \fBsc_event\fP &)\fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_event_list::push_back (\fBconst\fP \fBsc_event_list\fP &)\fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_event_list::remove_dynamic (\fBsc_method_handle\fP, \fBconst\fP \fBsc_event\fP *) const\fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_event_list::remove_dynamic (\fBsc_thread_handle\fP, \fBconst\fP \fBsc_event\fP *) const\fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_event_list::report_invalid_modification () const\fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_event_list::report_premature_destruction () const\fR [protected]\fP"

.SS "int sc_core::sc_event_list::size () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_core::sc_event_list::swap (\fBsc_event_list\fP & that)\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBbool\fP sc_core::sc_event_list::temporary () const\fR [inline]\fP, \fR [protected]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_method_process\fP\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_process_b\fP\fR [friend]\fP"

.SS "\fBvoid\fP sc_thread_cor_fn (\fBvoid\fP * arg)\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_thread_process\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP sc_core::sc_event_list::m_and_list\fR [private]\fP"

.SS "\fBbool\fP sc_core::sc_event_list::m_auto_delete\fR [private]\fP"

.SS "\fBunsigned\fP sc_core::sc_event_list::m_busy\fR [mutable]\fP, \fR [private]\fP"

.SS "std::vector<\fBconst\fP \fBsc_event\fP*> sc_core::sc_event_list::m_events\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
