.TH "sc_core::sc_vpool< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_vpool< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_temporary\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_vpool\fP (int \fBlog2\fP, \fBT\fP *\fBpool_p\fP=0)"
.br
.ti -1c
.RI "\fB~sc_vpool\fP ()"
.br
.ti -1c
.RI "\fBT\fP * \fBallocate\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP ()"
.br
.ti -1c
.RI "std::size_t \fBsize\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::size_t \fBm_pool_i\fP"
.br
.ti -1c
.RI "\fBT\fP * \fBm_pool_p\fP"
.br
.ti -1c
.RI "std::size_t \fBm_wrap\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_vpool\fP< \fBT\fP >::sc_vpool (int log2, \fBT\fP * pool_p = \fR0\fP)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_vpool\fP< \fBT\fP >::~\fBsc_vpool\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBT\fP * \fBsc_core::sc_vpool\fP< \fBT\fP >::allocate ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_vpool\fP< \fBT\fP >::reset ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > std::size_t \fBsc_core::sc_vpool\fP< \fBT\fP >::size ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > std::size_t \fBsc_core::sc_vpool\fP< \fBT\fP >::m_pool_i\fR [protected]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP* \fBsc_core::sc_vpool\fP< \fBT\fP >::m_pool_p\fR [protected]\fP"

.SS "template<\fBclass\fP \fBT\fP > std::size_t \fBsc_core::sc_vpool\fP< \fBT\fP >::m_wrap\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
