.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_clock_ports.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_clock_ports.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/communication/sc_signal_ports\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_in\fP< \fBbool\fP > \fBsc_core::sc_in_clk\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_inout\fP< \fBbool\fP > \fBsc_core::sc_inout_clk\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_out\fP< \fBbool\fP > \fBsc_core::sc_out_clk\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
