.TH "sc_core::sc_method_process" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_method_process
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_method_process\&.h>\fP
.PP
Inherits \fBsc_core::sc_process_b\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_method_process\fP (\fBconst\fP \fBchar\fP *\fBname_p\fP, \fBbool\fP \fBfree_host\fP, \fBSC_ENTRY_FUNC\fP \fBmethod_p\fP, \fBsc_process_host\fP *\fBhost_p\fP, \fBconst\fP \fBsc_spawn_options\fP *\fBopt_p\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBchar\fP * \fBkind\fP () \fBconst\fP"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_process_b\fP
.in +1c
.ti -1c
.RI "\fBsc_process_b\fP (\fBconst\fP \fBchar\fP *\fBname_p\fP, \fBbool\fP \fBis_thread\fP, \fBbool\fP \fBfree_host\fP, \fBSC_ENTRY_FUNC\fP \fBmethod_p\fP, \fBsc_process_host\fP *\fBhost_p\fP, \fBconst\fP \fBsc_spawn_options\fP *\fBopt_p\fP)"
.br
.ti -1c
.RI "int \fBcurrent_state\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBdont_initialize\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBdont_initialize\fP (\fBbool\fP \fBdont\fP)"
.br
.ti -1c
.RI "std::string \fBdump_state\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP ::std::vector< \fBsc_object\fP * > & \fBget_child_objects\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_curr_proc_kind\fP \fBproc_kind\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_event\fP & \fBreset_event\fP ()"
.br
.ti -1c
.RI "\fBsc_event\fP & \fBterminated_event\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_object\fP
.in +1c
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBname\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBbasename\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBprint\fP (::std::ostream &\fBos\fP=::std::cout) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBdump\fP (::std::ostream &\fBos\fP=::std::cout) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBtrace\fP (\fBsc_trace_file\fP *tf) \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_simcontext\fP * \fBsimcontext\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBadd_attribute\fP (\fBsc_attr_base\fP &)"
.br
.ti -1c
.RI "\fBsc_attr_base\fP * \fBget_attribute\fP (\fBconst\fP std::string &\fBname_\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_attr_base\fP * \fBget_attribute\fP (\fBconst\fP std::string &\fBname_\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_attr_base\fP * \fBremove_attribute\fP (\fBconst\fP std::string &\fBname_\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove_all_attributes\fP ()"
.br
.ti -1c
.RI "int \fBnum_attributes\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_attr_cltn\fP & \fBattr_cltn\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_attr_cltn\fP & \fBattr_cltn\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP std::vector< \fBsc_event\fP * > & \fBget_child_events\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_object\fP * \fBget_parent\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_object\fP * \fBget_parent_object\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBcheck_for_throws\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBdisable_process\fP (\fBsc_descendant_inclusion_info\fP \fBdescendants\fP=\fBSC_NO_DESCENDANTS\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBenable_process\fP (\fBsc_descendant_inclusion_info\fP \fBdescendants\fP=\fBSC_NO_DESCENDANTS\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBrun_process\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBkill_process\fP (\fBsc_descendant_inclusion_info\fP \fBdescendants\fP=\fBSC_NO_DESCENDANTS\fP)"
.br
.ti -1c
.RI "\fBsc_method_handle\fP \fBnext_exist\fP ()"
.br
.ti -1c
.RI "\fBsc_method_handle\fP \fBnext_runnable\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBclear_trigger\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_event\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_event_or_list\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_event_and_list\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_time\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event_or_list\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event_and_list\fP &)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBresume_process\fP (\fBsc_descendant_inclusion_info\fP \fBdescendants\fP=\fBSC_NO_DESCENDANTS\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_next_exist\fP (\fBsc_method_handle\fP \fBnext_p\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_next_runnable\fP (\fBsc_method_handle\fP \fBnext_p\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_stack_size\fP (std::size_t size)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBsuspend_process\fP (\fBsc_descendant_inclusion_info\fP \fBdescendants\fP=\fBSC_NO_DESCENDANTS\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBthrow_reset\fP (\fBbool\fP \fBasync\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBthrow_user\fP (\fBconst\fP \fBsc_throw_it_helper\fP &\fBhelper\fP, \fBsc_descendant_inclusion_info\fP \fBdescendants\fP=\fBSC_NO_DESCENDANTS\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBtrigger_dynamic\fP (\fBsc_event\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBtrigger_static\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_process_b\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~sc_process_b\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBadd_child_object\fP (\fBsc_object\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd_static_event\fP (\fBconst\fP \fBsc_event\fP &)"
.br
.ti -1c
.RI "\fBbool\fP \fBdynamic\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBgen_unique_name\fP (\fBconst\fP \fBchar\fP *\fBbasename_\fP, \fBbool\fP \fBpreserve_first\fP)"
.br
.ti -1c
.RI "\fBsc_report\fP * \fBget_last_report\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBis_disabled\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_runnable\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBremove_child_object\fP (\fBsc_object\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove_dynamic_events\fP (\fBbool\fP \fBskip_timeout\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove_static_events\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_last_report\fP (\fBsc_report\fP *\fBlast_p\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBtimed_out\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBreport_error\fP (\fBconst\fP \fBchar\fP *\fBmsgid\fP, \fBconst\fP \fBchar\fP *msg='') \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBreport_immediate_self_notification\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBdisconnect_process\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBinitially_in_reset\fP (\fBbool\fP \fBasync\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBis_unwinding\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBstart_unwinding\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBclear_unwinding\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset_changed\fP (\fBbool\fP \fBasync\fP, \fBbool\fP \fBasserted\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset_process\fP (\fBreset_type\fP \fBrt\fP, \fBsc_descendant_inclusion_info\fP \fBdescendants\fP=\fBSC_NO_DESCENDANTS\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBterminated\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBtrigger_reset_event\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsemantics\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_object\fP
.in +1c
.ti -1c
.RI "\fBsc_object\fP ()"
.br
.ti -1c
.RI "\fBsc_object\fP (\fBconst\fP \fBchar\fP *\fBnm\fP)"
.br
.ti -1c
.RI "\fBsc_object\fP (\fBconst\fP \fBsc_object\fP &)"
.br
.ti -1c
.RI "\fBsc_object\fP & \fBoperator=\fP (\fBconst\fP \fBsc_object\fP &)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_object\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBadd_child_event\fP (\fBsc_event\fP *\fBevent_p\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBremove_child_event\fP (\fBsc_event\fP *\fBevent_p\fP)"
.br
.ti -1c
.RI "\fBphase_cb_mask\fP \fBregister_simulation_phase_callback\fP (\fBphase_cb_mask\fP)"
.br
.ti -1c
.RI "\fBphase_cb_mask\fP \fBunregister_simulation_phase_callback\fP (\fBphase_cb_mask\fP)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBsc_cor\fP * \fBm_cor\fP"
.br
.ti -1c
.RI "std::size_t \fBm_stack_size\fP"
.br
.ti -1c
.RI "std::vector< \fBsc_process_monitor\fP * > \fBm_monitor_q\fP"
.br
.in -1c

Protected Attributes inherited from \fBsc_core::sc_process_b\fP
.in +1c
.ti -1c
.RI "int \fBm_active_areset_n\fP"
.br
.ti -1c
.RI "int \fBm_active_reset_n\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_dont_init\fP"
.br
.ti -1c
.RI "\fBspawn_t\fP \fBm_dynamic_proc\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_event\fP * \fBm_event_p\fP"
.br
.ti -1c
.RI "int \fBm_event_count\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_event_list\fP * \fBm_event_list_p\fP"
.br
.ti -1c
.RI "\fBsc_process_b\fP * \fBm_exist_p\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_free_host\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_has_reset_signal\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_has_stack\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_is_thread\fP"
.br
.ti -1c
.RI "\fBsc_report\fP * \fBm_last_report_p\fP"
.br
.ti -1c
.RI "\fBsc_name_gen\fP * \fBm_name_gen_p\fP"
.br
.ti -1c
.RI "\fBsc_curr_proc_kind\fP \fBm_process_kind\fP"
.br
.ti -1c
.RI "int \fBm_references_n\fP"
.br
.ti -1c
.RI "std::vector< \fBsc_reset\fP * > \fBm_resets\fP"
.br
.ti -1c
.RI "\fBsc_event\fP * \fBm_reset_event_p\fP"
.br
.ti -1c
.RI "\fBsc_event\fP * \fBm_resume_event_p\fP"
.br
.ti -1c
.RI "\fBsc_process_b\fP * \fBm_runnable_p\fP"
.br
.ti -1c
.RI "\fBsc_process_host\fP * \fBm_semantics_host_p\fP"
.br
.ti -1c
.RI "\fBSC_ENTRY_FUNC\fP \fBm_semantics_method_p\fP"
.br
.ti -1c
.RI "int \fBm_state\fP"
.br
.ti -1c
.RI "std::vector< \fBconst\fP \fBsc_event\fP * > \fBm_static_events\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_sticky_reset\fP"
.br
.ti -1c
.RI "\fBsc_event\fP * \fBm_term_event_p\fP"
.br
.ti -1c
.RI "\fBsc_throw_it_helper\fP * \fBm_throw_helper_p\fP"
.br
.ti -1c
.RI "\fBprocess_throw_type\fP \fBm_throw_status\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_timed_out\fP"
.br
.ti -1c
.RI "\fBsc_event\fP * \fBm_timeout_event_p\fP"
.br
.ti -1c
.RI "\fBtrigger_t\fP \fBm_trigger_type\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_unwinding\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~sc_method_process\fP ()"
.br
.ti -1c
.RI "\fBsc_method_process\fP (\fBconst\fP \fBsc_method_process\fP &)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_method_process\fP & \fBoperator=\fP (\fBconst\fP \fBsc_method_process\fP &)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBstruct\fP \fBsc_invoke_method\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_event\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_module\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_process_table\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_process_handle\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_simcontext\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_runnable\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_method_cor_fn\fP (\fBvoid\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_cmethod_cor_fn\fP (\fBvoid\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_set_stack_size\fP (\fBsc_method_handle\fP, std::size_t)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_event\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_event_or_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_event_and_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_time\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event_or_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBnext_trigger\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event_and_list\fP &, \fBsc_simcontext\fP *)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Types inherited from \fBsc_core::sc_process_b\fP
.in +1c
.ti -1c
.RI "enum \fBprocess_throw_type\fP { \fBTHROW_NONE\fP = 0, \fBTHROW_KILL\fP, \fBTHROW_USER\fP, \fBTHROW_ASYNC_RESET\fP, \fBTHROW_SYNC_RESET\fP }"
.br
.ti -1c
.RI "enum \fBprocess_state\fP { \fBps_bit_disabled\fP = 1, \fBps_bit_ready_to_run\fP = 2, \fBps_bit_suspended\fP = 4, \fBps_bit_zombie\fP = 8, \fBps_normal\fP = 0 }"
.br
.ti -1c
.RI "enum \fBreset_type\fP { \fBreset_asynchronous\fP = 0, \fBreset_synchronous_off\fP, \fBreset_synchronous_on\fP }"
.br
.ti -1c
.RI "enum \fBtrigger_t\fP { \fBSTATIC\fP, \fBEVENT\fP, \fBOR_LIST\fP, \fBAND_LIST\fP, \fBTIMEOUT\fP, \fBEVENT_TIMEOUT\fP, \fBOR_LIST_TIMEOUT\fP, \fBAND_LIST_TIMEOUT\fP }"
.br
.in -1c

Public Types inherited from \fBsc_core::sc_object\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBunsigned\fP \fBphase_cb_mask\fP"
.br
.in -1c

Static Public Member Functions inherited from \fBsc_core::sc_process_b\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsc_process_handle\fP \fBlast_created_process_handle\fP ()"
.br
.in -1c

Public Attributes inherited from \fBsc_core::sc_process_b\fP
.in +1c
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBfile\fP"
.br
.ti -1c
.RI "int \fBlineno\fP"
.br
.ti -1c
.RI "int \fBproc_id\fP"
.br
.in -1c

Protected Types inherited from \fBsc_core::sc_process_b\fP
.in +1c
.ti -1c
.RI "enum \fBspawn_t\fP { \fBSPAWN_ELAB\fP = 0x0, \fBSPAWN_START\fP = 0x1, \fBSPAWN_SIM\fP = 0x2 }"
.br
.in -1c

Static Protected Member Functions inherited from \fBsc_core::sc_process_b\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsc_process_b\fP * \fBlast_created_process_base\fP ()"
.br
.in -1c

Static Protected Attributes inherited from \fBsc_core::sc_process_b\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsc_process_b\fP * \fBm_last_created_process_p\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_method_process::sc_method_process (\fBconst\fP \fBchar\fP * name_p, \fBbool\fP free_host, \fBSC_ENTRY_FUNC\fP method_p, \fBsc_process_host\fP * host_p, \fBconst\fP \fBsc_spawn_options\fP * opt_p)"

.SS "\fBvirtual\fP sc_core::sc_method_process::~sc_method_process ()\fR [private]\fP, \fR [virtual]\fP"

.SS "sc_core::sc_method_process::sc_method_process (\fBconst\fP \fBsc_method_process\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP sc_core::sc_method_process::check_for_throws ()\fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_method_process::clear_trigger ()\fR [protected]\fP"

.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_method_process::disable_process (\fBsc_descendant_inclusion_info\fP descendants = \fR\fBSC_NO_DESCENDANTS\fP\fP)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_process_b\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_method_process::enable_process (\fBsc_descendant_inclusion_info\fP descendants = \fR\fBSC_NO_DESCENDANTS\fP\fP)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_process_b\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_method_process::kill_process (\fBsc_descendant_inclusion_info\fP descendants = \fR\fBSC_NO_DESCENDANTS\fP\fP)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_process_b\fP\&.
.SS "\fBvirtual\fP \fBconst\fP \fBchar\fP * sc_core::sc_method_process::kind () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBsc_core::sc_object\fP\&.
.SS "\fBsc_method_handle\fP sc_core::sc_method_process::next_exist ()\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBsc_method_handle\fP sc_core::sc_method_process::next_runnable ()\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_method_process::next_trigger (\fBconst\fP \fBsc_event\fP & e)\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_method_process::next_trigger (\fBconst\fP \fBsc_event_and_list\fP & el)\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_method_process::next_trigger (\fBconst\fP \fBsc_event_or_list\fP & el)\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_method_process::next_trigger (\fBconst\fP \fBsc_time\fP & t)\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_method_process::next_trigger (\fBconst\fP \fBsc_time\fP & t, \fBconst\fP \fBsc_event\fP & e)\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_method_process::next_trigger (\fBconst\fP \fBsc_time\fP & t, \fBconst\fP \fBsc_event_and_list\fP & el)\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_method_process::next_trigger (\fBconst\fP \fBsc_time\fP & t, \fBconst\fP \fBsc_event_or_list\fP & el)\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBconst\fP \fBsc_method_process\fP & sc_core::sc_method_process::operator= (\fBconst\fP \fBsc_method_process\fP &)\fR [private]\fP"

.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_method_process::resume_process (\fBsc_descendant_inclusion_info\fP descendants = \fR\fBSC_NO_DESCENDANTS\fP\fP)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_process_b\fP\&.
.SS "\fBbool\fP sc_core::sc_method_process::run_process ()\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_method_process::set_next_exist (\fBsc_method_handle\fP next_p)\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_method_process::set_next_runnable (\fBsc_method_handle\fP next_p)\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_method_process::set_stack_size (std::size_t size)\fR [protected]\fP"

.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_method_process::suspend_process (\fBsc_descendant_inclusion_info\fP descendants = \fR\fBSC_NO_DESCENDANTS\fP\fP)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_process_b\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_method_process::throw_reset (\fBbool\fP async)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_process_b\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP sc_core::sc_method_process::throw_user (\fBconst\fP \fBsc_throw_it_helper\fP & helper, \fBsc_descendant_inclusion_info\fP descendants = \fR\fBSC_NO_DESCENDANTS\fP\fP)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_process_b\fP\&.
.SS "\fBbool\fP sc_core::sc_method_process::trigger_dynamic (\fBsc_event\fP *)\fR [protected]\fP"

.SS "\fBvoid\fP sc_core::sc_method_process::trigger_static ()\fR [inline]\fP, \fR [protected]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBvoid\fP next_trigger (\fBconst\fP \fBsc_event\fP &, \fBsc_simcontext\fP *)\fR [friend]\fP"

.SS "\fBvoid\fP next_trigger (\fBconst\fP \fBsc_event_and_list\fP &, \fBsc_simcontext\fP *)\fR [friend]\fP"

.SS "\fBvoid\fP next_trigger (\fBconst\fP \fBsc_event_or_list\fP &, \fBsc_simcontext\fP *)\fR [friend]\fP"

.SS "\fBvoid\fP next_trigger (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event\fP &, \fBsc_simcontext\fP *)\fR [friend]\fP"

.SS "\fBvoid\fP next_trigger (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event_and_list\fP &, \fBsc_simcontext\fP *)\fR [friend]\fP"

.SS "\fBvoid\fP next_trigger (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event_or_list\fP &, \fBsc_simcontext\fP *)\fR [friend]\fP"

.SS "\fBvoid\fP next_trigger (\fBconst\fP \fBsc_time\fP &, \fBsc_simcontext\fP *)\fR [friend]\fP"

.SS "\fBvoid\fP next_trigger (\fBsc_simcontext\fP *)\fR [friend]\fP"

.SS "\fBvoid\fP sc_cmethod_cor_fn (\fBvoid\fP *)\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_event\fP\fR [friend]\fP"

.SS "\fBfriend\fP \fBstruct\fP sc_invoke_method\fR [friend]\fP"

.SS "\fBvoid\fP sc_method_cor_fn (\fBvoid\fP *)\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_module\fP\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_process_handle\fP\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP sc_process_table\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_runnable\fP\fR [friend]\fP"

.SS "\fBvoid\fP sc_set_stack_size (\fBsc_method_handle\fP, std::size_t)\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_simcontext\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_cor\fP* sc_core::sc_method_process::m_cor\fR [protected]\fP"

.SS "std::vector<\fBsc_process_monitor\fP*> sc_core::sc_method_process::m_monitor_q\fR [protected]\fP"

.SS "std::size_t sc_core::sc_method_process::m_stack_size\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
