.TH "sc_core::sc_kill" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_core::sc_kill
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_except\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_kill\fP ()"
.br
.ti -1c
.RI "\fBsc_kill\fP (\fBconst\fP \fBsc_kill\fP &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_core::sc_kill::sc_kill ()\fR [inline]\fP"

.SS "sc_core::sc_kill::sc_kill (\fBconst\fP \fBsc_kill\fP &)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
