.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/old_ui_project/qt-sc/sc_config.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/old_ui_project/qt-sc/sc_config.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'sc_config\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBsc_setConfig\fP (\fBsc_thread_config_t\fP *\fBtheConfig\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_getRstActLevel\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBsc_getRstActMicrosteps\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_getEnaActLevel\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_getClkActEdge\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBsc_time\fP \fBsc_getClkPeriod\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBsc_time\fP \fBsc_getMicrostep\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBsc_getClkSemiperiodMicrosteps\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBbool\fP sc_getClkActEdge (\fBvoid\fP)"

.SS "\fBsc_time\fP sc_getClkPeriod (\fBvoid\fP)"

.SS "int sc_getClkSemiperiodMicrosteps (\fBvoid\fP)"

.SS "\fBbool\fP sc_getEnaActLevel (\fBvoid\fP)"

.SS "\fBsc_time\fP sc_getMicrostep (\fBvoid\fP)"

.SS "\fBbool\fP sc_getRstActLevel (\fBvoid\fP)"

.SS "int sc_getRstActMicrosteps (\fBvoid\fP)"

.SS "\fBvoid\fP sc_setConfig (\fBsc_thread_config_t\fP * theConfig)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
