.TH "sc_dt::scfx_index" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::scfx_index
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scfx_rep\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscfx_index\fP (int \fBwi_\fP, int \fBbi_\fP)"
.br
.ti -1c
.RI "int \fBwi\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBbi\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBwi\fP (int \fBwi_\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_wi\fP"
.br
.ti -1c
.RI "int \fBm_bi\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::scfx_index::scfx_index (int wi_, int bi_)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int sc_dt::scfx_index::bi () const\fR [inline]\fP"

.SS "int sc_dt::scfx_index::wi () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_index::wi (int wi_)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int sc_dt::scfx_index::m_bi\fR [private]\fP"

.SS "int sc_dt::scfx_index::m_wi\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
