.TH "sc_dt::scfx_params" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::scfx_params
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scfx_params\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscfx_params\fP (\fBconst\fP \fBsc_fxtype_params\fP &, \fBsc_enc\fP, \fBconst\fP \fBsc_fxcast_switch\fP &)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_fxtype_params\fP & \fBtype_params\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_enc\fP \fBenc\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_fxcast_switch\fP & \fBcast_switch\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBwl\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBiwl\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBfwl\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_q_mode\fP \fBq_mode\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_o_mode\fP \fBo_mode\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBn_bits\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBdump\fP (::std::ostream &) \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBsc_fxtype_params\fP \fBm_type_params\fP"
.br
.ti -1c
.RI "\fBsc_enc\fP \fBm_enc\fP"
.br
.ti -1c
.RI "\fBsc_fxcast_switch\fP \fBm_cast_switch\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::scfx_params::scfx_params (\fBconst\fP \fBsc_fxtype_params\fP & type_params_, \fBsc_enc\fP enc_, \fBconst\fP \fBsc_fxcast_switch\fP & cast_sw)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBconst\fP \fBsc_fxcast_switch\fP & sc_dt::scfx_params::cast_switch () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_params::dump (::std::ostream & os) const\fR [inline]\fP"

.SS "\fBsc_enc\fP sc_dt::scfx_params::enc () const\fR [inline]\fP"

.SS "int sc_dt::scfx_params::fwl () const\fR [inline]\fP"

.SS "int sc_dt::scfx_params::iwl () const\fR [inline]\fP"

.SS "int sc_dt::scfx_params::n_bits () const\fR [inline]\fP"

.SS "\fBsc_o_mode\fP sc_dt::scfx_params::o_mode () const\fR [inline]\fP"

.SS "\fBsc_q_mode\fP sc_dt::scfx_params::q_mode () const\fR [inline]\fP"

.SS "\fBconst\fP \fBsc_fxtype_params\fP & sc_dt::scfx_params::type_params () const\fR [inline]\fP"

.SS "int sc_dt::scfx_params::wl () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_fxcast_switch\fP sc_dt::scfx_params::m_cast_switch\fR [private]\fP"

.SS "\fBsc_enc\fP sc_dt::scfx_params::m_enc\fR [private]\fP"

.SS "\fBsc_fxtype_params\fP sc_dt::scfx_params::m_type_params\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
