.TH "sc_dt::sc_generic_base< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_generic_base< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_value_base\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBT\fP * \fBoperator\->\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBT\fP * \fBoperator\->\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBT\fP * \fBsc_dt::sc_generic_base\fP< \fBT\fP >\fB::operator\fP\-> ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBT\fP * \fBsc_dt::sc_generic_base\fP< \fBT\fP >\fB::operator\fP\-> () const\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
