.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_dynamic_processes.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_dynamic_processes.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_cmnhdr\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_except\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_spawn\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_join\&.h'\fP
.br
\fR#include 'sysc/packages/boost/bind\&.hpp'\fP
.br
\fR#include 'sysc/packages/boost/ref\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBsc_bind\fP   sc_boost::bind"
.br
.ti -1c
.RI "#\fBdefine\fP \fBsc_ref\fP(\fBr\fP)   \fBsc_boost::ref\fP(\fBr\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBsc_cref\fP(\fBr\fP)   \fBsc_boost::cref\fP(\fBr\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP sc_bind   sc_boost::bind"

.SS "#\fBdefine\fP sc_cref(\fBr\fP)   \fBsc_boost::cref\fP(\fBr\fP)"

.SS "#\fBdefine\fP sc_ref(\fBr\fP)   \fBsc_boost::ref\fP(\fBr\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
