.TH "sc_dt::sc_mixed_proxy_traits_helper< X, X >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_mixed_proxy_traits_helper< X, X >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_proxy\&.h>\fP
.PP
Inherits X\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
