.TH "sc_dt::sc_proxy_traits< sc_lv_base >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_proxy_traits< sc_lv_base >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_proxy\&.h>\fP
.PP
Inherited by \fBsc_dt::sc_mixed_proxy_traits_helper< X::traits_type, Y::traits_type >\fP, and \fBsc_dt::sc_mixed_proxy_traits_helper< X, Y >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_proxy_traits\fP< \fBsc_lv_base\fP > \fBtraits_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_logic_value_t\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_logic\fP \fBbit_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv_base\fP \fBvector_type\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBsc_logic\fP \fBsc_dt::sc_proxy_traits\fP< \fBsc_lv_base\fP >::bit_type"

.SS "\fBtypedef\fP \fBsc_proxy_traits\fP<\fBsc_lv_base\fP> \fBsc_dt::sc_proxy_traits\fP< \fBsc_lv_base\fP >::traits_type"

.SS "\fBtypedef\fP \fBsc_logic_value_t\fP \fBsc_dt::sc_proxy_traits\fP< \fBsc_lv_base\fP >::value_type"

.SS "\fBtypedef\fP \fBsc_lv_base\fP \fBsc_dt::sc_proxy_traits\fP< \fBsc_lv_base\fP >::vector_type"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
