.TH "sc_dt::sc_uint< W >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_uint< W >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_uint\&.h>\fP
.PP
Inherits \fBsc_dt::sc_uint_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_uint\fP ()"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBconst\fP \fBsc_uint\fP< \fBW\fP > &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBconst\fP \fBsc_uint_subref_r\fP &\fBa\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_uint\fP (\fBconst\fP \fBsc_generic_base\fP< \fBT\fP > &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBconst\fP \fBsc_signed\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBconst\fP \fBsc_unsigned\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBconst\fP \fBsc_bv_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBconst\fP \fBsc_lv_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBconst\fP \fBchar\fP *\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBunsigned\fP \fBlong\fP \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBlong\fP \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBunsigned\fP int \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (int \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBint64\fP \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP (\fBdouble\fP \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_uint_subref_r\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_uint\fP< \fBW\fP > &\fBa\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_generic_base\fP< \fBT\fP > &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_signed\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_bv_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_lv_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBconst\fP \fBchar\fP *\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBunsigned\fP \fBlong\fP \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBlong\fP \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBunsigned\fP int \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (int \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBint64\fP \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator=\fP (\fBdouble\fP \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator+=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator\-=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator*=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator/=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator%=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator&=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator|=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator^=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator<<=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator>>=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_uint\fP< \fBW\fP > \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBsc_uint\fP< \fBW\fP > & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_uint\fP< \fBW\fP > \fBoperator\-\-\fP (int)"
.br
.in -1c

Public Member Functions inherited from \fBsc_dt::sc_uint_base\fP
.in +1c
.ti -1c
.RI "\fBsc_uint_base\fP (int \fBw\fP=\fBsc_length_param\fP()\&.len())"
.br
.ti -1c
.RI "\fBsc_uint_base\fP (\fBuint_type\fP v, int \fBw\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP (\fBconst\fP \fBsc_uint_subref_r\fP &\fBa\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_uint_base\fP (\fBconst\fP \fBsc_generic_base\fP< \fBT\fP > &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP (\fBconst\fP \fBsc_bv_base\fP &v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP (\fBconst\fP \fBsc_lv_base\fP &v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP (\fBconst\fP \fBsc_int_subref_r\fP &v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP (\fBconst\fP \fBsc_signed_subref_r\fP &v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP (\fBconst\fP \fBsc_unsigned_subref_r\fP &v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP (\fBconst\fP \fBsc_signed\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP (\fBconst\fP \fBsc_unsigned\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_uint_base\fP ()"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBconst\fP \fBsc_uint_subref_r\fP &\fBa\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBsc_uint_base\fP & \fBoperator=\fP (\fBconst\fP \fBsc_generic_base\fP< \fBT\fP > &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBconst\fP \fBsc_signed\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBconst\fP \fBsc_bv_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBconst\fP \fBsc_lv_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBconst\fP \fBchar\fP *\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBunsigned\fP \fBlong\fP \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBlong\fP \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBunsigned\fP int \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (int \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBint64\fP \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator=\fP (\fBdouble\fP \fBa\fP)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator+=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator\-=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator*=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator/=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator%=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator&=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator|=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator^=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator<<=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator>>=\fP (\fBuint_type\fP v)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_uint_base\fP \fBoperator++\fP (int)"
.br
.ti -1c
.RI "\fBsc_uint_base\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_uint_base\fP \fBoperator\-\-\fP (int)"
.br
.ti -1c
.RI "\fBsc_uint_bitref\fP & \fBoperator[]\fP (int \fBi\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_uint_bitref_r\fP & \fBoperator[]\fP (int \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_uint_bitref\fP & \fBbit\fP (int \fBi\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_uint_bitref_r\fP & \fBbit\fP (int \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_uint_subref\fP & \fBoperator()\fP (int left, int right)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_uint_subref_r\fP & \fBoperator()\fP (int left, int right) \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_uint_subref\fP & \fBrange\fP (int left, int right)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_uint_subref_r\fP & \fBrange\fP (int left, int right) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBtest\fP (int \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset\fP (int \fBi\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBset\fP (int \fBi\fP, \fBbool\fP v)"
.br
.ti -1c
.RI "int \fBlength\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP int \fBconcat_length\fP (\fBbool\fP *\fBxz_present_p\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBconcat_get_ctrl\fP (\fBsc_digit\fP *\fBdst_p\fP, int \fBlow_i\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBconcat_get_data\fP (\fBsc_digit\fP *\fBdst_p\fP, int \fBlow_i\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBuint64\fP \fBconcat_get_uint64\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBconcat_set\fP (\fBint64\fP \fBsrc\fP, int \fBlow_i\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBconcat_set\fP (\fBconst\fP \fBsc_signed\fP &\fBsrc\fP, int \fBlow_i\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBconcat_set\fP (\fBconst\fP \fBsc_unsigned\fP &\fBsrc\fP, int \fBlow_i\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBconcat_set\fP (\fBuint64\fP \fBsrc\fP, int \fBlow_i\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBand_reduce\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBnand_reduce\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBor_reduce\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBnor_reduce\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBxor_reduce\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBxnor_reduce\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBoperator uint_type\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBuint_type\fP \fBvalue\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBto_int\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP int \fBto_uint\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBlong\fP \fBto_long\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBlong\fP \fBto_ulong\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBint64\fP \fBto_int64\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBuint64\fP \fBto_uint64\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBdouble\fP \fBto_double\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBlong\fP \fBlong_low\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBlong\fP \fBlong_high\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP (\fBsc_numrep\fP \fBnumrep\fP=\fBSC_DEC\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP (\fBsc_numrep\fP \fBnumrep\fP, \fBbool\fP \fBw_prefix\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBprint\fP (::std::ostream &\fBos\fP=::std::cout) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBscan\fP (::std::istream &\fBis\fP=::std::cin)"
.br
.in -1c

Public Member Functions inherited from \fBsc_dt::sc_value_base\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~sc_value_base\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBsc_dt::sc_uint_base\fP
.in +1c
.ti -1c
.RI "\fBuint_type\fP \fBm_val\fP"
.br
.ti -1c
.RI "int \fBm_len\fP"
.br
.ti -1c
.RI "int \fBm_ulen\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint ()\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBuint_type\fP v)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBconst\fP \fBsc_uint\fP< \fBW\fP > & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBconst\fP \fBsc_uint_base\fP & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBconst\fP \fBsc_uint_subref_r\fP & a)\fR [inline]\fP"

.SS "template<int W> template<\fBclass\fP \fBT\fP > \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBconst\fP \fBsc_generic_base\fP< \fBT\fP > & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBconst\fP \fBsc_signed\fP & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBconst\fP \fBsc_unsigned\fP & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBconst\fP \fBsc_bv_base\fP & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBconst\fP \fBsc_lv_base\fP & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBconst\fP \fBchar\fP * a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBunsigned\fP \fBlong\fP a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBlong\fP a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBunsigned\fP int a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (int a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBint64\fP a)\fR [inline]\fP"

.SS "template<int W> \fBsc_dt::sc_uint\fP< \fBW\fP >::sc_uint (\fBdouble\fP a)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP%= (\fBuint_type\fP v)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP&= (\fBuint_type\fP v)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP*= (\fBuint_type\fP v)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP++ ()\fR [inline]\fP"

.SS "template<int W> \fBconst\fP \fBsc_uint\fP< \fBW\fP > \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP++ (int)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP+= (\fBuint_type\fP v)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP\-\- ()\fR [inline]\fP"

.SS "template<int W> \fBconst\fP \fBsc_uint\fP< \fBW\fP > \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP\-\- (int)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP\-= (\fBuint_type\fP v)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP/= (\fBuint_type\fP v)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP<<= (\fBuint_type\fP v)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBconst\fP \fBchar\fP * a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBconst\fP \fBsc_bv_base\fP & a)\fR [inline]\fP"

.SS "template<int W> template<\fBclass\fP \fBT\fP > \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBconst\fP \fBsc_generic_base\fP< \fBT\fP > & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBconst\fP \fBsc_lv_base\fP & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBconst\fP \fBsc_signed\fP & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBconst\fP \fBsc_uint\fP< \fBW\fP > & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBconst\fP \fBsc_uint_base\fP & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBconst\fP \fBsc_uint_subref_r\fP & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBconst\fP \fBsc_unsigned\fP & a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBdouble\fP a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (int a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBint64\fP a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBlong\fP a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBuint_type\fP v)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBunsigned\fP int a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP= (\fBunsigned\fP \fBlong\fP a)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP>>= (\fBuint_type\fP v)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP^= (\fBuint_type\fP v)\fR [inline]\fP"

.SS "template<int W> \fBsc_uint\fP< \fBW\fP > & \fBsc_dt::sc_uint\fP< \fBW\fP >\fB::operator\fP|= (\fBuint_type\fP v)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
