.TH "sc_dt::ieee_float" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::ieee_float
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scfx_ieee\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBfloat\fP \fBf\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "} \fBs\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBfloat\fP sc_dt::ieee_float::f"

.SS "struct  { \&.\&.\&. }  sc_dt::ieee_float::s"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
