.TH "sc_dt::scfx_ieee_float" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::scfx_ieee_float
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scfx_ieee\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscfx_ieee_float\fP ()"
.br
.ti -1c
.RI "\fBscfx_ieee_float\fP (\fBfloat\fP)"
.br
.ti -1c
.RI "\fBscfx_ieee_float\fP (\fBconst\fP \fBscfx_ieee_float\fP &)"
.br
.ti -1c
.RI "\fBscfx_ieee_float\fP & \fBoperator=\fP (\fBfloat\fP)"
.br
.ti -1c
.RI "\fBscfx_ieee_float\fP & \fBoperator=\fP (\fBconst\fP \fBscfx_ieee_float\fP &)"
.br
.ti -1c
.RI "\fBoperator float\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP int \fBnegative\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBnegative\fP (\fBunsigned\fP int)"
.br
.ti -1c
.RI "int \fBexponent\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBexponent\fP (int)"
.br
.ti -1c
.RI "\fBunsigned\fP int \fBmantissa\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBmantissa\fP (\fBunsigned\fP int)"
.br
.ti -1c
.RI "\fBbool\fP \fBis_zero\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_subnormal\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_normal\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_inf\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_nan\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_inf\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_nan\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBieee_float\fP \fBm_if\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::scfx_ieee_float::scfx_ieee_float ()\fR [inline]\fP"

.SS "sc_dt::scfx_ieee_float::scfx_ieee_float (\fBfloat\fP f)\fR [inline]\fP"

.SS "sc_dt::scfx_ieee_float::scfx_ieee_float (\fBconst\fP \fBscfx_ieee_float\fP & a)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int sc_dt::scfx_ieee_float::exponent () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_ieee_float::exponent (int a)\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::scfx_ieee_float::is_inf () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::scfx_ieee_float::is_nan () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::scfx_ieee_float::is_normal () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::scfx_ieee_float::is_subnormal () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::scfx_ieee_float::is_zero () const\fR [inline]\fP"

.SS "\fBunsigned\fP int sc_dt::scfx_ieee_float::mantissa () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_ieee_float::mantissa (\fBunsigned\fP int a)\fR [inline]\fP"

.SS "\fBunsigned\fP int sc_dt::scfx_ieee_float::negative () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_ieee_float::negative (\fBunsigned\fP int a)\fR [inline]\fP"

.SS "sc_dt::scfx_ieee_float::operator \fBfloat\fP () const\fR [inline]\fP"

.SS "\fBscfx_ieee_float\fP & sc_dt::scfx_ieee_float::operator= (\fBconst\fP \fBscfx_ieee_float\fP & a)\fR [inline]\fP"

.SS "\fBscfx_ieee_float\fP & sc_dt::scfx_ieee_float::operator= (\fBfloat\fP f)\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_ieee_float::set_inf ()\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_ieee_float::set_nan ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBieee_float\fP sc_dt::scfx_ieee_float::m_if\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
