.TH "sc_dt::scfx_mant" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::scfx_mant
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scfx_mant\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscfx_mant\fP (std::size_t)"
.br
.ti -1c
.RI "\fBscfx_mant\fP (\fBconst\fP \fBscfx_mant\fP &)"
.br
.ti -1c
.RI "\fBscfx_mant\fP & \fBoperator=\fP (\fBconst\fP \fBscfx_mant\fP &)"
.br
.ti -1c
.RI "\fB~scfx_mant\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBclear\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBresize_to\fP (int, int=0)"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBword\fP \fBoperator[]\fP (int) \fBconst\fP"
.br
.ti -1c
.RI "\fBword\fP & \fBoperator[]\fP (int)"
.br
.ti -1c
.RI "\fBhalf_word\fP \fBhalf_at\fP (int) \fBconst\fP"
.br
.ti -1c
.RI "\fBhalf_word\fP & \fBhalf_at\fP (int)"
.br
.ti -1c
.RI "\fBhalf_word\fP * \fBhalf_addr\fP (int=0) \fBconst\fP"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBword\fP * \fBalloc\fP (std::size_t)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBfree\fP (\fBword\fP *, std::size_t)"
.br
.ti -1c
.RI "\fBstatic\fP \fBword\fP * \fBalloc_word\fP (std::size_t \fBsize\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBfree_word\fP (\fBword\fP *\fBarray\fP, std::size_t \fBsize\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBword\fP * \fBm_array\fP"
.br
.ti -1c
.RI "int \fBm_size\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::scfx_mant::scfx_mant (std::size_t size_)\fR [inline]\fP, \fR [explicit]\fP"

.SS "sc_dt::scfx_mant::scfx_mant (\fBconst\fP \fBscfx_mant\fP & rhs)\fR [inline]\fP"

.SS "sc_dt::scfx_mant::~scfx_mant ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBword\fP * sc_dt::scfx_mant::alloc (std::size_t size)\fR [inline]\fP, \fR [static]\fP, \fR [private]\fP"

.SS "\fBstatic\fP \fBword\fP * sc_dt::scfx_mant::alloc_word (std::size_t size)\fR [static]\fP, \fR [private]\fP"

.SS "\fBvoid\fP sc_dt::scfx_mant::clear ()\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_mant::free (\fBword\fP * mant, std::size_t size)\fR [inline]\fP, \fR [static]\fP, \fR [private]\fP"

.SS "\fBstatic\fP \fBvoid\fP sc_dt::scfx_mant::free_word (\fBword\fP * array, std::size_t size)\fR [static]\fP, \fR [private]\fP"

.SS "\fBhalf_word\fP * sc_dt::scfx_mant::half_addr (int i = \fR0\fP) const\fR [inline]\fP"

.SS "\fBhalf_word\fP & sc_dt::scfx_mant::half_at (int i)\fR [inline]\fP"

.SS "\fBhalf_word\fP sc_dt::scfx_mant::half_at (int i) const\fR [inline]\fP"

.SS "\fBscfx_mant\fP & sc_dt::scfx_mant::operator= (\fBconst\fP \fBscfx_mant\fP & rhs)\fR [inline]\fP"

.SS "\fBword\fP & sc_dt::scfx_mant::operator[] (int i)\fR [inline]\fP"

.SS "\fBword\fP sc_dt::scfx_mant::operator[] (int i) const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_mant::resize_to (int size, int restore = \fR0\fP)\fR [inline]\fP"

.SS "int sc_dt::scfx_mant::size () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBword\fP* sc_dt::scfx_mant::m_array\fR [private]\fP"

.SS "int sc_dt::scfx_mant::m_size\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
