.TH "sc_dt::sc_bit" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_bit
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_bit\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_bit\fP ()"
.br
.ti -1c
.RI "\fBsc_bit\fP (\fBconst\fP \fBsc_logic\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_bit\fP (\fBconst\fP \fBsc_bit\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fB~sc_bit\fP ()"
.br
.ti -1c
.RI "\fBsc_bit\fP & \fBoperator=\fP (\fBconst\fP \fBsc_bit\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBsc_bit\fP & \fBoperator=\fP (\fBconst\fP \fBsc_logic\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBsc_bit\fP & \fBoperator&=\fP (\fBconst\fP \fBsc_bit\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBsc_bit\fP & \fBoperator|=\fP (\fBconst\fP \fBsc_bit\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBsc_bit\fP & \fBoperator^=\fP (\fBconst\fP \fBsc_bit\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBoperator bool\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBto_bool\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBchar\fP \fBto_char\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_bit\fP & \fBb_not\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBprint\fP (::std::ostream &\fBos\fP=::std::cout) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBscan\fP (::std::istream &=::std::cin)"
.br
.in -1c
.SS "Static Private Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBinvalid_value\fP (\fBchar\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBvoid\fP \fBinvalid_value\fP (int)"
.br
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBto_value\fP (\fBchar\fP \fBc\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBto_value\fP (int \fBi\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBto_value\fP (\fBbool\fP \fBb\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBm_val\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP \fBsc_bit\fP &\fBa\fP, \fBconst\fP \fBsc_bit\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBconst\fP \fBsc_bit\fP &\fBa\fP, \fBconst\fP \fBsc_bit\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_bit\fP \fBoperator~\fP (\fBconst\fP \fBsc_bit\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_bit\fP \fBoperator|\fP (\fBconst\fP \fBsc_bit\fP &\fBa\fP, \fBconst\fP \fBsc_bit\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_bit\fP \fBoperator&\fP (\fBconst\fP \fBsc_bit\fP &\fBa\fP, \fBconst\fP \fBsc_bit\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_bit\fP \fBoperator^\fP (\fBconst\fP \fBsc_bit\fP &\fBa\fP, \fBconst\fP \fBsc_bit\fP &\fBb\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::sc_bit::sc_bit ()\fR [inline]\fP"

.SS "sc_dt::sc_bit::sc_bit (\fBconst\fP \fBsc_logic\fP & a)\fR [explicit]\fP"

.SS "sc_dt::sc_bit::sc_bit (\fBconst\fP \fBsc_bit\fP & a)\fR [inline]\fP"

.SS "sc_dt::sc_bit::~sc_bit ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBsc_bit\fP & sc_dt::sc_bit::b_not ()\fR [inline]\fP"

.SS "\fBstatic\fP \fBvoid\fP sc_dt::sc_bit::invalid_value (\fBchar\fP)\fR [static]\fP, \fR [private]\fP"

.SS "\fBstatic\fP \fBvoid\fP sc_dt::sc_bit::invalid_value (int)\fR [static]\fP, \fR [private]\fP"

.SS "sc_dt::sc_bit::operator \fBbool\fP () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::sc_bit::operator! () const\fR [inline]\fP"

.SS "\fBsc_bit\fP & sc_dt::sc_bit::operator&= (\fBconst\fP \fBsc_bit\fP & b)\fR [inline]\fP"

.SS "\fBsc_bit\fP & sc_dt::sc_bit::operator= (\fBconst\fP \fBsc_bit\fP & b)\fR [inline]\fP"

.SS "\fBsc_bit\fP & sc_dt::sc_bit::operator= (\fBconst\fP \fBsc_logic\fP & b)"

.SS "\fBsc_bit\fP & sc_dt::sc_bit::operator^= (\fBconst\fP \fBsc_bit\fP & b)\fR [inline]\fP"

.SS "\fBsc_bit\fP & sc_dt::sc_bit::operator|= (\fBconst\fP \fBsc_bit\fP & b)\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_bit::print (::std::ostream & os = \fR::std::cout\fP) const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_bit::scan (::std::istream & = \fR::std::cin\fP)"

.SS "\fBbool\fP sc_dt::sc_bit::to_bool () const\fR [inline]\fP"

.SS "\fBchar\fP sc_dt::sc_bit::to_char () const\fR [inline]\fP"

.SS "\fBstatic\fP \fBbool\fP sc_dt::sc_bit::to_value (\fBbool\fP b)\fR [inline]\fP, \fR [static]\fP, \fR [private]\fP"

.SS "\fBstatic\fP \fBbool\fP sc_dt::sc_bit::to_value (\fBchar\fP c)\fR [inline]\fP, \fR [static]\fP, \fR [private]\fP"

.SS "\fBstatic\fP \fBbool\fP sc_dt::sc_bit::to_value (int i)\fR [inline]\fP, \fR [static]\fP, \fR [private]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBbool\fP \fBoperator!\fP= (\fBconst\fP \fBsc_bit\fP & a, \fBconst\fP \fBsc_bit\fP & b)\fR [friend]\fP"

.SS "\fBconst\fP \fBsc_bit\fP \fBoperator\fP& (\fBconst\fP \fBsc_bit\fP & a, \fBconst\fP \fBsc_bit\fP & b)\fR [friend]\fP"

.SS "\fBbool\fP \fBoperator\fP== (\fBconst\fP \fBsc_bit\fP & a, \fBconst\fP \fBsc_bit\fP & b)\fR [friend]\fP"

.SS "\fBconst\fP \fBsc_bit\fP \fBoperator\fP^ (\fBconst\fP \fBsc_bit\fP & a, \fBconst\fP \fBsc_bit\fP & b)\fR [friend]\fP"

.SS "\fBconst\fP \fBsc_bit\fP \fBoperator\fP| (\fBconst\fP \fBsc_bit\fP & a, \fBconst\fP \fBsc_bit\fP & b)\fR [friend]\fP"

.SS "\fBconst\fP \fBsc_bit\fP operator~ (\fBconst\fP \fBsc_bit\fP & a)\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP sc_dt::sc_bit::m_val\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
