.TH "sc_dt::scfx_ieee_double" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::scfx_ieee_double
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scfx_ieee\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscfx_ieee_double\fP ()"
.br
.ti -1c
.RI "\fBscfx_ieee_double\fP (\fBdouble\fP)"
.br
.ti -1c
.RI "\fBscfx_ieee_double\fP (\fBconst\fP \fBscfx_ieee_double\fP &)"
.br
.ti -1c
.RI "\fBscfx_ieee_double\fP & \fBoperator=\fP (\fBdouble\fP)"
.br
.ti -1c
.RI "\fBscfx_ieee_double\fP & \fBoperator=\fP (\fBconst\fP \fBscfx_ieee_double\fP &)"
.br
.ti -1c
.RI "\fBoperator double\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP int \fBnegative\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBnegative\fP (\fBunsigned\fP int)"
.br
.ti -1c
.RI "int \fBexponent\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBexponent\fP (int)"
.br
.ti -1c
.RI "\fBunsigned\fP int \fBmantissa0\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBmantissa0\fP (\fBunsigned\fP int)"
.br
.ti -1c
.RI "\fBunsigned\fP int \fBmantissa1\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBmantissa1\fP (\fBunsigned\fP int)"
.br
.ti -1c
.RI "\fBbool\fP \fBis_zero\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_subnormal\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_normal\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_inf\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_nan\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_inf\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_nan\fP ()"
.br
.ti -1c
.RI "int \fBmsb\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBlsb\fP () \fBconst\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBscfx_ieee_double\fP \fBnan\fP ()"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBscfx_ieee_double\fP \fBinf\fP (int)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBieee_double\fP \fBm_id\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::scfx_ieee_double::scfx_ieee_double ()\fR [inline]\fP"

.SS "sc_dt::scfx_ieee_double::scfx_ieee_double (\fBdouble\fP d)\fR [inline]\fP"

.SS "sc_dt::scfx_ieee_double::scfx_ieee_double (\fBconst\fP \fBscfx_ieee_double\fP & a)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "int sc_dt::scfx_ieee_double::exponent () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_ieee_double::exponent (int a)\fR [inline]\fP"

.SS "\fBconst\fP \fBscfx_ieee_double\fP sc_dt::scfx_ieee_double::inf (int sign)\fR [inline]\fP, \fR [static]\fP"

.SS "\fBbool\fP sc_dt::scfx_ieee_double::is_inf () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::scfx_ieee_double::is_nan () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::scfx_ieee_double::is_normal () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::scfx_ieee_double::is_subnormal () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::scfx_ieee_double::is_zero () const\fR [inline]\fP"

.SS "int sc_dt::scfx_ieee_double::lsb () const\fR [inline]\fP"

.SS "\fBunsigned\fP int sc_dt::scfx_ieee_double::mantissa0 () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_ieee_double::mantissa0 (\fBunsigned\fP int a)\fR [inline]\fP"

.SS "\fBunsigned\fP int sc_dt::scfx_ieee_double::mantissa1 () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_ieee_double::mantissa1 (\fBunsigned\fP int a)\fR [inline]\fP"

.SS "int sc_dt::scfx_ieee_double::msb () const\fR [inline]\fP"

.SS "\fBconst\fP \fBscfx_ieee_double\fP sc_dt::scfx_ieee_double::nan ()\fR [inline]\fP, \fR [static]\fP"

.SS "\fBunsigned\fP int sc_dt::scfx_ieee_double::negative () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_ieee_double::negative (\fBunsigned\fP int a)\fR [inline]\fP"

.SS "sc_dt::scfx_ieee_double::operator \fBdouble\fP () const\fR [inline]\fP"

.SS "\fBscfx_ieee_double\fP & sc_dt::scfx_ieee_double::operator= (\fBconst\fP \fBscfx_ieee_double\fP & a)\fR [inline]\fP"

.SS "\fBscfx_ieee_double\fP & sc_dt::scfx_ieee_double::operator= (\fBdouble\fP d)\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_ieee_double::set_inf ()\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_ieee_double::set_nan ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBieee_double\fP sc_dt::scfx_ieee_double::m_id\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
