.TH "sc_dt::scfx_string" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::scfx_string
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scfx_string\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscfx_string\fP ()"
.br
.ti -1c
.RI "\fB~scfx_string\fP ()"
.br
.ti -1c
.RI "int \fBlength\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBclear\fP ()"
.br
.ti -1c
.RI "\fBchar\fP & \fBoperator[]\fP (int)"
.br
.ti -1c
.RI "\fBvoid\fP \fBappend\fP (int)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdiscard\fP (int)"
.br
.ti -1c
.RI "\fBvoid\fP \fBremove\fP (int)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator+=\fP (\fBchar\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBoperator+=\fP (\fBconst\fP \fBchar\fP *)"
.br
.ti -1c
.RI "\fBoperator const char *\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBresize\fP (std::size_t)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::size_t \fBm_len\fP"
.br
.ti -1c
.RI "std::size_t \fBm_alloc\fP"
.br
.ti -1c
.RI "\fBchar\fP * \fBm_buffer\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::scfx_string::scfx_string ()\fR [inline]\fP"

.SS "sc_dt::scfx_string::~scfx_string ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP sc_dt::scfx_string::append (int n)\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_string::clear ()\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_string::discard (int n)\fR [inline]\fP"

.SS "int sc_dt::scfx_string::length () const\fR [inline]\fP"

.SS "sc_dt::scfx_string::operator \fBconst\fP \fBchar\fP * ()\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_string::operator+= (\fBchar\fP c)\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_string::operator+= (\fBconst\fP \fBchar\fP * s)\fR [inline]\fP"

.SS "\fBchar\fP & sc_dt::scfx_string::operator[] (int i)\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_string::remove (int i)\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_string::resize (std::size_t i)\fR [inline]\fP, \fR [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "std::size_t sc_dt::scfx_string::m_alloc\fR [private]\fP"

.SS "\fBchar\fP* sc_dt::scfx_string::m_buffer\fR [private]\fP"

.SS "std::size_t sc_dt::scfx_string::m_len\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
