.TH "sc_dt::sc_fxtype_params" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_fxtype_params
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_fxtype_params\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_fxtype_params\fP ()"
.br
.ti -1c
.RI "\fBsc_fxtype_params\fP (int, int)"
.br
.ti -1c
.RI "\fBsc_fxtype_params\fP (\fBsc_q_mode\fP, \fBsc_o_mode\fP, int=0)"
.br
.ti -1c
.RI "\fBsc_fxtype_params\fP (int, int, \fBsc_q_mode\fP, \fBsc_o_mode\fP, int=0)"
.br
.ti -1c
.RI "\fBsc_fxtype_params\fP (\fBconst\fP \fBsc_fxtype_params\fP &)"
.br
.ti -1c
.RI "\fBsc_fxtype_params\fP (\fBconst\fP \fBsc_fxtype_params\fP &, int, int)"
.br
.ti -1c
.RI "\fBsc_fxtype_params\fP (\fBconst\fP \fBsc_fxtype_params\fP &, \fBsc_q_mode\fP, \fBsc_o_mode\fP, int=0)"
.br
.ti -1c
.RI "\fBsc_fxtype_params\fP (\fBsc_without_context\fP)"
.br
.ti -1c
.RI "\fBsc_fxtype_params\fP & \fBoperator=\fP (\fBconst\fP \fBsc_fxtype_params\fP &)"
.br
.ti -1c
.RI "int \fBwl\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBwl\fP (int)"
.br
.ti -1c
.RI "int \fBiwl\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBiwl\fP (int)"
.br
.ti -1c
.RI "\fBsc_q_mode\fP \fBq_mode\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBq_mode\fP (\fBsc_q_mode\fP)"
.br
.ti -1c
.RI "\fBsc_o_mode\fP \fBo_mode\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBo_mode\fP (\fBsc_o_mode\fP)"
.br
.ti -1c
.RI "int \fBn_bits\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBn_bits\fP (int)"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBprint\fP (::std::ostream &=::std::cout) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBdump\fP (::std::ostream &=::std::cout) \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "int \fBm_wl\fP"
.br
.ti -1c
.RI "int \fBm_iwl\fP"
.br
.ti -1c
.RI "\fBsc_q_mode\fP \fBm_q_mode\fP"
.br
.ti -1c
.RI "\fBsc_o_mode\fP \fBm_o_mode\fP"
.br
.ti -1c
.RI "int \fBm_n_bits\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP \fBsc_fxtype_params\fP &, \fBconst\fP \fBsc_fxtype_params\fP &)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBconst\fP \fBsc_fxtype_params\fP &, \fBconst\fP \fBsc_fxtype_params\fP &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::sc_fxtype_params::sc_fxtype_params ()\fR [inline]\fP"

.SS "sc_dt::sc_fxtype_params::sc_fxtype_params (int wl_, int iwl_)\fR [inline]\fP"

.SS "sc_dt::sc_fxtype_params::sc_fxtype_params (\fBsc_q_mode\fP q_mode_, \fBsc_o_mode\fP o_mode_, int n_bits_ = \fR0\fP)\fR [inline]\fP"

.SS "sc_dt::sc_fxtype_params::sc_fxtype_params (int wl_, int iwl_, \fBsc_q_mode\fP q_mode_, \fBsc_o_mode\fP o_mode_, int n_bits_ = \fR0\fP)\fR [inline]\fP"

.SS "sc_dt::sc_fxtype_params::sc_fxtype_params (\fBconst\fP \fBsc_fxtype_params\fP & a)\fR [inline]\fP"

.SS "sc_dt::sc_fxtype_params::sc_fxtype_params (\fBconst\fP \fBsc_fxtype_params\fP & a, int wl_, int iwl_)\fR [inline]\fP"

.SS "sc_dt::sc_fxtype_params::sc_fxtype_params (\fBconst\fP \fBsc_fxtype_params\fP & a, \fBsc_q_mode\fP q_mode_, \fBsc_o_mode\fP o_mode_, int n_bits_ = \fR0\fP)\fR [inline]\fP"

.SS "sc_dt::sc_fxtype_params::sc_fxtype_params (\fBsc_without_context\fP)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP sc_dt::sc_fxtype_params::dump (::std::ostream & = \fR::std::cout\fP) const"

.SS "int sc_dt::sc_fxtype_params::iwl () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_fxtype_params::iwl (int iwl_)\fR [inline]\fP"

.SS "int sc_dt::sc_fxtype_params::n_bits () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_fxtype_params::n_bits (int n_bits_)\fR [inline]\fP"

.SS "\fBsc_o_mode\fP sc_dt::sc_fxtype_params::o_mode () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_fxtype_params::o_mode (\fBsc_o_mode\fP o_mode_)\fR [inline]\fP"

.SS "\fBsc_fxtype_params\fP & sc_dt::sc_fxtype_params::operator= (\fBconst\fP \fBsc_fxtype_params\fP & a)\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_fxtype_params::print (::std::ostream & = \fR::std::cout\fP) const"

.SS "\fBsc_q_mode\fP sc_dt::sc_fxtype_params::q_mode () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_fxtype_params::q_mode (\fBsc_q_mode\fP q_mode_)\fR [inline]\fP"

.SS "\fBconst\fP std::string sc_dt::sc_fxtype_params::to_string () const"

.SS "int sc_dt::sc_fxtype_params::wl () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_fxtype_params::wl (int wl_)\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBbool\fP operator!= (\fBconst\fP \fBsc_fxtype_params\fP & a, \fBconst\fP \fBsc_fxtype_params\fP & b)\fR [friend]\fP"

.SS "\fBbool\fP \fBoperator\fP== (\fBconst\fP \fBsc_fxtype_params\fP & a, \fBconst\fP \fBsc_fxtype_params\fP & b)\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int sc_dt::sc_fxtype_params::m_iwl\fR [private]\fP"

.SS "int sc_dt::sc_fxtype_params::m_n_bits\fR [private]\fP"

.SS "\fBsc_o_mode\fP sc_dt::sc_fxtype_params::m_o_mode\fR [private]\fP"

.SS "\fBsc_q_mode\fP sc_dt::sc_fxtype_params::m_q_mode\fR [private]\fP"

.SS "int sc_dt::sc_fxtype_params::m_wl\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
