.TH "sc_dt::sc_context< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_context< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_context\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_context\fP (\fBconst\fP \fBT\fP &, \fBsc_context_begin\fP=\fBSC_NOW\fP)"
.br
.ti -1c
.RI "\fB~sc_context\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBbegin\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBend\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBT\fP & \fBvalue\fP () \fBconst\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBT\fP & \fBdefault_value\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_context\fP (\fBconst\fP \fBsc_context\fP< \fBT\fP > &)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (std::size_t)"
.br
.ti -1c
.RI "\fBsc_context\fP & \fBoperator=\fP (\fBconst\fP \fBsc_context\fP &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBT\fP \fBm_value\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBT\fP *& \fBm_def_value_ptr\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBT\fP * \fBm_old_value_ptr\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_dt::sc_context\fP< \fBT\fP >::sc_context (\fBconst\fP \fBsc_context\fP< \fBT\fP > &)\fR [private]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_dt::sc_context\fP< \fBT\fP >::sc_context (\fBconst\fP \fBT\fP & value_, \fBsc_context_begin\fP begin_ = \fR\fBSC_NOW\fP\fP)\fR [inline]\fP, \fR [explicit]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_dt::sc_context\fP< \fBT\fP >::~\fBsc_context\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_dt::sc_context\fP< \fBT\fP >::begin ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBT\fP & \fBsc_dt::sc_context\fP< \fBT\fP >::default_value ()\fR [inline]\fP, \fR [static]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_dt::sc_context\fP< \fBT\fP >::end ()\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP * \fBsc_dt::sc_context\fP< \fBT\fP >\fB::operator\fP \fBnew\fP (std::size_t)\fR [private]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_context\fP & \fBsc_dt::sc_context\fP< \fBT\fP >\fB::operator\fP= (\fBconst\fP \fBsc_context\fP< \fBT\fP > &)\fR [private]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBT\fP & \fBsc_dt::sc_context\fP< \fBT\fP >::value () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBT\fP*& \fBsc_dt::sc_context\fP< \fBT\fP >::m_def_value_ptr\fR [private]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBT\fP* \fBsc_dt::sc_context\fP< \fBT\fP >::m_old_value_ptr\fR [private]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBT\fP \fBsc_dt::sc_context\fP< \fBT\fP >::m_value\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
