.TH "sc_dt::sc_global< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_global< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_context\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBT\fP *& \fBvalue_ptr\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsc_global\fP< \fBT\fP > * \fBinstance\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_global\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBupdate\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBsc_core::sc_phash\fP< \fBvoid\fP *, \fBconst\fP \fBT\fP * > \fBm_map\fP"
.br
.ti -1c
.RI "\fBvoid\fP * \fBm_proc\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBT\fP * \fBm_value_ptr\fP"
.br
.in -1c
.SS "Static Private Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsc_global\fP< \fBT\fP > * \fBm_instance\fP = 0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_dt::sc_global\fP< \fBT\fP >::sc_global ()\fR [inline]\fP, \fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_global\fP< \fBT\fP > * \fBsc_dt::sc_global\fP< \fBT\fP >::instance ()\fR [inline]\fP, \fR [static]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_dt::sc_global\fP< \fBT\fP >::update ()\fR [inline]\fP, \fR [private]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBT\fP *& \fBsc_dt::sc_global\fP< \fBT\fP >::value_ptr ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_global\fP< \fBT\fP > * \fBsc_dt::sc_global\fP< \fBT\fP >::m_instance = 0\fR [static]\fP, \fR [private]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_core::sc_phash\fP<\fBvoid\fP*,\fBconst\fP \fBT\fP*> \fBsc_dt::sc_global\fP< \fBT\fP >::m_map\fR [private]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP* \fBsc_dt::sc_global\fP< \fBT\fP >::m_proc\fR [private]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBconst\fP \fBT\fP* \fBsc_dt::sc_global\fP< \fBT\fP >::m_value_ptr\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
