.TH "sc_dt::sc_uint_bitref" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_uint_bitref
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_uint_base\&.h>\fP
.PP
Inherits \fBsc_dt::sc_uint_bitref_r\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_uint_bitref\fP (\fBconst\fP \fBsc_uint_bitref\fP &init)"
.br
.ti -1c
.RI "\fBsc_uint_bitref\fP & \fBoperator=\fP (\fBconst\fP \fBsc_uint_bitref_r\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBsc_uint_bitref\fP & \fBoperator=\fP (\fBconst\fP \fBsc_uint_bitref\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBsc_uint_bitref\fP & \fBoperator=\fP (\fBbool\fP \fBb\fP)"
.br
.ti -1c
.RI "\fBsc_uint_bitref\fP & \fBoperator&=\fP (\fBbool\fP \fBb\fP)"
.br
.ti -1c
.RI "\fBsc_uint_bitref\fP & \fBoperator|=\fP (\fBbool\fP \fBb\fP)"
.br
.ti -1c
.RI "\fBsc_uint_bitref\fP & \fBoperator^=\fP (\fBbool\fP \fBb\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBconcat_set\fP (\fBint64\fP \fBsrc\fP, int \fBlow_i\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBconcat_set\fP (\fBconst\fP \fBsc_signed\fP &\fBsrc\fP, int \fBlow_i\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBconcat_set\fP (\fBconst\fP \fBsc_unsigned\fP &\fBsrc\fP, int \fBlow_i\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBconcat_set\fP (\fBuint64\fP \fBsrc\fP, int \fBlow_i\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBscan\fP (::std::istream &\fBis\fP=::std::cin)"
.br
.in -1c

Public Member Functions inherited from \fBsc_dt::sc_uint_bitref_r\fP
.in +1c
.ti -1c
.RI "\fBsc_uint_bitref_r\fP (\fBconst\fP \fBsc_uint_bitref_r\fP &init)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_uint_bitref_r\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP int \fBconcat_length\fP (\fBbool\fP *\fBxz_present_p\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBconcat_get_ctrl\fP (\fBsc_digit\fP *\fBdst_p\fP, int \fBlow_i\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBconcat_get_data\fP (\fBsc_digit\fP *\fBdst_p\fP, int \fBlow_i\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBuint64\fP \fBconcat_get_uint64\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBlength\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBoperator uint64\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator~\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBuint64\fP \fBvalue\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBto_bool\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBprint\fP (::std::ostream &\fBos\fP=::std::cout) \fBconst\fP"
.br
.in -1c

Public Member Functions inherited from \fBsc_dt::sc_value_base\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~sc_value_base\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_uint_bitref\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBsc_dt::sc_uint_bitref_r\fP
.in +1c
.ti -1c
.RI "\fBsc_uint_bitref_r\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBinitialize\fP (\fBconst\fP \fBsc_uint_base\fP *\fBobj_p\fP, int \fBindex_\fP)"
.br
.in -1c
.SS "Static Protected Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBsc_core::sc_vpool\fP< \fBsc_uint_bitref\fP > \fBm_pool\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_uint_base\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_core::sc_vpool< sc_uint_bitref >\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBsc_dt::sc_uint_bitref_r\fP
.in +1c
.ti -1c
.RI "int \fBm_index\fP"
.br
.ti -1c
.RI "\fBsc_uint_base\fP * \fBm_obj_p\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::sc_uint_bitref::sc_uint_bitref ()\fR [inline]\fP, \fR [protected]\fP"

.SS "sc_dt::sc_uint_bitref::sc_uint_bitref (\fBconst\fP \fBsc_uint_bitref\fP & init)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBvoid\fP sc_dt::sc_uint_bitref::concat_set (\fBconst\fP \fBsc_signed\fP & src, int low_i)\fR [virtual]\fP"

.PP
Reimplemented from \fBsc_dt::sc_value_base\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP sc_dt::sc_uint_bitref::concat_set (\fBconst\fP \fBsc_unsigned\fP & src, int low_i)\fR [virtual]\fP"

.PP
Reimplemented from \fBsc_dt::sc_value_base\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP sc_dt::sc_uint_bitref::concat_set (\fBint64\fP src, int low_i)\fR [virtual]\fP"

.PP
Reimplemented from \fBsc_dt::sc_value_base\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP sc_dt::sc_uint_bitref::concat_set (\fBuint64\fP src, int low_i)\fR [virtual]\fP"

.PP
Reimplemented from \fBsc_dt::sc_value_base\fP\&.
.SS "\fBsc_uint_bitref\fP & sc_dt::sc_uint_bitref::operator&= (\fBbool\fP b)\fR [inline]\fP"

.SS "\fBsc_uint_bitref\fP & sc_dt::sc_uint_bitref::operator= (\fBbool\fP b)\fR [inline]\fP"

.SS "\fBsc_uint_bitref\fP & sc_dt::sc_uint_bitref::operator= (\fBconst\fP \fBsc_uint_bitref\fP & b)\fR [inline]\fP"

.SS "\fBsc_uint_bitref\fP & sc_dt::sc_uint_bitref::operator= (\fBconst\fP \fBsc_uint_bitref_r\fP & b)\fR [inline]\fP"

.SS "\fBsc_uint_bitref\fP & sc_dt::sc_uint_bitref::operator^= (\fBbool\fP b)\fR [inline]\fP"

.SS "\fBsc_uint_bitref\fP & sc_dt::sc_uint_bitref::operator|= (\fBbool\fP b)\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_uint_bitref::scan (::std::istream & is = \fR::std::cin\fP)"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_core::sc_vpool\fP< \fBsc_uint_bitref\fP >\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_uint_base\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_core::sc_vpool\fP<\fBsc_uint_bitref\fP> sc_dt::sc_uint_bitref::m_pool\fR [static]\fP, \fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
