.TH "sc_dt::sc_proxy_traits< sc_bitref< X > >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_proxy_traits< sc_bitref< X > >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_proxy\&.h>\fP
.PP
Inherits \fBsc_dt::sc_proxy_traits< X >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
