.TH "sc_dt::scfx_mant_ref" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::scfx_mant_ref
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scfx_mant\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscfx_mant_ref\fP ()"
.br
.ti -1c
.RI "\fBscfx_mant_ref\fP (\fBconst\fP \fBscfx_mant\fP &)"
.br
.ti -1c
.RI "\fBscfx_mant_ref\fP (\fBscfx_mant\fP *)"
.br
.ti -1c
.RI "\fBscfx_mant_ref\fP & \fBoperator=\fP (\fBconst\fP \fBscfx_mant\fP &)"
.br
.ti -1c
.RI "\fBscfx_mant_ref\fP & \fBoperator=\fP (\fBscfx_mant\fP *)"
.br
.ti -1c
.RI "\fB~scfx_mant_ref\fP ()"
.br
.ti -1c
.RI "\fBoperator scfx_mant &\fP ()"
.br
.ti -1c
.RI "\fBword\fP \fBoperator[]\fP (int)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBremove_it\fP ()"
.br
.ti -1c
.RI "\fBscfx_mant_ref\fP (\fBconst\fP \fBscfx_mant_ref\fP &)"
.br
.ti -1c
.RI "\fBscfx_mant_ref\fP & \fBoperator=\fP (\fBconst\fP \fBscfx_mant_ref\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (std::size_t \fBsz\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBscfx_mant\fP * \fBm_mant\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBm_not_const\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::scfx_mant_ref::scfx_mant_ref ()\fR [inline]\fP"

.SS "sc_dt::scfx_mant_ref::scfx_mant_ref (\fBconst\fP \fBscfx_mant\fP & mant)\fR [inline]\fP"

.SS "sc_dt::scfx_mant_ref::scfx_mant_ref (\fBscfx_mant\fP * mant)\fR [inline]\fP"

.SS "sc_dt::scfx_mant_ref::~scfx_mant_ref ()\fR [inline]\fP"

.SS "sc_dt::scfx_mant_ref::scfx_mant_ref (\fBconst\fP \fBscfx_mant_ref\fP &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP * sc_dt::scfx_mant_ref::operator \fBnew\fP (std::size_t sz)\fR [inline]\fP, \fR [private]\fP"

.SS "sc_dt::scfx_mant_ref::operator \fBscfx_mant\fP & ()\fR [inline]\fP"

.SS "\fBscfx_mant_ref\fP & sc_dt::scfx_mant_ref::operator= (\fBconst\fP \fBscfx_mant\fP & mant)\fR [inline]\fP"

.SS "\fBscfx_mant_ref\fP & sc_dt::scfx_mant_ref::operator= (\fBconst\fP \fBscfx_mant_ref\fP &)\fR [private]\fP"

.SS "\fBscfx_mant_ref\fP & sc_dt::scfx_mant_ref::operator= (\fBscfx_mant\fP * mant)\fR [inline]\fP"

.SS "\fBword\fP sc_dt::scfx_mant_ref::operator[] (int i)\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::scfx_mant_ref::remove_it ()\fR [inline]\fP, \fR [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBscfx_mant\fP* sc_dt::scfx_mant_ref::m_mant\fR [private]\fP"

.SS "\fBbool\fP sc_dt::scfx_mant_ref::m_not_const\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
