.TH "sc_dt::sc_proxy_traits< sc_concref< X, Y > >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_proxy_traits< sc_concref< X, Y > >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_proxy\&.h>\fP
.PP
Inherits \fBsc_dt::sc_mixed_proxy_traits_helper< X::traits_type, Y::traits_type >\fP\&.
.SS "Additional Inherited Members"


Public Types inherited from \fBsc_dt::sc_proxy_traits< sc_lv_base >\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_proxy_traits\fP< \fBsc_lv_base\fP > \fBtraits_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_logic_value_t\fP \fBvalue_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_logic\fP \fBbit_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv_base\fP \fBvector_type\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
