.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/old_ui_project/qt-sc/sc_debug_object.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/old_ui_project/qt-sc/sc_debug_object.h
.SH SYNOPSIS
.br
.PP
\fR#include <string>\fP
.br
\fR#include <systemc\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdebug_object\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
