.TH "sc_dt::sc_bitref_r< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_bitref_r< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_bit_proxies\&.h>\fP
.PP
Inherits \fBsc_dt::sc_bitref_conv_r< T, Traits >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP T::traits_type \fBtraits_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP traits_type::bit_type \fBbit_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP traits_type::value_type \fBvalue_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_bitref_r\fP (\fBconst\fP \fBT\fP &\fBobj_\fP, int \fBindex_\fP)"
.br
.ti -1c
.RI "\fBsc_bitref_r\fP (\fBconst\fP \fBsc_bitref_r\fP< \fBT\fP > &\fBa\fP)"
.br
.ti -1c
.RI "\fBsc_bitref_r\fP< \fBT\fP > * \fBclone\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbit_type\fP \fBoperator~\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBoperator bit_type\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvalue_type\fP \fBvalue\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_01\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBto_bool\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBchar\fP \fBto_char\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBlength\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBsize\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvalue_type\fP \fBget_bit\fP (int \fBn\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_digit\fP \fBget_word\fP (int \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_digit\fP \fBget_cword\fP (int \fBi\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBprint\fP (::std::ostream &\fBos\fP=::std::cout) \fBconst\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBT\fP & \fBm_obj\fP"
.br
.ti -1c
.RI "int \fBm_index\fP"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_bitref_r\fP ()"
.br
.ti -1c
.RI "\fBsc_bitref_r\fP< \fBT\fP > & \fBoperator=\fP (\fBconst\fP \fBsc_bitref_r\fP< \fBT\fP > &)"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_bv_base\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBsc_lv_base\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP traits_type::bit_type \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::bit_type"

.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP T::traits_type \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::traits_type"

.SS "template<\fBclass\fP \fBT\fP > \fBtypedef\fP traits_type::value_type \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::value_type"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::sc_bitref_r (\fBconst\fP \fBT\fP & obj_, int index_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::sc_bitref_r (\fBconst\fP \fBsc_bitref_r\fP< \fBT\fP > & a)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::sc_bitref_r ()\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBsc_bitref_r\fP< \fBT\fP > * \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::clone () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_bitref_r\fP< \fBT\fP >\fB::value_type\fP \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::get_bit (int n) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_digit\fP \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::get_cword (int i) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_digit\fP \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::get_word (int i) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBbool\fP \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::is_01 () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > int \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::length () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_dt::sc_bitref_r\fP< \fBT\fP >\fB::operator\fP \fBbit_type\fP () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBsc_bitref_r\fP< \fBT\fP > & \fBsc_dt::sc_bitref_r\fP< \fBT\fP >\fB::operator\fP= (\fBconst\fP \fBsc_bitref_r\fP< \fBT\fP > &)\fR [private]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBbit_type\fP \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::operator~ () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::print (::std::ostream & os = \fR::std::cout\fP) const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > int \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::size () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBbool\fP \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::to_bool () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBchar\fP \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::to_char () const\fR [inline]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBvalue_type\fP \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::value () const\fR [inline]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > \fBfriend\fP \fBclass\fP \fBsc_bv_base\fP\fR [friend]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBfriend\fP \fBclass\fP \fBsc_lv_base\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBT\fP > int \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::m_index\fR [protected]\fP"

.SS "template<\fBclass\fP \fBT\fP > \fBT\fP& \fBsc_dt::sc_bitref_r\fP< \fBT\fP >::m_obj\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
