.TH "sc_dt::sc_fxnum_subref_r" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_fxnum_subref_r
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_fxnum\&.h>\fP
.PP
Inherited by \fBsc_dt::sc_fxnum_subref\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_fxnum_subref_r\fP (\fBconst\fP \fBsc_fxnum_subref_r\fP &)"
.br
.ti -1c
.RI "\fB~sc_fxnum_subref_r\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBand_reduce\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBnand_reduce\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBor_reduce\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBnor_reduce\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBxor_reduce\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBxnor_reduce\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBlength\fP () \fBconst\fP"
.br
.ti -1c
.RI "int \fBto_int\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP int \fBto_uint\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBlong\fP \fBto_long\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBlong\fP \fBto_ulong\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBint64\fP \fBto_int64\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBuint64\fP \fBto_uint64\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP (\fBsc_numrep\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP (\fBsc_numrep\fP, \fBbool\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBoperator sc_bv_base\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBprint\fP (::std::ostream &=::std::cout) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBdump\fP (::std::ostream &=::std::cout) \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBget\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_fxnum_subref_r\fP (\fBsc_fxnum\fP &, int, int)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBsc_fxnum\fP & \fBm_num\fP"
.br
.ti -1c
.RI "int \fBm_from\fP"
.br
.ti -1c
.RI "int \fBm_to\fP"
.br
.ti -1c
.RI "\fBsc_bv_base\fP & \fBm_bv\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_fxnum\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::sc_fxnum_subref_r::sc_fxnum_subref_r (\fBsc_fxnum\fP & num_, int from_, int to_)\fR [inline]\fP, \fR [protected]\fP"

.SS "sc_dt::sc_fxnum_subref_r::sc_fxnum_subref_r (\fBconst\fP \fBsc_fxnum_subref_r\fP & a)\fR [inline]\fP"

.SS "sc_dt::sc_fxnum_subref_r::~sc_fxnum_subref_r ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP sc_dt::sc_fxnum_subref_r::and_reduce () const"

.SS "\fBvoid\fP sc_dt::sc_fxnum_subref_r::dump (::std::ostream & = \fR::std::cout\fP) const"

.SS "\fBbool\fP sc_dt::sc_fxnum_subref_r::get () const\fR [protected]\fP"

.SS "int sc_dt::sc_fxnum_subref_r::length () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::sc_fxnum_subref_r::nand_reduce () const"

.SS "\fBbool\fP sc_dt::sc_fxnum_subref_r::nor_reduce () const"

.SS "sc_dt::sc_fxnum_subref_r::operator \fBsc_bv_base\fP () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::sc_fxnum_subref_r::or_reduce () const"

.SS "\fBvoid\fP sc_dt::sc_fxnum_subref_r::print (::std::ostream & = \fR::std::cout\fP) const"

.SS "int sc_dt::sc_fxnum_subref_r::to_int () const\fR [inline]\fP"

.SS "\fBint64\fP sc_dt::sc_fxnum_subref_r::to_int64 () const\fR [inline]\fP"

.SS "\fBlong\fP sc_dt::sc_fxnum_subref_r::to_long () const\fR [inline]\fP"

.SS "\fBconst\fP std::string sc_dt::sc_fxnum_subref_r::to_string () const\fR [inline]\fP"

.SS "\fBconst\fP std::string sc_dt::sc_fxnum_subref_r::to_string (\fBsc_numrep\fP numrep) const\fR [inline]\fP"

.SS "\fBconst\fP std::string sc_dt::sc_fxnum_subref_r::to_string (\fBsc_numrep\fP numrep, \fBbool\fP w_prefix) const\fR [inline]\fP"

.SS "\fBunsigned\fP int sc_dt::sc_fxnum_subref_r::to_uint () const\fR [inline]\fP"

.SS "\fBuint64\fP sc_dt::sc_fxnum_subref_r::to_uint64 () const\fR [inline]\fP"

.SS "\fBunsigned\fP \fBlong\fP sc_dt::sc_fxnum_subref_r::to_ulong () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::sc_fxnum_subref_r::xnor_reduce () const"

.SS "\fBbool\fP sc_dt::sc_fxnum_subref_r::xor_reduce () const"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBsc_fxnum\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_bv_base\fP& sc_dt::sc_fxnum_subref_r::m_bv\fR [protected]\fP"

.SS "int sc_dt::sc_fxnum_subref_r::m_from\fR [protected]\fP"

.SS "\fBsc_fxnum\fP& sc_dt::sc_fxnum_subref_r::m_num\fR [protected]\fP"

.SS "int sc_dt::sc_fxnum_subref_r::m_to\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
