.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemC/systemc_modules/sc_debug_object.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemC/systemc_modules/sc_debug_object.h
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include <systemc\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBdebug_object\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
