.TH "sc_dt::sc_fxcast_switch" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_fxcast_switch
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_fxcast_switch\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_fxcast_switch\fP ()"
.br
.ti -1c
.RI "\fBsc_fxcast_switch\fP (\fBsc_switch\fP)"
.br
.ti -1c
.RI "\fBsc_fxcast_switch\fP (\fBconst\fP \fBsc_fxcast_switch\fP &)"
.br
.ti -1c
.RI "\fBsc_fxcast_switch\fP (\fBsc_without_context\fP)"
.br
.ti -1c
.RI "\fBsc_fxcast_switch\fP & \fBoperator=\fP (\fBconst\fP \fBsc_fxcast_switch\fP &)"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBprint\fP (::std::ostream &=::std::cout) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBdump\fP (::std::ostream &=::std::cout) \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBsc_switch\fP \fBm_sw\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBoperator==\fP (\fBconst\fP \fBsc_fxcast_switch\fP &, \fBconst\fP \fBsc_fxcast_switch\fP &)"
.br
.ti -1c
.RI "\fBbool\fP \fBoperator!=\fP (\fBconst\fP \fBsc_fxcast_switch\fP &, \fBconst\fP \fBsc_fxcast_switch\fP &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::sc_fxcast_switch::sc_fxcast_switch ()\fR [inline]\fP"

.SS "sc_dt::sc_fxcast_switch::sc_fxcast_switch (\fBsc_switch\fP sw_)\fR [inline]\fP"

.SS "sc_dt::sc_fxcast_switch::sc_fxcast_switch (\fBconst\fP \fBsc_fxcast_switch\fP & a)\fR [inline]\fP"

.SS "sc_dt::sc_fxcast_switch::sc_fxcast_switch (\fBsc_without_context\fP)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP sc_dt::sc_fxcast_switch::dump (::std::ostream & = \fR::std::cout\fP) const"

.SS "\fBsc_fxcast_switch\fP & sc_dt::sc_fxcast_switch::operator= (\fBconst\fP \fBsc_fxcast_switch\fP & a)\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_fxcast_switch::print (::std::ostream & = \fR::std::cout\fP) const"

.SS "\fBconst\fP std::string sc_dt::sc_fxcast_switch::to_string () const"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBbool\fP operator!= (\fBconst\fP \fBsc_fxcast_switch\fP & a, \fBconst\fP \fBsc_fxcast_switch\fP & b)\fR [friend]\fP"

.SS "\fBbool\fP \fBoperator\fP== (\fBconst\fP \fBsc_fxcast_switch\fP & a, \fBconst\fP \fBsc_fxcast_switch\fP & b)\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_switch\fP sc_dt::sc_fxcast_switch::m_sw\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
