.TH "sc_dt::sc_bitref_conv_r< T, Traits >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_bitref_conv_r< T, Traits >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_bit_proxies\&.h>\fP
.PP
Inherited by \fBsc_dt::sc_bitref_r< X >\fP, and \fBsc_dt::sc_bitref_r< T >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
