.TH "sc_dt::sc_proxy_traits< X >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_proxy_traits< X >
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBsc_dt::sc_proxy_traits< sc_bitref< X > >\fP, \fBsc_dt::sc_proxy_traits< sc_bitref_r< X > >\fP, \fBsc_dt::sc_proxy_traits< sc_proxy< X > >\fP, \fBsc_dt::sc_proxy_traits< sc_subref< X > >\fP, and \fBsc_dt::sc_proxy_traits< sc_subref_r< X > >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
