.TH "sc_dt::scfx_pow10" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::scfx_pow10
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <scfx_pow10\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBscfx_pow10\fP ()"
.br
.ti -1c
.RI "\fB~scfx_pow10\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBscfx_rep\fP \fBoperator()\fP (int)"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBscfx_rep\fP * \fBpos\fP (int)"
.br
.ti -1c
.RI "\fBscfx_rep\fP * \fBneg\fP (int)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBscfx_rep\fP \fBm_pos\fP [\fBSCFX_POW10_TABLE_SIZE\fP]"
.br
.ti -1c
.RI "\fBscfx_rep\fP \fBm_neg\fP [\fBSCFX_POW10_TABLE_SIZE\fP]"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::scfx_pow10::scfx_pow10 ()"

.SS "sc_dt::scfx_pow10::~scfx_pow10 ()"

.SH "Member Function Documentation"
.PP 
.SS "\fBscfx_rep\fP * sc_dt::scfx_pow10::neg (int)\fR [private]\fP"

.SS "\fBconst\fP \fBscfx_rep\fP sc_dt::scfx_pow10::operator() (int)"

.SS "\fBscfx_rep\fP * sc_dt::scfx_pow10::pos (int)\fR [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBscfx_rep\fP sc_dt::scfx_pow10::m_neg[\fBSCFX_POW10_TABLE_SIZE\fP]\fR [private]\fP"

.SS "\fBscfx_rep\fP sc_dt::scfx_pow10::m_pos[\fBSCFX_POW10_TABLE_SIZE\fP]\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
