.TH "sc_dt::sc_fxval" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_dt::sc_fxval
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_fxval\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_fxval\fP (\fBscfx_rep\fP *)"
.br
.ti -1c
.RI "\fBsc_fxval\fP (\fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_\fP \fBsc_fxval\fP (\fBint\fP, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_\fP \fBsc_fxval\fP (\fBunsigned\fP \fBint\fP, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_\fP \fBsc_fxval\fP (\fBlong\fP, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_\fP \fBsc_fxval\fP (\fBunsigned\fP \fBlong\fP, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_\fP \fBsc_fxval\fP (\fBfloat\fP, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_\fP \fBsc_fxval\fP (\fBdouble\fP, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_\fP \fBsc_fxval\fP (\fBconst\fP \fBchar\fP *, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBsc_fxval\fP (\fBconst\fP \fBsc_fxval\fP &, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBsc_fxval\fP (\fBconst\fP \fBsc_fxval_fast\fP &, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBsc_fxval\fP (\fBconst\fP \fBsc_fxnum\fP &, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBsc_fxval\fP (\fBconst\fP \fBsc_fxnum_fast\fP &, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_OTHER_\fP \fBsc_fxval\fP (\fBint64\fP, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_OTHER_\fP \fBsc_fxval\fP (\fBuint64\fP, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_OTHER_\fP \fBsc_fxval\fP (\fBconst\fP \fBsc_int_base\fP &, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_OTHER_\fP \fBsc_fxval\fP (\fBconst\fP \fBsc_uint_base\fP &, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_OTHER_\fP \fBsc_fxval\fP (\fBconst\fP \fBsc_signed\fP &, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fBSCFX_EXPLICIT_OTHER_\fP \fBsc_fxval\fP (\fBconst\fP \fBsc_unsigned\fP &, \fBsc_fxval_observer\fP *=0)"
.br
.ti -1c
.RI "\fB~sc_fxval\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBscfx_rep\fP * \fBget_rep\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBset_rep\fP (\fBscfx_rep\fP *)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_fxval\fP \fBoperator\-\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_fxval\fP & \fBoperator+\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBDECL_BIN_OP_T\fP (/, \fBint64\fP) DECL_BIN_OP_T(/"
.br
.ti -1c
.RI "\fBuint64\fP \fBDECL_BIN_OP_T\fP (/, \fBconst\fP \fBsc_int_base\fP &) DECL_BIN_OP_T(/"
.br
.ti -1c
.RI "\fBuint64\fP \fBconst\fP \fBsc_uint_base\fP & \fBDECL_BIN_OP_T\fP (/, \fBconst\fP \fBsc_signed\fP &) \fBfriend\fP \fBconst\fP \fBsc_fxval\fP \fBoperator\fP<<(\fBconst\fP \fBsc_fxval\fP &"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_fxval\fP \fBoperator++\fP (\fBint\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_fxval\fP \fBoperator\-\-\fP (\fBint\fP)"
.br
.ti -1c
.RI "\fBsc_fxval\fP & \fBoperator++\fP ()"
.br
.ti -1c
.RI "\fBsc_fxval\fP & \fBoperator\-\-\fP ()"
.br
.ti -1c
.RI "\fBoperator double\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBshort\fP \fBto_short\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBshort\fP \fBto_ushort\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBint\fP \fBto_int\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBint\fP \fBto_uint\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBlong\fP \fBto_long\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBlong\fP \fBto_ulong\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBint64\fP \fBto_int64\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBuint64\fP \fBto_uint64\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBfloat\fP \fBto_float\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBdouble\fP \fBto_double\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP (\fBsc_numrep\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP (\fBsc_numrep\fP, \fBbool\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP (\fBsc_fmt\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP (\fBsc_numrep\fP, \fBsc_fmt\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_string\fP (\fBsc_numrep\fP, \fBbool\fP, \fBsc_fmt\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_dec\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_bin\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_oct\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBto_hex\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_neg\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_zero\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_nan\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_inf\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBis_normal\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBrounding_flag\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBprint\fP (::std::ostream &=::std::cout) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBscan\fP (::std::istream &=::std::cin)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdump\fP (::std::ostream &=::std::cout) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBget_bit\fP (\fBint\fP) \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint64\fP \fBconst\fP \fBsc_uint_base\fP \fBint\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBsc_fxval_observer\fP * \fBobserver\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_fxval_observer\fP * \fBlock_observer\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBunlock_observer\fP (\fBsc_fxval_observer\fP *) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBget_type\fP (\fBint\fP &, \fBint\fP &, \fBsc_enc\fP &) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_fxval\fP \fBquantization\fP (\fBconst\fP \fBscfx_params\fP &, \fBbool\fP &) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_fxval\fP \fBoverflow\fP (\fBconst\fP \fBscfx_params\fP &, \fBbool\fP &) \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBscfx_rep\fP * \fBm_rep\fP"
.br
.ti -1c
.RI "\fBsc_fxval_observer\fP * \fBm_observer\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBsc_fxnum\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBneg\fP (\fBsc_fxval\fP &, \fBconst\fP \fBsc_fxval\fP &)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_fxval\fP \fBoperator/\fP (\fBconst\fP \fBsc_fxval\fP &, \fBconst\fP \fBsc_fxval\fP &)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_fxval\fP \fBoperator>>\fP (\fBconst\fP \fBsc_fxval\fP &, \fBint\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBlshift\fP (\fBsc_fxval\fP &, \fBconst\fP \fBsc_fxval\fP &, \fBint\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBrshift\fP (\fBsc_fxval\fP &, \fBconst\fP \fBsc_fxval\fP &, \fBint\fP)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "sc_dt::sc_fxval::sc_fxval (\fBscfx_rep\fP * a)\fR [inline]\fP, \fR [explicit]\fP"

.SS "sc_dt::sc_fxval::sc_fxval (\fBsc_fxval_observer\fP * observer_ = \fR0\fP)\fR [inline]\fP, \fR [explicit]\fP"

.SS "\fBSCFX_EXPLICIT_\fP sc_dt::sc_fxval::sc_fxval (\fBint\fP, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "\fBSCFX_EXPLICIT_\fP sc_dt::sc_fxval::sc_fxval (\fBunsigned\fP \fBint\fP, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "\fBSCFX_EXPLICIT_\fP sc_dt::sc_fxval::sc_fxval (\fBlong\fP, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "\fBSCFX_EXPLICIT_\fP sc_dt::sc_fxval::sc_fxval (\fBunsigned\fP \fBlong\fP, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "\fBSCFX_EXPLICIT_\fP sc_dt::sc_fxval::sc_fxval (\fBfloat\fP, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "\fBSCFX_EXPLICIT_\fP sc_dt::sc_fxval::sc_fxval (\fBdouble\fP, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "\fBSCFX_EXPLICIT_\fP sc_dt::sc_fxval::sc_fxval (\fBconst\fP \fBchar\fP *, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "sc_dt::sc_fxval::sc_fxval (\fBconst\fP \fBsc_fxval\fP & a, \fBsc_fxval_observer\fP * observer_ = \fR0\fP)\fR [inline]\fP"

.SS "sc_dt::sc_fxval::sc_fxval (\fBconst\fP \fBsc_fxval_fast\fP &, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "sc_dt::sc_fxval::sc_fxval (\fBconst\fP \fBsc_fxnum\fP & a, \fBsc_fxval_observer\fP * observer_ = \fR0\fP)\fR [inline]\fP"

.SS "sc_dt::sc_fxval::sc_fxval (\fBconst\fP \fBsc_fxnum_fast\fP & a, \fBsc_fxval_observer\fP * observer_ = \fR0\fP)\fR [inline]\fP"

.SS "\fBSCFX_EXPLICIT_OTHER_\fP sc_dt::sc_fxval::sc_fxval (\fBint64\fP, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "\fBSCFX_EXPLICIT_OTHER_\fP sc_dt::sc_fxval::sc_fxval (\fBuint64\fP, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "\fBSCFX_EXPLICIT_OTHER_\fP sc_dt::sc_fxval::sc_fxval (\fBconst\fP \fBsc_int_base\fP &, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "\fBSCFX_EXPLICIT_OTHER_\fP sc_dt::sc_fxval::sc_fxval (\fBconst\fP \fBsc_uint_base\fP &, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "\fBSCFX_EXPLICIT_OTHER_\fP sc_dt::sc_fxval::sc_fxval (\fBconst\fP \fBsc_signed\fP &, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "\fBSCFX_EXPLICIT_OTHER_\fP sc_dt::sc_fxval::sc_fxval (\fBconst\fP \fBsc_unsigned\fP &, \fBsc_fxval_observer\fP * = \fR0\fP)"

.SS "sc_dt::sc_fxval::~sc_fxval ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBuint64\fP sc_dt::sc_fxval::DECL_BIN_OP_T (/, \fBconst\fP \fBsc_int_base\fP &)"

.SS "\fBuint64\fP \fBconst\fP \fBsc_uint_base\fP & sc_dt::sc_fxval::DECL_BIN_OP_T (/, \fBconst\fP \fBsc_signed\fP &) const &"

.SS "sc_dt::sc_fxval::DECL_BIN_OP_T (/, \fBint64\fP)"

.SS "\fBvoid\fP sc_dt::sc_fxval::dump (::std::ostream & = \fR::std::cout\fP) const"

.SS "\fBbool\fP sc_dt::sc_fxval::get_bit (\fBint\fP i) const\fR [inline]\fP"

.SS "\fBconst\fP \fBscfx_rep\fP * sc_dt::sc_fxval::get_rep () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_fxval::get_type (\fBint\fP & wl, \fBint\fP & iwl, \fBsc_enc\fP & enc) const\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBbool\fP sc_dt::sc_fxval::is_inf () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::sc_fxval::is_nan () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::sc_fxval::is_neg () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::sc_fxval::is_normal () const\fR [inline]\fP"

.SS "\fBbool\fP sc_dt::sc_fxval::is_zero () const\fR [inline]\fP"

.SS "\fBsc_fxval_observer\fP * sc_dt::sc_fxval::lock_observer () const\fR [protected]\fP"

.SS "\fBsc_fxval_observer\fP * sc_dt::sc_fxval::observer () const\fR [inline]\fP, \fR [protected]\fP"

.SS "sc_dt::sc_fxval::operator \fBdouble\fP () const\fR [inline]\fP"

.SS "\fBconst\fP \fBsc_fxval\fP & sc_dt::sc_fxval::operator+ () const\fR [inline]\fP"

.SS "\fBsc_fxval\fP & sc_dt::sc_fxval::operator++ ()\fR [inline]\fP"

.SS "\fBconst\fP \fBsc_fxval\fP sc_dt::sc_fxval::operator++ (\fBint\fP)\fR [inline]\fP"

.SS "\fBconst\fP \fBsc_fxval\fP sc_dt::sc_fxval::operator\- () const\fR [inline]\fP"

.SS "\fBsc_fxval\fP & sc_dt::sc_fxval::operator\-\- ()\fR [inline]\fP"

.SS "\fBconst\fP \fBsc_fxval\fP sc_dt::sc_fxval::operator\-\- (\fBint\fP)\fR [inline]\fP"

.SS "\fBconst\fP \fBsc_fxval\fP sc_dt::sc_fxval::overflow (\fBconst\fP \fBscfx_params\fP & params, \fBbool\fP & o_flag) const\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP sc_dt::sc_fxval::print (::std::ostream & = \fR::std::cout\fP) const"

.SS "\fBconst\fP \fBsc_fxval\fP sc_dt::sc_fxval::quantization (\fBconst\fP \fBscfx_params\fP & params, \fBbool\fP & q_flag) const\fR [inline]\fP, \fR [protected]\fP"

.SS "\fBbool\fP sc_dt::sc_fxval::rounding_flag () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_fxval::scan (::std::istream & = \fR::std::cin\fP)"

.SS "\fBvoid\fP sc_dt::sc_fxval::set_rep (\fBscfx_rep\fP * rep_)\fR [inline]\fP"

.SS "\fBconst\fP std::string sc_dt::sc_fxval::to_bin () const"

.SS "\fBconst\fP std::string sc_dt::sc_fxval::to_dec () const"

.SS "\fBdouble\fP sc_dt::sc_fxval::to_double () const\fR [inline]\fP"

.SS "\fBfloat\fP sc_dt::sc_fxval::to_float () const\fR [inline]\fP"

.SS "\fBconst\fP std::string sc_dt::sc_fxval::to_hex () const"

.SS "\fBint\fP sc_dt::sc_fxval::to_int () const\fR [inline]\fP"

.SS "\fBint64\fP sc_dt::sc_fxval::to_int64 () const\fR [inline]\fP"

.SS "\fBlong\fP sc_dt::sc_fxval::to_long () const\fR [inline]\fP"

.SS "\fBconst\fP std::string sc_dt::sc_fxval::to_oct () const"

.SS "\fBshort\fP sc_dt::sc_fxval::to_short () const\fR [inline]\fP"

.SS "\fBconst\fP std::string sc_dt::sc_fxval::to_string () const"

.SS "\fBconst\fP std::string sc_dt::sc_fxval::to_string (\fBsc_fmt\fP) const"

.SS "\fBconst\fP std::string sc_dt::sc_fxval::to_string (\fBsc_numrep\fP) const"

.SS "\fBconst\fP std::string sc_dt::sc_fxval::to_string (\fBsc_numrep\fP, \fBbool\fP) const"

.SS "\fBconst\fP std::string sc_dt::sc_fxval::to_string (\fBsc_numrep\fP, \fBbool\fP, \fBsc_fmt\fP) const"

.SS "\fBconst\fP std::string sc_dt::sc_fxval::to_string (\fBsc_numrep\fP, \fBsc_fmt\fP) const"

.SS "\fBunsigned\fP \fBint\fP sc_dt::sc_fxval::to_uint () const\fR [inline]\fP"

.SS "\fBuint64\fP sc_dt::sc_fxval::to_uint64 () const\fR [inline]\fP"

.SS "\fBunsigned\fP \fBlong\fP sc_dt::sc_fxval::to_ulong () const\fR [inline]\fP"

.SS "\fBunsigned\fP \fBshort\fP sc_dt::sc_fxval::to_ushort () const\fR [inline]\fP"

.SS "\fBvoid\fP sc_dt::sc_fxval::unlock_observer (\fBsc_fxval_observer\fP *) const\fR [protected]\fP"

.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBvoid\fP lshift (\fBsc_fxval\fP & c, \fBconst\fP \fBsc_fxval\fP & a, \fBint\fP b)\fR [friend]\fP"

.SS "\fBvoid\fP neg (\fBsc_fxval\fP & c, \fBconst\fP \fBsc_fxval\fP & a)\fR [friend]\fP"

.SS "\fBconst\fP \fBsc_fxval\fP \fBoperator\fP/ (\fBconst\fP \fBsc_fxval\fP & a, \fBconst\fP \fBsc_fxval\fP & b)\fR [friend]\fP"

.SS "\fBconst\fP \fBsc_fxval\fP \fBoperator\fP>> (\fBconst\fP \fBsc_fxval\fP & a, \fBint\fP b)\fR [friend]\fP"

.SS "\fBvoid\fP rshift (\fBsc_fxval\fP & c, \fBconst\fP \fBsc_fxval\fP & a, \fBint\fP b)\fR [friend]\fP"

.SS "\fBfriend\fP \fBclass\fP \fBsc_fxnum\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBuint64\fP \fBconst\fP \fBsc_uint_base\fP sc_dt::sc_fxval::int"

.SS "\fBsc_fxval_observer\fP* sc_dt::sc_fxval::m_observer\fR [mutable]\fP, \fR [private]\fP"

.SS "\fBscfx_rep\fP* sc_dt::sc_fxval::m_rep\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
