.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_externs.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_externs.h
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsc_main\fP (int \fBargc\fP, \fBchar\fP *\fBargv\fP[])"
.br
.ti -1c
.RI "int \fBsc_core::sc_elab_and_sim\fP (int \fBargc\fP, \fBchar\fP *\fBargv\fP[])"
.br
.ti -1c
.RI "int \fBsc_core::sc_argc\fP ()"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP *\fBconst\fP * \fBsc_core::sc_argv\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int sc_main (int argc, \fBchar\fP * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
