.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_except.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_except.h
.SH SYNOPSIS
.br
.PP
\fR#include <exception>\fP
.br
\fR#include 'sysc/kernel/sc_cmnhdr\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_user\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_halt\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_kill\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_unwind_exception\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBsc_core::sc_thread_cor_fn\fP (\fBvoid\fP *arg)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_report\fP * \fBsc_core::sc_handle_exception\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
