.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_event.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_event.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_cmnhdr\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_kernel_ids\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_simcontext\&.h'\fP
.br
\fR#include 'sysc/communication/sc_writer_policy\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_event_expr< T >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_event_list\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_event_and_list\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_event_or_list\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_event\fP"
.br
.ti -1c
.RI "struct \fBsc_core::sc_event::kernel_tag\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_event_timed\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_event_expr\fP< \fBsc_event_and_list\fP > \fBsc_core::sc_event_and_expr\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_event_expr\fP< \fBsc_event_or_list\fP > \fBsc_core::sc_event_or_expr\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_API\fP int \fBsc_core::sc_notify_time_compare\fP (\fBconst\fP \fBvoid\fP *, \fBconst\fP \fBvoid\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_core::notify\fP (\fBsc_event\fP &\fBe\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_core::notify\fP (\fBconst\fP \fBsc_time\fP &t, \fBsc_event\fP &\fBe\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_core::notify\fP (\fBdouble\fP v, \fBsc_time_unit\fP \fBtu\fP, \fBsc_event\fP &\fBe\fP)"
.br
.ti -1c
.RI "\fBsc_event_or_expr\fP \fBsc_core::operator|\fP (\fBsc_event_or_expr\fP \fBexpr\fP, \fBsc_event\fP \fBconst\fP &\fBe\fP)"
.br
.ti -1c
.RI "\fBsc_event_or_expr\fP \fBsc_core::operator|\fP (\fBsc_event_or_expr\fP \fBexpr\fP, \fBsc_event_or_list\fP \fBconst\fP &\fBel\fP)"
.br
.ti -1c
.RI "\fBsc_event_and_expr\fP \fBsc_core::operator&\fP (\fBsc_event_and_expr\fP \fBexpr\fP, \fBsc_event\fP \fBconst\fP &\fBe\fP)"
.br
.ti -1c
.RI "\fBsc_event_and_expr\fP \fBsc_core::operator&\fP (\fBsc_event_and_expr\fP \fBexpr\fP, \fBsc_event_and_list\fP \fBconst\fP &\fBel\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
