.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/sc_fx_ids.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/sc_fx_ids.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/utils/sc_report\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_DEFINE_MESSAGE\fP(id,  \fBunused1\fP,  \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_INVALID_WL_\fP, 300, 'total \fBwordlength\fP <= 0 \fBis\fP \fBnot\fP \fBvalid'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_INVALID_N_BITS_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_DEFINE_MESSAGE(id, \fBunused1\fP, \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"

.SH "Function Documentation"
.PP 
.SS "SC_DEFINE_MESSAGE (\fBSC_ID_INVALID_WL_\fP, 300, 'total \fBwordlength\fP <= 0 \fBis\fP \fBnot\fP \fBvalid'\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
