.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_fifo_ports.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_fifo_ports.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/communication/sc_port\&.h'\fP
.br
\fR#include 'sysc/communication/sc_fifo_ifs\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_fifo_in< T >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_fifo_out< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
