.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/sc_fxnum_observer.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/sc_fxnum_observer.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/datatypes/fx/sc_fxdefs\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_dt::sc_fxnum_observer\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_fxnum_fast_observer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_dt\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_FXNUM_OBSERVER_CONSTRUCT_\fP(\fBobject\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_FXNUM_OBSERVER_DESTRUCT_\fP(\fBobject\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_FXNUM_OBSERVER_READ_\fP(\fBobject\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_FXNUM_OBSERVER_WRITE_\fP(\fBobject\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_FXNUM_OBSERVER_DEFAULT_\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_FXNUM_FAST_OBSERVER_CONSTRUCT_\fP(\fBobject\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_FXNUM_FAST_OBSERVER_DESTRUCT_\fP(\fBobject\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_FXNUM_FAST_OBSERVER_READ_\fP(\fBobject\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_FXNUM_FAST_OBSERVER_WRITE_\fP(\fBobject\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_FXNUM_FAST_OBSERVER_DEFAULT_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_FXNUM_FAST_OBSERVER_CONSTRUCT_(\fBobject\fP)"

.SS "#\fBdefine\fP SC_FXNUM_FAST_OBSERVER_DEFAULT_"

.SS "#\fBdefine\fP SC_FXNUM_FAST_OBSERVER_DESTRUCT_(\fBobject\fP)"

.SS "#\fBdefine\fP SC_FXNUM_FAST_OBSERVER_READ_(\fBobject\fP)"

.SS "#\fBdefine\fP SC_FXNUM_FAST_OBSERVER_WRITE_(\fBobject\fP)"

.SS "#\fBdefine\fP SC_FXNUM_OBSERVER_CONSTRUCT_(\fBobject\fP)"

.SS "#\fBdefine\fP SC_FXNUM_OBSERVER_DEFAULT_"

.SS "#\fBdefine\fP SC_FXNUM_OBSERVER_DESTRUCT_(\fBobject\fP)"

.SS "#\fBdefine\fP SC_FXNUM_OBSERVER_READ_(\fBobject\fP)"

.SS "#\fBdefine\fP SC_FXNUM_OBSERVER_WRITE_(\fBobject\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
