.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_fifo.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_fifo.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/communication/sc_communication_ids\&.h'\fP
.br
\fR#include 'sysc/communication/sc_prim_channel\&.h'\fP
.br
\fR#include 'sysc/communication/sc_fifo_ifs\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_event\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_simcontext\&.h'\fP
.br
\fR#include 'sysc/tracing/sc_trace\&.h'\fP
.br
\fR#include <typeinfo>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_fifo< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > inline::std::ostream & \fBsc_core::operator<<\fP (::std::ostream &\fBos\fP, \fBconst\fP \fBsc_fifo\fP< \fBT\fP > &\fBa\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
