.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/sc_fxcast_switch.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/sc_fxcast_switch.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/datatypes/fx/sc_context\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_dt::sc_fxcast_switch\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_dt\fP"
.br
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_context\fP< \fBsc_fxcast_switch\fP > \fBsc_dt::sc_fxcast_context\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_fxcast_switch\fP &\fBa\fP, \fBconst\fP \fBsc_fxcast_switch\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_fxcast_switch\fP &\fBa\fP, \fBconst\fP \fBsc_fxcast_switch\fP &\fBb\fP)"
.br
.ti -1c
.RI "inline::std::ostream & \fBsc_dt::operator<<\fP (::std::ostream &\fBos\fP, \fBconst\fP \fBsc_fxcast_switch\fP &\fBa\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSC_API_TEMPLATE_DECL_\fP \fBsc_dt::sc_global< sc_fxcast_switch >\fP"
.br
.ti -1c
.RI "\fBSC_API_TEMPLATE_DECL_\fP \fBsc_dt::sc_context< sc_fxcast_switch >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
