.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemc_modules/sc_flexint.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemc_modules/sc_flexint.h \- FlexInt SystemC module\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <stdint\&.h>\fP
.br
\fR#include <systemc\&.h>\fP
.br
\fR#include <type_traits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSyscFlexInt< CLKEDGE, FLEXINT >\fP"
.br
.ti -1c
.RI "struct \fBis_boolean< typename >\fP"
.br
.ti -1c
.RI "struct \fBis_boolean< bool >\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBDEFAULT_CLKEDGE\fP   \fBtrue\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDEFAULT_FLEXINT\fP   \fBRST_LOW_ENA_HIGH\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBenum\fP \fBflexinterface_e\fP \fBflexinterface_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBflexinterface_e\fP { \fBNO_RST_NO_ENA\fP = 0x00, \fBNO_RST_ENA_HIGH\fP = 0x01, \fBNO_RST_ENA_LOW\fP = 0x02, \fBRST_HIGH_NO_ENA\fP = 0x10, \fBRST_HIGH_ENA_HIGH\fP = 0x11, \fBRST_HIGH_ENA_LOW\fP = 0x12, \fBRST_LOW_NO_ENA\fP = 0x20, \fBRST_LOW_ENA_HIGH\fP = 0x21, \fBRST_LOW_ENA_LOW\fP = 0x22 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
FlexInt SystemC module\&. 

This file contains the FlexInt SystemC module\&.
.PP
The FlexInt module is a SystemC module that provides a flexible interface for the reset and enable signals of a module\&. The reset and enable signals can be active high or active low, and can be synchronous or asynchronous\&. The module can be configured to use the reset and enable signals or not, and can be configured to use the rising edge or falling edge of the clock signal\&.
.PP
The module is a template class that can be instantiated with the following parameters:
.IP "\(bu" 2
CLKEDGE: boolean value that specifies the clock edge to use (true for rising edge, false for falling edge)\&. Default value is true\&.
.IP "  \(bu" 4
FLEXINT: flexinterface_t value that specifies the reset and enable signals configuration\&. Default value is RST_LOW_ENA_HIGH\&. 
.PP

.PP

.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP DEFAULT_CLKEDGE   \fBtrue\fP"

.SS "#\fBdefine\fP DEFAULT_FLEXINT   \fBRST_LOW_ENA_HIGH\fP"

.SH "Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBenum\fP \fBflexinterface_e\fP \fBflexinterface_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "\fBenum\fP \fBflexinterface_e\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fINO_RST_NO_ENA \fP\fP
.TP
\fB\fINO_RST_ENA_HIGH \fP\fP
.TP
\fB\fINO_RST_ENA_LOW \fP\fP
.TP
\fB\fIRST_HIGH_NO_ENA \fP\fP
.TP
\fB\fIRST_HIGH_ENA_HIGH \fP\fP
.TP
\fB\fIRST_HIGH_ENA_LOW \fP\fP
.TP
\fB\fIRST_LOW_NO_ENA \fP\fP
.TP
\fB\fIRST_LOW_ENA_HIGH \fP\fP
.TP
\fB\fIRST_LOW_ENA_LOW \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
