.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemc_modules/sc_gates.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemc_modules/sc_gates.h
.SH SYNOPSIS
.br
.PP
\fR#include <systemc\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSyscLogicGate< N, W >\fP"
.br
.RI "The SyscLogicGate::sc_core::sc_module class\&. "
.ti -1c
.RI "class \fBSyscAnd< N, W >\fP"
.br
.RI "The \fBSyscAnd\fP class\&. "
.ti -1c
.RI "class \fBSyscNand< N, W >\fP"
.br
.RI "The \fBSyscNand\fP class\&. "
.ti -1c
.RI "class \fBSyscOr< N, W >\fP"
.br
.RI "The \fBSyscOr\fP class\&. "
.ti -1c
.RI "class \fBSyscNor< N, W >\fP"
.br
.RI "The \fBSyscNor\fP class\&. "
.ti -1c
.RI "class \fBSyscXor< N, W >\fP"
.br
.RI "The \fBSyscXor\fP class\&. "
.ti -1c
.RI "class \fBSyscXnor< N, W >\fP"
.br
.RI "The \fBSyscXnor\fP class\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
