.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemc_modules/sc_gates_pv.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemc_modules/sc_gates_pv.h
.SH SYNOPSIS
.br
.PP
\fR#include <QtXml>\fP
.br
\fR#include <systemc\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSyscLogicGate_pv< N, W >\fP"
.br
.RI "The SyscLogicGate_pv::sc_core::sc_module class\&. "
.ti -1c
.RI "class \fBSyscAnd_pv< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscNand_pv< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscOr_pv< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscNor_pv< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscXor_pv< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscXnor_pv< N, W >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
