.TH "systemc_modules/sc_gates.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
systemc_modules/sc_gates.h
.SH SYNOPSIS
.br
.PP
\fR#include <systemc\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSyscLogicGate< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscAnd< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscNand< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscOr< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscNor< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscXor< N, W >\fP"
.br
.ti -1c
.RI "class \fBSyscXnor< N, W >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
