.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/int/sc_int_ids.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/int/sc_int_ids.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/utils/sc_report\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_DEFINE_MESSAGE\fP(id,  \fBunused1\fP,  \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP \fBchar\fP \fBSC_ID_REGISTER_ID_FAILED_\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_DEFINE_MESSAGE(id, \fBunused1\fP, \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"

.SH "Variable Documentation"
.PP 
.SS "\fBSC_API\fP \fBconst\fP \fBchar\fP SC_ID_REGISTER_ID_FAILED_[]\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
