.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_kernel_ids.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_kernel_ids.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/utils/sc_report\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_DEFINE_MESSAGE\fP(id,  \fBunused1\fP,  \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_NO_BOOL_RETURNED_\fP, 500, 'operator \fBdoes\fP \fBnot\fP \fBreturn\fP \fBboolean'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_NO_INT_RETURNED_\fP"
.br
.ti -1c
.RI "\fBoperator does not return int') SC_DEFINE_MESSAGE\fP (\fBSC_ID_NO_SC_LOGIC_RETURNED_\fP, 502, 'operator \fBdoes\fP \fBnot\fP \fBreturn\fP \fBsc_logic'\fP) \fBSC_DEFINE_MESSAGE\fP(\fBSC_ID_OPERAND_NOT_SC_LOGIC_\fP"
.br
.ti -1c
.RI "\fBoperand\fP \fBis\fP \fBnot\fP sc_logic \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_OPERAND_NOT_BOOL_\fP, 504, 'operand \fBis\fP \fBnot\fP \fBbool'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_INSTANCE_EXISTS_\fP"
.br
.ti -1c
.RI "\fBoperand\fP \fBis\fP \fBnot\fP sc_logic \fBobject\fP \fBalready\fP \fBexists\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_ILLEGAL_CHARACTERS_\fP, 506, 'illegal \fBcharacters'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_VC6_PROCESS_HELPER_\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBoperand\fP \fBis\fP \fBnot\fP sc_logic \fBobject\fP \fBalready\fP \fBexists\fP \fBinternal\fP \fBerror\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_DEFINE_MESSAGE(id, \fBunused1\fP, \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"

.SH "Function Documentation"
.PP 
.SS "\fBoperator\fP \fBdoes\fP \fBnot\fP \fBreturn\fP \fBint'\fP) \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_NO_SC_LOGIC_RETURNED_\fP, 502, 'operator \fBdoes\fP \fBnot\fP \fBreturn\fP \fBsc_logic'\fP)"

.SS "\fBoperand\fP \fBis\fP \fBnot\fP sc_logic \fBobject\fP \fBalready\fP \fBexists\fP SC_DEFINE_MESSAGE (\fBSC_ID_ILLEGAL_CHARACTERS_\fP, 506, 'illegal \fBcharacters'\fP)"

.SS "SC_DEFINE_MESSAGE (\fBSC_ID_NO_BOOL_RETURNED_\fP, 500, 'operator \fBdoes\fP \fBnot\fP \fBreturn\fP \fBboolean'\fP)"

.SS "\fBoperand\fP \fBis\fP \fBnot\fP sc_logic SC_DEFINE_MESSAGE (\fBSC_ID_OPERAND_NOT_BOOL_\fP, 504, 'operand \fBis\fP \fBnot\fP \fBbool'\fP)"

.SH "Variable Documentation"
.PP 
.SS "\fBoperand\fP \fBis\fP \fBnot\fP sc_logic \fBobject\fP \fBalready\fP \fBexists\fP \fBinternal\fP error"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
