.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemc_modules/sc_main.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemc_modules/sc_main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <pthread\&.h>\fP
.br
\fR#include <systemc\&.h>\fP
.br
\fR#include 'sc_main\&.h'\fP
.br
\fR#include 'sc_run\&.h'\fP
.br
\fR#include 'sc_qt_adaptor\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBscSimMain\fP (\fBvoid\fP *\fBargs\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBsc_main\fP (\fBint\fP \fBargc\fP, \fBchar\fP *\fBargv\fP[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP sc_main (\fBint\fP argc, \fBchar\fP * argv[])"

.SS "\fBvoid\fP * scSimMain (\fBvoid\fP * args)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
