.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/utils/sc_machine.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/utils/sc_machine.h
.SH SYNOPSIS
.br
.PP
\fR#include <climits>\fP
.br
\fR#include 'sysc/packages/boost/detail/endian\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_LONG_64\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_LONG_64"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
