.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/int/sc_nbexterns.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/int/sc_nbexterns.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/datatypes/int/sc_nbutils\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_dt\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBsc_dt::add_on_help\fP (\fBsmall_type\fP &\fBus\fP, int \fBunb\fP, int \fBund\fP, \fBsc_digit\fP *\fBud\fP, \fBsmall_type\fP \fBvs\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_dt::mul_on_help_signed\fP (\fBsmall_type\fP &\fBus\fP, int \fBunb\fP, int \fBund\fP, \fBsc_digit\fP *\fBud\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_dt::div_on_help_signed\fP (\fBsmall_type\fP &\fBus\fP, int \fBunb\fP, int \fBund\fP, \fBsc_digit\fP *\fBud\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_dt::mod_on_help_signed\fP (\fBsmall_type\fP &\fBus\fP, int \fBunb\fP, int \fBund\fP, \fBsc_digit\fP *\fBud\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_dt::mul_on_help_unsigned\fP (\fBsmall_type\fP &\fBus\fP, int \fBunb\fP, int \fBund\fP, \fBsc_digit\fP *\fBud\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_dt::div_on_help_unsigned\fP (\fBsmall_type\fP &\fBus\fP, int \fBunb\fP, int \fBund\fP, \fBsc_digit\fP *\fBud\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_dt::mod_on_help_unsigned\fP (\fBsmall_type\fP &\fBus\fP, int \fBunb\fP, int \fBund\fP, \fBsc_digit\fP *\fBud\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_dt::and_on_help\fP (\fBsmall_type\fP \fBus\fP, int \fBunb\fP, int \fBund\fP, \fBsc_digit\fP *\fBud\fP, \fBsmall_type\fP \fBvs\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_dt::or_on_help\fP (\fBsmall_type\fP \fBus\fP, int \fBunb\fP, int \fBund\fP, \fBsc_digit\fP *\fBud\fP, \fBsmall_type\fP \fBvs\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_dt::xor_on_help\fP (\fBsmall_type\fP \fBus\fP, int \fBunb\fP, int \fBund\fP, \fBsc_digit\fP *\fBud\fP, \fBsmall_type\fP \fBvs\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
