.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_object.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_object.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_attribute\&.h'\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_object\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsc_object\fP * \fBsc_core::sc_get_parent\fP (\fBconst\fP \fBsc_object\fP *\fBobj_p\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBSC_API\fP \fBsc_core::sc_module\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBSC_API\fP \fBsc_core::sc_simcontext\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBSC_API\fP \fBsc_core::sc_trace_file\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBSC_API\fP \fBsc_core::sc_trace_file_base\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP \fBsc_core::SC_HIERARCHY_CHAR\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_core::sc_enable_name_checking\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
