.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_phase_callback_registry.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_phase_callback_registry.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_simcontext\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_object_int\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_status\&.h'\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_phase_callback_registry\fP"
.br
.ti -1c
.RI "struct \fBsc_core::sc_phase_callback_registry::entry\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_HAS_PHASE_CALLBACKS_\fP   0"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_HAS_PHASE_CALLBACKS_   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
