.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_process_handle.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_process_handle.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_module\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_process_handle\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBsc_core::operator==\fP (\fBconst\fP \fBsc_process_handle\fP &left, \fBconst\fP \fBsc_process_handle\fP &right)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_core::operator!=\fP (\fBconst\fP \fBsc_process_handle\fP &left, \fBconst\fP \fBsc_process_handle\fP &right)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_core::operator<\fP (\fBconst\fP \fBsc_process_handle\fP &left, \fBconst\fP \fBsc_process_handle\fP &right)"
.br
.ti -1c
.RI "\fBsc_process_handle\fP \fBsc_core::sc_get_last_created_process_handle\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
