.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_port.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_port.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/communication/sc_communication_ids\&.h'\fP
.br
\fR#include 'sysc/communication/sc_interface\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_event\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_object\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_process\&.h'\fP
.br
\fR#include 'sysc/utils/sc_typeindex\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_port_base\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_port_registry\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_port_b< IF >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_port< IF, N, P >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_VIRTUAL_\fP   \fBvirtual\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBsc_core::sc_port_policy\fP { \fBsc_core::SC_ONE_OR_MORE_BOUND\fP, \fBsc_core::SC_ZERO_OR_MORE_BOUND\fP, \fBsc_core::SC_ALL_BOUND\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_warn_port_constructor\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_VIRTUAL_   \fBvirtual\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
