.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_runnable_int.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_runnable_int.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_runnable\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_method_process\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_thread_process\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBDEBUG_MSG\fP(\fBNAME\fP,  \fBP\fP,  \fBMSG\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_NO_METHODS\fP   ((sc_method_handle)0xdb)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_NO_THREADS\fP   ((sc_thread_handle)0xdb)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP DEBUG_MSG(\fBNAME\fP, \fBP\fP, \fBMSG\fP)"

.SS "#\fBdefine\fP SC_NO_METHODS   ((sc_method_handle)0xdb)"

.SS "#\fBdefine\fP SC_NO_THREADS   ((sc_thread_handle)0xdb)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
