.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/utils/sc_report_handler.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/utils/sc_report_handler.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsc_core::sc_msg_def\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_report_handler\fP"
.br
.ti -1c
.RI "struct \fBsc_core::sc_report_handler::msg_def_items\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBvoid\fP(* \fBsc_core::sc_report_handler_proc\fP) (\fBconst\fP \fBsc_report\fP &, \fBconst\fP \fBsc_actions\fP &)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_core::sc_report_close_default_log\fP ()"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
