.TH "systemc_modules/sc_reg.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
systemc_modules/sc_reg.h
.SH SYNOPSIS
.br
.PP
\fR#include <systemc\&.h>\fP
.br
\fR#include 'sc_flexint\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSyscReg< W, CLKEDGE, FLEXINT >\fP"
.br
.ti -1c
.RI "class \fBSyscCnt< W, CLKEDGE, FLEXINT >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
