.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/old_ui_project/qt-sc/sc_run.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/old_ui_project/qt-sc/sc_run.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'sc_run\&.h'\fP
.br
\fR#include <systemc\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsc_getRunResultFromUI\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_setRunFromUI\fP (\fBsc_thread_run_t\fP *\fBtheRun\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_setRunResult\fP (int \fBtheResult\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_setReportFromSC\fP (std::vector< std::string > &rep)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_setHierarchyFromSC\fP (std::vector< std::string > &\fBhier\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_NotifyUIFromSC\fP (int \fBnewState\fP)"
.br
.ti -1c
.RI "int \fBsc_waitStateChange\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBsc_StartTransactionFromUI\fP ()"
.br
.ti -1c
.RI "int \fBsc_NotifyTransactionFromUI\fP ()"
.br
.ti -1c
.RI "int \fBsc_EndTransactionFromUI\fP ()"
.br
.ti -1c
.RI "int \fBsc_waitStateChangeFromUI\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "int \fBsc_NewStateFromUI\fP (int \fBnewState\fP)"
.br
.ti -1c
.RI "std::vector< std::string > \fBsc_getHierarchyFromUI\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_setTraceListFromUI\fP (std::vector< std::string > &\fBtl\fP)"
.br
.ti -1c
.RI "std::vector< std::string > \fBsc_getReportFromUI\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int sc_EndTransactionFromUI ()"

.SS "std::vector< std::string > sc_getHierarchyFromUI ()"

.SS "std::vector< std::string > sc_getReportFromUI ()"

.SS "int sc_getRunResultFromUI (\fBvoid\fP)"

.SS "int sc_NewStateFromUI (int newState)"

.SS "int sc_NotifyTransactionFromUI ()"

.SS "\fBvoid\fP sc_NotifyUIFromSC (int newState)"

.SS "\fBvoid\fP sc_setHierarchyFromSC (std::vector< std::string > & hier)"

.SS "\fBvoid\fP sc_setReportFromSC (std::vector< std::string > & rep)"

.SS "\fBvoid\fP sc_setRunFromUI (\fBsc_thread_run_t\fP * theRun)"

.SS "\fBvoid\fP sc_setRunResult (int theResult)"

.SS "\fBvoid\fP sc_setTraceListFromUI (std::vector< std::string > & tl)"

.SS "int sc_StartTransactionFromUI ()"

.SS "int sc_waitStateChange (\fBvoid\fP)"

.SS "int sc_waitStateChangeFromUI (\fBvoid\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
