.TH "systemc_modules/sc_rst.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
systemc_modules/sc_rst.h
.SH SYNOPSIS
.br
.PP
\fR#include <systemc\&.h>\fP
.br
\fR#include 'sc_config\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_MODULE\fP (\fBscRst\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "SC_MODULE (\fBscRst\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
