.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemc_modules/sc_run.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemc_modules/sc_run.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'sc_run\&.h'\fP
.br
\fR#include <systemc\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBint\fP \fBsc_getRunResultFromUI\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_setRunFromUI\fP (\fBsc_thread_run_t\fP *\fBtheRun\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_setRunResult\fP (\fBint\fP \fBtheResult\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_setReportFromSC\fP (std::vector< std::string > &\fBrep\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_setHierarchyFromSC\fP (std::vector< std::string > &\fBhier\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_NotifyUIFromSC\fP (\fBint\fP \fBnewState\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBsc_waitStateChange\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBsc_StartTransactionFromUI\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBsc_NotifyTransactionFromUI\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBsc_EndTransactionFromUI\fP ()"
.br
.ti -1c
.RI "\fBint\fP \fBsc_waitStateChangeFromUI\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBint\fP \fBsc_NewStateFromUI\fP (\fBint\fP \fBnewState\fP)"
.br
.ti -1c
.RI "std::vector< std::string > \fBsc_getHierarchyFromUI\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_setTraceListFromUI\fP (std::vector< std::string > &\fBtl\fP)"
.br
.ti -1c
.RI "std::vector< std::string > \fBsc_getReportFromUI\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBint\fP sc_EndTransactionFromUI ()"

.SS "std::vector< std::string > sc_getHierarchyFromUI ()"

.SS "std::vector< std::string > sc_getReportFromUI ()"

.SS "\fBint\fP sc_getRunResultFromUI (\fBvoid\fP)"

.SS "\fBint\fP sc_NewStateFromUI (\fBint\fP newState)"

.SS "\fBint\fP sc_NotifyTransactionFromUI ()"

.SS "\fBvoid\fP sc_NotifyUIFromSC (\fBint\fP newState)"

.SS "\fBvoid\fP sc_setHierarchyFromSC (std::vector< std::string > & hier)"

.SS "\fBvoid\fP sc_setReportFromSC (std::vector< std::string > & rep)"

.SS "\fBvoid\fP sc_setRunFromUI (\fBsc_thread_run_t\fP * theRun)"

.SS "\fBvoid\fP sc_setRunResult (\fBint\fP theResult)"

.SS "\fBvoid\fP sc_setTraceListFromUI (std::vector< std::string > & tl)"

.SS "\fBint\fP sc_StartTransactionFromUI ()"

.SS "\fBint\fP sc_waitStateChange (\fBvoid\fP)"

.SS "\fBint\fP sc_waitStateChangeFromUI (\fBvoid\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
