.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/utils/sc_string_view.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/utils/sc_string_view.h
.SH SYNOPSIS
.br
.PP
\fR#include <sysc/kernel/sc_cmnhdr\&.h>\fP
.br
\fR#include <sysc/packages/boost/utility/string_view\&.hpp>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_zstring_view\fP"
.br
.RI "non-owning, const-ref to null-terminated string (implementation-defined) "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_STRING_VIEW_NS_\fP   sc_boost"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP SC_STRING_VIEW_NS_::string_view \fBsc_core::sc_string_view\fP"
.br
.RI "non-owning, constant reference to a string (implementation-defined) "
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_STRING_VIEW_NS_   sc_boost"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
