.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_signal_ifs.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_signal_ifs.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/communication/sc_interface\&.h'\fP
.br
\fR#include 'sysc/communication/sc_writer_policy\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_signal_in_if< T >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_signal_in_if< bool >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_signal_in_if< sc_dt::sc_logic >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_signal_write_if< T >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_signal_inout_if< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_dt\fP"
.br
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBsc_signal_out_if\fP   sc_signal_inout_if"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBSC_API\fP \fBsc_dt::sc_logic\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP sc_signal_out_if   sc_signal_inout_if"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
