.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_signal_ports.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_signal_ports.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/communication/sc_event_finder\&.h'\fP
.br
\fR#include 'sysc/communication/sc_port\&.h'\fP
.br
\fR#include 'sysc/communication/sc_signal_ifs\&.h'\fP
.br
\fR#include 'sysc/datatypes/bit/sc_logic\&.h'\fP
.br
\fR#include 'sysc/tracing/sc_trace\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsc_core::sc_trace_params\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_in< T >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_in< bool >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_in< sc_dt::sc_logic >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_inout< T >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_inout< bool >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_inout< sc_dt::sc_logic >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_out< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_VIRTUAL_\fP   \fBvirtual\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP std::vector< \fBsc_trace_params\fP * > \fBsc_core::sc_trace_params_vec\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_deprecated_add_trace\fP ()"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > ::std::ostream & \fBsc_core::operator<<\fP (::std::ostream &\fBos\fP, \fBconst\fP \fBsc_in\fP< \fBT\fP > &\fBa\fP)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > ::std::ostream & \fBsc_core::operator<<\fP (::std::ostream &\fBos\fP, \fBconst\fP \fBsc_inout\fP< \fBT\fP > &\fBa\fP)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_trace\fP (\fBsc_trace_file\fP *tf, \fBconst\fP \fBsc_in\fP< \fBT\fP > &port, \fBconst\fP std::string &name)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_trace\fP (\fBsc_trace_file\fP *tf, \fBconst\fP \fBsc_inout\fP< \fBT\fP > &port, \fBconst\fP std::string &name)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSC_API_TEMPLATE_DECL_\fP \fBsc_core::sc_port< sc_signal_in_if< bool >, 1, SC_ONE_OR_MORE_BOUND >\fP"
.br
.ti -1c
.RI "\fBSC_API_TEMPLATE_DECL_\fP \fBsc_core::sc_port< sc_signal_inout_if< bool >, 1, SC_ONE_OR_MORE_BOUND >\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_VIRTUAL_   \fBvirtual\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
