.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_spawn.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_spawn.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_process_handle\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_spawn_options\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_spawn_object< T >\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_spawn_object_v< T >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBsc_process_handle\fP \fBsc_core::sc_spawn\fP (\fBT\fP \fBobject\fP, \fBconst\fP \fBchar\fP *\fBname_p\fP=0, \fBconst\fP \fBsc_spawn_options\fP *\fBopt_p\fP=0)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBsc_process_handle\fP \fBsc_core::sc_spawn\fP (\fBtypename\fP T::result_type *\fBr_p\fP, \fBT\fP \fBobject\fP, \fBconst\fP \fBchar\fP *\fBname_p\fP=0, \fBconst\fP \fBsc_spawn_options\fP *\fBopt_p\fP=0)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
