.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_simcontext_int.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_simcontext_int.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_simcontext\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_runnable\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_runnable_int\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBDEBUG_MSG\fP(\fBNAME\fP,  \fBP\fP,  \fBMSG\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBsc_core::sc_get_current_process_name\fP (\fBconst\fP \fBchar\fP *\fBif_empty\fP=\fBNULL\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_defunct_process_function\fP (\fBsc_module\fP *)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP DEBUG_MSG(\fBNAME\fP, \fBP\fP, \fBMSG\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
