.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/utils/sc_string.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/utils/sc_string.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/utils/sc_report\&.h'\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_dt::sc_string_old\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_dt\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsc_string_old\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBchar\fP *s, \fBconst\fP \fBsc_string_old\fP &t)"
.br
.ti -1c
.RI "inline::std::ostream & \fBsc_dt::operator<<\fP (::std::ostream &\fBos\fP, \fBconst\fP \fBsc_string_old\fP &\fBa\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
