.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/tracing/sc_tracing_ids.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/tracing/sc_tracing_ids.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_cmnhdr\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_DEFINE_MESSAGE\fP(id,  \fBunused1\fP,  \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_TRACING_FOPEN_FAILED_\fP, 701, 'cannot \fBopen\fP trace file \fBfor\fP \fBwriting'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_TRACING_TIMESCALE_DEFAULT_\fP"
.br
.ti -1c
.RI "\fBdefault\fP \fBtimescale\fP unit used \fBfor\fP \fBtracing\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_TRACING_TIMESCALE_UNIT_\fP, 703, 'tracing \fBtimescale\fP unit \fBset'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_TRACING_VCD_DELTA_CYCLE_\fP"
.br
.ti -1c
.RI "\fBdefault\fP \fBtimescale\fP unit used \fBfor\fP \fBtracing\fP \fBVCD\fP \fBdelta\fP cycle \fBtracing\fP \fBwith\fP \fBpseudo\fP \fBtimesteps\fP (1 unit)' ) SC_DEFINE_MESSAGE( \fBSC_ID_TRACING_INVALID_TIMESCALE_UNIT_\fP"
.br
.ti -1c
.RI "\fBdefault\fP \fBtimescale\fP unit used \fBfor\fP \fBtracing\fP \fBVCD\fP \fBdelta\fP cycle \fBtracing\fP \fBwith\fP \fBpseudo\fP \fBinvalid\fP \fBtracing\fP \fBtimescale\fP unit set \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_TRACING_OBJECT_IGNORED_\fP, 710, 'object \fBcannot\fP \fBnot\fP \fBbe\fP \fBtraced'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_TRACING_OBJECT_NAME_FILTERED_\fP"
.br
.ti -1c
.RI "\fBdefault\fP \fBtimescale\fP unit used \fBfor\fP \fBtracing\fP \fBVCD\fP \fBdelta\fP cycle \fBtracing\fP \fBwith\fP \fBpseudo\fP \fBinvalid\fP \fBtracing\fP \fBtimescale\fP unit set \fBtraced\fP \fBobject\fP name \fBfiltered\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_TRACING_INVALID_ENUM_VALUE_\fP, 712, 'traced \fBvalue\fP \fBof\fP \fBenumerated\fP type \fBundefined'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_TRACING_VCD_TIME_RESOLUTION_\fP"
.br
.ti -1c
.RI "\fBdefault\fP \fBtimescale\fP unit used \fBfor\fP \fBtracing\fP \fBVCD\fP \fBdelta\fP cycle \fBtracing\fP \fBwith\fP \fBpseudo\fP \fBinvalid\fP \fBtracing\fP \fBtimescale\fP unit set \fBtraced\fP \fBobject\fP name \fBfiltered\fP \fBcurrent\fP \fBkernel\fP \fBtime\fP \fBis\fP \fBnot\fP \fBrepresentable\fP \fBin\fP \fBVCD\fP \fBtime\fP \fBunits\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_TRACING_REVERSED_TIME_\fP, 714, 'tracing cycle \fBwith\fP \fBduplicate\fP \fBor\fP reversed \fBtime\fP \fBdetected'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_TRACING_CLOSE_EMPTY_FILE_\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBdefault\fP \fBtimescale\fP unit used \fBfor\fP \fBtracing\fP \fBVCD\fP \fBdelta\fP cycle \fBtracing\fP \fBwith\fP \fBpseudo\fP \fBinvalid\fP \fBtracing\fP \fBtimescale\fP unit set traced \fBobject\fP name \fBfiltered\fP \fBcurrent\fP \fBkernel\fP \fBtime\fP \fBis\fP \fBnot\fP \fBrepresentable\fP \fBin\fP \fBVCD\fP \fBtime\fP \fBunits\fP trace file \fBclosed\fP \fBbefore\fP \fBany\fP \fBcycles\fP \fBwere\fP \fBtraced\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_DEFINE_MESSAGE(id, \fBunused1\fP, \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"

.SH "Function Documentation"
.PP 
.SS "SC_DEFINE_MESSAGE (\fBSC_ID_TRACING_FOPEN_FAILED_\fP, 701, 'cannot \fBopen\fP trace file \fBfor\fP \fBwriting'\fP)"

.SS "\fBdefault\fP \fBtimescale\fP unit used \fBfor\fP \fBtracing\fP \fBVCD\fP \fBdelta\fP cycle \fBtracing\fP \fBwith\fP \fBpseudo\fP \fBinvalid\fP \fBtracing\fP \fBtimescale\fP unit set \fBtraced\fP \fBobject\fP name \fBfiltered\fP SC_DEFINE_MESSAGE (\fBSC_ID_TRACING_INVALID_ENUM_VALUE_\fP, 712, 'traced \fBvalue\fP \fBof\fP \fBenumerated\fP type \fBundefined'\fP)"

.SS "\fBdefault\fP \fBtimescale\fP unit used \fBfor\fP \fBtracing\fP \fBVCD\fP \fBdelta\fP cycle \fBtracing\fP \fBwith\fP \fBpseudo\fP \fBinvalid\fP \fBtracing\fP \fBtimescale\fP unit set SC_DEFINE_MESSAGE (\fBSC_ID_TRACING_OBJECT_IGNORED_\fP, 710, 'object \fBcannot\fP \fBnot\fP \fBbe\fP \fBtraced'\fP)"

.SS "\fBdefault\fP \fBtimescale\fP unit used \fBfor\fP \fBtracing\fP \fBVCD\fP \fBdelta\fP cycle \fBtracing\fP \fBwith\fP \fBpseudo\fP \fBinvalid\fP \fBtracing\fP \fBtimescale\fP unit set \fBtraced\fP \fBobject\fP name \fBfiltered\fP \fBcurrent\fP \fBkernel\fP \fBtime\fP \fBis\fP \fBnot\fP \fBrepresentable\fP \fBin\fP \fBVCD\fP \fBtime\fP \fBunits\fP SC_DEFINE_MESSAGE (\fBSC_ID_TRACING_REVERSED_TIME_\fP, 714, 'tracing cycle \fBwith\fP \fBduplicate\fP \fBor\fP reversed \fBtime\fP \fBdetected'\fP)"

.SS "\fBdefault\fP \fBtimescale\fP unit used \fBfor\fP \fBtracing\fP SC_DEFINE_MESSAGE (\fBSC_ID_TRACING_TIMESCALE_UNIT_\fP, 703, 'tracing \fBtimescale\fP unit \fBset'\fP)"

.SS "\fBdefault\fP \fBtimescale\fP unit used \fBfor\fP \fBtracing\fP \fBVCD\fP \fBdelta\fP cycle \fBtracing\fP \fBwith\fP \fBpseudo\fP timesteps (1 unit)"

.SH "Variable Documentation"
.PP 
.SS "\fBdefault\fP \fBtimescale\fP unit used \fBfor\fP \fBtracing\fP \fBVCD\fP \fBdelta\fP cycle \fBtracing\fP \fBwith\fP \fBpseudo\fP \fBinvalid\fP \fBtracing\fP \fBtimescale\fP unit set traced \fBobject\fP name \fBfiltered\fP \fBcurrent\fP \fBkernel\fP \fBtime\fP \fBis\fP \fBnot\fP \fBrepresentable\fP \fBin\fP \fBVCD\fP \fBtime\fP \fBunits\fP trace file \fBclosed\fP \fBbefore\fP \fBany\fP \fBcycles\fP \fBwere\fP traced"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
