.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_thread_process.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_thread_process.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_spawn_options\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_process\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_cor\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_event\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_except\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_reset\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_thread_process\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBDEBUG_MSG\fP(\fBNAME\fP,  \fBP\fP,  \fBMSG\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBsc_core::sc_thread_cor_fn\fP (\fBvoid\fP *arg)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_set_stack_size\fP (\fBsc_thread_handle\fP, std::size_t)"
.br
.ti -1c
.RI "\fBsc_cor\fP * \fBsc_core::get_cor_pointer\fP (\fBsc_process_b\fP *\fBprocess_p\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (int, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_event\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_event_or_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_event_and_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_time\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event_or_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event_and_list\fP &, \fBsc_simcontext\fP *)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP DEBUG_MSG(\fBNAME\fP, \fBP\fP, \fBMSG\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
