.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_time.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_time.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/datatypes/int/sc_nbdefs\&.h'\fP
.br
\fR#include 'sysc/datatypes/fx/scfx_ieee\&.h'\fP
.br
\fR#include <iostream>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_time\fP"
.br
.ti -1c
.RI "class \fBsc_core::sc_time_tuple\fP"
.br
.ti -1c
.RI "struct \fBsc_core::sc_time_params\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBsc_core::sc_time_unit\fP { \fBsc_core::SC_FS\fP = 0, \fBsc_core::SC_PS\fP, \fBsc_core::SC_NS\fP, \fBsc_core::SC_US\fP, \fBsc_core::SC_MS\fP, \fBsc_core::SC_SEC\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBsc_time\fP \fBsc_core::operator+\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_time\fP &)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_time\fP \fBsc_core::operator\-\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_time\fP &)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_time\fP \fBsc_core::operator*\fP (\fBconst\fP \fBsc_time\fP &, \fBdouble\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_time\fP \fBsc_core::operator*\fP (\fBdouble\fP, \fBconst\fP \fBsc_time\fP &)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_time\fP \fBsc_core::operator/\fP (\fBconst\fP \fBsc_time\fP &, \fBdouble\fP)"
.br
.ti -1c
.RI "\fBdouble\fP \fBsc_core::operator/\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_time\fP &)"
.br
.ti -1c
.RI "\fBinline\fP ::std::ostream & \fBsc_core::operator<<\fP (::std::ostream &, \fBconst\fP \fBsc_time\fP &)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_time\fP \fBsc_core::operator%\fP (\fBconst\fP \fBsc_time\fP &\fBt1\fP, \fBconst\fP \fBsc_time\fP &\fBt2\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_set_time_resolution\fP (\fBdouble\fP, \fBsc_time_unit\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_time\fP \fBsc_core::sc_get_time_resolution\fP ()"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_set_default_time_unit\fP (\fBdouble\fP, \fBsc_time_unit\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_time\fP \fBsc_core::sc_get_default_time_unit\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBSC_API\fP \fBsc_core::sc_time_tuple\fP"
.br
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP \fBsc_time\fP \fBsc_core::SC_ZERO_TIME\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
