.TH "systemc_modules/sc_terminals.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
systemc_modules/sc_terminals.h
.SH SYNOPSIS
.br
.PP
\fR#include <systemc\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSyscTerminal< W >\fP"
.br
.ti -1c
.RI "class \fBSyscIn< W >\fP"
.br
.ti -1c
.RI "class \fBSyscOut< W >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
