.TH "sc_thread_config_s" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_thread_config_s
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_config\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBrst_act_level\fP"
.br
.ti -1c
.RI "\fBint\fP \fBrst_act_microsteps\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBena_act_level\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBclk_act_edge\fP"
.br
.ti -1c
.RI "\fBsc_time\fP \fBclk_period\fP"
.br
.ti -1c
.RI "\fBsc_time\fP \fBmicrostep\fP"
.br
.ti -1c
.RI "\fBint\fP \fBclk_semiperiod_microsteps\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBbool\fP sc_thread_config_s::clk_act_edge"

.SS "\fBsc_time\fP sc_thread_config_s::clk_period"

.SS "\fBint\fP sc_thread_config_s::clk_semiperiod_microsteps"

.SS "\fBbool\fP sc_thread_config_s::ena_act_level"

.SS "\fBsc_time\fP sc_thread_config_s::microstep"

.SS "\fBbool\fP sc_thread_config_s::rst_act_level"

.SS "\fBint\fP sc_thread_config_s::rst_act_microsteps"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
