.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/tracing/sc_trace.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/tracing/sc_trace.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstdio>\fP
.br
\fR#include 'sysc/datatypes/int/sc_nbdefs\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_time\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_trace_file\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_dt\fP"
.br
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBDECL_TRACE_METHOD_A\fP(\fBtp\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDECL_TRACE_METHOD_B\fP(\fBtp\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDECL_TRACE_FUNC_REF_A\fP(\fBtp\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDECL_TRACE_FUNC_PTR_A\fP(\fBtp\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDECL_TRACE_FUNC_A\fP(\fBtp\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDECL_TRACE_FUNC_REF_B\fP(\fBtp\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDECL_TRACE_FUNC_PTR_B\fP(\fBtp\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDECL_TRACE_FUNC_B\fP(\fBtp\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_trace\fP (\fBsc_trace_file\fP *tf, \fBconst\fP \fBsc_signal_in_if\fP< \fBT\fP > &\fBobject\fP, \fBconst\fP std::string &name)"
.br
.ti -1c
.RI "template<\fBclass\fP \fBT\fP > \fBvoid\fP \fBsc_core::sc_trace\fP (\fBsc_trace_file\fP *tf, \fBconst\fP \fBsc_signal_in_if\fP< \fBT\fP > &\fBobject\fP, \fBconst\fP \fBchar\fP *name)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_trace\fP (\fBsc_trace_file\fP *tf, \fBconst\fP \fBsc_signal_in_if\fP< \fBchar\fP > &\fBobject\fP, \fBconst\fP std::string &name, int width)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_trace\fP (\fBsc_trace_file\fP *tf, \fBconst\fP \fBsc_signal_in_if\fP< \fBshort\fP > &\fBobject\fP, \fBconst\fP std::string &name, int width)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_trace\fP (\fBsc_trace_file\fP *tf, \fBconst\fP \fBsc_signal_in_if\fP< int > &\fBobject\fP, \fBconst\fP std::string &name, int width)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_trace\fP (\fBsc_trace_file\fP *tf, \fBconst\fP \fBsc_signal_in_if\fP< \fBlong\fP > &\fBobject\fP, \fBconst\fP std::string &name, int width)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_trace\fP (\fBsc_trace_file\fP *tf, \fBconst\fP \fBunsigned\fP int &\fBobject\fP, \fBconst\fP std::string &name, \fBconst\fP \fBchar\fP **\fBenum_literals\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_trace\fP (\fBsc_trace_file\fP *tf, \fBconst\fP \fBvoid\fP *\fBobject\fP, \fBconst\fP std::string &name)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_trace_delta_cycles\fP (\fBsc_trace_file\fP *tf, \fBbool\fP \fBon\fP=\fBtrue\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_write_comment\fP (\fBsc_trace_file\fP *tf, \fBconst\fP std::string &\fBcomment\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::tprintf\fP (\fBsc_trace_file\fP *tf, \fBconst\fP \fBchar\fP *\fBformat\fP,\&.\&.\&.)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_trace_file\fP * \fBsc_core::sc_create_vcd_trace_file\fP (\fBconst\fP \fBchar\fP *name)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_close_vcd_trace_file\fP (\fBsc_trace_file\fP *tf)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_trace_file\fP * \fBsc_core::sc_create_wif_trace_file\fP (\fBconst\fP \fBchar\fP *name)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_close_wif_trace_file\fP (\fBsc_trace_file\fP *tf)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP DECL_TRACE_FUNC_A(\fBtp\fP)"
\fBValue:\fP.PP
.nf
DECL_TRACE_FUNC_REF_A(tp)             \\
DECL_TRACE_FUNC_PTR_A(tp)
.fi

.SS "#\fBdefine\fP DECL_TRACE_FUNC_B(\fBtp\fP)"
\fBValue:\fP.PP
.nf
DECL_TRACE_FUNC_REF_B(tp)      \\
DECL_TRACE_FUNC_PTR_B(tp)
.fi

.SS "#\fBdefine\fP DECL_TRACE_FUNC_PTR_A(\fBtp\fP)"
\fBValue:\fP.PP
.nf
SC_API void                           \\
sc_trace( sc_trace_file* tf,          \\
      const tp* object,               \\
      const std::string& name );      \\
.fi

.SS "#\fBdefine\fP DECL_TRACE_FUNC_PTR_B(\fBtp\fP)"
\fBValue:\fP.PP
.nf
SC_API void                                                              \\
sc_trace( sc_trace_file* tf, const tp* object, const std::string& name,  \\
          int width = 8 * sizeof( tp ) );
.fi

.SS "#\fBdefine\fP DECL_TRACE_FUNC_REF_A(\fBtp\fP)"
\fBValue:\fP.PP
.nf
SC_API void                           \\
sc_trace( sc_trace_file* tf,          \\
      const tp& object,               \\
      const std::string& name );
.fi

.SS "#\fBdefine\fP DECL_TRACE_FUNC_REF_B(\fBtp\fP)"
\fBValue:\fP.PP
.nf
SC_API void                                                              \\
sc_trace( sc_trace_file* tf, const tp& object, const std::string& name,  \\
          int width = 8 * sizeof( tp ) );
.fi

.SS "#\fBdefine\fP DECL_TRACE_METHOD_A(\fBtp\fP)"
\fBValue:\fP.PP
.nf
    virtual void trace( const tp& object,                                     \\
            const std::string& name ) = 0;
.fi

.SS "#\fBdefine\fP DECL_TRACE_METHOD_B(\fBtp\fP)"
\fBValue:\fP.PP
.nf
    virtual void trace( const tp& object,                                     \\
            const std::string& name,                                     \\
            int width ) = 0;
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
