.TH "systemc_modules/sc_tri.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
systemc_modules/sc_tri.h
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br
\fR#include <string>\fP
.br
\fR#include <systemc\&.h>\fP
.br
\fR#include 'sc_gates\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSyscTri< W, TRI_XORZ_CONV >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBenum\fP \fBTRI_CONV_CTL_XORZ_e\fP \fBTRI_CONV_CTL_XORZ_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTRI_CONV_CTL_XORZ_e\fP { \fBTRI_CONV_CTL_XORZ_X\fP, \fBTRI_CONV_CTL_XORZ_Z\fP, \fBTRI_CONV_CTL_XORZ_D\fP }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBenum\fP \fBTRI_CONV_CTL_XORZ_e\fP \fBTRI_CONV_CTL_XORZ_t\fP"
Numeric conversion to use when selection value contains X or Z 
.SH "Enumeration Type Documentation"
.PP 
.SS "\fBenum\fP \fBTRI_CONV_CTL_XORZ_e\fP"
Numeric conversion to use when selection value contains X or Z 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITRI_CONV_CTL_XORZ_X \fP\fP
Tri output is X (default) 
.br
 
.TP
\fB\fITRI_CONV_CTL_XORZ_Z \fP\fP
Tri output is Z (assume ctl == 0) 
.TP
\fB\fITRI_CONV_CTL_XORZ_D \fP\fP
Tri output is D (assume ctl == 1) 
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
