.TH "sc_thread_run_s" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sc_thread_run_s
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_run\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBint\fP \fBstate\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBhierarchy\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBtracelist\fP"
.br
.ti -1c
.RI "std::vector< std::string > \fBreport\fP"
.br
.ti -1c
.RI "\fBpthread_mutex_t\fP \fBrun_mutex\fP"
.br
.ti -1c
.RI "\fBpthread_mutex_t\fP \fBcondvar_mutex\fP"
.br
.ti -1c
.RI "\fBpthread_cond_t\fP \fBcondvar\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBpthread_cond_t\fP sc_thread_run_s::condvar"

.SS "\fBpthread_mutex_t\fP sc_thread_run_s::condvar_mutex"

.SS "std::vector<std::string> sc_thread_run_s::hierarchy"

.SS "std::vector<std::string> sc_thread_run_s::report"

.SS "\fBpthread_mutex_t\fP sc_thread_run_s::run_mutex"

.SS "\fBint\fP sc_thread_run_s::state"

.SS "std::vector<std::string> sc_thread_run_s::tracelist"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
