.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/tracing/sc_trace_file_base.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/tracing/sc_trace_file_base.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstdio>\fP
.br
\fR#include 'sysc/tracing/sc_trace\&.h'\fP
.br
\fR#include 'sysc/tracing/sc_tracing_ids\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::sc_trace_file_base\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_TRACING_PHASE_CALLBACKS_\fP   0"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_API\fP std::string \fBsc_core::localtime_string\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_TRACING_PHASE_CALLBACKS_   0"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
