.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/int/sc_uint_base.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/int/sc_uint_base.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_object\&.h'\fP
.br
\fR#include 'sysc/datatypes/misc/sc_value_base\&.h'\fP
.br
\fR#include 'sysc/datatypes/int/sc_int_ids\&.h'\fP
.br
\fR#include 'sysc/datatypes/int/sc_length_param\&.h'\fP
.br
\fR#include 'sysc/datatypes/int/sc_nbdefs\&.h'\fP
.br
\fR#include 'sysc/datatypes/fx/scfx_ieee\&.h'\fP
.br
\fR#include 'sysc/utils/sc_temporary\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_dt::sc_uint_bitref_r\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_uint_bitref\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_uint_subref_r\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_uint_subref\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_uint_base\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_dt\fP"
.br
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP, \fBconst\fP \fBsc_uint_base\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP, \fBconst\fP \fBsc_uint_base\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP, \fBconst\fP \fBsc_uint_base\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP, \fBconst\fP \fBsc_uint_base\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP, \fBconst\fP \fBsc_uint_base\fP &\fBb\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP, \fBconst\fP \fBsc_uint_base\fP &\fBb\fP)"
.br
.ti -1c
.RI "inline::std::ostream & \fBsc_dt::operator<<\fP (::std::ostream &, \fBconst\fP \fBsc_uint_bitref_r\fP &)"
.br
.ti -1c
.RI "inline::std::istream & \fBsc_dt::operator>>\fP (::std::istream &, \fBsc_uint_bitref\fP &)"
.br
.ti -1c
.RI "inline::std::ostream & \fBsc_dt::operator<<\fP (::std::ostream &, \fBconst\fP \fBsc_uint_subref_r\fP &)"
.br
.ti -1c
.RI "inline::std::istream & \fBsc_dt::operator>>\fP (::std::istream &, \fBsc_uint_subref\fP &)"
.br
.ti -1c
.RI "inline::std::ostream & \fBsc_dt::operator<<\fP (::std::ostream &, \fBconst\fP \fBsc_uint_base\fP &)"
.br
.ti -1c
.RI "inline::std::istream & \fBsc_dt::operator>>\fP (::std::istream &, \fBsc_uint_base\fP &)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::and_reduce\fP (\fBconst\fP \fBsc_uint_subref_r\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::nand_reduce\fP (\fBconst\fP \fBsc_uint_subref_r\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::or_reduce\fP (\fBconst\fP \fBsc_uint_subref_r\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::nor_reduce\fP (\fBconst\fP \fBsc_uint_subref_r\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::xor_reduce\fP (\fBconst\fP \fBsc_uint_subref_r\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::xnor_reduce\fP (\fBconst\fP \fBsc_uint_subref_r\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::and_reduce\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::nand_reduce\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::or_reduce\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::nor_reduce\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::xor_reduce\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::xnor_reduce\fP (\fBconst\fP \fBsc_uint_base\fP &\fBa\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
