.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/utils/sc_utils_ids.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/utils/sc_utils_ids.h
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_DEFINE_MESSAGE\fP(id,  \fBunused1\fP,  \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_STRING_TOO_LONG_\fP, 801, 'string \fBis\fP \fBtoo\fP \fBlong'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_FRONT_ON_EMPTY_LIST_\fP"
.br
.ti -1c
.RI "\fBattempt\fP \fBto\fP \fBtake\fP \fBfront\fP () \fBon\fP \fBan\fP empty \fBlist'\fP) \fBSC_DEFINE_MESSAGE\fP(\fBSC_ID_BACK_ON_EMPTY_LIST_\fP"
.br
.ti -1c
.RI "\fBattempt\fP \fBto\fP \fBtake\fP \fBattempt\fP \fBto\fP \fBtake\fP \fBback\fP () \fBon\fP \fBan\fP empty \fBlist'\fP) \fBSC_DEFINE_MESSAGE\fP(\fBSC_ID_IEEE_1666_DEPRECATION_\fP"
.br
.ti -1c
.RI "\fBattempt\fP \fBto\fP \fBtake\fP \fBattempt\fP \fBto\fP \fBtake\fP \fBIEEE_Std_1666\fP \fBdeprecated\fP \fBSC_DEFINE_MESSAGE\fP (\fBSC_ID_VECTOR_INIT_CALLED_TWICE_\fP, 805, 'sc_vector::init \fBhas\fP \fBalready\fP \fBbeen\fP \fBcalled'\fP) SC_DEFINE_MESSAGE(\fBSC_ID_VECTOR_BIND_EMPTY_\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_DEFINE_MESSAGE(id, \fBunused1\fP, \fBunused2\fP)       \fBnamespace\fP sc_core { \fBextern\fP \fBSC_API\fP \fBconst\fP \fBchar\fP id[]; }"

.SH "Function Documentation"
.PP 
.SS "\fBattempt\fP \fBto\fP \fBtake\fP \fBattempt\fP \fBto\fP \fBtake\fP back ()"

.SS "\fBattempt\fP \fBto\fP \fBtake\fP front ()"

.SS "SC_DEFINE_MESSAGE (\fBSC_ID_STRING_TOO_LONG_\fP, 801, 'string \fBis\fP \fBtoo\fP \fBlong'\fP)"

.SS "\fBattempt\fP \fBto\fP \fBtake\fP \fBattempt\fP \fBto\fP \fBtake\fP \fBIEEE_Std_1666\fP \fBdeprecated\fP SC_DEFINE_MESSAGE (\fBSC_ID_VECTOR_INIT_CALLED_TWICE_\fP, 805, 'sc_vector::init \fBhas\fP \fBalready\fP \fBbeen\fP \fBcalled'\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
