.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/int/sc_unsigned.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/int/sc_unsigned.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_object\&.h'\fP
.br
\fR#include 'sysc/datatypes/misc/sc_value_base\&.h'\fP
.br
\fR#include 'sysc/utils/sc_temporary\&.h'\fP
.br
\fR#include 'sysc/datatypes/int/sc_length_param\&.h'\fP
.br
\fR#include 'sysc/datatypes/int/sc_nbdefs\&.h'\fP
.br
\fR#include 'sysc/datatypes/int/sc_nbutils\&.h'\fP
.br
\fR#include 'sysc/datatypes/int/sc_nbexterns\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_dt::sc_unsigned_bitref_r\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_unsigned_bitref\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_unsigned_subref_r\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_unsigned_subref\fP"
.br
.ti -1c
.RI "class \fBsc_dt::sc_unsigned\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_dt\fP"
.br
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBsc_dt::compare_unsigned\fP (\fBsmall_type\fP \fBus\fP, int \fBunb\fP, int \fBund\fP, \fBconst\fP \fBsc_digit\fP *\fBud\fP, \fBsmall_type\fP \fBvs\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP, \fBsmall_type\fP \fBif_u_signed\fP=0, \fBsmall_type\fP \fBif_v_signed\fP=0)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::add_unsigned_friend\fP (\fBsmall_type\fP \fBus\fP, int \fBunb\fP, int \fBund\fP, \fBconst\fP \fBsc_digit\fP *\fBud\fP, \fBsmall_type\fP \fBvs\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::sub_unsigned_friend\fP (\fBsmall_type\fP \fBus\fP, int \fBunb\fP, int \fBund\fP, \fBconst\fP \fBsc_digit\fP *\fBud\fP, \fBsmall_type\fP \fBvs\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::mul_unsigned_friend\fP (\fBsmall_type\fP s, int \fBunb\fP, int \fBund\fP, \fBconst\fP \fBsc_digit\fP *\fBud\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::div_unsigned_friend\fP (\fBsmall_type\fP s, int \fBunb\fP, int \fBund\fP, \fBconst\fP \fBsc_digit\fP *\fBud\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::mod_unsigned_friend\fP (\fBsmall_type\fP \fBus\fP, int \fBunb\fP, int \fBund\fP, \fBconst\fP \fBsc_digit\fP *\fBud\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::and_unsigned_friend\fP (\fBsmall_type\fP \fBus\fP, int \fBunb\fP, int \fBund\fP, \fBconst\fP \fBsc_digit\fP *\fBud\fP, \fBsmall_type\fP \fBvs\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::or_unsigned_friend\fP (\fBsmall_type\fP \fBus\fP, int \fBunb\fP, int \fBund\fP, \fBconst\fP \fBsc_digit\fP *\fBud\fP, \fBsmall_type\fP \fBvs\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::xor_unsigned_friend\fP (\fBsmall_type\fP \fBus\fP, int \fBunb\fP, int \fBund\fP, \fBconst\fP \fBsc_digit\fP *\fBud\fP, \fBsmall_type\fP \fBvs\fP, int \fBvnb\fP, int \fBvnd\fP, \fBconst\fP \fBsc_digit\fP *\fBvd\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator+\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator+\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator+\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator+\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator+\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator+\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator\-\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator*\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator*\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator*\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator*\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator*\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator*\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator*\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator/\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator/\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator/\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator/\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator/\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator/\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator/\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator%\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator%\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator%\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator%\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator%\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator%\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator%\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator&\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator&\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator&\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator&\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator&\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator&\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator&\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator|\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator|\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator|\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator|\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator|\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator|\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator|\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator^\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator^\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator^\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator^\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_signed\fP \fBsc_dt::operator^\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator^\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator^\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator<<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator<<\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator<<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator<<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator<<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator<<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator<<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator<<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator<<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator<<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator<<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator>>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator>>\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator>>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator>>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator>>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator>>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator>>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator>>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBsc_unsigned\fP \fBsc_dt::operator>>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator>>\fP (\fBconst\fP \fBsc_unsigned\fP &, \fBconst\fP \fBsc_uint_base\fP &)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator>>\fP (\fBconst\fP \fBsc_unsigned\fP &, \fBconst\fP \fBsc_int_base\fP &)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator+\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_signed\fP \fBsc_dt::operator\-\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator==\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator==\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator==\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator!=\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator!=\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator!=\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator<\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator<\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator<=\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator<=\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator<=\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator>\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator>\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_signed\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_signed\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBuint64\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBlong\fP v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP \fBlong\fP v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, int v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBunsigned\fP int v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBuint64\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBunsigned\fP \fBlong\fP \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator>=\fP (int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBbool\fP \fBsc_dt::operator>=\fP (\fBunsigned\fP int \fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_uint_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP, \fBconst\fP \fBsc_int_base\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_uint_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_dt::operator>=\fP (\fBconst\fP \fBsc_int_base\fP &\fBu\fP, \fBconst\fP \fBsc_unsigned\fP &v)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBsc_unsigned\fP \fBsc_dt::operator~\fP (\fBconst\fP \fBsc_unsigned\fP &\fBu\fP)"
.br
.ti -1c
.RI "inline::std::ostream & \fBsc_dt::operator<<\fP (::std::ostream &, \fBconst\fP \fBsc_unsigned_bitref_r\fP &)"
.br
.ti -1c
.RI "inline::std::istream & \fBsc_dt::operator>>\fP (::std::istream &, \fBsc_unsigned_bitref\fP &)"
.br
.ti -1c
.RI "inline::std::ostream & \fBsc_dt::operator<<\fP (::std::ostream &, \fBconst\fP \fBsc_unsigned_subref_r\fP &)"
.br
.ti -1c
.RI "inline::std::istream & \fBsc_dt::operator>>\fP (::std::istream &, \fBsc_unsigned_subref\fP &)"
.br
.ti -1c
.RI "inline::std::ostream & \fBsc_dt::operator<<\fP (::std::ostream &, \fBconst\fP \fBsc_unsigned\fP &)"
.br
.ti -1c
.RI "inline::std::istream & \fBsc_dt::operator>>\fP (::std::istream &, \fBsc_unsigned\fP &)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
