.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_ver.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_ver.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_cmnhdr\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_macros\&.h'\fP
.br
\fR#include 'sysc/communication/sc_writer_policy\&.h'\fP
.br
\fR#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsc_core::SC_API_VERSION_STRING\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSYSTEMC_2_3_3\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSYSTEMC_VERSION\fP   20181013"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_VERSION_ORIGINATOR\fP   'Accellera'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_VERSION_MAJOR\fP   2"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_VERSION_MINOR\fP   3"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_VERSION_PATCH\fP   3"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_IS_PRERELEASE\fP   0"
.br
.ti -1c
.RI "#\fBdefine\fP \fBIEEE_1666_SYSTEMC\fP   201101\fBL\fP"
.br
.RI "compliancy with IEEE 1666-2011 (see 8\&.6\&.5) "
.ti -1c
.RI "#\fBdefine\fP \fBSC_COPYRIGHT\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_VERSION_RELEASE_DATE\fP     \fBSC_STRINGIFY_HELPER_\fP( \fBSYSTEMC_VERSION\fP )"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_VERSION_PRERELEASE\fP   ''"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_VERSION\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_API_VERSION_STRING\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_API_DEFINED_\fP(\fBSymbol\fP)     \fBSymbol\fP ## \fB_DEFINED_\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_API_UNDEFINED_\fP(\fBSymbol\fP)     \fBSymbol\fP ## \fB_UNDEFINED_\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_DISABLE_VIRTUAL_BIND_CHECK_\fP       \fBSC_API_UNDEFINED_\fP(\fBSC_DISABLE_VIRTUAL_BIND\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP \fBchar\fP * \fBsc_core::sc_copyright\fP ()"
.br
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP \fBchar\fP * \fBsc_core::sc_release\fP ()"
.br
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP \fBchar\fP * \fBsc_core::sc_version\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP \fBunsigned\fP int \fBsc_core::sc_version_major\fP"
.br
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP \fBunsigned\fP int \fBsc_core::sc_version_minor\fP"
.br
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP \fBunsigned\fP int \fBsc_core::sc_version_patch\fP"
.br
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP std::string \fBsc_core::sc_version_originator\fP"
.br
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP std::string \fBsc_core::sc_version_release_date\fP"
.br
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP std::string \fBsc_core::sc_version_prerelease\fP"
.br
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP \fBbool\fP \fBsc_core::sc_is_prerelease\fP"
.br
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP std::string \fBsc_core::sc_version_string\fP"
.br
.ti -1c
.RI "\fBSC_API\fP \fBconst\fP std::string \fBsc_core::sc_copyright_string\fP"
.br
.ti -1c
.RI "\fBconst\fP int \fBsc_core::SC_DISABLE_VIRTUAL_BIND_CHECK_\fP"
.br
.ti -1c
.RI "\fBSC_TPLEXTERN_\fP \fBtemplate\fP \fBstruct\fP \fBSC_API\fP \fBsc_core::SC_API_VERSION_STRING< &SC_DISABLE_VIRTUAL_BIND_CHECK_ >\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP IEEE_1666_SYSTEMC   201101\fBL\fP"

.PP
compliancy with IEEE 1666-2011 (see 8\&.6\&.5) 
.SS "#\fBdefine\fP SC_API_DEFINED_(\fBSymbol\fP)     \fBSymbol\fP ## \fB_DEFINED_\fP"

.SS "#\fBdefine\fP SC_API_UNDEFINED_(\fBSymbol\fP)     \fBSymbol\fP ## \fB_UNDEFINED_\fP"

.SS "#\fBdefine\fP SC_API_VERSION_STRING"
\fBValue:\fP.PP
.nf
      SC_CONCAT_UNDERSCORE_( sc_api_version, \\
      SC_CONCAT_UNDERSCORE_( SC_VERSION_MAJOR, \\
      SC_CONCAT_UNDERSCORE_( SC_VERSION_MINOR, \\
      SC_CONCAT_UNDERSCORE_( SC_VERSION_PATCH, \\
      SC_CONCAT_HELPER_( cxx, SC_CPLUSPLUS ) \\
  ) ) ) )
.fi

.SS "#\fBdefine\fP SC_COPYRIGHT"
\fBValue:\fP.PP
.nf
  "Copyright (c) 1996\-2018 by all Contributors,\\n" \\
  "ALL RIGHTS RESERVED\\n"
.fi

.SS "#\fBdefine\fP SC_DISABLE_VIRTUAL_BIND_CHECK_       \fBSC_API_UNDEFINED_\fP(\fBSC_DISABLE_VIRTUAL_BIND\fP)"

.SS "#\fBdefine\fP SC_IS_PRERELEASE   0"

.SS "#\fBdefine\fP SC_VERSION"
\fBValue:\fP.PP
.nf
    SC_STRINGIFY_HELPER_( SC_VERSION_MAJOR\&.SC_VERSION_MINOR\&.SC_VERSION_PATCH ) \\
    "\-" SC_VERSION_ORIGINATOR
.fi

.SS "#\fBdefine\fP SC_VERSION_MAJOR   2"

.SS "#\fBdefine\fP SC_VERSION_MINOR   3"

.SS "#\fBdefine\fP SC_VERSION_ORIGINATOR   'Accellera'"

.SS "#\fBdefine\fP SC_VERSION_PATCH   3"

.SS "#\fBdefine\fP SC_VERSION_PRERELEASE   ''"

.SS "#\fBdefine\fP SC_VERSION_RELEASE_DATE     \fBSC_STRINGIFY_HELPER_\fP( \fBSYSTEMC_VERSION\fP )"

.SS "#\fBdefine\fP SYSTEMC_2_3_3"

.SS "#\fBdefine\fP SYSTEMC_VERSION   20181013"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
