.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/tracing/sc_wif_trace.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/tracing/sc_wif_trace.h
.SH SYNOPSIS
.br
.PP
\fR#include <cstdio>\fP
.br
\fR#include 'sysc/datatypes/int/sc_nbdefs\&.h'\fP
.br
\fR#include 'sysc/tracing/sc_trace_file_base\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_core::wif_trace_file\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
