.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_wait.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_wait.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_simcontext\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBsc_simcontext\fP * \fBsc_core::sc_get_curr_simcontext\fP ()"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_event\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_event_or_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_event_and_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_time\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBdouble\fP v, \fBsc_time_unit\fP \fBtu\fP, \fBsc_simcontext\fP *\fBsimc\fP=\fBsc_get_curr_simcontext\fP())"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBdouble\fP v, \fBsc_time_unit\fP \fBtu\fP, \fBconst\fP \fBsc_event\fP &\fBe\fP, \fBsc_simcontext\fP *\fBsimc\fP=\fBsc_get_curr_simcontext\fP())"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event_or_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBdouble\fP v, \fBsc_time_unit\fP \fBtu\fP, \fBconst\fP \fBsc_event_or_list\fP &\fBel\fP, \fBsc_simcontext\fP *\fBsimc\fP=\fBsc_get_curr_simcontext\fP())"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event_and_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (\fBdouble\fP v, \fBsc_time_unit\fP \fBtu\fP, \fBconst\fP \fBsc_event_and_list\fP &\fBel\fP, \fBsc_simcontext\fP *\fBsimc\fP=\fBsc_get_curr_simcontext\fP())"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::next_trigger\fP (\fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::next_trigger\fP (\fBconst\fP \fBsc_event\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::next_trigger\fP (\fBconst\fP \fBsc_event_or_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::next_trigger\fP (\fBconst\fP \fBsc_event_and_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::next_trigger\fP (\fBconst\fP \fBsc_time\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::next_trigger\fP (\fBdouble\fP v, \fBsc_time_unit\fP \fBtu\fP, \fBsc_simcontext\fP *\fBsimc\fP=\fBsc_get_curr_simcontext\fP())"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::next_trigger\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::next_trigger\fP (\fBdouble\fP v, \fBsc_time_unit\fP \fBtu\fP, \fBconst\fP \fBsc_event\fP &\fBe\fP, \fBsc_simcontext\fP *\fBsimc\fP=\fBsc_get_curr_simcontext\fP())"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::next_trigger\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event_or_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::next_trigger\fP (\fBdouble\fP v, \fBsc_time_unit\fP \fBtu\fP, \fBconst\fP \fBsc_event_or_list\fP &\fBel\fP, \fBsc_simcontext\fP *\fBsimc\fP=\fBsc_get_curr_simcontext\fP())"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::next_trigger\fP (\fBconst\fP \fBsc_time\fP &, \fBconst\fP \fBsc_event_and_list\fP &, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_core::next_trigger\fP (\fBdouble\fP v, \fBsc_time_unit\fP \fBtu\fP, \fBconst\fP \fBsc_event_and_list\fP &\fBel\fP, \fBsc_simcontext\fP *\fBsimc\fP=\fBsc_get_curr_simcontext\fP())"
.br
.ti -1c
.RI "\fBSC_API\fP \fBbool\fP \fBsc_core::timed_out\fP (\fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_set_location\fP (\fBconst\fP \fBchar\fP *, int, \fBsc_simcontext\fP *=\fBsc_get_curr_simcontext\fP())"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
