.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_wait_cthread.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/kernel/sc_wait_cthread.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_simcontext\&.h'\fP
.br
\fR#include 'sysc/datatypes/bit/sc_logic\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBSC_API\fP \fBsc_core::halt\fP (\fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::wait\fP (int, \fBsc_simcontext\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_core::at_posedge\fP (\fBconst\fP \fBsc_signal_in_if\fP< \fBbool\fP > &, \fBsc_simcontext\fP *=\fBsc_get_curr_simcontext\fP())"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_core::at_posedge\fP (\fBconst\fP \fBsc_signal_in_if\fP< \fBsc_dt::sc_logic\fP > &, \fBsc_simcontext\fP *=\fBsc_get_curr_simcontext\fP())"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_core::at_negedge\fP (\fBconst\fP \fBsc_signal_in_if\fP< \fBbool\fP > &, \fBsc_simcontext\fP *=\fBsc_get_curr_simcontext\fP())"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_core::at_negedge\fP (\fBconst\fP \fBsc_signal_in_if\fP< \fBsc_dt::sc_logic\fP > &, \fBsc_simcontext\fP *=\fBsc_get_curr_simcontext\fP())"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
