.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_writer_policy.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/communication/sc_writer_policy.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_process_handle\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBsc_core::sc_writer_policy_nocheck_write\fP"
.br
.ti -1c
.RI "struct \fBsc_core::sc_writer_policy_check_write\fP"
.br
.ti -1c
.RI "struct \fBsc_core::sc_writer_policy_check_delta\fP"
.br
.ti -1c
.RI "struct \fBsc_core::sc_writer_policy_nocheck_port\fP"
.br
.ti -1c
.RI "struct \fBsc_core::sc_writer_policy_check_port\fP"
.br
.ti -1c
.RI "struct \fBsc_core::sc_writer_policy_check< SC_ONE_WRITER >\fP"
.br
.ti -1c
.RI "struct \fBsc_core::sc_writer_policy_check< SC_MANY_WRITERS >\fP"
.br
.ti -1c
.RI "struct \fBsc_core::sc_writer_policy_check< SC_UNCHECKED_WRITERS >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_core\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_DEFAULT_WRITER_POLICY\fP   SC_ONE_WRITER"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBsc_core::sc_writer_policy\fP { \fBsc_core::SC_ONE_WRITER\fP = 0, \fBsc_core::SC_MANY_WRITERS\fP = 1, \fBsc_core::SC_UNCHECKED_WRITERS\fP = 3 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_core::sc_signal_invalid_writer\fP (\fBsc_object\fP *target, \fBsc_object\fP *\fBfirst_writer\fP, \fBsc_object\fP *\fBsecond_writer\fP, \fBbool\fP \fBcheck_delta\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_DEFAULT_WRITER_POLICY   SC_ONE_WRITER"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
