.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/scfx_ieee.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/scfx_ieee.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/datatypes/fx/sc_fxdefs\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "union \fBsc_dt::ieee_double\fP"
.br
.ti -1c
.RI "class \fBsc_dt::scfx_ieee_double\fP"
.br
.ti -1c
.RI "union \fBsc_dt::ieee_float\fP"
.br
.ti -1c
.RI "class \fBsc_dt::scfx_ieee_float\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_dt\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSCFX_MASK_\fP(\fBSize\fP)      ((1\fBu\fP << (\fBSize\fP))\-1\fBu\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBMSB_STATEMENT\fP(\fBx\fP,  \fBn\fP)   \fBif\fP( \fBx\fP >> \fBn\fP ) { \fBx\fP >>= \fBn\fP; \fBi\fP += \fBn\fP; }"
.br
.ti -1c
.RI "#\fBdefine\fP \fBLSB_STATEMENT\fP(\fBx\fP,  \fBn\fP)   \fBif\fP( \fBx\fP << \fBn\fP ) { \fBx\fP <<= \fBn\fP; \fBi\fP \-= \fBn\fP; }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBdouble\fP \fBsc_dt::scfx_pow2\fP (int \fBexp\fP)"
.br
.ti -1c
.RI "\fBdouble\fP \fBsc_dt::uint64_to_double\fP (\fBuint64\fP \fBa\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBunsigned\fP int \fBsc_dt::SCFX_IEEE_DOUBLE_BIAS\fP = 1023\fBU\fP"
.br
.ti -1c
.RI "\fBconst\fP int \fBsc_dt::SCFX_IEEE_DOUBLE_E_MAX\fP = 1023"
.br
.ti -1c
.RI "\fBconst\fP int \fBsc_dt::SCFX_IEEE_DOUBLE_E_MIN\fP = \-1022"
.br
.ti -1c
.RI "\fBconst\fP \fBunsigned\fP int \fBsc_dt::SCFX_IEEE_DOUBLE_M_SIZE\fP = 52"
.br
.ti -1c
.RI "\fBconst\fP \fBunsigned\fP int \fBsc_dt::SCFX_IEEE_DOUBLE_M0_SIZE\fP = 20"
.br
.ti -1c
.RI "\fBconst\fP \fBunsigned\fP int \fBsc_dt::SCFX_IEEE_DOUBLE_M1_SIZE\fP = 32"
.br
.ti -1c
.RI "\fBconst\fP \fBunsigned\fP int \fBsc_dt::SCFX_IEEE_DOUBLE_E_SIZE\fP = 11"
.br
.ti -1c
.RI "\fBconst\fP \fBunsigned\fP int \fBsc_dt::SCFX_IEEE_FLOAT_BIAS\fP = 127\fBU\fP"
.br
.ti -1c
.RI "\fBconst\fP int \fBsc_dt::SCFX_IEEE_FLOAT_E_MAX\fP = 127"
.br
.ti -1c
.RI "\fBconst\fP int \fBsc_dt::SCFX_IEEE_FLOAT_E_MIN\fP = \-126"
.br
.ti -1c
.RI "\fBconst\fP \fBunsigned\fP int \fBsc_dt::SCFX_IEEE_FLOAT_M_SIZE\fP = 23"
.br
.ti -1c
.RI "\fBconst\fP \fBunsigned\fP int \fBsc_dt::SCFX_IEEE_FLOAT_E_SIZE\fP = 8"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP LSB_STATEMENT(\fBx\fP, \fBn\fP)   \fBif\fP( \fBx\fP << \fBn\fP ) { \fBx\fP <<= \fBn\fP; \fBi\fP \-= \fBn\fP; }"

.SS "#\fBdefine\fP MSB_STATEMENT(\fBx\fP, \fBn\fP)   \fBif\fP( \fBx\fP >> \fBn\fP ) { \fBx\fP >>= \fBn\fP; \fBi\fP += \fBn\fP; }"

.SS "#\fBdefine\fP SCFX_MASK_(\fBSize\fP)      ((1\fBu\fP << (\fBSize\fP))\-1\fBu\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
