.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/scfx_rep.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/scfx_rep.h
.SH SYNOPSIS
.br
.PP
\fR#include <climits>\fP
.br
\fR#include 'sysc/datatypes/fx/scfx_mant\&.h'\fP
.br
\fR#include 'sysc/datatypes/fx/scfx_params\&.h'\fP
.br
\fR#include 'sysc/datatypes/fx/scfx_string\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_dt::scfx_index\fP"
.br
.ti -1c
.RI "class \fBsc_dt::scfx_rep\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_dt\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_API\fP \fBvoid\fP \fBsc_dt::multiply\fP (\fBscfx_rep\fP &, \fBconst\fP \fBscfx_rep\fP &, \fBconst\fP \fBscfx_rep\fP &, int \fBmax_wl\fP=\fBSC_DEFAULT_MAX_WL_\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBscfx_rep\fP * \fBsc_dt::neg_scfx_rep\fP (\fBconst\fP \fBscfx_rep\fP &)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBscfx_rep\fP * \fBsc_dt::mult_scfx_rep\fP (\fBconst\fP \fBscfx_rep\fP &, \fBconst\fP \fBscfx_rep\fP &, int \fBmax_wl\fP=\fBSC_DEFAULT_MAX_WL_\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBscfx_rep\fP * \fBsc_dt::div_scfx_rep\fP (\fBconst\fP \fBscfx_rep\fP &, \fBconst\fP \fBscfx_rep\fP &, int \fBmax_wl\fP=\fBSC_DEFAULT_DIV_WL_\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBscfx_rep\fP * \fBsc_dt::add_scfx_rep\fP (\fBconst\fP \fBscfx_rep\fP &, \fBconst\fP \fBscfx_rep\fP &, int \fBmax_wl\fP=\fBSC_DEFAULT_MAX_WL_\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBscfx_rep\fP * \fBsc_dt::sub_scfx_rep\fP (\fBconst\fP \fBscfx_rep\fP &, \fBconst\fP \fBscfx_rep\fP &, int \fBmax_wl\fP=\fBSC_DEFAULT_MAX_WL_\fP)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBscfx_rep\fP * \fBsc_dt::lsh_scfx_rep\fP (\fBconst\fP \fBscfx_rep\fP &, int)"
.br
.ti -1c
.RI "\fBSC_API\fP \fBscfx_rep\fP * \fBsc_dt::rsh_scfx_rep\fP (\fBconst\fP \fBscfx_rep\fP &, int)"
.br
.ti -1c
.RI "\fBSC_API\fP int \fBsc_dt::cmp_scfx_rep\fP (\fBconst\fP \fBscfx_rep\fP &, \fBconst\fP \fBscfx_rep\fP &)"
.br
.ti -1c
.RI "\fBscfx_rep\fP * \fBsc_dt::quantization_scfx_rep\fP (\fBconst\fP \fBscfx_rep\fP &\fBa\fP, \fBconst\fP \fBscfx_params\fP &\fBparams\fP, \fBbool\fP &\fBq_flag\fP)"
.br
.ti -1c
.RI "\fBscfx_rep\fP * \fBsc_dt::overflow_scfx_rep\fP (\fBconst\fP \fBscfx_rep\fP &\fBa\fP, \fBconst\fP \fBscfx_params\fP &\fBparams\fP, \fBbool\fP &\fBo_flag\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP int \fBsc_dt::min_mant\fP = 4"
.br
.ti -1c
.RI "\fBconst\fP int \fBsc_dt::bits_in_int\fP = \fBsizeof\fP(int) * \fBCHAR_BIT\fP"
.br
.ti -1c
.RI "\fBconst\fP int \fBsc_dt::bits_in_word\fP = \fBsizeof\fP(\fBword\fP) * \fBCHAR_BIT\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
