.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/scfx_mant.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/datatypes/fx/scfx_mant.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/datatypes/fx/scfx_ieee\&.h'\fP
.br
\fR#include 'sysc/datatypes/fx/scfx_utils\&.h'\fP
.br
\fR#include 'sysc/kernel/sc_macros\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBsc_dt::scfx_mant\fP"
.br
.ti -1c
.RI "class \fBsc_dt::scfx_mant_ref\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_dt\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBunsigned\fP int \fBsc_dt::word\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBunsigned\fP \fBshort\fP \fBsc_dt::half_word\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBsc_dt::complement\fP (\fBscfx_mant\fP &target, \fBconst\fP \fBscfx_mant\fP &\fBsource\fP, int size)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsc_dt::inc\fP (\fBscfx_mant\fP &\fBmant\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
