.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/old_ui_project/qt-sc/scqt_worker.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/old_ui_project/qt-sc/scqt_worker.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'scqt_worker\&.h'\fP
.br
\fR#include <QThread>\fP
.br
\fR#include 'sc_run\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
