.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemC/systemc_modules/scqt_worker.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemC/systemc_modules/scqt_worker.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'scqt_worker\&.h'\fP
.br
\fC#include <QThread>\fP
.br
\fC#include 'sc_run\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
