.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemC/systemc_modules/scregister.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemC/systemc_modules/scregister.cpp
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
