.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/sgi_mipspro.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/sgi_mipspro.hpp
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/packages/boost/config/compiler/common_edg\&.hpp'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_COMPILER\fP   'SGI \fBIrix\fP \fBcompiler\fP \fBversion\fP ' SC_BOOST_STRINGIZE(\fB_COMPILER_VERSION\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_THREADS\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_COMPILER   'SGI \fBIrix\fP \fBcompiler\fP \fBversion\fP ' SC_BOOST_STRINGIZE(\fB_COMPILER_VERSION\fP)"

.SS "#\fBdefine\fP SC_BOOST_HAS_THREADS"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
