.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_utils/simple_initiator_socket.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_utils/simple_initiator_socket.h
.SH SYNOPSIS
.br
.PP
\fR#include <tlm>\fP
.br
\fR#include 'tlm_utils/convenience_socket_bases\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::simple_initiator_socket_b< MODULE, BUSWIDTH, TYPES, POL >::process\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::simple_initiator_socket< MODULE, BUSWIDTH, TYPES >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::simple_initiator_socket_optional< MODULE, BUSWIDTH, TYPES >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::simple_initiator_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::process\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::simple_initiator_socket_tagged< MODULE, BUSWIDTH, TYPES >\fP"
.br
.ti -1c
.RI "class \fBtlm_utils::simple_initiator_socket_tagged_optional< MODULE, BUSWIDTH, TYPES >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtlm_utils\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
