.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/simulation/simulationworker.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/simulation/simulationworker.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'simulationworker\&.h'\fP
.br
\fC#include 'svghandler\&.h'\fP
.br
\fC#include <QThread>\fP
.br
\fC#include <systemC/systemcbuilder\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
