.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/simulationstate.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/simulationstate.h
.SH SYNOPSIS
.br
.PP
\fR#include <QObject>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimulationState\fP"
.br
.RI "The \fBSimulationState\fP class manages the state of the simulation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
