.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/simulation/simulationworker.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/simulation/simulationworker.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include 'ComponentsStruct\&.h'\fP
.br
\fC#include 'SvgParseManager\&.h'\fP
.br
\fC#include 'simulationstate\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimulationWorker\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
