.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/platform/solaris.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/platform/solaris.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <sysc/packages/boost/config/posix_features\&.hpp>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_PLATFORM\fP   'Sun \fBSolaris'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_GETTIMEOFDAY\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_UNISTD_H\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_HAS_GETTIMEOFDAY"

.SS "#\fBdefine\fP SC_BOOST_HAS_UNISTD_H"

.SS "#\fBdefine\fP SC_BOOST_PLATFORM   'Sun \fBSolaris'\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
