.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/stdlib/stlport.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/stdlib/stlport.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <utility>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_ITERATOR_TRAITS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_TEMPLATED_ITERATOR_CONSTRUCTORS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_ALLOCATOR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_PARTIAL_STD_ALLOCATOR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_ALLOCATOR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_WSTRING\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_STD_WSTREAMBUF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_HASH\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_SLIST\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INTRINSIC_WCHAR_T\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_STDLIB\fP   'STLPort \fBstandard\fP \fBlibrary\fP \fBversion\fP ' SC_BOOST_STRINGIZE(\fB__SGI_STL_PORT\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_HAS_HASH"

.SS "#\fBdefine\fP SC_BOOST_HAS_PARTIAL_STD_ALLOCATOR"

.SS "#\fBdefine\fP SC_BOOST_HAS_SLIST"

.SS "#\fBdefine\fP SC_BOOST_NO_INTRINSIC_WCHAR_T"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_ALLOCATOR"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_ALLOCATOR"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_ITERATOR_TRAITS"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_WSTREAMBUF"

.SS "#\fBdefine\fP SC_BOOST_NO_STD_WSTRING"

.SS "#\fBdefine\fP SC_BOOST_NO_TEMPLATED_ITERATOR_CONSTRUCTORS"

.SS "#\fBdefine\fP SC_BOOST_STDLIB   'STLPort \fBstandard\fP \fBlibrary\fP \fBversion\fP ' SC_BOOST_STRINGIZE(\fB__SGI_STL_PORT\fP)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
