.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/qt/stp.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/qt/stp.h
.SH SYNOPSIS
.br
.PP
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBstruct\fP \fBstp_t\fP \fBstp_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBvoid\fP \fBstp_userf_t\fP(\fBvoid\fP *\fBp0\fP)"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBstp_init\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBstp_start\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBstp_create\fP (\fBstp_userf_t\fP *f, \fBvoid\fP *\fBp0\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBstp_yield\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBstp_abort\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBstruct\fP \fBstp_t\fP \fBstp_t\fP"

.SS "\fBtypedef\fP \fBvoid\fP stp_userf_t(\fBvoid\fP *\fBp0\fP)"

.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP stp_abort (\fBvoid\fP)\fR [extern]\fP"

.SS "\fBvoid\fP stp_create (\fBstp_userf_t\fP * f, \fBvoid\fP * p0)\fR [extern]\fP"

.SS "\fBvoid\fP stp_init ()\fR [extern]\fP"

.SS "\fBvoid\fP stp_start (\fBvoid\fP)\fR [extern]\fP"

.SS "\fBvoid\fP stp_yield (\fBvoid\fP)\fR [extern]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
