.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/utility/string_view_fwd.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/utility/string_view_fwd.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <sysc/packages/boost/config\&.hpp>\fP
.br
\fR#include <string>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsc_boost\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_CXX11_CHAR16_T\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_CXX11_CHAR32_T\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBbasic_string_view\fP< \fBchar\fP, std::char_traits< \fBchar\fP > > \fBsc_boost::string_view\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBbasic_string_view\fP< \fBwchar_t\fP, std::char_traits< \fBwchar_t\fP > > \fBsc_boost::wstring_view\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_NO_CXX11_CHAR16_T"

.SS "#\fBdefine\fP SC_BOOST_NO_CXX11_CHAR32_T"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
