.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/suffix.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/suffix.hpp
.SH SYNOPSIS
.br
.PP
\fR#include <limits\&.h>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INTEGRAL_INT64_T\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_STD_EXTENSION_NAMESPACE\fP   std"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_LONG_LONG_NUMERIC_LIMITS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MS_INT64_NUMERIC_LIMITS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_MSVC6_MEMBER_TEMPLATES\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_PARTIAL_STD_ALLOCATOR\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_SLIST\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_HASH\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_PREVENT_MACRO_SUBSTITUTION\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_USING_STD_MIN\fP()   \fBusing\fP std::min"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_USING_STD_MAX\fP()   \fBusing\fP std::max"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_STATIC_CONSTANT\fP(type,  \fBassignment\fP)   \fBstatic\fP \fBconst\fP type \fBassignment\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_USE_FACET\fP(\fBType\fP,  \fBloc\fP)   std::use_facet< \fBType\fP >(\fBloc\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_FACET\fP(\fBType\fP,  \fBloc\fP)   std::has_facet< \fBType\fP >(\fBloc\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NESTED_TEMPLATE\fP   \fBtemplate\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_UNREACHABLE_RETURN\fP(\fBx\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_DEDUCED_TYPENAME\fP   \fBtypename\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_EXPLICIT_TEMPLATE_TYPE\fP(t)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_EXPLICIT_TEMPLATE_TYPE_SPEC\fP(t)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_EXPLICIT_TEMPLATE_NON_TYPE\fP(t,  v)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_EXPLICIT_TEMPLATE_NON_TYPE_SPEC\fP(t,  v)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_APPEND_EXPLICIT_TEMPLATE_TYPE\fP(t)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_APPEND_EXPLICIT_TEMPLATE_TYPE_SPEC\fP(t)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_APPEND_EXPLICIT_TEMPLATE_NON_TYPE\fP(t,  v)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_APPEND_EXPLICIT_TEMPLATE_NON_TYPE_SPEC\fP(t,  v)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_STRINGIZE\fP(X)   \fBSC_BOOST_DO_STRINGIZE\fP(X)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_DO_STRINGIZE\fP(X)   #X"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_JOIN\fP(X,  \fBY\fP)   \fBSC_BOOST_DO_JOIN\fP( X, \fBY\fP )"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_DO_JOIN\fP(X,  \fBY\fP)   \fBSC_BOOST_DO_JOIN2\fP(X,\fBY\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_DO_JOIN2\fP(X,  \fBY\fP)   X##\fBY\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_COMPILER\fP   'Unknown \fBISO\fP \fBC\fP++ \fBCompiler'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_STDLIB\fP   'Unknown \fBISO\fP \fBstandard\fP \fBlibrary'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_PLATFORM\fP   'Unknown'"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_APPEND_EXPLICIT_TEMPLATE_NON_TYPE(t, v)"

.SS "#\fBdefine\fP SC_BOOST_APPEND_EXPLICIT_TEMPLATE_NON_TYPE_SPEC(t, v)"

.SS "#\fBdefine\fP SC_BOOST_APPEND_EXPLICIT_TEMPLATE_TYPE(t)"

.SS "#\fBdefine\fP SC_BOOST_APPEND_EXPLICIT_TEMPLATE_TYPE_SPEC(t)"

.SS "#\fBdefine\fP SC_BOOST_COMPILER   'Unknown \fBISO\fP \fBC\fP++ \fBCompiler'\fP"

.SS "#\fBdefine\fP SC_BOOST_DEDUCED_TYPENAME   \fBtypename\fP"

.SS "#\fBdefine\fP SC_BOOST_DO_JOIN(X, \fBY\fP)   \fBSC_BOOST_DO_JOIN2\fP(X,\fBY\fP)"

.SS "#\fBdefine\fP SC_BOOST_DO_JOIN2(X, \fBY\fP)   X##\fBY\fP"

.SS "#\fBdefine\fP SC_BOOST_DO_STRINGIZE(X)   #X"

.SS "#\fBdefine\fP SC_BOOST_EXPLICIT_TEMPLATE_NON_TYPE(t, v)"

.SS "#\fBdefine\fP SC_BOOST_EXPLICIT_TEMPLATE_NON_TYPE_SPEC(t, v)"

.SS "#\fBdefine\fP SC_BOOST_EXPLICIT_TEMPLATE_TYPE(t)"

.SS "#\fBdefine\fP SC_BOOST_EXPLICIT_TEMPLATE_TYPE_SPEC(t)"

.SS "#\fBdefine\fP SC_BOOST_HAS_FACET(\fBType\fP, \fBloc\fP)   std::has_facet< \fBType\fP >(\fBloc\fP)"

.SS "#\fBdefine\fP SC_BOOST_HAS_PARTIAL_STD_ALLOCATOR"

.SS "#\fBdefine\fP SC_BOOST_JOIN(X, \fBY\fP)   \fBSC_BOOST_DO_JOIN\fP( X, \fBY\fP )"

.SS "#\fBdefine\fP SC_BOOST_MSVC6_MEMBER_TEMPLATES"

.SS "#\fBdefine\fP SC_BOOST_NESTED_TEMPLATE   \fBtemplate\fP"

.SS "#\fBdefine\fP SC_BOOST_NO_HASH"

.SS "#\fBdefine\fP SC_BOOST_NO_INTEGRAL_INT64_T"

.SS "#\fBdefine\fP SC_BOOST_NO_LONG_LONG_NUMERIC_LIMITS"

.SS "#\fBdefine\fP SC_BOOST_NO_MS_INT64_NUMERIC_LIMITS"

.SS "#\fBdefine\fP SC_BOOST_NO_SLIST"

.SS "#\fBdefine\fP SC_BOOST_PLATFORM   'Unknown'"

.SS "#\fBdefine\fP SC_BOOST_PREVENT_MACRO_SUBSTITUTION"

.SS "#\fBdefine\fP SC_BOOST_STATIC_CONSTANT(type, \fBassignment\fP)   \fBstatic\fP \fBconst\fP type \fBassignment\fP"

.SS "#\fBdefine\fP SC_BOOST_STD_EXTENSION_NAMESPACE   std"

.SS "#\fBdefine\fP SC_BOOST_STDLIB   'Unknown \fBISO\fP \fBstandard\fP \fBlibrary'\fP"

.SS "#\fBdefine\fP SC_BOOST_STRINGIZE(X)   \fBSC_BOOST_DO_STRINGIZE\fP(X)"

.SS "#\fBdefine\fP SC_BOOST_UNREACHABLE_RETURN(\fBx\fP)"

.SS "#\fBdefine\fP SC_BOOST_USE_FACET(\fBType\fP, \fBloc\fP)   std::use_facet< \fBType\fP >(\fBloc\fP)"

.SS "#\fBdefine\fP SC_BOOST_USING_STD_MAX()   \fBusing\fP std::max"

.SS "#\fBdefine\fP SC_BOOST_USING_STD_MIN()   \fBusing\fP std::min"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
