.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/sunpro_cc.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/sunpro_cc.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MEMBER_TEMPLATES\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_FUNCTION_TEMPLATE_ORDERING\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INCLASS_MEMBER_INITIALIZATION\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_TEMPLATE_PARTIAL_SPECIALIZATION\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INCLASS_MEMBER_INITIALIZATION\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INTEGRAL_INT64_T\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_TEMPLATE_TEMPLATES\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INCLASS_MEMBER_INITIALIZATION\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_SFINAE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_ARRAY_TYPE_SPECIALIZATIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_IS_ABSTRACT\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_COMPILER\fP   'Sun \fBcompiler\fP \fBversion\fP ' SC_BOOST_STRINGIZE(\fB__SUNPRO_CC\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_COMPILER   'Sun \fBcompiler\fP \fBversion\fP ' SC_BOOST_STRINGIZE(\fB__SUNPRO_CC\fP)"

.SS "#\fBdefine\fP SC_BOOST_NO_ARRAY_TYPE_SPECIALIZATIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_FUNCTION_TEMPLATE_ORDERING"

.SS "#\fBdefine\fP SC_BOOST_NO_INCLASS_MEMBER_INITIALIZATION"

.SS "#\fBdefine\fP SC_BOOST_NO_INCLASS_MEMBER_INITIALIZATION"

.SS "#\fBdefine\fP SC_BOOST_NO_INCLASS_MEMBER_INITIALIZATION"

.SS "#\fBdefine\fP SC_BOOST_NO_INTEGRAL_INT64_T"

.SS "#\fBdefine\fP SC_BOOST_NO_IS_ABSTRACT"

.SS "#\fBdefine\fP SC_BOOST_NO_MEMBER_TEMPLATES"

.SS "#\fBdefine\fP SC_BOOST_NO_SFINAE"

.SS "#\fBdefine\fP SC_BOOST_NO_TEMPLATE_PARTIAL_SPECIALIZATION"

.SS "#\fBdefine\fP SC_BOOST_NO_TEMPLATE_TEMPLATES"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
