.TH "SVG_Viewer" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SVG_Viewer
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SVG_Viewer\&.h>\fP
.PP
Inherits QThread\&.
.SS "Public Slots"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBsetHighlight\fP (\fBbool\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_verticalSlider_valueChanged\fP (int \fBvalue\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_lineEdit_textEdited\fP (\fBconst\fP \fBQString\fP &\fBarg1\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_lineEdit_returnPressed\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBcheckLeft\fP (\fBbool\fP state)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcheckRight\fP (\fBbool\fP state)"
.br
.in -1c
.SS "Signals"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBmonSignal\fP (\fBbool\fP \fBvalue\fP)"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSVG_Viewer\fP (QObject *parent)"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBgetItem\fP ()"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBgetItem1\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBwheelEvent\fP (\fBQWheelEvent\fP *event)"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBgetText\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBgetTotal\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBQSvgRenderer\fP * \fBgetRenderer\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBgetTxt\fP ()"
.br
.ti -1c
.RI "\fBQByteArray\fP \fBgetBytes\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBQGraphicsScene\fP * \fBgetScene\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBQDomDocument\fP * \fBgetDom\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetApp\fP (\fBQApplication\fP \fBnewApp\fP)"
.br
.ti -1c
.RI "\fBQDomElement\fP \fBgetDom_el\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBQStringList\fP * \fBgetStrDom\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBQDomElement\fP * \fBgetElem\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBQStringList\fP * \fBgetStrDomValues\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBQList\fP< \fBunsigned\fP int > * \fBgetIndex_elem\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBQList\fP< \fBQDomElement\fP > * \fBgetListElem\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBrefresh\fP ()"
.br
.ti -1c
.RI "\fBQStringList\fP * \fBgetPrior_value\fP () \fBconst\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBitem\fP"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBitem1\fP"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBtext\fP"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBtxt\fP"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBred\fP"
.br
.ti -1c
.RI "\fBQSvgRenderer\fP * \fBrenderer\fP"
.br
.ti -1c
.RI "\fBQLabel\fP * \fBlabl\fP"
.br
.ti -1c
.RI "\fBQPaintDevice\fP * \fBpaint\fP"
.br
.ti -1c
.RI "\fBQSvgWidget\fP * \fBwidg\fP"
.br
.ti -1c
.RI "\fBQByteArray\fP \fBbytes\fP"
.br
.ti -1c
.RI "\fBQGraphicsScene\fP * \fBscene\fP"
.br
.ti -1c
.RI "\fBQDomDocument\fP * \fBdom\fP"
.br
.ti -1c
.RI "\fBQString\fP * \fBstr_line\fP"
.br
.ti -1c
.RI "\fBQString\fP \fBdisplay_left\fP"
.br
.ti -1c
.RI "\fBQString\fP \fBdisplay_right\fP"
.br
.ti -1c
.RI "\fBQString\fP \fBcolor_left\fP"
.br
.ti -1c
.RI "\fBQString\fP \fBcolor_left_dom\fP"
.br
.ti -1c
.RI "\fBQString\fP \fBcolor_right_dom\fP"
.br
.ti -1c
.RI "\fBQString\fP \fBcolor_right\fP"
.br
.ti -1c
.RI "\fBQStringList\fP * \fBprior_value\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBleft_txt\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBright_txt\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBret_dom_el_left\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBret_dom_el_right\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBret_dom_el_left_txt\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBret_dom_el_right_txt\fP"
.br
.ti -1c
.RI "\fBQDomElement\fP \fBdom_el_left\fP"
.br
.ti -1c
.RI "\fBQDomElement\fP \fBdom_el_right\fP"
.br
.ti -1c
.RI "\fBQDomElement\fP \fBdom_el_left_txt\fP"
.br
.ti -1c
.RI "\fBQDomElement\fP \fBdom_el_right_txt\fP"
.br
.ti -1c
.RI "\fBQDomElement\fP \fBdom_el\fP"
.br
.ti -1c
.RI "\fBQStringList\fP * \fBstrDom\fP"
.br
.ti -1c
.RI "\fBQStringList\fP * \fBstrDomValues\fP"
.br
.ti -1c
.RI "\fBQList\fP< \fBQDomElement\fP > * \fBlistElem\fP"
.br
.ti -1c
.RI "\fBQList\fP< \fBunsigned\fP int > * \fBindex_elem\fP"
.br
.ti -1c
.RI "\fBQDomElement\fP * \fBelem\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SVG_Viewer::SVG_Viewer (QObject * parent)"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP SVG_Viewer::checkLeft (\fBbool\fP state)\fR [slot]\fP"

.SS "\fBvoid\fP SVG_Viewer::checkRight (\fBbool\fP state)\fR [slot]\fP"

.SS "\fBQByteArray\fP SVG_Viewer::getBytes () const"

.SS "\fBQDomDocument\fP * SVG_Viewer::getDom () const"

.SS "\fBQDomElement\fP SVG_Viewer::getDom_el () const"

.SS "\fBQDomElement\fP * SVG_Viewer::getElem () const"

.SS "\fBQList\fP< \fBunsigned\fP int > * SVG_Viewer::getIndex_elem () const"

.SS "\fBQGraphicsSvgItem\fP * SVG_Viewer::getItem (\fBvoid\fP)"

.SS "\fBQGraphicsSvgItem\fP * SVG_Viewer::getItem1 (\fBvoid\fP)"

.SS "\fBQList\fP< \fBQDomElement\fP > * SVG_Viewer::getListElem () const"

.SS "\fBQStringList\fP * SVG_Viewer::getPrior_value () const"

.SS "\fBQSvgRenderer\fP * SVG_Viewer::getRenderer (\fBvoid\fP)"

.SS "\fBQGraphicsScene\fP * SVG_Viewer::getScene () const"

.SS "\fBQStringList\fP * SVG_Viewer::getStrDom () const"

.SS "\fBQStringList\fP * SVG_Viewer::getStrDomValues () const"

.SS "\fBQGraphicsSvgItem\fP * SVG_Viewer::getText (\fBvoid\fP)"

.SS "\fBQGraphicsSvgItem\fP * SVG_Viewer::getTotal (\fBvoid\fP)"

.SS "\fBQGraphicsSvgItem\fP * SVG_Viewer::getTxt (\fBvoid\fP)"

.SS "\fBvoid\fP SVG_Viewer::monSignal (\fBbool\fP value)\fR [signal]\fP"

.SS "\fBvoid\fP SVG_Viewer::on_lineEdit_returnPressed ()\fR [slot]\fP"

.SS "\fBvoid\fP SVG_Viewer::on_lineEdit_textEdited (\fBconst\fP \fBQString\fP & arg1)\fR [slot]\fP"

.SS "\fBvoid\fP SVG_Viewer::on_verticalSlider_valueChanged (int value)\fR [slot]\fP"

.SS "\fBvoid\fP SVG_Viewer::refresh ()"

.SS "\fBvoid\fP SVG_Viewer::setApp (\fBQApplication\fP newApp)"

.SS "\fBvoid\fP SVG_Viewer::setHighlight (\fBbool\fP state)\fR [slot]\fP"

.SS "\fBvoid\fP SVG_Viewer::wheelEvent (\fBQWheelEvent\fP * event)"

.SH "Member Data Documentation"
.PP 
.SS "\fBQByteArray\fP SVG_Viewer::bytes\fR [private]\fP"

.SS "\fBQString\fP SVG_Viewer::color_left\fR [private]\fP"

.SS "\fBQString\fP SVG_Viewer::color_left_dom\fR [private]\fP"

.SS "\fBQString\fP SVG_Viewer::color_right\fR [private]\fP"

.SS "\fBQString\fP SVG_Viewer::color_right_dom\fR [private]\fP"

.SS "\fBQString\fP SVG_Viewer::display_left\fR [private]\fP"

.SS "\fBQString\fP SVG_Viewer::display_right\fR [private]\fP"

.SS "\fBQDomDocument\fP* SVG_Viewer::dom\fR [private]\fP"

.SS "\fBQDomElement\fP SVG_Viewer::dom_el\fR [private]\fP"

.SS "\fBQDomElement\fP SVG_Viewer::dom_el_left\fR [private]\fP"

.SS "\fBQDomElement\fP SVG_Viewer::dom_el_left_txt\fR [private]\fP"

.SS "\fBQDomElement\fP SVG_Viewer::dom_el_right\fR [private]\fP"

.SS "\fBQDomElement\fP SVG_Viewer::dom_el_right_txt\fR [private]\fP"

.SS "\fBQDomElement\fP* SVG_Viewer::elem\fR [private]\fP"

.SS "\fBQList\fP<\fBunsigned\fP int>* SVG_Viewer::index_elem\fR [private]\fP"

.SS "\fBQGraphicsSvgItem\fP* SVG_Viewer::item\fR [private]\fP"

.SS "\fBQGraphicsSvgItem\fP* SVG_Viewer::item1\fR [private]\fP"

.SS "\fBQLabel\fP* SVG_Viewer::labl\fR [private]\fP"

.SS "\fBbool\fP SVG_Viewer::left_txt\fR [private]\fP"

.SS "\fBQList\fP<\fBQDomElement\fP>* SVG_Viewer::listElem\fR [private]\fP"

.SS "\fBQPaintDevice\fP* SVG_Viewer::paint\fR [private]\fP"

.SS "\fBQStringList\fP* SVG_Viewer::prior_value\fR [private]\fP"

.SS "\fBQGraphicsSvgItem\fP* SVG_Viewer::red\fR [private]\fP"

.SS "\fBQSvgRenderer\fP* SVG_Viewer::renderer\fR [private]\fP"

.SS "\fBbool\fP SVG_Viewer::ret_dom_el_left\fR [private]\fP"

.SS "\fBbool\fP SVG_Viewer::ret_dom_el_left_txt\fR [private]\fP"

.SS "\fBbool\fP SVG_Viewer::ret_dom_el_right\fR [private]\fP"

.SS "\fBbool\fP SVG_Viewer::ret_dom_el_right_txt\fR [private]\fP"

.SS "\fBbool\fP SVG_Viewer::right_txt\fR [private]\fP"

.SS "\fBQGraphicsScene\fP* SVG_Viewer::scene\fR [private]\fP"

.SS "\fBQString\fP* SVG_Viewer::str_line\fR [private]\fP"

.SS "\fBQStringList\fP* SVG_Viewer::strDom\fR [private]\fP"

.SS "\fBQStringList\fP* SVG_Viewer::strDomValues\fR [private]\fP"

.SS "\fBQGraphicsSvgItem\fP* SVG_Viewer::text\fR [private]\fP"

.SS "\fBQGraphicsSvgItem\fP* SVG_Viewer::txt\fR [private]\fP"

.SS "\fBQSvgWidget\fP* SVG_Viewer::widg\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
