.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/old_ui_project/SVG_Viewer.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/old_ui_project/SVG_Viewer.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <QWheelEvent>\fP
.br
\fR#include <iostream>\fP
.br
\fR#include <QSvgRenderer>\fP
.br
\fR#include <QLabel>\fP
.br
\fR#include 'qgraphicsscene\&.h'\fP
.br
\fR#include 'SVG_Viewer\&.h'\fP
.br
\fR#include <QMessageBox>\fP
.br
\fR#include <QTextStream>\fP
.br
\fR#include <QFile>\fP
.br
\fR#include <QDataStream>\fP
.br
\fR#include <QChar>\fP
.br
\fR#include <QXmlStreamReader>\fP
.br
\fR#include <QXmlStreamWriter>\fP
.br
\fR#include <QByteArray>\fP
.br
\fR#include <QDir>\fP
.br
\fR#include <QTime>\fP
.br
\fR#include <QWindow>\fP
.br
\fR#include <QRegularExpression>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBid_sep\fP   ':'"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBQDomElement\fP \fBfindDomElement\fP (\fBQString\fP \fBhierarchy_element\fP, \fBQDomDocument\fP dom)"
.br
.ti -1c
.RI "\fBvoid\fP \fBhideDomElement\fP (\fBQDomElement\fP *dm)"
.br
.ti -1c
.RI "\fBvoid\fP \fBshowDomElement\fP (\fBQDomElement\fP *dm)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetTextDomElement\fP (\fBQDomElement\fP *dm, \fBQString\fP str_line)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetTextDomElementSim\fP (\fBQDomElement\fP dm, \fBQString\fP str_line)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetColorDomElement\fP (\fBQDomElement\fP dm, \fBQString\fP \fBcolor\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBhideDomElementSim\fP (\fBQDomElement\fP dm)"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetStyleAttrDomElementSim\fP (\fBQDomElement\fP dm, \fBQString\fP \fBdisp_attr\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBshowDomElementSim\fP (\fBQDomElement\fP dm)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP id_sep   ':'"

.SH "Function Documentation"
.PP 
.SS "\fBQDomElement\fP findDomElement (\fBQString\fP hierarchy_element, \fBQDomDocument\fP dom)"

.SS "\fBvoid\fP hideDomElement (\fBQDomElement\fP * dm)"

.SS "\fBvoid\fP hideDomElementSim (\fBQDomElement\fP dm)"

.SS "\fBvoid\fP setColorDomElement (\fBQDomElement\fP dm, \fBQString\fP color)"

.SS "\fBvoid\fP setStyleAttrDomElementSim (\fBQDomElement\fP dm, \fBQString\fP disp_attr)"

.SS "\fBvoid\fP setTextDomElement (\fBQDomElement\fP * dm, \fBQString\fP str_line)"

.SS "\fBvoid\fP setTextDomElementSim (\fBQDomElement\fP dm, \fBQString\fP str_line)"

.SS "\fBvoid\fP showDomElement (\fBQDomElement\fP * dm)"

.SS "\fBvoid\fP showDomElementSim (\fBQDomElement\fP dm)"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
