.TH "svg_link_parser.h" 3 "SvgVHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
svg_link_parser.h \- Header file for \fBSvgLinkParser\fP class\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <QXmlStreamReader>\fP
.br
\fR#include <QFile>\fP
.br
\fR#include <QDebug>\fP
.br
\fR#include <QXmlStreamAttributes>\fP
.br
\fR#include <QString>\fP
.br
\fR#include <QDomDocument>\fP
.br
\fR#include <vector>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSvgLinkParser\fP"
.br
.RI "The \fBSvgLinkParser\fP class\&. "
.ti -1c
.RI "struct \fBSvgLinkParser::s_io\fP"
.br
.RI "Struct for storing input/output information\&. "
.ti -1c
.RI "struct \fBSvgLinkParser::s_tree_node_info\fP"
.br
.RI "Struct for storing tree node information\&. "
.ti -1c
.RI "struct \fBSvgLinkParser::s_tree_node\fP"
.br
.RI "Struct for representing tree nodes\&. "
.ti -1c
.RI "struct \fBSvgLinkParser::sim_I_O\fP"
.br
.ti -1c
.RI "struct \fBSvgLinkParser::element_io_list\fP"
.br
.RI "Struct for storing element IO information\&. "
.ti -1c
.RI "struct \fBSvgLinkParser::components_list\fP"
.br
.RI "Struct for storing components list\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBDEFAULT_WIDTH\fP   1"
.br
.ti -1c
.RI "#define \fBDEFAULT_INPUT_NAME\fP   'in'"
.br
.ti -1c
.RI "#define \fBDEFAULT_OUTPUT_NAME\fP   'out'"
.br
.ti -1c
.RI "#define \fBIO_NAME_ATTRIBUTE\fP   'inkscape:label'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Header file for \fBSvgLinkParser\fP class\&. 

This file contains the declaration of the \fBSvgLinkParser\fP class, which is responsible for parsing SVG files and extracting electrical links\&. 
.SH "Macro Definition Documentation"
.PP 
.SS "#define DEFAULT_INPUT_NAME   'in'"

.SS "#define DEFAULT_OUTPUT_NAME   'out'"

.SS "#define DEFAULT_WIDTH   1"

.SS "#define IO_NAME_ATTRIBUTE   'inkscape:label'"

.SH "Author"
.PP 
Generated automatically by Doxygen for SvgVHDL simulator from the source code\&.
