.TH "svgComp_s" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
svgComp_s
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBuint32_t\fP \fBid\fP"
.br
.ti -1c
.RI "\fBsvgCompType_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBQString\fP \fBname\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBN\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBWin\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBWout\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBWsel\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBuint32_t\fP svgComp_s::id"

.SS "\fBuint32_t\fP svgComp_s::N"

.SS "\fBQString\fP svgComp_s::name"

.SS "\fBsvgCompType_t\fP svgComp_s::type"

.SS "\fBuint32_t\fP svgComp_s::Win"

.SS "\fBuint32_t\fP svgComp_s::Wout"

.SS "\fBuint32_t\fP svgComp_s::Wsel"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
