.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/svghandler.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/svghandler.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'svghandler\&.h'\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'SvgParseManager\&.h'\fP
.br
\fC#include 'elementsdisplay\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
