.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/svghandler.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/svghandler.h
.SH SYNOPSIS
.br
.PP
\fC#include <QObject>\fP
.br
\fC#include <QTemporaryDir>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include 'svgwidget\&.h'\fP
.br
\fC#include 'simulationstate\&.h'\fP
.br
\fC#include 'elementsdisplay\&.h'\fP
.br
\fC#include 'SvgParseManager\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSvgHandler\fP"
.br
.RI "The SvgHandling class provides functionality to handle SVG files\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
