.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/svghandler.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/svghandler.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'svghandler\&.h'\fP
.br
\fR#include 'mainwindow\&.h'\fP
.br
\fR#include 'SystemcLinker\&.h'\fP
.br
\fR#include 'elementsdisplay\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
