.TH "SvgLinkParser::s_io" 3 "SvgVHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgLinkParser::s_io \- Struct for storing input/output information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.RI "Name of the input/output\&. "
.ti -1c
.RI "uint \fBwidth\fP"
.br
.RI "Width of the input/output\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct for storing input/output information\&. 
.SH "Member Data Documentation"
.PP 
.SS "QString SvgLinkParser::s_io::name"

.PP
Name of the input/output\&. 
.SS "uint SvgLinkParser::s_io::width"

.PP
Width of the input/output\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SvgVHDL simulator from the source code\&.
