.TH "SvgLinkParser::components_list" 3 "SvgVHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgLinkParser::components_list \- Struct for storing components list\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QList< \fBelement_io_list\fP > \fBelements\fP"
.br
.RI "List of elements\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct for storing components list\&. 
.SH "Member Data Documentation"
.PP 
.SS "QList<\fBelement_io_list\fP> SvgLinkParser::components_list::elements"

.PP
List of elements\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SvgVHDL simulator from the source code\&.
