.TH "SvgLinkParser::s_tree_node_info" 3 "SvgVHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgLinkParser::s_tree_node_info \- Struct for storing tree node information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBtag_name\fP"
.br
.RI "Tag name of the node\&. "
.ti -1c
.RI "QString \fBid\fP"
.br
.RI "ID attribute of the node\&. "
.ti -1c
.RI "QString \fBlabel\fP"
.br
.RI "Label attribute of the node\&. "
.ti -1c
.RI "QString \fBtype\fP"
.br
.RI "Type attribute of the node\&. "
.ti -1c
.RI "unsigned int \fBcomponent_in_width\fP"
.br
.RI "Input width of the component\&. "
.ti -1c
.RI "unsigned int \fBcomponent_out_width\fP"
.br
.RI "Output width of the component\&. "
.ti -1c
.RI "std::vector< \fBs_io\fP > \fBinputs\fP"
.br
.RI "Vector of input information\&. "
.ti -1c
.RI "std::vector< \fBs_io\fP > \fBoutputs\fP"
.br
.RI "Vector of output information\&. "
.ti -1c
.RI "bool \fBis_parse_error\fP"
.br
.RI "Flag indicating parsing error\&. "
.ti -1c
.RI "bool \fBhas_been_parsed\fP"
.br
.RI "Flag indicating node has been parsed\&. "
.ti -1c
.RI "std::vector< QString > \fBerror_messages\fP"
.br
.RI "Vector of error messages\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct for storing tree node information\&. 
.SH "Member Data Documentation"
.PP 
.SS "unsigned int SvgLinkParser::s_tree_node_info::component_in_width"

.PP
Input width of the component\&. 
.SS "unsigned int SvgLinkParser::s_tree_node_info::component_out_width"

.PP
Output width of the component\&. 
.SS "std::vector<QString> SvgLinkParser::s_tree_node_info::error_messages"

.PP
Vector of error messages\&. 
.SS "bool SvgLinkParser::s_tree_node_info::has_been_parsed"

.PP
Flag indicating node has been parsed\&. 
.SS "QString SvgLinkParser::s_tree_node_info::id"

.PP
ID attribute of the node\&. 
.SS "std::vector<\fBs_io\fP> SvgLinkParser::s_tree_node_info::inputs"

.PP
Vector of input information\&. 
.SS "bool SvgLinkParser::s_tree_node_info::is_parse_error"

.PP
Flag indicating parsing error\&. 
.SS "QString SvgLinkParser::s_tree_node_info::label"

.PP
Label attribute of the node\&. 
.SS "std::vector<\fBs_io\fP> SvgLinkParser::s_tree_node_info::outputs"

.PP
Vector of output information\&. 
.SS "QString SvgLinkParser::s_tree_node_info::tag_name"

.PP
Tag name of the node\&. 
.SS "QString SvgLinkParser::s_tree_node_info::type"

.PP
Type attribute of the node\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SvgVHDL simulator from the source code\&.
