.TH "SvgLinkParser::sim_I_O" 3 "SvgVHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgLinkParser::sim_I_O
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBname\fP"
.br
.RI "Name of the component\&. "
.ti -1c
.RI "int \fBwidth\fP"
.br
.RI "Width of the component\&. "
.ti -1c
.RI "\fBI_O\fP \fBtype\fP"
.br
.RI "Type of the component\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "QString SvgLinkParser::sim_I_O::name"

.PP
Name of the component\&. 
.SS "\fBI_O\fP SvgLinkParser::sim_I_O::type"

.PP
Type of the component\&. 
.SS "int SvgLinkParser::sim_I_O::width"

.PP
Width of the component\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SvgVHDL simulator from the source code\&.
