.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/parser_linker/SvgParser.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/parser_linker/SvgParser.h
.SH SYNOPSIS
.br
.PP
\fR#include <QXmlStreamReader>\fP
.br
\fR#include <QFile>\fP
.br
\fR#include <QDebug>\fP
.br
\fR#include <QXmlStreamAttributes>\fP
.br
\fR#include <QString>\fP
.br
\fR#include <QDomDocument>\fP
.br
\fR#include 'ComponentsStruct\&.h'\fP
.br
\fR#include 'debugwindow\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSvgParser\fP"
.br
.RI "The \fBSvgParser\fP class\&. "
.ti -1c
.RI "struct \fBSvgParser::s_io\fP"
.br
.RI "Struct for storing input/output information\&. "
.ti -1c
.RI "struct \fBSvgParser::s_tree_node_info\fP"
.br
.RI "Struct for storing tree node information\&. "
.ti -1c
.RI "struct \fBSvgParser::s_tree_node\fP"
.br
.RI "Struct for representing tree nodes\&. "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBDEBUG\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDEFAULT_WIDTH\fP   1"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDEFAULT_INPUT_NAME\fP   'in'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDEFAULT_OUTPUT_NAME\fP   'out'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBDEFAULT_WIRE_NAME\fP   'wire_'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBFORMAT_ERROR\fP   \-10"
.br
.ti -1c
.RI "#\fBdefine\fP \fBFLAG_NAME_FROM_INKSCAPE\fP   'inkscape_label'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBCUSTOM_ATTRIBUTE\fP   'sim'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBNAME_ATTRIBUTE\fP   'inkscape:label'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBATTR_FOR_STR\fP(attr)   (\fBQString\fP(\fBCUSTOM_ATTRIBUTE\fP) + ':' + attr)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP ATTR_FOR_STR(attr)   (\fBQString\fP(\fBCUSTOM_ATTRIBUTE\fP) + ':' + attr)"

.SS "#\fBdefine\fP CUSTOM_ATTRIBUTE   'sim'"

.SS "#\fBdefine\fP DEBUG"

.SS "#\fBdefine\fP DEFAULT_INPUT_NAME   'in'"

.SS "#\fBdefine\fP DEFAULT_OUTPUT_NAME   'out'"

.SS "#\fBdefine\fP DEFAULT_WIDTH   1"

.SS "#\fBdefine\fP DEFAULT_WIRE_NAME   'wire_'"

.SS "#\fBdefine\fP FLAG_NAME_FROM_INKSCAPE   'inkscape_label'"

.SS "#\fBdefine\fP FORMAT_ERROR   \-10"

.SS "#\fBdefine\fP NAME_ATTRIBUTE   'inkscape:label'"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
