.TH "SvgParser::s_tree_node_info" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgParser::s_tree_node_info \- Struct for storing tree node information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SvgParser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQString\fP \fBtag_name\fP"
.br
.RI "Tag name of the node\&. "
.ti -1c
.RI "\fBQString\fP \fBid\fP"
.br
.RI "ID attribute of the node\&. "
.ti -1c
.RI "\fBQString\fP \fBlabel\fP"
.br
.RI "Label attribute of the node\&. "
.ti -1c
.RI "\fBQString\fP \fBtype\fP"
.br
.RI "Type attribute of the node\&. "
.ti -1c
.RI "\fBunsigned\fP \fBint\fP \fBcomponent_in_width\fP"
.br
.RI "Input width of the component\&. "
.ti -1c
.RI "\fBunsigned\fP \fBint\fP \fBcomponent_out_width\fP"
.br
.RI "Output width of the component\&. "
.ti -1c
.RI "\fBQList\fP< \fBs_io\fP > \fBinputs\fP"
.br
.RI "Vector of input information\&. "
.ti -1c
.RI "\fBQList\fP< \fBs_io\fP > \fBoutputs\fP"
.br
.RI "Vector of output information\&. "
.ti -1c
.RI "\fBbool\fP \fBis_parse_error\fP"
.br
.RI "Flag indicating parsing error\&. "
.ti -1c
.RI "\fBbool\fP \fBhas_been_parsed\fP"
.br
.RI "Flag indicating node has been parsed\&. "
.ti -1c
.RI "\fBQList\fP< \fBQString\fP > \fBerror_messages\fP"
.br
.RI "Vector of error messages\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct for storing tree node information\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBunsigned\fP \fBint\fP SvgParser::s_tree_node_info::component_in_width"

.PP
Input width of the component\&. 
.SS "\fBunsigned\fP \fBint\fP SvgParser::s_tree_node_info::component_out_width"

.PP
Output width of the component\&. 
.SS "\fBQList\fP<\fBQString\fP> SvgParser::s_tree_node_info::error_messages"

.PP
Vector of error messages\&. 
.SS "\fBbool\fP SvgParser::s_tree_node_info::has_been_parsed"

.PP
Flag indicating node has been parsed\&. 
.SS "\fBQString\fP SvgParser::s_tree_node_info::id"

.PP
ID attribute of the node\&. 
.SS "\fBQList\fP<\fBs_io\fP> SvgParser::s_tree_node_info::inputs"

.PP
Vector of input information\&. 
.SS "\fBbool\fP SvgParser::s_tree_node_info::is_parse_error"

.PP
Flag indicating parsing error\&. 
.SS "\fBQString\fP SvgParser::s_tree_node_info::label"

.PP
Label attribute of the node\&. 
.SS "\fBQList\fP<\fBs_io\fP> SvgParser::s_tree_node_info::outputs"

.PP
Vector of output information\&. 
.SS "\fBQString\fP SvgParser::s_tree_node_info::tag_name"

.PP
Tag name of the node\&. 
.SS "\fBQString\fP SvgParser::s_tree_node_info::type"

.PP
Type attribute of the node\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
