.TH "SvgParser::s_io" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgParser::s_io \- Struct for storing input/output information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SvgParser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQString\fP \fBname\fP"
.br
.RI "Name of the input/output\&. "
.ti -1c
.RI "\fBuint\fP \fBwidth\fP"
.br
.RI "Width of the input/output\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct for storing input/output information\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBQString\fP SvgParser::s_io::name"

.PP
Name of the input/output\&. 
.SS "\fBuint\fP SvgParser::s_io::width"

.PP
Width of the input/output\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
