.TH "SvgParser::s_components_list" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgParser::s_components_list \- Struct for storing components list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SvgParser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBs_elements\fP \fBelements\fP"
.br
.RI "List of elements\&. "
.ti -1c
.RI "\fBs_sim_I_Os\fP \fBsimulation_IOs\fP"
.br
.RI "List of simulation IO\&. "
.ti -1c
.RI "\fBs_sim_wires\fP \fBsimulation_wires\fP"
.br
.RI "List of simulation wires\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct for storing components list\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBs_elements\fP SvgParser::s_components_list::elements"

.PP
List of elements\&. 
.SS "\fBs_sim_I_Os\fP SvgParser::s_components_list::simulation_IOs"

.PP
List of simulation IO\&. 
.SS "\fBs_sim_wires\fP SvgParser::s_components_list::simulation_wires"

.PP
List of simulation wires\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
