.TH "SvgParser::s_sim_I_O" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgParser::s_sim_I_O \- Struct for storing I/Os information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SvgParser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQString\fP \fBname\fP"
.br
.RI "Name of the component\&. "
.ti -1c
.RI "int \fBwidth\fP"
.br
.RI "Width of the component\&. "
.ti -1c
.RI "\fBe_IO_type\fP \fBtype\fP"
.br
.RI "Type of the I/O\&. "
.ti -1c
.RI "\fBQString\fP \fBconnected_to\fP"
.br
.RI "Connected to (if output) "
.ti -1c
.RI "\fBs_parse_error\fP \fBerror\fP"
.br
.RI "error "
.in -1c
.SH "Detailed Description"
.PP 
Struct for storing I/Os information\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBQString\fP SvgParser::s_sim_I_O::connected_to"

.PP
Connected to (if output) 
.SS "\fBs_parse_error\fP SvgParser::s_sim_I_O::error"

.PP
error 
.SS "\fBQString\fP SvgParser::s_sim_I_O::name"

.PP
Name of the component\&. 
.SS "\fBe_IO_type\fP SvgParser::s_sim_I_O::type"

.PP
Type of the I/O\&. 
.SS "int SvgParser::s_sim_I_O::width"

.PP
Width of the component\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
