.TH "SvgParser::s_sim_I_Os" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgParser::s_sim_I_Os \- Struct for storing all the I/Os\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SvgParser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQList\fP< \fBs_sim_I_O\fP > \fBi_os\fP"
.br
.RI "List of I/Os\&. "
.ti -1c
.RI "\fBs_parse_error\fP \fBerror\fP"
.br
.RI "error "
.in -1c
.SH "Detailed Description"
.PP 
Struct for storing all the I/Os\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBs_parse_error\fP SvgParser::s_sim_I_Os::error"

.PP
error 
.SS "\fBQList\fP<\fBs_sim_I_O\fP> SvgParser::s_sim_I_Os::i_os"

.PP
List of I/Os\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
