.TH "SvgParser::s_sim_wire" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgParser::s_sim_wire \- Struct for storing wire information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SvgParser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQString\fP \fBname\fP"
.br
.RI "wire name "
.ti -1c
.RI "int \fBwidth\fP"
.br
.RI "wire width "
.ti -1c
.RI "\fBQString\fP \fBconnected_to\fP"
.br
.RI "connected to "
.ti -1c
.RI "\fBs_parse_error\fP \fBerror\fP"
.br
.RI "error "
.in -1c
.SH "Detailed Description"
.PP 
Struct for storing wire information\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBQString\fP SvgParser::s_sim_wire::connected_to"

.PP
connected to 
.SS "\fBs_parse_error\fP SvgParser::s_sim_wire::error"

.PP
error 
.SS "\fBQString\fP SvgParser::s_sim_wire::name"

.PP
wire name 
.SS "int SvgParser::s_sim_wire::width"

.PP
wire width 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
