.TH "SvgParser::s_element_io" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgParser::s_element_io
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SvgParser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQString\fP \fBname\fP"
.br
.RI "List of names\&. "
.ti -1c
.RI "int \fBwidth\fP"
.br
.RI "List of widths\&. "
.ti -1c
.RI "\fBQString\fP \fBconnected_to\fP"
.br
.RI "List of connected to\&. "
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBQString\fP SvgParser::s_element_io::connected_to"

.PP
List of connected to\&. 
.SS "\fBQString\fP SvgParser::s_element_io::name"

.PP
List of names\&. 
.SS "int SvgParser::s_element_io::width"

.PP
List of widths\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
