.TH "SvgParser::s_sim_wires" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgParser::s_sim_wires \- Struct for storing all the wires\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <SvgParser\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQList\fP< \fBs_sim_wire\fP > \fBwires\fP"
.br
.RI "List of wires\&. "
.ti -1c
.RI "\fBs_parse_error\fP \fBerror\fP"
.br
.RI "error "
.in -1c
.SH "Detailed Description"
.PP 
Struct for storing all the wires\&. 
.SH "Member Data Documentation"
.PP 
.SS "\fBs_parse_error\fP SvgParser::s_sim_wires::error"

.PP
error 
.SS "\fBQList\fP<\fBs_sim_wire\fP> SvgParser::s_sim_wires::wires"

.PP
List of wires\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
