.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/svgwidget.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/svgwidget.h
.SH SYNOPSIS
.br
.PP
\fR#include <QWidget>\fP
.br
\fR#include <QGraphicsView>\fP
.br
\fR#include <QGraphicsSvgItem>\fP
.br
\fR#include <QSlider>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSvgWidget\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBBASE_ZOOM\fP   50"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP BASE_ZOOM   50"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
