.TH "SvgWidget::s_style_lists" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgWidget::s_style_lists
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBs_style\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBQList\fP< \fBs_style\fP > \fBstyles\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBQList\fP<\fBs_style\fP> SvgWidget::s_style_lists::styles"
A list of styles to be modified\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
