.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/svgwidget.cpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/svgwidget.cpp
.SH SYNOPSIS
.br
.PP
\fR#include 'svgwidget\&.h'\fP
.br
\fR#include <QVBoxLayout>\fP
.br
\fR#include <QGraphicsScene>\fP
.br
\fR#include <QGraphicsView>\fP
.br
\fR#include <QGraphicsSvgItem>\fP
.br
\fR#include <QWheelEvent>\fP
.br
\fR#include <QScrollBar>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBmin\fP(\fBX\fP,  \fBY\fP)   (((\fBX\fP) < (\fBY\fP)) ? (\fBX\fP) : (\fBY\fP))"
.br
.ti -1c
.RI "#\fBdefine\fP \fBmax\fP(\fBX\fP,  \fBY\fP)   (((\fBX\fP) > (\fBY\fP)) ? (\fBX\fP) : (\fBY\fP))"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP max(\fBX\fP, \fBY\fP)   (((\fBX\fP) > (\fBY\fP)) ? (\fBX\fP) : (\fBY\fP))"

.SS "#\fBdefine\fP min(\fBX\fP, \fBY\fP)   (((\fBX\fP) < (\fBY\fP)) ? (\fBX\fP) : (\fBY\fP))"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
