.TH "SvgWidget::s_style_lists::s_style" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgWidget::s_style_lists::s_style
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <svgwidget\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBQString\fP \fBname\fP"
.br
.ti -1c
.RI "   \fBQString\fP \fBvalue\fP"
.br
.ti -1c
.RI "} \fBdef\fP"
.br
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   \fBQString\fP \fBname\fP"
.br
.ti -1c
.RI "   \fBQString\fP \fBvalue\fP"
.br
.ti -1c
.RI "} \fBon\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "struct  { \&.\&.\&. }  SvgWidget::s_style_lists::s_style::def"

.SS "\fBQString\fP SvgWidget::s_style_lists::s_style::name"
The name of the style attribute (\fBe\&.g\fP\&., 'stroke')\&. 
.SS "struct  { \&.\&.\&. }  SvgWidget::s_style_lists::s_style::on"
Default and 'on' state of the style\&. 
.SS "\fBQString\fP SvgWidget::s_style_lists::s_style::value"
The value of the style attribute (\fBe\&.g\fP\&., '#000000')\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
