.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/svgwidget.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/gui/svgwidget.h \- This file contains the \fBSvgWidget\fP class, which provides functionality for loading, displaying, and interacting with SVG files in a QWidget using QGraphicsView and QGraphicsSvgItem\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QGraphicsView>\fP
.br
\fC#include <QGraphicsSvgItem>\fP
.br
\fC#include <QSlider>\fP
.br
\fC#include <QDomDocument>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSvgWidget\fP"
.br
.RI "The \fBSvgWidget\fP class allows for loading, viewing, and interacting with SVG files using Qt's graphics framework\&. "
.ti -1c
.RI "struct \fBSvgWidget::s_style_lists\fP"
.br
.ti -1c
.RI "struct \fBSvgWidget::s_style_lists::s_style\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBBASE_ZOOM\fP   50"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains the \fBSvgWidget\fP class, which provides functionality for loading, displaying, and interacting with SVG files in a QWidget using QGraphicsView and QGraphicsSvgItem\&. 


.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP BASE_ZOOM   50"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
