.TH "SvgWidget" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgWidget
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <svgwidget\&.h>\fP
.PP
Inherits QWidget\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSvgWidget\fP (QWidget *\fBparent\fP=\fBnullptr\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBloadSvg\fP (\fBconst\fP \fBQString\fP &\fBfilePath\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBclearSvg\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBclearScene\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBsetZoom\fP (\fBint\fP \fBvalue\fP)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBwheelEvent\fP (\fBQWheelEvent\fP *\fBevent\fP) \fBoverride\fP"
.br
.in -1c
.SS "Private Slots"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBzoomChanged\fP (\fBint\fP \fBvalue\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBQGraphicsView\fP * \fBgraphicsView\fP"
.br
.ti -1c
.RI "\fBQGraphicsSvgItem\fP * \fBsvgItem\fP"
.br
.ti -1c
.RI "\fBQSlider\fP * \fBzoomSlider\fP"
.br
.ti -1c
.RI "\fBQPoint\fP \fBlastMousePos\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBpanning\fP"
.br
.ti -1c
.RI "\fBint\fP \fBzoomValue\fP = \fBBASE_ZOOM\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SvgWidget::SvgWidget (QWidget * parent = \fR\fBnullptr\fP\fP)\fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP SvgWidget::clearScene ()"

.SS "\fBvoid\fP SvgWidget::clearSvg ()"

.SS "\fBvoid\fP SvgWidget::loadSvg (\fBconst\fP \fBQString\fP & filePath)"

.SS "\fBvoid\fP SvgWidget::setZoom (\fBint\fP value)"

.SS "\fBvoid\fP SvgWidget::wheelEvent (\fBQWheelEvent\fP * event)\fR [override]\fP, \fR [protected]\fP"

.SS "\fBvoid\fP SvgWidget::zoomChanged (\fBint\fP value)\fR [private]\fP, \fR [slot]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBQGraphicsView\fP* SvgWidget::graphicsView\fR [private]\fP"

.SS "\fBQPoint\fP SvgWidget::lastMousePos\fR [private]\fP"

.SS "\fBbool\fP SvgWidget::panning\fR [private]\fP"

.SS "\fBQGraphicsSvgItem\fP* SvgWidget::svgItem\fR [private]\fP"

.SS "\fBQSlider\fP* SvgWidget::zoomSlider\fR [private]\fP"

.SS "\fBint\fP SvgWidget::zoomValue = \fBBASE_ZOOM\fP\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
