.TH "SyscMuxT_pv< N, W, SEL_INVALID_BEH, SEL_XORZ_CONV >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyscMuxT_pv< N, W, SEL_INVALID_BEH, SEL_XORZ_CONV >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_mux\&.h>\fP
.PP
Inherits sc_core::sc_module\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< \fBW\fP > \fBdata_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< \fBlog2_N_\fP > \fBsel_t\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSC_CTOR\fP (\fBSyscMuxT_pv\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBcombinational\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsc_vector\fP< \fBsc_in\fP< \fBdata_t\fP > > \fBd\fP"
.br
.ti -1c
.RI "\fBsc_in\fP< \fBsel_t\fP > \fBsel\fP {'sel'}"
.br
.ti -1c
.RI "\fBsc_out\fP< \fBdata_t\fP > \fBy\fP {'y'}"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBunsigned\fP \fBint\fP \fBlog2_N_\fP = \fBstatic_cast\fP<\fBint\fP>(\fBceil\fP(\fBlog\fP(\fBN\fP)))"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBdata_t\fP \fBall0\fP {\fB::sc_dt::SC_LOGIC_0\fP}"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBdata_t\fP \fBall1\fP {\fB::sc_dt::SC_LOGIC_1\fP}"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1, \fBMUX_SEL_INVALID_BEH_t\fP SEL_INVALID_BEH = MUX_BEH_SEL_INVALID_ZEROES, \fBMUX_CONV_SEL_XORZ_t\fP SEL_XORZ_CONV = MUX_CONV_SEL_XORZ_FIRST> \fBtypedef\fP \fBsc_lv\fP<\fBW\fP> \fBSyscMuxT_pv\fP< \fBN\fP, \fBW\fP, \fBSEL_INVALID_BEH\fP, \fBSEL_XORZ_CONV\fP >::data_t"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1, \fBMUX_SEL_INVALID_BEH_t\fP SEL_INVALID_BEH = MUX_BEH_SEL_INVALID_ZEROES, \fBMUX_CONV_SEL_XORZ_t\fP SEL_XORZ_CONV = MUX_CONV_SEL_XORZ_FIRST> \fBtypedef\fP \fBsc_lv\fP<\fBlog2_N_\fP> \fBSyscMuxT_pv\fP< \fBN\fP, \fBW\fP, \fBSEL_INVALID_BEH\fP, \fBSEL_XORZ_CONV\fP >::sel_t"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1, \fBMUX_SEL_INVALID_BEH_t\fP SEL_INVALID_BEH = MUX_BEH_SEL_INVALID_ZEROES, \fBMUX_CONV_SEL_XORZ_t\fP SEL_XORZ_CONV = MUX_CONV_SEL_XORZ_FIRST> \fBvoid\fP \fBSyscMuxT_pv\fP< \fBN\fP, \fBW\fP, \fBSEL_INVALID_BEH\fP, \fBSEL_XORZ_CONV\fP >::combinational ()\fR [inline]\fP"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1, \fBMUX_SEL_INVALID_BEH_t\fP SEL_INVALID_BEH = MUX_BEH_SEL_INVALID_ZEROES, \fBMUX_CONV_SEL_XORZ_t\fP SEL_XORZ_CONV = MUX_CONV_SEL_XORZ_FIRST> \fBSyscMuxT_pv\fP< \fBN\fP, \fBW\fP, \fBSEL_INVALID_BEH\fP, \fBSEL_XORZ_CONV\fP >::SC_CTOR (\fBSyscMuxT_pv\fP< \fBN\fP, \fBW\fP, \fBSEL_INVALID_BEH\fP, \fBSEL_XORZ_CONV\fP >)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1, \fBMUX_SEL_INVALID_BEH_t\fP SEL_INVALID_BEH = MUX_BEH_SEL_INVALID_ZEROES, \fBMUX_CONV_SEL_XORZ_t\fP SEL_XORZ_CONV = MUX_CONV_SEL_XORZ_FIRST> \fBconst\fP \fBdata_t\fP \fBSyscMuxT_pv\fP< \fBN\fP, \fBW\fP, \fBSEL_INVALID_BEH\fP, \fBSEL_XORZ_CONV\fP >::all0 {\fB::sc_dt::SC_LOGIC_0\fP}\fR [inline]\fP, \fR [static]\fP"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1, \fBMUX_SEL_INVALID_BEH_t\fP SEL_INVALID_BEH = MUX_BEH_SEL_INVALID_ZEROES, \fBMUX_CONV_SEL_XORZ_t\fP SEL_XORZ_CONV = MUX_CONV_SEL_XORZ_FIRST> \fBconst\fP \fBdata_t\fP \fBSyscMuxT_pv\fP< \fBN\fP, \fBW\fP, \fBSEL_INVALID_BEH\fP, \fBSEL_XORZ_CONV\fP >::all1 {\fB::sc_dt::SC_LOGIC_1\fP}\fR [inline]\fP, \fR [static]\fP"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1, \fBMUX_SEL_INVALID_BEH_t\fP SEL_INVALID_BEH = MUX_BEH_SEL_INVALID_ZEROES, \fBMUX_CONV_SEL_XORZ_t\fP SEL_XORZ_CONV = MUX_CONV_SEL_XORZ_FIRST> \fBsc_vector\fP<\fBsc_in\fP<\fBdata_t\fP> > \fBSyscMuxT_pv\fP< \fBN\fP, \fBW\fP, \fBSEL_INVALID_BEH\fP, \fBSEL_XORZ_CONV\fP >::d"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1, \fBMUX_SEL_INVALID_BEH_t\fP SEL_INVALID_BEH = MUX_BEH_SEL_INVALID_ZEROES, \fBMUX_CONV_SEL_XORZ_t\fP SEL_XORZ_CONV = MUX_CONV_SEL_XORZ_FIRST> \fBconst\fP \fBunsigned\fP \fBint\fP \fBSyscMuxT_pv\fP< \fBN\fP, \fBW\fP, \fBSEL_INVALID_BEH\fP, \fBSEL_XORZ_CONV\fP >::log2_N_ = \fBstatic_cast\fP<\fBint\fP>(\fBceil\fP(\fBlog\fP(\fBN\fP)))\fR [inline]\fP, \fR [static]\fP"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1, \fBMUX_SEL_INVALID_BEH_t\fP SEL_INVALID_BEH = MUX_BEH_SEL_INVALID_ZEROES, \fBMUX_CONV_SEL_XORZ_t\fP SEL_XORZ_CONV = MUX_CONV_SEL_XORZ_FIRST> \fBsc_in\fP<\fBsel_t\fP> \fBSyscMuxT_pv\fP< \fBN\fP, \fBW\fP, \fBSEL_INVALID_BEH\fP, \fBSEL_XORZ_CONV\fP >::sel {'sel'}"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1, \fBMUX_SEL_INVALID_BEH_t\fP SEL_INVALID_BEH = MUX_BEH_SEL_INVALID_ZEROES, \fBMUX_CONV_SEL_XORZ_t\fP SEL_XORZ_CONV = MUX_CONV_SEL_XORZ_FIRST> \fBsc_out\fP<\fBdata_t\fP> \fBSyscMuxT_pv\fP< \fBN\fP, \fBW\fP, \fBSEL_INVALID_BEH\fP, \fBSEL_XORZ_CONV\fP >::y {'y'}"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
