.TH "SyscTri< W, TRI_XORZ_CONV >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyscTri< W, TRI_XORZ_CONV >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_tri\&.h>\fP
.PP
Inherits \fBSyscLogicGate< N, W >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< 1 > \fBctl_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscLogicGate\fP< 1, \fBW\fP > \fBBASE_MODULE\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscTri\fP< \fBW\fP, \fBTRI_XORZ_CONV\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c

Public Types inherited from \fBSyscLogicGate< N, W >\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< \fBW\fP > \fBdata_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscLogicGate\fP< \fBN\fP, \fBW\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyscTri\fP (::sc_core::sc_module_name name)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBcombinational\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBSyscLogicGate< N, W >\fP
.in +1c
.ti -1c
.RI "\fBSyscLogicGate\fP (::sc_core::sc_module_name name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsc_in\fP< \fBctl_t\fP > \fBctl\fP {'ctl'}"
.br
.in -1c

Public Attributes inherited from \fBSyscLogicGate< N, W >\fP
.in +1c
.ti -1c
.RI "\fBsc_in\fP< \fBdata_t\fP > * \fBd\fP [\fBN\fP]"
.br
.ti -1c
.RI "\fBsc_out\fP< \fBdata_t\fP > \fBy\fP {'y'}"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBsc_lv\fP< 1 > \fBy_is_d\fP {\fB::sc_dt::SC_LOGIC_1\fP}"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBBASE_MODULE::data_t\fP \fBallx\fP {\fB::sc_dt::SC_LOGIC_X\fP}"
.br
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBBASE_MODULE::data_t\fP \fBallz\fP {\fB::sc_dt::SC_LOGIC_Z\fP}"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBTRI_CONV_CTL_XORZ_t\fP TRI_XORZ_CONV = TRI_CONV_CTL_XORZ_X> \fBtypedef\fP \fBSyscLogicGate\fP<1,\fBW\fP> \fBSyscTri\fP< \fBW\fP, \fBTRI_XORZ_CONV\fP >::BASE_MODULE"

.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBTRI_CONV_CTL_XORZ_t\fP TRI_XORZ_CONV = TRI_CONV_CTL_XORZ_X> \fBtypedef\fP \fBsc_lv\fP<1> \fBSyscTri\fP< \fBW\fP, \fBTRI_XORZ_CONV\fP >::ctl_t"

.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBTRI_CONV_CTL_XORZ_t\fP TRI_XORZ_CONV = TRI_CONV_CTL_XORZ_X> \fBtypedef\fP \fBSyscTri\fP<\fBW\fP,\fBTRI_XORZ_CONV\fP> \fBSyscTri\fP< \fBW\fP, \fBTRI_XORZ_CONV\fP >::SC_CURRENT_USER_MODULE"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBTRI_CONV_CTL_XORZ_t\fP TRI_XORZ_CONV = TRI_CONV_CTL_XORZ_X> \fBSyscTri\fP< \fBW\fP, \fBTRI_XORZ_CONV\fP >\fB::SyscTri\fP (::sc_core::sc_module_name name)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBTRI_CONV_CTL_XORZ_t\fP TRI_XORZ_CONV = TRI_CONV_CTL_XORZ_X> \fBvirtual\fP \fBvoid\fP \fBSyscTri\fP< \fBW\fP, \fBTRI_XORZ_CONV\fP >::combinational ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBSyscLogicGate< N, W >\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBTRI_CONV_CTL_XORZ_t\fP TRI_XORZ_CONV = TRI_CONV_CTL_XORZ_X> \fBconst\fP \fBBASE_MODULE::data_t\fP \fBSyscTri\fP< \fBW\fP, \fBTRI_XORZ_CONV\fP >::allx {\fB::sc_dt::SC_LOGIC_X\fP}\fR [inline]\fP, \fR [static]\fP"

.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBTRI_CONV_CTL_XORZ_t\fP TRI_XORZ_CONV = TRI_CONV_CTL_XORZ_X> \fBconst\fP \fBBASE_MODULE::data_t\fP \fBSyscTri\fP< \fBW\fP, \fBTRI_XORZ_CONV\fP >::allz {\fB::sc_dt::SC_LOGIC_Z\fP}\fR [inline]\fP, \fR [static]\fP"

.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBTRI_CONV_CTL_XORZ_t\fP TRI_XORZ_CONV = TRI_CONV_CTL_XORZ_X> \fBsc_in\fP<\fBctl_t\fP> \fBSyscTri\fP< \fBW\fP, \fBTRI_XORZ_CONV\fP >::ctl {'ctl'}"

.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBTRI_CONV_CTL_XORZ_t\fP TRI_XORZ_CONV = TRI_CONV_CTL_XORZ_X> \fBconst\fP \fBsc_lv\fP<1> \fBSyscTri\fP< \fBW\fP, \fBTRI_XORZ_CONV\fP >::y_is_d {\fB::sc_dt::SC_LOGIC_1\fP}\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
