.TH "SyscOut< W >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyscOut< W >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_terminals\&.h>\fP
.PP
Inherits \fBSyscTerminal< W >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< \fBW\fP > \fBdata_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscTerminal\fP< \fBW\fP > \fBBASE_MODULE\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscOut\fP< \fBW\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c

Public Types inherited from \fBSyscTerminal< W >\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< \fBW\fP > \fBdata_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscTerminal\fP< \fBW\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyscOut\fP (::sc_core::sc_module_name name)"
.br
.in -1c

Public Member Functions inherited from \fBSyscTerminal< W >\fP
.in +1c
.ti -1c
.RI "\fBSyscTerminal\fP (::sc_core::sc_module_name name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsc_in\fP< \fBtypename\fP \fBBASE_MODULE::data_t\fP > \fBterminal\fP {'terminal'}"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBSyscTerminal\fP<\fBW\fP> \fBSyscOut\fP< \fBW\fP >::BASE_MODULE"

.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBsc_lv\fP<\fBW\fP> \fBSyscOut\fP< \fBW\fP >::data_t"

.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBSyscOut\fP<\fBW\fP> \fBSyscOut\fP< \fBW\fP >::SC_CURRENT_USER_MODULE"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBSyscOut\fP< \fBW\fP >\fB::SyscOut\fP (::sc_core::sc_module_name name)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBsc_in\fP<\fBtypename\fP \fBBASE_MODULE::data_t\fP> \fBSyscOut\fP< \fBW\fP >::terminal {'terminal'}"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
