.TH "SyscLogicGate_pv< N, W >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyscLogicGate_pv< N, W > \- The SyscLogicGate_pv::sc_core::sc_module class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_gates_pv\&.h>\fP
.PP
Inherits sc_core::sc_module\&.
.PP
Inherited by \fBSyscAdd_pv< N, W >\fP, \fBSyscAnd_pv< N, W >\fP, \fBSyscNand_pv< N, W >\fP, \fBSyscNor_pv< N, W >\fP, \fBSyscOr_pv< N, W >\fP, \fBSyscSub_pv< N, W >\fP, \fBSyscXnor_pv< N, W >\fP, and \fBSyscXor_pv< N, W >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< \fBW\fP > \fBdata_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyscLogicGate_pv\fP (::sc_core::sc_module_name name)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBcombinational\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBfind\fP (\fBQString\fP id, \fBQDomNodeList\fP children)"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBgetNInputs\fP (\fBQString\fP \fBgate\fP, \fBbool\fP &\fBok\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBgetWInputs\fP (\fBQString\fP \fBgate\fP, \fBbool\fP &\fBok\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBvalidate\fP (\fBQString\fP \fBgate\fP, \fBQString\fP id, \fBQDomElement\fP \fBgElement\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsc_vector\fP< \fBsc_in\fP< \fBdata_t\fP > > \fBd\fP"
.br
.ti -1c
.RI "\fBsc_out\fP< \fBdata_t\fP > \fBy\fP {'y'}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1>
.br
class SyscLogicGate_pv< N, W >"The SyscLogicGate_pv::sc_core::sc_module class\&. 

A generic SystemC module that implements a logic gate with N inputs and 1 output\&. The gate is combinational, \fBi\&.e\fP\&., the output is updated whenever any of the inputs changes\&. pv 
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBsc_lv\fP<\fBW\fP> \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP >::data_t"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBSyscLogicGate_pv\fP<\fBN\fP,\fBW\fP> \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP >::SC_CURRENT_USER_MODULE"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP >\fB::SyscLogicGate_pv\fP (::sc_core::sc_module_name name)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBvirtual\fP \fBvoid\fP \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP >::combinational ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBSyscAdd_pv< N, W >\fP, \fBSyscSub_pv< N, W >\fP, \fBSyscAnd_pv< N, W >\fP, \fBSyscNand_pv< N, W >\fP, \fBSyscOr_pv< N, W >\fP, \fBSyscNor_pv< N, W >\fP, \fBSyscXor_pv< N, W >\fP, and \fBSyscXnor_pv< N, W >\fP\&.
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBstatic\fP \fBbool\fP \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP >::find (\fBQString\fP id, \fBQDomNodeList\fP children)\fR [inline]\fP, \fR [static]\fP"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBstatic\fP \fBint\fP \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP >::getNInputs (\fBQString\fP gate, \fBbool\fP & ok)\fR [inline]\fP, \fR [static]\fP"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBstatic\fP \fBint\fP \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP >::getWInputs (\fBQString\fP gate, \fBbool\fP & ok)\fR [inline]\fP, \fR [static]\fP"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBstatic\fP \fBbool\fP \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP >::validate (\fBQString\fP gate, \fBQString\fP id, \fBQDomElement\fP gElement)\fR [inline]\fP, \fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBsc_vector\fP<\fBsc_in\fP<\fBdata_t\fP> > \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP >::d"
Data input(s) Array of pointers so each port name can be initialized in the constructor to 'd0', 'd1', and so on (instead of 'port_0', 'port_1', etc\&.) mapping is done as (*mux_object\&.d[index])(signal_to_bind_the_port) instead of \fBmux_object\&.d\fP[index](signal_to_bind_the_port) see https://stackoverflow.com/questions/35425052/how-to-initialize-a-systemc-port-name-which-is-an-array/35535730#35535730 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBsc_out\fP<\fBdata_t\fP> \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP >::y {'y'}"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
