.TH "SyscOr< N, W >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyscOr< N, W > \- The \fBSyscOr\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_gates\&.h>\fP
.PP
Inherits \fBSyscLogicGate< N, W >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBSyscLogicGate\fP< \fBN\fP, \fBW\fP > \fBBASE_MODULE\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscOr\fP< \fBN\fP, \fBW\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c

Public Types inherited from \fBSyscLogicGate< N, W >\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< \fBW\fP > \fBdata_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscLogicGate\fP< \fBN\fP, \fBW\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyscOr\fP (::sc_core::sc_module_name name)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBcombinational\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBSyscLogicGate< N, W >\fP
.in +1c
.ti -1c
.RI "\fBSyscLogicGate\fP (::sc_core::sc_module_name name)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBSyscLogicGate< N, W >\fP
.in +1c
.ti -1c
.RI "\fBsc_in\fP< \fBdata_t\fP > * \fBd\fP [\fBN\fP]"
.br
.ti -1c
.RI "\fBsc_out\fP< \fBdata_t\fP > \fBy\fP {'y'}"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1>
.br
class SyscOr< N, W >"The \fBSyscOr\fP class\&. 

A generic SystemC module that implements an OR gate with N inputs and 1 output\&. The gate is combinational, \fBi\&.e\fP\&., the output is updated whenever any of the inputs changes\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBSyscLogicGate\fP<\fBN\fP,\fBW\fP> \fBSyscOr\fP< \fBN\fP, \fBW\fP >::BASE_MODULE"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBSyscOr\fP<\fBN\fP,\fBW\fP> \fBSyscOr\fP< \fBN\fP, \fBW\fP >::SC_CURRENT_USER_MODULE"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBSyscOr\fP< \fBN\fP, \fBW\fP >\fB::SyscOr\fP (::sc_core::sc_module_name name)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBvirtual\fP \fBvoid\fP \fBSyscOr\fP< \fBN\fP, \fBW\fP >::combinational ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBSyscLogicGate< N, W >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
