.TH "SyscTAnd< W >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyscTAnd< W >
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sc_t_gates\&.h>\fP
.PP
Inherits \fBSyscTComb< W >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBSyscTComb\fP< W > \fBBASE_MODULE\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscTAnd\fP< W > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c

Public Types inherited from \fBSyscTComb< W >\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< W > \fBdata_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscTComb\fP< W > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyscTAnd\fP (\fBconst\fP \fBchar\fP *name, \fBunsigned\fP \fBint\fP N=2)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBcombinational\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBSyscTComb< W >\fP
.in +1c
.ti -1c
.RI "\fBSyscTComb\fP (\fBconst\fP \fBchar\fP *name, \fBunsigned\fP \fBint\fP N=2)"
.br
.ti -1c
.RI "\fB~SyscTComb\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBSyscTComb< W >\fP
.in +1c
.ti -1c
.RI "\fBsc_out\fP< \fBdata_t\fP > \fBy\fP {'y'}"
.br
.ti -1c
.RI "\fBsc_in\fP< \fBdata_t\fP > ** \fBd\fP"
.br
.in -1c

Protected Attributes inherited from \fBSyscTComb< W >\fP
.in +1c
.ti -1c
.RI "\fBunsigned\fP \fBint\fP \fBm_N\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBSyscTComb\fP<W> \fBSyscTAnd\fP< W >::BASE_MODULE"

.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBSyscTAnd\fP<W> \fBSyscTAnd\fP< W >::SC_CURRENT_USER_MODULE"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBSyscTAnd\fP< W >\fB::SyscTAnd\fP (\fBconst\fP \fBchar\fP * name, \fBunsigned\fP \fBint\fP N = \fC2\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBvirtual\fP \fBvoid\fP \fBSyscTAnd\fP< W >::combinational ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Reimplemented from \fBSyscTComb< W >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
