.TH "SyscLogicGateRT" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyscLogicGateRT \- The SyscLogicGate::sc_core::sc_module class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sc_gates\&.h>\fP
.PP
Inherits sc_core::sc_module\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< 128 > \fBdata_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscLogicGateRT\fP \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyscLogicGateRT\fP (::sc_core::sc_module_name name, \fBunsigned\fP \fBint\fP N=2, \fBunsigned\fP \fBint\fP W=1)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBcombinational\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBsc_in\fP< \fBdata_t\fP > * > \fBd\fP"
.br
.ti -1c
.RI "\fBsc_out\fP< \fBdata_t\fP > \fBy\fP {'y'}"
.br
.ti -1c
.RI "\fBunsigned\fP \fBint\fP \fB_N\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBint\fP \fB_W\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The SyscLogicGate::sc_core::sc_module class\&. 

A generic SystemC module that implements a logic gate with N inputs and 1 output\&. The gate is combinational, \fBi\&.e\fP\&., the output is updated whenever any of the inputs changes\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBsc_lv\fP<128> \fBSyscLogicGateRT::data_t\fP"

.SS "\fBtypedef\fP \fBSyscLogicGateRT\fP \fBSyscLogicGateRT::SC_CURRENT_USER_MODULE\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "SyscLogicGateRT::SyscLogicGateRT (::sc_core::sc_module_name name, \fBunsigned\fP \fBint\fP N = \fC2\fP, \fBunsigned\fP \fBint\fP W = \fC1\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBvoid\fP SyscLogicGateRT::combinational ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBunsigned\fP \fBint\fP SyscLogicGateRT::_N"

.SS "\fBunsigned\fP \fBint\fP SyscLogicGateRT::_W"

.SS "std::vector<\fBsc_in\fP<\fBdata_t\fP> *> SyscLogicGateRT::d"
Data input(s) Array of pointers so each port name can be initialized in the constructor to 'd0', 'd1', and so on (instead of 'port_0', 'port_1', etc\&.) mapping is done as (*mux_object\&.d[index])(signal_to_bind_the_port) instead of \fBmux_object\&.d\fP[index](signal_to_bind_the_port) see https://stackoverflow.com/questions/35425052/how-to-initialize-a-systemc-port-name-which-is-an-array/35535730#35535730 
.SS "\fBsc_out\fP<\fBdata_t\fP> SyscLogicGateRT::y {'y'}"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
