.TH "SyscNor_pv< N, W >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyscNor_pv< N, W >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_gates_pv\&.h>\fP
.PP
Inherits \fBSyscLogicGate_pv< N, W >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP > \fBBASE_MODULE\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscNor_pv\fP< \fBN\fP, \fBW\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c

Public Types inherited from \fBSyscLogicGate_pv< N, W >\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< \fBW\fP > \fBdata_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscLogicGate_pv\fP< \fBN\fP, \fBW\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyscNor_pv\fP (::sc_core::sc_module_name name)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBcombinational\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBSyscLogicGate_pv< N, W >\fP
.in +1c
.ti -1c
.RI "\fBSyscLogicGate_pv\fP (::sc_core::sc_module_name name)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBvalidate\fP (\fBQString\fP id, \fBQDomElement\fP \fBgElement\fP)"
.br
.in -1c

Static Public Member Functions inherited from \fBSyscLogicGate_pv< N, W >\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBfind\fP (\fBQString\fP id, \fBQDomNodeList\fP children)"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBgetNInputs\fP (\fBQString\fP \fBgate\fP, \fBbool\fP &\fBok\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBint\fP \fBgetWInputs\fP (\fBQString\fP \fBgate\fP, \fBbool\fP &\fBok\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBbool\fP \fBvalidate\fP (\fBQString\fP \fBgate\fP, \fBQString\fP id, \fBQDomElement\fP \fBgElement\fP)"
.br
.in -1c
.SS "Additional Inherited Members"


Public Attributes inherited from \fBSyscLogicGate_pv< N, W >\fP
.in +1c
.ti -1c
.RI "\fBsc_vector\fP< \fBsc_in\fP< \fBdata_t\fP > > \fBd\fP"
.br
.ti -1c
.RI "\fBsc_out\fP< \fBdata_t\fP > \fBy\fP {'y'}"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBSyscLogicGate_pv\fP<\fBN\fP,\fBW\fP> \fBSyscNor_pv\fP< \fBN\fP, \fBW\fP >::BASE_MODULE"

.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBSyscNor_pv\fP<\fBN\fP,\fBW\fP> \fBSyscNor_pv\fP< \fBN\fP, \fBW\fP >::SC_CURRENT_USER_MODULE"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBSyscNor_pv\fP< \fBN\fP, \fBW\fP >\fB::SyscNor_pv\fP (::sc_core::sc_module_name name)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBvirtual\fP \fBvoid\fP \fBSyscNor_pv\fP< \fBN\fP, \fBW\fP >::combinational ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBSyscLogicGate_pv< N, W >\fP\&.
.SS "template<\fBunsigned\fP \fBint\fP N = 2, \fBunsigned\fP \fBint\fP W = 1> \fBstatic\fP \fBbool\fP \fBSyscNor_pv\fP< \fBN\fP, \fBW\fP >::validate (\fBQString\fP id, \fBQDomElement\fP gElement)\fR [inline]\fP, \fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
