.TH "SyscTerminal< W >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyscTerminal< W >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_terminals\&.h>\fP
.PP
Inherits sc_core::sc_module\&.
.PP
Inherited by \fBSyscIn< W >\fP, and \fBSyscOut< W >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< \fBW\fP > \fBdata_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscTerminal\fP< \fBW\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyscTerminal\fP (::sc_core::sc_module_name name)"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBsc_lv\fP<\fBW\fP> \fBSyscTerminal\fP< \fBW\fP >::data_t"

.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBSyscTerminal\fP<\fBW\fP> \fBSyscTerminal\fP< \fBW\fP >::SC_CURRENT_USER_MODULE"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBSyscTerminal\fP< \fBW\fP >\fB::SyscTerminal\fP (::sc_core::sc_module_name name)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
