.TH "SyscCnt< W, CLKEDGE, FLEXINT >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyscCnt< W, CLKEDGE, FLEXINT > \- The \fBSyscCnt\fP class\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_reg\&.h>\fP
.PP
Inherits \fBSyscFlexInt< CLKEDGE, FLEXINT >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< \fBW\fP > \fBdata_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscFlexInt\fP< \fBCLKEDGE\fP, \fBFLEXINT\fP > \fBBASE_MODULE\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscCnt\fP< \fBW\fP, \fBCLKEDGE\fP, \fBFLEXINT\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c

Public Types inherited from \fBSyscFlexInt< CLKEDGE, FLEXINT >\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< 1 > \fBrst_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< 1 > \fBena_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscFlexInt\fP< \fBCLKEDGE\fP, \fBFLEXINT\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyscCnt\fP (::sc_core::sc_module_name name)"
.br
.ti -1c
.RI "\fBvoid\fP \fBreact\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBSyscFlexInt< CLKEDGE, FLEXINT >\fP
.in +1c
.ti -1c
.RI "\fBSyscFlexInt\fP (::sc_core::sc_module_name name)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdoSensitive\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBbResetAction\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBbEnableAction\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBbefore_end_of_elaboration\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBflexintDecode\fP (\fBconst\fP \fBuint8_t\fP \fBf\fP, \fBbool\fP *\fBuse\fP, \fBbool\fP *level)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsc_out\fP< \fBdata_t\fP > \fBq\fP {'q'}"
.br
.in -1c

Public Attributes inherited from \fBSyscFlexInt< CLKEDGE, FLEXINT >\fP
.in +1c
.ti -1c
.RI "\fBsc_in_clk\fP \fBclock\fP {'clock'}"
.br
.ti -1c
.RI "\fBsc_in\fP< \fBrst_t\fP > \fBreset\fP {'reset'}"
.br
.ti -1c
.RI "\fBsc_in\fP< \fBena_t\fP > \fBenable\fP {'enable'}"
.br
.ti -1c
.RI "\fBsc_signal\fP< \fBrst_t\fP > \fBrst_defbind\fP {'IGNORErst'}"
.br
.ti -1c
.RI "\fBsc_signal\fP< \fBena_t\fP > \fBena_defbind\fP {'IGNOREena'}"
.br
.ti -1c
.RI "\fBbool\fP \fBuse_rst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBrst_level\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBuse_ena\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBena_level\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBbool\fP CLKEDGE = DEFAULT_CLKEDGE, \fBflexinterface_t\fP FLEXINT = DEFAULT_FLEXINT>
.br
class SyscCnt< W, CLKEDGE, FLEXINT >"The \fBSyscCnt\fP class\&. 

A generic SystemC module that implements a counter with a single data output\&. The counter is synchronous, \fBi\&.e\fP\&., the output is updated on the rising edge of the clock signal\&. 
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBbool\fP CLKEDGE = DEFAULT_CLKEDGE, \fBflexinterface_t\fP FLEXINT = DEFAULT_FLEXINT> \fBtypedef\fP \fBSyscFlexInt\fP<\fBCLKEDGE\fP, \fBFLEXINT\fP> \fBSyscCnt\fP< \fBW\fP, \fBCLKEDGE\fP, \fBFLEXINT\fP >::BASE_MODULE"

.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBbool\fP CLKEDGE = DEFAULT_CLKEDGE, \fBflexinterface_t\fP FLEXINT = DEFAULT_FLEXINT> \fBtypedef\fP \fBsc_lv\fP<\fBW\fP> \fBSyscCnt\fP< \fBW\fP, \fBCLKEDGE\fP, \fBFLEXINT\fP >::data_t"

.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBbool\fP CLKEDGE = DEFAULT_CLKEDGE, \fBflexinterface_t\fP FLEXINT = DEFAULT_FLEXINT> \fBtypedef\fP \fBSyscCnt\fP<\fBW\fP,\fBCLKEDGE\fP, \fBFLEXINT\fP> \fBSyscCnt\fP< \fBW\fP, \fBCLKEDGE\fP, \fBFLEXINT\fP >::SC_CURRENT_USER_MODULE"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBbool\fP CLKEDGE = DEFAULT_CLKEDGE, \fBflexinterface_t\fP FLEXINT = DEFAULT_FLEXINT> \fBSyscCnt\fP< \fBW\fP, \fBCLKEDGE\fP, \fBFLEXINT\fP >\fB::SyscCnt\fP (::sc_core::sc_module_name name)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBbool\fP CLKEDGE = DEFAULT_CLKEDGE, \fBflexinterface_t\fP FLEXINT = DEFAULT_FLEXINT> \fBvoid\fP \fBSyscCnt\fP< \fBW\fP, \fBCLKEDGE\fP, \fBFLEXINT\fP >::react ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1, \fBbool\fP CLKEDGE = DEFAULT_CLKEDGE, \fBflexinterface_t\fP FLEXINT = DEFAULT_FLEXINT> \fBsc_out\fP<\fBdata_t\fP> \fBSyscCnt\fP< \fBW\fP, \fBCLKEDGE\fP, \fBFLEXINT\fP >::q {'q'}"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
