.TH "SyscIn< W >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SyscIn< W >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <sc_terminals\&.h>\fP
.PP
Inherits \fBSyscTerminal< W >\fP\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBSyscTerminal\fP< \fBW\fP > \fBBASE_MODULE\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscIn\fP< \fBW\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c

Public Types inherited from \fBSyscTerminal< W >\fP
.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBsc_lv\fP< \fBW\fP > \fBdata_t\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBSyscTerminal\fP< \fBW\fP > \fBSC_CURRENT_USER_MODULE\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSyscIn\fP (::sc_core::sc_module_name name)"
.br
.ti -1c
.RI "\fBSyscIn\fP (\fBunsigned\fP \fBint\fP \fBhigh_usteps\fP, \fBunsigned\fP \fBint\fP \fBlow_usteps\fP, \fBunsigned\fP \fBint\fP \fBinit_usteps\fP, \fBsc_logic\fP \fBinit_value\fP, ::sc_core::sc_module_name name)"
.br
.ti -1c
.RI "\fBvoid\fP \fBThread\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBSyscTerminal< W >\fP
.in +1c
.ti -1c
.RI "\fBSyscTerminal\fP (::sc_core::sc_module_name name)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBunsigned\fP \fBint\fP \fBm_high_usteps\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBint\fP \fBm_low_usteps\fP"
.br
.ti -1c
.RI "\fBunsigned\fP \fBint\fP \fBm_init_usteps\fP"
.br
.ti -1c
.RI "\fBsc_logic\fP \fBm_init_value\fP"
.br
.ti -1c
.RI "\fBsc_out\fP< \fBtypename\fP \fBBASE_MODULE::data_t\fP > \fBterminal\fP {'terminal'}"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBSyscTerminal\fP<\fBW\fP> \fBSyscIn\fP< \fBW\fP >::BASE_MODULE"

.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBtypedef\fP \fBSyscIn\fP<\fBW\fP> \fBSyscIn\fP< \fBW\fP >::SC_CURRENT_USER_MODULE"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBSyscIn\fP< \fBW\fP >\fB::SyscIn\fP (::sc_core::sc_module_name name)\fR [inline]\fP"

.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBSyscIn\fP< \fBW\fP >\fB::SyscIn\fP (\fBunsigned\fP \fBint\fP high_usteps, \fBunsigned\fP \fBint\fP low_usteps, \fBunsigned\fP \fBint\fP init_usteps, \fBsc_logic\fP init_value, ::sc_core::sc_module_name name)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBvoid\fP \fBSyscIn\fP< \fBW\fP >::Thread ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBunsigned\fP \fBint\fP \fBSyscIn\fP< \fBW\fP >::m_high_usteps"

.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBunsigned\fP \fBint\fP \fBSyscIn\fP< \fBW\fP >::m_init_usteps"

.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBsc_logic\fP \fBSyscIn\fP< \fBW\fP >::m_init_value"

.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBunsigned\fP \fBint\fP \fBSyscIn\fP< \fBW\fP >::m_low_usteps"

.SS "template<\fBunsigned\fP \fBint\fP W = 1> \fBsc_out\fP<\fBtypename\fP \fBBASE_MODULE::data_t\fP> \fBSyscIn\fP< \fBW\fP >::terminal {'terminal'}"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
