.TH "S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemC/systemcbuilder.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
S:/code/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/systemC/systemcbuilder.h
.SH SYNOPSIS
.br
.PP
\fC#include 'ComponentsStruct\&.h'\fP
.br
\fC#include 'debugwindow\&.h'\fP
.br
\fC#include <systemc\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSystemCBuilder\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBenum\fP \fBe_device\fP \fBdevice\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBe_device\fP { \fBMULTIPLEXER_DEVICE\fP, \fBAND_GATE_DEVICE\fP, \fBOR_GATE_DEVICE\fP, \fBNAND_GATE_DEVICE\fP, \fBNOR_GATE_DEVICE\fP, \fBXOR_GATE_DEVICE\fP, \fBXNOR_GATE_DEVICE\fP, \fBCOUNTER_DEVICE\fP, \fBDEFAULT_DEVICE\fP }"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBenum\fP \fBe_device\fP \fBdevice\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "\fBenum\fP \fBe_device\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMULTIPLEXER_DEVICE \fP\fP
.TP
\fB\fIAND_GATE_DEVICE \fP\fP
.TP
\fB\fIOR_GATE_DEVICE \fP\fP
.TP
\fB\fINAND_GATE_DEVICE \fP\fP
.TP
\fB\fINOR_GATE_DEVICE \fP\fP
.TP
\fB\fIXOR_GATE_DEVICE \fP\fP
.TP
\fB\fIXNOR_GATE_DEVICE \fP\fP
.TP
\fB\fICOUNTER_DEVICE \fP\fP
.TP
\fB\fIDEFAULT_DEVICE \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
