.TH "tlm::tlm_phase" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_phase
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_phase\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_phase\fP ()"
.br
.ti -1c
.RI "\fBtlm_phase\fP (\fBunsigned\fP int id)"
.br
.ti -1c
.RI "\fBtlm_phase\fP (\fBtlm_phase_enum\fP \fBstandard\fP)"
.br
.ti -1c
.RI "\fBtlm_phase\fP & \fBoperator=\fP (\fBtlm_phase_enum\fP \fBstandard\fP)"
.br
.ti -1c
.RI "\fBoperator unsigned int\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBget_name\fP () \fBconst\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_phase\fP (\fBconst\fP std::type_info &type, \fBconst\fP \fBchar\fP *name)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBunsigned\fP int \fBm_id\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tlm::tlm_phase::tlm_phase ()\fR [inline]\fP"

.SS "tlm::tlm_phase::tlm_phase (\fBunsigned\fP int id)"

.SS "tlm::tlm_phase::tlm_phase (\fBtlm_phase_enum\fP standard)\fR [inline]\fP"

.SS "tlm::tlm_phase::tlm_phase (\fBconst\fP std::type_info & type, \fBconst\fP \fBchar\fP * name)\fR [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBconst\fP \fBchar\fP * tlm::tlm_phase::get_name () const"

.SS "tlm::tlm_phase::operator \fBunsigned\fP int () const\fR [inline]\fP"

.SS "\fBtlm_phase\fP & tlm::tlm_phase::operator= (\fBtlm_phase_enum\fP standard)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBunsigned\fP int tlm::tlm_phase::m_id\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
