.TH "tlm::tlm_event_finder_t< IF, T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_event_finder_t< IF, T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_event_finder\&.h>\fP
.PP
Inherits \fBsc_core::sc_event_finder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_event_finder_t\fP (\fBconst\fP \fBsc_core::sc_port_base\fP &\fBport_\fP, \fBconst\fP \fBsc_core::sc_event\fP &(IF::*\fBevent_method_\fP)(\fBtlm_tag\fP< \fBT\fP > *) \fBconst\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~tlm_event_finder_t\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_core::sc_event\fP & \fBfind_event\fP (\fBsc_core::sc_interface\fP *\fBif_p\fP=0) \fBconst\fP"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_event_finder\fP
.in +1c
.ti -1c
.RI "\fBconst\fP \fBsc_port_base\fP & \fBport\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_event_finder\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_event_finder_t\fP ()"
.br
.ti -1c
.RI "\fBtlm_event_finder_t\fP (\fBconst\fP \fBtlm_event_finder_t\fP< \fBIF\fP, \fBT\fP > &)"
.br
.ti -1c
.RI "\fBtlm_event_finder_t\fP< \fBIF\fP, \fBT\fP > & \fBoperator=\fP (\fBconst\fP \fBtlm_event_finder_t\fP< \fBIF\fP, \fBT\fP > &)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBsc_core::sc_event\fP &(IF::* \fBm_event_method\fP )(\fBtlm_tag\fP< \fBT\fP > *) \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Member Functions inherited from \fBsc_core::sc_event_finder\fP
.in +1c
.ti -1c
.RI "template<\fBtypename\fP \fBIF\fP > \fBstatic\fP \fBsc_event_finder\fP & \fBcached_create\fP (\fBsc_event_finder\fP *&\fBcache_p\fP, \fBconst\fP \fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBsc_event\fP &(IF::*\fBef_p\fP)() \fBconst\fP)"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_event_finder\fP
.in +1c
.ti -1c
.RI "\fBsc_event_finder\fP (\fBconst\fP \fBsc_port_base\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBreport_error\fP (\fBconst\fP \fBchar\fP *id, \fBconst\fP \fBchar\fP *\fBadd_msg\fP=0) \fBconst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBIF\fP , \fBclass\fP \fBT\fP > \fBtlm::tlm_event_finder_t\fP< \fBIF\fP, \fBT\fP >::tlm_event_finder_t (\fBconst\fP \fBsc_core::sc_port_base\fP & port_, \fBconst\fP \fBsc_core::sc_event\fP &(IF::*)(\fBtlm_tag\fP< \fBT\fP > *) \fBconst\fP event_method_)\fR [inline]\fP"

.SS "template<\fBclass\fP \fBIF\fP , \fBclass\fP \fBT\fP > \fBvirtual\fP \fBtlm::tlm_event_finder_t\fP< \fBIF\fP, \fBT\fP >::~\fBtlm_event_finder_t\fP ()\fR [inline]\fP, \fR [virtual]\fP"

.SS "template<\fBclass\fP \fBIF\fP , \fBclass\fP \fBT\fP > \fBtlm::tlm_event_finder_t\fP< \fBIF\fP, \fBT\fP >::tlm_event_finder_t ()\fR [private]\fP"

.SS "template<\fBclass\fP \fBIF\fP , \fBclass\fP \fBT\fP > \fBtlm::tlm_event_finder_t\fP< \fBIF\fP, \fBT\fP >::tlm_event_finder_t (\fBconst\fP \fBtlm_event_finder_t\fP< \fBIF\fP, \fBT\fP > &)\fR [private]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBIF\fP , \fBclass\fP \fBT\fP > \fBconst\fP \fBsc_core::sc_event\fP & \fBtlm::tlm_event_finder_t\fP< \fBIF\fP, \fBT\fP >::find_event (\fBsc_core::sc_interface\fP * if_p = \fR0\fP) const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBsc_core::sc_event_finder\fP\&.
.SS "template<\fBclass\fP \fBIF\fP , \fBclass\fP \fBT\fP > \fBtlm_event_finder_t\fP< \fBIF\fP, \fBT\fP > & \fBtlm::tlm_event_finder_t\fP< \fBIF\fP, \fBT\fP >\fB::operator\fP= (\fBconst\fP \fBtlm_event_finder_t\fP< \fBIF\fP, \fBT\fP > &)\fR [private]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBIF\fP , \fBclass\fP \fBT\fP > \fBconst\fP \fBsc_core::sc_event\fP &(IF::* \fBtlm::tlm_event_finder_t\fP< \fBIF\fP, \fBT\fP >::m_event_method) (\fBtlm_tag\fP< \fBT\fP > *) \fBconst\fP\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
