.TH "tlm_utils::time_ordered_list< PAYLOAD >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_utils::time_ordered_list< PAYLOAD >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <peq_with_cb_and_phase\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBelement\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtime_ordered_list\fP ()"
.br
.ti -1c
.RI "\fB~time_ordered_list\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBinsert\fP (\fBconst\fP PAYLOAD &p, \fBsc_core::sc_time\fP t)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdelete_top\fP ()"
.br
.ti -1c
.RI "\fBunsigned\fP int \fBget_size\fP ()"
.br
.ti -1c
.RI "PAYLOAD & \fBtop\fP ()"
.br
.ti -1c
.RI "\fBsc_core::sc_time\fP \fBtop_time\fP ()"
.br
.ti -1c
.RI "\fBsc_dt::uint64\fP & \fBtop_delta\fP ()"
.br
.ti -1c
.RI "\fBsc_core::sc_time\fP \fBnext_time\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBelement\fP * \fBnill\fP"
.br
.ti -1c
.RI "\fBelement\fP * \fBempties\fP"
.br
.ti -1c
.RI "\fBelement\fP * \fBlist\fP"
.br
.ti -1c
.RI "\fBunsigned\fP int \fBsize\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP PAYLOAD > \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::time_ordered_list ()\fR [inline]\fP"

.SS "template<\fBtypename\fP PAYLOAD > \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::~\fBtime_ordered_list\fP ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP PAYLOAD > \fBvoid\fP \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::delete_top ()\fR [inline]\fP"

.SS "template<\fBtypename\fP PAYLOAD > \fBunsigned\fP int \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::get_size ()\fR [inline]\fP"

.SS "template<\fBtypename\fP PAYLOAD > \fBvoid\fP \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::insert (\fBconst\fP PAYLOAD & p, \fBsc_core::sc_time\fP t)\fR [inline]\fP"

.SS "template<\fBtypename\fP PAYLOAD > \fBsc_core::sc_time\fP \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::next_time ()\fR [inline]\fP"

.SS "template<\fBtypename\fP PAYLOAD > \fBvoid\fP \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::reset ()\fR [inline]\fP"

.SS "template<\fBtypename\fP PAYLOAD > PAYLOAD & \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::top ()\fR [inline]\fP"

.SS "template<\fBtypename\fP PAYLOAD > \fBsc_dt::uint64\fP & \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::top_delta ()\fR [inline]\fP"

.SS "template<\fBtypename\fP PAYLOAD > \fBsc_core::sc_time\fP \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::top_time ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP PAYLOAD > \fBelement\fP* \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::empties"

.SS "template<\fBtypename\fP PAYLOAD > \fBelement\fP* \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::list"

.SS "template<\fBtypename\fP PAYLOAD > \fBelement\fP* \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::nill"

.SS "template<\fBtypename\fP PAYLOAD > \fBunsigned\fP int \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
