.TH "tlm_utils::time_ordered_list< PAYLOAD >::element" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_utils::time_ordered_list< PAYLOAD >::element
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <peq_with_cb_and_phase\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBelement\fP (PAYLOAD &\fBp\fP, \fBsc_core::sc_time\fP \fBt\fP, \fBsc_dt::uint64\fP \fBd\fP)"
.br
.ti -1c
.RI "\fBelement\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstruct\fP \fBelement\fP * \fBnext\fP"
.br
.ti -1c
.RI "PAYLOAD \fBp\fP"
.br
.ti -1c
.RI "\fBsc_core::sc_time\fP \fBt\fP"
.br
.ti -1c
.RI "\fBsc_dt::uint64\fP \fBd\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP PAYLOAD > \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::element::element (PAYLOAD & p, \fBsc_core::sc_time\fP t, \fBsc_dt::uint64\fP d)\fR [inline]\fP"

.SS "template<\fBtypename\fP PAYLOAD > \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::element::element ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP PAYLOAD > \fBsc_dt::uint64\fP \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::element::d"

.SS "template<\fBtypename\fP PAYLOAD > \fBstruct\fP \fBelement\fP* \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::element::next"

.SS "template<\fBtypename\fP PAYLOAD > PAYLOAD \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::element::p"

.SS "template<\fBtypename\fP PAYLOAD > \fBsc_core::sc_time\fP \fBtlm_utils::time_ordered_list\fP< PAYLOAD >::element::t"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
