.TH "tlm::tlm_global_quantum" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_global_quantum
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_global_quantum\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBset\fP (\fBconst\fP \fBsc_core::sc_time\fP &t)"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_core::sc_time\fP & \fBget\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBsc_core::sc_time\fP \fBcompute_local_quantum\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBtlm_global_quantum\fP & \fBinstance\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_global_quantum\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBsc_core::sc_time\fP \fBm_global_quantum\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tlm::tlm_global_quantum::tlm_global_quantum ()\fR [protected]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBsc_core::sc_time\fP tlm::tlm_global_quantum::compute_local_quantum ()"

.SS "\fBconst\fP \fBsc_core::sc_time\fP & tlm::tlm_global_quantum::get () const\fR [inline]\fP"

.SS "\fBstatic\fP \fBtlm_global_quantum\fP & tlm::tlm_global_quantum::instance ()\fR [static]\fP"

.SS "\fBvoid\fP tlm::tlm_global_quantum::set (\fBconst\fP \fBsc_core::sc_time\fP & t)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBsc_core::sc_time\fP tlm::tlm_global_quantum::m_global_quantum\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
