.TH "tlm::tlm_get_if< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_get_if< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_core_ifs\&.h>\fP
.PP
Inherits \fBtlm::tlm_blocking_get_if< T >\fP, and \fBtlm::tlm_nonblocking_get_if< T >\fP\&.
.PP
Inherited by \fBtlm::tlm_get_peek_if< RSP >\fP\fR [virtual]\fP, \fBtlm::tlm_get_peek_if< GET_DATA >\fP\fR [virtual]\fP, \fBtlm::tlm_get_peek_if< REQ >\fP\fR [virtual]\fP, and \fBtlm::tlm_get_peek_if< T >\fP\fR [virtual]\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBtlm::tlm_blocking_get_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBT\fP \fBget\fP (\fBtlm_tag\fP< \fBT\fP > *t=0)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBget\fP (\fBT\fP &t)"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBregister_port\fP (\fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBchar\fP *\fBif_typename_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_interface\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_nonblocking_get_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_get\fP (\fBT\fP &t)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_can_get\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_core::sc_event\fP & \fBok_to_get\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBsc_interface\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
