.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_2_interfaces/tlm_fw_bw_ifs.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_2_interfaces/tlm_fw_bw_ifs.h
.SH SYNOPSIS
.br
.PP
\fR#include <systemc>\fP
.br
\fR#include 'tlm_core/tlm_2/tlm_generic_payload/tlm_generic_payload\&.h'\fP
.br
\fR#include 'tlm_core/tlm_2/tlm_2_interfaces/tlm_dmi\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtlm::tlm_fw_nonblocking_transport_if< TRANS, PHASE >\fP"
.br
.ti -1c
.RI "class \fBtlm::tlm_bw_nonblocking_transport_if< TRANS, PHASE >\fP"
.br
.ti -1c
.RI "class \fBtlm::tlm_blocking_transport_if< TRANS >\fP"
.br
.ti -1c
.RI "class \fBtlm::tlm_fw_direct_mem_if< TRANS >\fP"
.br
.ti -1c
.RI "class \fBtlm::tlm_bw_direct_mem_if\fP"
.br
.ti -1c
.RI "class \fBtlm::tlm_transport_dbg_if< TRANS >\fP"
.br
.ti -1c
.RI "struct \fBtlm::tlm_base_protocol_types\fP"
.br
.ti -1c
.RI "class \fBtlm::tlm_fw_transport_if< TYPES >\fP"
.br
.ti -1c
.RI "class \fBtlm::tlm_bw_transport_if< TYPES >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtlm\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtlm::tlm_sync_enum\fP { \fBtlm::TLM_ACCEPTED\fP, \fBtlm::TLM_UPDATED\fP, \fBtlm::TLM_COMPLETED\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
