.TH "tlm::tlm_fifo_config_size_if" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_fifo_config_size_if
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_fifo_ifs\&.h>\fP
.PP
Inherits \fBsc_core::sc_interface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBnb_expand\fP (\fBunsigned\fP int \fBn\fP=1)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBnb_unbound\fP (\fBunsigned\fP int \fBn\fP=16)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_reduce\fP (\fBunsigned\fP int \fBn\fP=1)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_bound\fP (\fBunsigned\fP int \fBn\fP)=0"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBregister_port\fP (\fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBchar\fP *\fBif_typename_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_interface\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBsc_interface\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBbool\fP tlm::tlm_fifo_config_size_if::nb_bound (\fBunsigned\fP int n)\fR [pure virtual]\fP"

.SS "\fBvirtual\fP \fBvoid\fP tlm::tlm_fifo_config_size_if::nb_expand (\fBunsigned\fP int n = \fR1\fP)\fR [pure virtual]\fP"

.SS "\fBvirtual\fP \fBbool\fP tlm::tlm_fifo_config_size_if::nb_reduce (\fBunsigned\fP int n = \fR1\fP)\fR [pure virtual]\fP"

.SS "\fBvirtual\fP \fBvoid\fP tlm::tlm_fifo_config_size_if::nb_unbound (\fBunsigned\fP int n = \fR16\fP)\fR [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
