.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_version.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_version.h
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtlm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_MAJOR\fP   2"
.br
.RI "version major level ( numeric ) "
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_MINOR\fP   0"
.br
.RI "version minor level ( numeric ) "
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_PATCH\fP   5"
.br
.RI "version patch level ( numeric ) "
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_ORIGINATOR\fP   'Accellera'"
.br
.RI "TLM creator string\&. "
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_SEPARATOR\fP   '\&.'"
.br
.RI "version string separator "
.ti -1c
.RI "#\fBdefine\fP \fBTLM_IS_PRERELEASE\fP   1"
.br
.RI "pre-release flag ( 1 / 0 ) "
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_PRERELEASE\fP   'pub_rev'"
.br
.RI "pre-release version string "
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_RELEASE_YEAR\fP   '2018'"
.br
.RI "release year ( YYYY ) "
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_RELEASE_MONTH\fP   '09'"
.br
.RI "release month ( MM ) "
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_RELEASE_DAY\fP   '04'"
.br
.RI "release day ( DD ) "
.ti -1c
.RI "#\fBdefine\fP \fBTLM_COPYRIGHT\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_RELEASE_DATE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_STR\fP(\fBx\fP)   \fBTLM_VERSION_STR_HELPER\fP(\fBx\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_STR_HELPER\fP(\fBx\fP)   #\fBx\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_STRING_MAJOR\fP   \fBTLM_VERSION_STR\fP(\fBTLM_VERSION_MAJOR\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_STRING_MINOR\fP   \fBTLM_VERSION_STR\fP(\fBTLM_VERSION_MINOR\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_STRING_PATCH\fP   \fBTLM_VERSION_STR\fP(\fBTLM_VERSION_PATCH\fP)"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_STRING_MMP\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_STRING_PRE_START\fP   '_'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_STRING_PRE_END\fP   '\-'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_STRING_PRERELEASE\fP   \fBTLM_VERSION_PRERELEASE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_STRING_RELEASE_DATE\fP   ''"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_STRING\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION_STRING_2\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_VERSION\fP   \fBTLM_VERSION_STRING\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBunsigned\fP int \fBtlm::tlm_version_major\fP (\fBTLM_VERSION_MAJOR\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBunsigned\fP int \fBtlm::tlm_version_minor\fP (\fBTLM_VERSION_MINOR\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBunsigned\fP int \fBtlm::tlm_version_patch\fP (\fBTLM_VERSION_PATCH\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBbool\fP \fBtlm::tlm_is_prerelease\fP (\fBTLM_IS_PRERELEASE\fP)"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBtlm::tlm_version_string\fP (\fBTLM_VERSION_STRING\fP)"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBtlm::tlm_version_originator\fP (\fBTLM_VERSION_ORIGINATOR\fP)"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBtlm::tlm_version_prerelease\fP (\fBTLM_VERSION_PRERELEASE\fP)"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBtlm::tlm_version_release_date\fP (\fBTLM_VERSION_STRING_RELEASE_DATE\fP)"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBtlm::tlm_copyright_string\fP (\fBTLM_COPYRIGHT\fP)"
.br
.ti -1c
.RI "\fBconst\fP std::string \fBtlm::tlm_version_string_2\fP (\fBTLM_VERSION_STRING_2\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBtlm::tlm_release\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBtlm::tlm_version\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBtlm::tlm_copyright\fP (\fBvoid\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP TLM_COPYRIGHT"
\fBValue:\fP.PP
.nf
  "Copyright (c) 1996\-" TLM_VERSION_RELEASE_YEAR " by all Contributors\\n" \\
  "ALL RIGHTS RESERVED"
.fi

.SS "#\fBdefine\fP TLM_IS_PRERELEASE   1"

.PP
pre-release flag ( 1 / 0 ) 
.SS "#\fBdefine\fP TLM_VERSION   \fBTLM_VERSION_STRING\fP"

.SS "#\fBdefine\fP TLM_VERSION_MAJOR   2"

.PP
version major level ( numeric ) 
.SS "#\fBdefine\fP TLM_VERSION_MINOR   0"

.PP
version minor level ( numeric ) 
.SS "#\fBdefine\fP TLM_VERSION_ORIGINATOR   'Accellera'"

.PP
TLM creator string\&. 
.SS "#\fBdefine\fP TLM_VERSION_PATCH   5"

.PP
version patch level ( numeric ) 
.SS "#\fBdefine\fP TLM_VERSION_PRERELEASE   'pub_rev'"

.PP
pre-release version string 
.SS "#\fBdefine\fP TLM_VERSION_RELEASE_DATE"
\fBValue:\fP.PP
.nf
                                            TLM_VERSION_RELEASE_YEAR \\
                                            TLM_VERSION_RELEASE_MONTH \\
                                            TLM_VERSION_RELEASE_DAY
.fi

.SS "#\fBdefine\fP TLM_VERSION_RELEASE_DAY   '04'"

.PP
release day ( DD ) 
.SS "#\fBdefine\fP TLM_VERSION_RELEASE_MONTH   '09'"

.PP
release month ( MM ) 
.SS "#\fBdefine\fP TLM_VERSION_RELEASE_YEAR   '2018'"

.PP
release year ( YYYY ) 
.SS "#\fBdefine\fP TLM_VERSION_SEPARATOR   '\&.'"

.PP
version string separator 
.SS "#\fBdefine\fP TLM_VERSION_STR(\fBx\fP)   \fBTLM_VERSION_STR_HELPER\fP(\fBx\fP)"

.SS "#\fBdefine\fP TLM_VERSION_STR_HELPER(\fBx\fP)   #\fBx\fP"

.SS "#\fBdefine\fP TLM_VERSION_STRING"
\fBValue:\fP.PP
.nf
                                            TLM_VERSION_STRING_MMP \\
                                            TLM_VERSION_STRING_PRE_START \\
                                            TLM_VERSION_STRING_PRERELEASE \\
                                            TLM_VERSION_STRING_PRE_END \\
                                            TLM_VERSION_ORIGINATOR
.fi

.SS "#\fBdefine\fP TLM_VERSION_STRING_2"
\fBValue:\fP.PP
.nf
                                            "TLM " \\
                                            TLM_VERSION_STRING_MMP \\
                                            " \-\-\- " \\
                                            TLM_VERSION_RELEASE_YEAR \\
                                            "\-" \\
                                            TLM_VERSION_RELEASE_MONTH \\
                                            "\-" \\
                                            TLM_VERSION_RELEASE_DAY
.fi

.SS "#\fBdefine\fP TLM_VERSION_STRING_MAJOR   \fBTLM_VERSION_STR\fP(\fBTLM_VERSION_MAJOR\fP)"

.SS "#\fBdefine\fP TLM_VERSION_STRING_MINOR   \fBTLM_VERSION_STR\fP(\fBTLM_VERSION_MINOR\fP)"

.SS "#\fBdefine\fP TLM_VERSION_STRING_MMP"
\fBValue:\fP.PP
.nf
                                            TLM_VERSION_STRING_MAJOR TLM_VERSION_SEPARATOR \\
                                            TLM_VERSION_STRING_MINOR TLM_VERSION_SEPARATOR \\
                                            TLM_VERSION_STRING_PATCH
.fi

.SS "#\fBdefine\fP TLM_VERSION_STRING_PATCH   \fBTLM_VERSION_STR\fP(\fBTLM_VERSION_PATCH\fP)"

.SS "#\fBdefine\fP TLM_VERSION_STRING_PRE_END   '\-'"

.SS "#\fBdefine\fP TLM_VERSION_STRING_PRE_START   '_'"

.SS "#\fBdefine\fP TLM_VERSION_STRING_PRERELEASE   \fBTLM_VERSION_PRERELEASE\fP"

.SS "#\fBdefine\fP TLM_VERSION_STRING_RELEASE_DATE   ''"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
