.TH "tlm::tlm_mm_interface" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_mm_interface
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_gp\&.h>\fP
.PP
Inherited by \fBtlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process\fP, and \fBtlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBfree\fP (\fBtlm_generic_payload\fP *)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~tlm_mm_interface\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBvirtual\fP tlm::tlm_mm_interface::~tlm_mm_interface ()\fR [inline]\fP, \fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBvoid\fP tlm::tlm_mm_interface::free (\fBtlm_generic_payload\fP *)\fR [pure virtual]\fP"

.PP
Implemented in \fBtlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process\fP, and \fBtlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
