.TH "tlm::tlm_master_imp< REQ, RSP >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_master_imp< REQ, RSP >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_put_get_imp\&.h>\fP
.PP
Inherits \fBtlm::tlm_put_get_imp< REQ, RSP >\fP, and \fBtlm::tlm_master_if< REQ, RSP >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_master_imp\fP (\fBtlm_put_if\fP< \fBREQ\fP > &\fBreq\fP, \fBtlm_get_peek_if\fP< \fBRSP\fP > &rsp)"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_blocking_put_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBput\fP (\fBconst\fP \fBT\fP &t)=0"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBregister_port\fP (\fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBchar\fP *\fBif_typename_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_interface\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_nonblocking_put_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_put\fP (\fBconst\fP \fBT\fP &t)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_can_put\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_core::sc_event\fP & \fBok_to_put\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_blocking_get_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBT\fP \fBget\fP (\fBtlm_tag\fP< \fBT\fP > *t=0)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBget\fP (\fBT\fP &t)"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_nonblocking_get_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_get\fP (\fBT\fP &t)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_can_get\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_core::sc_event\fP & \fBok_to_get\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_blocking_peek_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBT\fP \fBpeek\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBpeek\fP (\fBT\fP &t) \fBconst\fP"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_nonblocking_peek_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_peek\fP (\fBT\fP &t) \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_can_peek\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_core::sc_event\fP & \fBok_to_peek\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_blocking_put_if< REQ >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBput\fP (\fBconst\fP \fBREQ\fP &t)=0"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_nonblocking_put_if< REQ >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_put\fP (\fBconst\fP \fBREQ\fP &t)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_can_put\fP (\fBtlm_tag\fP< \fBREQ\fP > *t=0) \fBconst\fP=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_core::sc_event\fP & \fBok_to_put\fP (\fBtlm_tag\fP< \fBREQ\fP > *t=0) \fBconst\fP=0"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBsc_interface\fP ()"
.br
.in -1c

Private Member Functions inherited from \fBtlm::tlm_put_get_imp< REQ, RSP >\fP
.in +1c
.ti -1c
.RI "\fBtlm_put_get_imp\fP (\fBtlm_put_if\fP< \fBREQ\fP > &p, \fBtlm_get_peek_if\fP< \fBRSP\fP > &\fBg\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBput\fP (\fBconst\fP \fBREQ\fP &t)"
.br
.ti -1c
.RI "\fBbool\fP \fBnb_put\fP (\fBconst\fP \fBREQ\fP &t)"
.br
.ti -1c
.RI "\fBbool\fP \fBnb_can_put\fP (\fBtlm_tag\fP< \fBREQ\fP > *t=0) \fBconst\fP"
.br
.ti -1c
.RI "\fBconst\fP \fBsc_core::sc_event\fP & \fBok_to_put\fP (\fBtlm_tag\fP< \fBREQ\fP > *t=0) \fBconst\fP"
.br
.ti -1c
.RI "\fBRSP\fP \fBget\fP (\fBtlm_tag\fP< \fBRSP\fP > *=0)"
.br
.ti -1c
.RI "\fBbool\fP \fBnb_get\fP (\fBRSP\fP &t)"
.br
.ti -1c
.RI "\fBbool\fP \fBnb_can_get\fP (\fBtlm_tag\fP< \fBRSP\fP > *t=0) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_core::sc_event\fP & \fBok_to_get\fP (\fBtlm_tag\fP< \fBRSP\fP > *t=0) \fBconst\fP"
.br
.ti -1c
.RI "\fBRSP\fP \fBpeek\fP (\fBtlm_tag\fP< \fBRSP\fP > *=0) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBnb_peek\fP (\fBRSP\fP &t) \fBconst\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBnb_can_peek\fP (\fBtlm_tag\fP< \fBRSP\fP > *t=0) \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_core::sc_event\fP & \fBok_to_peek\fP (\fBtlm_tag\fP< \fBRSP\fP > *t=0) \fBconst\fP"
.br
.in -1c

Private Member Functions inherited from \fBtlm::tlm_blocking_put_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBput\fP (\fBconst\fP \fBT\fP &t)=0"
.br
.in -1c

Private Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBregister_port\fP (\fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBchar\fP *\fBif_typename_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_interface\fP ()"
.br
.in -1c
.in +1c
.ti -1c
.RI "\fBsc_interface\fP ()"
.br
.in -1c

Private Member Functions inherited from \fBtlm::tlm_nonblocking_put_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_put\fP (\fBconst\fP \fBT\fP &t)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_can_put\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_core::sc_event\fP & \fBok_to_put\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.in -1c

Private Member Functions inherited from \fBtlm::tlm_blocking_get_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBT\fP \fBget\fP (\fBtlm_tag\fP< \fBT\fP > *t=0)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBget\fP (\fBT\fP &t)"
.br
.in -1c

Private Member Functions inherited from \fBtlm::tlm_nonblocking_get_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_get\fP (\fBT\fP &t)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_can_get\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_core::sc_event\fP & \fBok_to_get\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.in -1c

Private Member Functions inherited from \fBtlm::tlm_blocking_peek_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBT\fP \fBpeek\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBpeek\fP (\fBT\fP &t) \fBconst\fP"
.br
.in -1c

Private Member Functions inherited from \fBtlm::tlm_nonblocking_peek_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_peek\fP (\fBT\fP &t) \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBnb_can_peek\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_core::sc_event\fP & \fBok_to_peek\fP (\fBtlm_tag\fP< \fBT\fP > *t=0) \fBconst\fP =0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBREQ\fP , \fBtypename\fP \fBRSP\fP > \fBtlm::tlm_master_imp\fP< \fBREQ\fP, \fBRSP\fP >::tlm_master_imp (\fBtlm_put_if\fP< \fBREQ\fP > & req, \fBtlm_get_peek_if\fP< \fBRSP\fP > & rsp)\fR [inline]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
