.TH "tlm_utils" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_utils
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcallback_binder_bw\fP"
.br
.ti -1c
.RI "class \fBcallback_binder_fw\fP"
.br
.ti -1c
.RI "class \fBconvenience_socket_base\fP"
.br
.ti -1c
.RI "class \fBconvenience_socket_cb_holder\fP"
.br
.ti -1c
.RI "struct \fBfn_container\fP"
.br
.ti -1c
.RI "class \fBinstance_specific_extension\fP"
.br
.ti -1c
.RI "class \fBinstance_specific_extension_accessor\fP"
.br
.ti -1c
.RI "class \fBinstance_specific_extension_carrier\fP"
.br
.ti -1c
.RI "class \fBinstance_specific_extension_container\fP"
.br
.ti -1c
.RI "class \fBinstance_specific_extensions_per_accessor\fP"
.br
.ti -1c
.RI "class \fBispex_base\fP"
.br
.ti -1c
.RI "class \fBmulti_init_base\fP"
.br
.ti -1c
.RI "class \fBmulti_init_base_if\fP"
.br
.ti -1c
.RI "class \fBmulti_passthrough_initiator_socket\fP"
.br
.ti -1c
.RI "class \fBmulti_passthrough_initiator_socket_optional\fP"
.br
.ti -1c
.RI "class \fBmulti_passthrough_target_socket\fP"
.br
.ti -1c
.RI "class \fBmulti_passthrough_target_socket_optional\fP"
.br
.ti -1c
.RI "class \fBmulti_socket_base\fP"
.br
.ti -1c
.RI "class \fBmulti_target_base\fP"
.br
.ti -1c
.RI "class \fBmulti_target_base_if\fP"
.br
.ti -1c
.RI "class \fBmulti_to_multi_bind_base\fP"
.br
.ti -1c
.RI "class \fBpassthrough_socket_base\fP"
.br
.ti -1c
.RI "class \fBpassthrough_target_socket\fP"
.br
.ti -1c
.RI "class \fBpassthrough_target_socket_b\fP"
.br
.ti -1c
.RI "class \fBpassthrough_target_socket_optional\fP"
.br
.ti -1c
.RI "class \fBpassthrough_target_socket_tagged\fP"
.br
.ti -1c
.RI "class \fBpassthrough_target_socket_tagged_b\fP"
.br
.ti -1c
.RI "class \fBpassthrough_target_socket_tagged_optional\fP"
.br
.ti -1c
.RI "class \fBpeq_with_cb_and_phase\fP"
.br
.ti -1c
.RI "class \fBpeq_with_get\fP"
.br
.ti -1c
.RI "class \fBsimple_initiator_socket\fP"
.br
.ti -1c
.RI "class \fBsimple_initiator_socket_b\fP"
.br
.ti -1c
.RI "class \fBsimple_initiator_socket_optional\fP"
.br
.ti -1c
.RI "class \fBsimple_initiator_socket_tagged\fP"
.br
.ti -1c
.RI "class \fBsimple_initiator_socket_tagged_b\fP"
.br
.ti -1c
.RI "class \fBsimple_initiator_socket_tagged_optional\fP"
.br
.ti -1c
.RI "class \fBsimple_socket_base\fP"
.br
.ti -1c
.RI "class \fBsimple_target_socket\fP"
.br
.ti -1c
.RI "class \fBsimple_target_socket_b\fP"
.br
.ti -1c
.RI "class \fBsimple_target_socket_optional\fP"
.br
.ti -1c
.RI "class \fBsimple_target_socket_tagged\fP"
.br
.ti -1c
.RI "class \fBsimple_target_socket_tagged_b\fP"
.br
.ti -1c
.RI "class \fBsimple_target_socket_tagged_optional\fP"
.br
.ti -1c
.RI "class \fBtime_ordered_list\fP"
.br
.ti -1c
.RI "class \fBtlm_quantumkeeper\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBTLM_DEFINE_FUNCTOR\fP (\fBnb_transport\fP)"
.br
.ti -1c
.RI "\fBTLM_DEFINE_FUNCTOR\fP (b_transport)"
.br
.ti -1c
.RI "\fBTLM_DEFINE_FUNCTOR\fP (\fBdebug_transport\fP)"
.br
.ti -1c
.RI "\fBTLM_DEFINE_FUNCTOR\fP (get_dmi_ptr)"
.br
.ti -1c
.RI "\fBTLM_DEFINE_FUNCTOR\fP (\fBinvalidate_dmi\fP)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBSC_API\fP \fBispex_base\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBSC_API\fP \fBinstance_specific_extension_accessor\fP"
.br
.ti -1c
.RI "\fBclass\fP \fBSC_API\fP \fBinstance_specific_extension_container\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "tlm_utils::TLM_DEFINE_FUNCTOR (b_transport)"

.SS "tlm_utils::TLM_DEFINE_FUNCTOR (\fBdebug_transport\fP)"

.SS "tlm_utils::TLM_DEFINE_FUNCTOR (get_dmi_ptr)"

.SS "tlm_utils::TLM_DEFINE_FUNCTOR (\fBinvalidate_dmi\fP)"

.SS "tlm_utils::TLM_DEFINE_FUNCTOR (\fBnb_transport\fP)"

.SH "Variable Documentation"
.PP 
.SS "\fBclass\fP \fBSC_API\fP tlm_utils::instance_specific_extension_accessor"

.SS "\fBclass\fP \fBSC_API\fP tlm_utils::instance_specific_extension_container"

.SS "\fBclass\fP \fBSC_API\fP tlm_utils::ispex_base"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
