.TH "tlm::tlm_extension< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_extension< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_gp\&.h>\fP
.PP
Inherits \fBtlm::tlm_extension_base\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBtlm_extension_base\fP * \fBclone\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBcopy_from\fP (\fBtlm_extension_base\fP \fBconst\fP &\fBext\fP)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~tlm_extension\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_extension_base\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBfree\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBunsigned\fP int \fBID\fP = \fBtlm_extension_base::register_extension\fP(\fBtypeid\fP(\fBT\fP))"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBtlm::tlm_extension_base\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~tlm_extension_base\fP ()"
.br
.in -1c

Static Protected Member Functions inherited from \fBtlm::tlm_extension_base\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBunsigned\fP int \fBregister_extension\fP (\fBconst\fP std::type_info &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBvirtual\fP \fBtlm::tlm_extension\fP< \fBT\fP >::~\fBtlm_extension\fP ()\fR [inline]\fP, \fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBvirtual\fP \fBtlm_extension_base\fP * \fBtlm::tlm_extension\fP< \fBT\fP >::clone () const\fR [pure virtual]\fP"

.PP
Implements \fBtlm::tlm_extension_base\fP\&.
.PP
Implemented in \fBtlm::tlm_endian_context\fP, \fBtlm_utils::instance_specific_extension_carrier\fP, \fBtlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext\fP, and \fBtlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext\fP\&.
.SS "template<\fBtypename\fP \fBT\fP > \fBvirtual\fP \fBvoid\fP \fBtlm::tlm_extension\fP< \fBT\fP >::copy_from (\fBtlm_extension_base\fP \fBconst\fP & ext)\fR [pure virtual]\fP"

.PP
Implements \fBtlm::tlm_extension_base\fP\&.
.PP
Implemented in \fBtlm_utils::instance_specific_extension_carrier\fP, \fBtlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext\fP, \fBtlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext\fP, and \fBtlm::tlm_endian_context\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBconst\fP \fBunsigned\fP int \fBtlm::tlm_extension\fP< \fBT\fP >::ID = \fBtlm_extension_base::register_extension\fP(\fBtypeid\fP(\fBT\fP))\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
