.TH "tlm::tlm_delayed_write_if< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_delayed_write_if< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_write_if\&.h>\fP
.PP
Inherits \fBsc_core::sc_interface\fP\&.
.PP
Inherited by \fBtlm::tlm_delayed_analysis_if< T >\fP\fR [virtual]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBwrite\fP (\fBconst\fP \fBT\fP &t, \fBconst\fP \fBsc_core::sc_time\fP &\fBtime\fP)=0"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBregister_port\fP (\fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBchar\fP *\fBif_typename_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_interface\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBsc_interface\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBvirtual\fP \fBvoid\fP \fBtlm::tlm_delayed_write_if\fP< \fBT\fP >::write (\fBconst\fP \fBT\fP & t, \fBconst\fP \fBsc_core::sc_time\fP & time)\fR [pure virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
