.TH "tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBtlm::tlm_extension< mm_end_event_ext >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm::tlm_extension_base\fP * \fBclone\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBfree\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBcopy_from\fP (\fBtlm::tlm_extension_base\fP \fBconst\fP &)"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_extension< mm_end_event_ext >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~tlm_extension\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsc_core::sc_event\fP \fBdone\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBtlm::tlm_extension< mm_end_event_ext >\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBunsigned\fP int \fBID\fP"
.br
.in -1c

Protected Member Functions inherited from \fBtlm::tlm_extension_base\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~tlm_extension_base\fP ()"
.br
.in -1c

Static Protected Member Functions inherited from \fBtlm::tlm_extension_base\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBunsigned\fP int \fBregister_extension\fP (\fBconst\fP std::type_info &)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBMODULE\fP , \fBunsigned\fP int BUSWIDTH, \fBtypename\fP \fBTYPES\fP , \fBsc_core::sc_port_policy\fP POL = sc_core::SC_ONE_OR_MORE_BOUND> \fBtlm::tlm_extension_base\fP * \fBtlm_utils::simple_target_socket_b\fP< \fBMODULE\fP, \fBBUSWIDTH\fP, \fBTYPES\fP, \fBPOL\fP >::fw_process::mm_end_event_ext::clone () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBtlm::tlm_extension< mm_end_event_ext >\fP\&.
.SS "template<\fBtypename\fP \fBMODULE\fP , \fBunsigned\fP int BUSWIDTH, \fBtypename\fP \fBTYPES\fP , \fBsc_core::sc_port_policy\fP POL = sc_core::SC_ONE_OR_MORE_BOUND> \fBvoid\fP \fBtlm_utils::simple_target_socket_b\fP< \fBMODULE\fP, \fBBUSWIDTH\fP, \fBTYPES\fP, \fBPOL\fP >::fw_process::mm_end_event_ext::copy_from (\fBtlm::tlm_extension_base\fP \fBconst\fP &)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBtlm::tlm_extension< mm_end_event_ext >\fP\&.
.SS "template<\fBtypename\fP \fBMODULE\fP , \fBunsigned\fP int BUSWIDTH, \fBtypename\fP \fBTYPES\fP , \fBsc_core::sc_port_policy\fP POL = sc_core::SC_ONE_OR_MORE_BOUND> \fBvoid\fP \fBtlm_utils::simple_target_socket_b\fP< \fBMODULE\fP, \fBBUSWIDTH\fP, \fBTYPES\fP, \fBPOL\fP >::fw_process::mm_end_event_ext::free ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBtlm::tlm_extension_base\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBMODULE\fP , \fBunsigned\fP int BUSWIDTH, \fBtypename\fP \fBTYPES\fP , \fBsc_core::sc_port_policy\fP POL = sc_core::SC_ONE_OR_MORE_BOUND> \fBsc_core::sc_event\fP \fBtlm_utils::simple_target_socket_b\fP< \fBMODULE\fP, \fBBUSWIDTH\fP, \fBTYPES\fP, \fBPOL\fP >::fw_process::mm_end_event_ext::done"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
