.TH "tlm::tlm_analysis_if< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_analysis_if< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_analysis_if\&.h>\fP
.PP
Inherits \fBtlm::tlm_write_if< T >\fP\&.
.PP
Inherited by \fBtlm::tlm_analysis_fifo< T >\fP\fR [virtual]\fP, and \fBtlm::tlm_analysis_port< T >\fP\fR [virtual]\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBtlm::tlm_write_if< T >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBwrite\fP (\fBconst\fP \fBT\fP &t)=0"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBregister_port\fP (\fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBchar\fP *\fBif_typename_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_interface\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBsc_interface\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
