.TH "tlm_utils::instance_specific_extension_carrier" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_utils::instance_specific_extension_carrier
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <instance_specific_extensions\&.h>\fP
.PP
Inherits \fBtlm::tlm_extension< instance_specific_extension_carrier >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinstance_specific_extension_carrier\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBtlm::tlm_extension_base\fP * \fBclone\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBcopy_from\fP (\fBtlm::tlm_extension_base\fP \fBconst\fP &)"
.br
.ti -1c
.RI "\fBvoid\fP \fBfree\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_extension< instance_specific_extension_carrier >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~tlm_extension\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBinstance_specific_extension_container\fP * \fBm_container\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "\fBclass\fP \fBinstance_specific_extension_accessor\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBtlm::tlm_extension< instance_specific_extension_carrier >\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBunsigned\fP int \fBID\fP"
.br
.in -1c

Protected Member Functions inherited from \fBtlm::tlm_extension_base\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~tlm_extension_base\fP ()"
.br
.in -1c

Static Protected Member Functions inherited from \fBtlm::tlm_extension_base\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBunsigned\fP int \fBregister_extension\fP (\fBconst\fP std::type_info &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tlm_utils::instance_specific_extension_carrier::instance_specific_extension_carrier ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBtlm::tlm_extension_base\fP * tlm_utils::instance_specific_extension_carrier::clone () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBtlm::tlm_extension< instance_specific_extension_carrier >\fP\&.
.SS "\fBvoid\fP tlm_utils::instance_specific_extension_carrier::copy_from (\fBtlm::tlm_extension_base\fP \fBconst\fP &)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBtlm::tlm_extension< instance_specific_extension_carrier >\fP\&.
.SS "\fBvoid\fP tlm_utils::instance_specific_extension_carrier::free ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBtlm::tlm_extension_base\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "\fBfriend\fP \fBclass\fP \fBinstance_specific_extension_accessor\fP\fR [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBinstance_specific_extension_container\fP* tlm_utils::instance_specific_extension_carrier::m_container\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
