.TH "tlm::tlm_array< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_array< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_array\&.h>\fP
.PP
Inherits std::vector< T >\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_array\fP (\fBsize_type\fP size=0)"
.br
.ti -1c
.RI "\fBvoid\fP \fBexpand\fP (\fBsize_type\fP \fBnew_size\fP)"
.br
.ti -1c
.RI "\fBconst\fP \fBchar\fP * \fBkind\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBinsert_in_cache\fP (\fBT\fP *p)"
.br
.ti -1c
.RI "\fBvoid\fP \fBfree_entire_cache\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBchar\fP *\fBconst\fP \fBkind_string\fP = 'tlm_array'"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBsize_type\fP > \fBm_entries\fP"
.br
.in -1c
.SS "Private Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP std::vector< \fBT\fP > \fBbase_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP base_type::size_type \fBsize_type\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBtypedef\fP std::vector<\fBT\fP> \fBtlm::tlm_array\fP< \fBT\fP >::base_type\fR [private]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBtypedef\fP base_type::size_type \fBtlm::tlm_array\fP< \fBT\fP >::size_type\fR [private]\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBtlm::tlm_array\fP< \fBT\fP >::tlm_array (\fBsize_type\fP size = \fR0\fP)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBvoid\fP \fBtlm::tlm_array\fP< \fBT\fP >::expand (\fBsize_type\fP new_size)\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBvoid\fP \fBtlm::tlm_array\fP< \fBT\fP >::free_entire_cache ()\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBvoid\fP \fBtlm::tlm_array\fP< \fBT\fP >::insert_in_cache (\fBT\fP * p)\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBconst\fP \fBchar\fP * \fBtlm::tlm_array\fP< \fBT\fP >::kind () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBconst\fP \fBchar\fP *\fBconst\fP \fBtlm::tlm_array\fP< \fBT\fP >::kind_string = 'tlm_array'\fR [static]\fP"

.SS "template<\fBtypename\fP \fBT\fP > std::vector<\fBsize_type\fP> \fBtlm::tlm_array\fP< \fBT\fP >::m_entries\fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
