.TH "tlm::tlm_endian_context_pool" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_endian_context_pool
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_endian_conv\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_endian_context_pool\fP ()"
.br
.ti -1c
.RI "\fB~tlm_endian_context_pool\fP ()"
.br
.ti -1c
.RI "\fBtlm_endian_context\fP * \fBpop\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBpush\fP (\fBtlm_endian_context\fP *\fBc\fP)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBtlm_endian_context\fP * \fBfirst\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tlm::tlm_endian_context_pool::tlm_endian_context_pool ()\fR [inline]\fP"

.SS "tlm::tlm_endian_context_pool::~tlm_endian_context_pool ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBtlm_endian_context\fP * tlm::tlm_endian_context_pool::pop ()\fR [inline]\fP"

.SS "\fBvoid\fP tlm::tlm_endian_context_pool::push (\fBtlm_endian_context\fP * c)\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBtlm_endian_context\fP* tlm::tlm_endian_context_pool::first"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
