.TH "tlm::tlm_analysis_triple< T >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_analysis_triple< T >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_analysis_triple\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_analysis_triple\fP ()"
.br
.ti -1c
.RI "\fBtlm_analysis_triple\fP (\fBconst\fP \fBtlm_analysis_triple\fP &\fBtriple\fP)"
.br
.ti -1c
.RI "\fBtlm_analysis_triple\fP (\fBconst\fP \fBT\fP &t)"
.br
.ti -1c
.RI "\fBoperator T\fP ()"
.br
.ti -1c
.RI "\fBoperator const T &\fP () \fBconst\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsc_core::sc_time\fP \fBstart_time\fP"
.br
.ti -1c
.RI "\fBT\fP \fBtransaction\fP"
.br
.ti -1c
.RI "\fBsc_core::sc_time\fP \fBend_time\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBtlm::tlm_analysis_triple\fP< \fBT\fP >::tlm_analysis_triple ()\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBtlm::tlm_analysis_triple\fP< \fBT\fP >::tlm_analysis_triple (\fBconst\fP \fBtlm_analysis_triple\fP< \fBT\fP > & triple)\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBtlm::tlm_analysis_triple\fP< \fBT\fP >::tlm_analysis_triple (\fBconst\fP \fBT\fP & t)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBtlm::tlm_analysis_triple\fP< \fBT\fP >\fB::operator\fP \fBconst\fP \fBT\fP & () const\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBT\fP > \fBtlm::tlm_analysis_triple\fP< \fBT\fP >\fB::operator\fP \fBT\fP ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBsc_core::sc_time\fP \fBtlm::tlm_analysis_triple\fP< \fBT\fP >::end_time"

.SS "template<\fBtypename\fP \fBT\fP > \fBsc_core::sc_time\fP \fBtlm::tlm_analysis_triple\fP< \fBT\fP >::start_time"

.SS "template<\fBtypename\fP \fBT\fP > \fBT\fP \fBtlm::tlm_analysis_triple\fP< \fBT\fP >::transaction"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
