.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_generic_payload/tlm_helpers.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_generic_payload/tlm_helpers.h
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtlm\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtlm::tlm_endianness\fP { \fBtlm::TLM_UNKNOWN_ENDIAN\fP, \fBtlm::TLM_LITTLE_ENDIAN\fP, \fBtlm::TLM_BIG_ENDIAN\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBtlm_endianness\fP \fBtlm::get_host_endianness\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBtlm::host_has_little_endianness\fP (\fBvoid\fP)"
.br
.ti -1c
.RI "\fBbool\fP \fBtlm::has_host_endianness\fP (\fBtlm_endianness\fP \fBendianness\fP)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
