.TH "tlm::tlm_extension_base" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_extension_base
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_gp\&.h>\fP
.PP
Inherited by \fBtlm::tlm_extension< tlm_endian_context >\fP, \fBtlm::tlm_extension< instance_specific_extension_carrier >\fP, \fBtlm::tlm_extension< mm_end_event_ext >\fP, and \fBtlm::tlm_extension< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBtlm_extension_base\fP * \fBclone\fP () \fBconst\fP =0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBfree\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBcopy_from\fP (\fBtlm_extension_base\fP \fBconst\fP &)=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~tlm_extension_base\fP ()"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBunsigned\fP int \fBregister_extension\fP (\fBconst\fP std::type_info &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBvirtual\fP tlm::tlm_extension_base::~tlm_extension_base ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBtlm_extension_base\fP * tlm::tlm_extension_base::clone () const\fR [pure virtual]\fP"

.PP
Implemented in \fBtlm::tlm_endian_context\fP, \fBtlm_utils::instance_specific_extension_carrier\fP, \fBtlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext\fP, \fBtlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext\fP, \fBtlm::tlm_extension< T >\fP, \fBtlm::tlm_extension< instance_specific_extension_carrier >\fP, \fBtlm::tlm_extension< mm_end_event_ext >\fP, and \fBtlm::tlm_extension< tlm_endian_context >\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP tlm::tlm_extension_base::copy_from (\fBtlm_extension_base\fP \fBconst\fP &)\fR [pure virtual]\fP"

.PP
Implemented in \fBtlm_utils::instance_specific_extension_carrier\fP, \fBtlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext\fP, \fBtlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext\fP, \fBtlm::tlm_endian_context\fP, \fBtlm::tlm_extension< T >\fP, \fBtlm::tlm_extension< instance_specific_extension_carrier >\fP, \fBtlm::tlm_extension< mm_end_event_ext >\fP, and \fBtlm::tlm_extension< tlm_endian_context >\fP\&.
.SS "\fBvirtual\fP \fBvoid\fP tlm::tlm_extension_base::free ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented in \fBtlm::tlm_endian_context\fP, \fBtlm_utils::instance_specific_extension_carrier\fP, \fBtlm_utils::simple_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext\fP, and \fBtlm_utils::simple_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >::fw_process::mm_end_event_ext\fP\&.
.SS "\fBstatic\fP \fBunsigned\fP int tlm::tlm_extension_base::register_extension (\fBconst\fP std::type_info &)\fR [static]\fP, \fR [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
