.TH "tlm_utils::instance_specific_extensions_per_accessor" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_utils::instance_specific_extensions_per_accessor
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <instance_specific_extensions_int\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBinstance_specific_extension_container\fP \fBcontainer_type\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBinstance_specific_extensions_per_accessor\fP (\fBcontainer_type\fP *\fBcontainer\fP)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBT\fP * \fBset_extension\fP (\fBT\fP *\fBext\fP)"
.br
.ti -1c
.RI "\fBispex_base\fP * \fBset_extension\fP (\fBunsigned\fP int index, \fBispex_base\fP *\fBext\fP)"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBvoid\fP \fBget_extension\fP (\fBT\fP *&\fBext\fP) \fBconst\fP"
.br
.ti -1c
.RI "\fBispex_base\fP * \fBget_extension\fP (\fBunsigned\fP int index) \fBconst\fP"
.br
.ti -1c
.RI "template<\fBtypename\fP \fBT\fP > \fBvoid\fP \fBclear_extension\fP (\fBconst\fP \fBT\fP *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBclear_extension\fP (\fBunsigned\fP int index)"
.br
.ti -1c
.RI "\fBvoid\fP \fBresize_extensions\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBtlm::tlm_array\fP< \fBispex_base\fP * > \fBm_extensions\fP"
.br
.ti -1c
.RI "\fBcontainer_type\fP * \fBm_container\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBinstance_specific_extension_container\fP \fBtlm_utils::instance_specific_extensions_per_accessor::container_type\fP"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "tlm_utils::instance_specific_extensions_per_accessor::instance_specific_extensions_per_accessor (\fBcontainer_type\fP * container)\fR [inline]\fP, \fR [explicit]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBT\fP > \fBvoid\fP tlm_utils::instance_specific_extensions_per_accessor::clear_extension (\fBconst\fP \fBT\fP *)\fR [inline]\fP"

.SS "\fBvoid\fP tlm_utils::instance_specific_extensions_per_accessor::clear_extension (\fBunsigned\fP int index)"

.SS "template<\fBtypename\fP \fBT\fP > \fBvoid\fP tlm_utils::instance_specific_extensions_per_accessor::get_extension (\fBT\fP *& ext) const\fR [inline]\fP"

.SS "\fBispex_base\fP * tlm_utils::instance_specific_extensions_per_accessor::get_extension (\fBunsigned\fP int index) const"

.SS "\fBvoid\fP tlm_utils::instance_specific_extensions_per_accessor::resize_extensions ()"

.SS "template<\fBtypename\fP \fBT\fP > \fBT\fP * tlm_utils::instance_specific_extensions_per_accessor::set_extension (\fBT\fP * ext)\fR [inline]\fP"

.SS "\fBispex_base\fP * tlm_utils::instance_specific_extensions_per_accessor::set_extension (\fBunsigned\fP int index, \fBispex_base\fP * ext)"

.SH "Member Data Documentation"
.PP 
.SS "\fBcontainer_type\fP* tlm_utils::instance_specific_extensions_per_accessor::m_container\fR [private]\fP"

.SS "\fBtlm::tlm_array\fP<\fBispex_base\fP*> tlm_utils::instance_specific_extensions_per_accessor::m_extensions\fR [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
