.TH "tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::delta_list" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_utils::peq_with_cb_and_phase< OWNER, TYPES >::delta_list
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBdelta_list\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBinsert\fP (\fBconst\fP \fBPAYLOAD\fP &p)"
.br
.ti -1c
.RI "\fBPAYLOAD\fP & \fBget\fP ()"
.br
.ti -1c
.RI "\fBbool\fP \fBnext\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBreset\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBunsigned\fP int \fBsize\fP"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::vector< \fBPAYLOAD\fP > \fBentries\fP"
.br
.ti -1c
.RI "\fBunsigned\fP int \fBout\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBOWNER\fP , \fBtypename\fP \fBTYPES\fP  = tlm::tlm_base_protocol_types> \fBtlm_utils::peq_with_cb_and_phase\fP< \fBOWNER\fP, \fBTYPES\fP >::delta_list::delta_list ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBOWNER\fP , \fBtypename\fP \fBTYPES\fP  = tlm::tlm_base_protocol_types> \fBPAYLOAD\fP & \fBtlm_utils::peq_with_cb_and_phase\fP< \fBOWNER\fP, \fBTYPES\fP >::delta_list::get ()\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBOWNER\fP , \fBtypename\fP \fBTYPES\fP  = tlm::tlm_base_protocol_types> \fBvoid\fP \fBtlm_utils::peq_with_cb_and_phase\fP< \fBOWNER\fP, \fBTYPES\fP >::delta_list::insert (\fBconst\fP \fBPAYLOAD\fP & p)\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBOWNER\fP , \fBtypename\fP \fBTYPES\fP  = tlm::tlm_base_protocol_types> \fBbool\fP \fBtlm_utils::peq_with_cb_and_phase\fP< \fBOWNER\fP, \fBTYPES\fP >::delta_list::next ()\fR [inline]\fP"

.SS "template<\fBtypename\fP \fBOWNER\fP , \fBtypename\fP \fBTYPES\fP  = tlm::tlm_base_protocol_types> \fBvoid\fP \fBtlm_utils::peq_with_cb_and_phase\fP< \fBOWNER\fP, \fBTYPES\fP >::delta_list::reset ()\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBOWNER\fP , \fBtypename\fP \fBTYPES\fP  = tlm::tlm_base_protocol_types> std::vector<\fBPAYLOAD\fP> \fBtlm_utils::peq_with_cb_and_phase\fP< \fBOWNER\fP, \fBTYPES\fP >::delta_list::entries\fR [private]\fP"

.SS "template<\fBtypename\fP \fBOWNER\fP , \fBtypename\fP \fBTYPES\fP  = tlm::tlm_base_protocol_types> \fBunsigned\fP int \fBtlm_utils::peq_with_cb_and_phase\fP< \fBOWNER\fP, \fBTYPES\fP >::delta_list::out\fR [private]\fP"

.SS "template<\fBtypename\fP \fBOWNER\fP , \fBtypename\fP \fBTYPES\fP  = tlm::tlm_base_protocol_types> \fBunsigned\fP int \fBtlm_utils::peq_with_cb_and_phase\fP< \fBOWNER\fP, \fBTYPES\fP >::delta_list::size"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
