.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_generic_payload/tlm_gp.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_generic_payload/tlm_gp.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/kernel/sc_cmnhdr\&.h'\fP
.br
\fR#include 'sysc/utils/sc_report\&.h'\fP
.br
\fR#include 'sysc/datatypes/int/sc_nbdefs\&.h'\fP
.br
\fR#include 'tlm_core/tlm_2/tlm_generic_payload/tlm_array\&.h'\fP
.br
\fR#include <typeinfo>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtlm::tlm_mm_interface\fP"
.br
.ti -1c
.RI "class \fBtlm::tlm_extension_base\fP"
.br
.ti -1c
.RI "class \fBtlm::tlm_extension< T >\fP"
.br
.ti -1c
.RI "class \fBtlm::tlm_generic_payload\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtlm\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBTLM_BYTE_DISABLED\fP   0x0"
.br
.ti -1c
.RI "#\fBdefine\fP \fBTLM_BYTE_ENABLED\fP   0xff"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtlm::tlm_command\fP { \fBtlm::TLM_READ_COMMAND\fP, \fBtlm::TLM_WRITE_COMMAND\fP, \fBtlm::TLM_IGNORE_COMMAND\fP }"
.br
.ti -1c
.RI "enum \fBtlm::tlm_response_status\fP { \fBtlm::TLM_OK_RESPONSE\fP = 1, \fBtlm::TLM_INCOMPLETE_RESPONSE\fP = 0, \fBtlm::TLM_GENERIC_ERROR_RESPONSE\fP = -1, \fBtlm::TLM_ADDRESS_ERROR_RESPONSE\fP = -2, \fBtlm::TLM_COMMAND_ERROR_RESPONSE\fP = -3, \fBtlm::TLM_BURST_ERROR_RESPONSE\fP = -4, \fBtlm::TLM_BYTE_ENABLE_ERROR_RESPONSE\fP = -5 }"
.br
.ti -1c
.RI "enum \fBtlm::tlm_gp_option\fP { \fBtlm::TLM_MIN_PAYLOAD\fP, \fBtlm::TLM_FULL_PAYLOAD\fP, \fBtlm::TLM_FULL_PAYLOAD_ACCEPTED\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBSC_API\fP \fBunsigned\fP int \fBtlm::max_num_extensions\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBSC_API_TEMPLATE_DECL_\fP \fBtlm::tlm_array< tlm_extension_base * >\fP"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP TLM_BYTE_DISABLED   0x0"

.SS "#\fBdefine\fP TLM_BYTE_ENABLED   0xff"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
