.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_2_interfaces/tlm_2_interfaces.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_2_interfaces/tlm_2_interfaces.h
.SH SYNOPSIS
.br
.PP
\fR#include 'tlm_core/tlm_2/tlm_2_interfaces/tlm_dmi\&.h'\fP
.br
\fR#include 'tlm_core/tlm_2/tlm_2_interfaces/tlm_fw_bw_ifs\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
