.TH "tlm::tlm_transport_if< REQ, RSP >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_transport_if< REQ, RSP >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_core_ifs\&.h>\fP
.PP
Inherits \fBsc_core::sc_interface\fP\&.
.PP
Inherited by \fBtlm::tlm_transport_to_master< REQ, RSP >\fP\fR [virtual]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBRSP\fP \fBtransport\fP (\fBconst\fP \fBREQ\fP &)=0"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBtransport\fP (\fBconst\fP \fBREQ\fP &\fBreq\fP, \fBRSP\fP &rsp)"
.br
.in -1c

Public Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBregister_port\fP (\fBsc_port_base\fP &\fBport_\fP, \fBconst\fP \fBchar\fP *\fBif_typename_\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBsc_event\fP & \fBdefault_event\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fB~sc_interface\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBsc_core::sc_interface\fP
.in +1c
.ti -1c
.RI "\fBsc_interface\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBREQ\fP , \fBtypename\fP \fBRSP\fP > \fBvirtual\fP \fBRSP\fP \fBtlm::tlm_transport_if\fP< \fBREQ\fP, \fBRSP\fP >::transport (\fBconst\fP \fBREQ\fP &)\fR [pure virtual]\fP"

.PP
Implemented in \fBtlm::tlm_transport_to_master< REQ, RSP >\fP\&.
.SS "template<\fBtypename\fP \fBREQ\fP , \fBtypename\fP \fBRSP\fP > \fBvirtual\fP \fBvoid\fP \fBtlm::tlm_transport_if\fP< \fBREQ\fP, \fBRSP\fP >::transport (\fBconst\fP \fBREQ\fP & req, \fBRSP\fP & rsp)\fR [inline]\fP, \fR [virtual]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
