.TH "tlm_utils::passthrough_socket_base" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_utils::passthrough_socket_base
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <convenience_socket_bases\&.h>\fP
.PP
Inherits \fBtlm_utils::convenience_socket_base\fP\&.
.PP
Inherited by \fBtlm_utils::passthrough_target_socket_b< MODULE, 32, tlm::tlm_base_protocol_types >\fP\fR [protected]\fP, \fBtlm_utils::passthrough_target_socket_b< MODULE, 32, tlm::tlm_base_protocol_types, sc_core::SC_ZERO_OR_MORE_BOUND >\fP\fR [protected]\fP, \fBtlm_utils::passthrough_target_socket_tagged_b< MODULE, 32, tlm::tlm_base_protocol_types >\fP\fR [protected]\fP, \fBtlm_utils::passthrough_target_socket_tagged_b< MODULE, 32, tlm::tlm_base_protocol_types, sc_core::SC_ZERO_OR_MORE_BOUND >\fP\fR [protected]\fP, \fBtlm_utils::passthrough_target_socket_b< MODULE, BUSWIDTH, TYPES, POL >\fP\fR [protected]\fP, and \fBtlm_utils::passthrough_target_socket_tagged_b< MODULE, BUSWIDTH, TYPES, POL >\fP\fR [protected]\fP\&.
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBconst\fP \fBchar\fP * \fBget_report_type\fP () \fBconst\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBtlm_utils::convenience_socket_base\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBdisplay_warning\fP (\fBconst\fP \fBchar\fP *msg) \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBdisplay_error\fP (\fBconst\fP \fBchar\fP *msg) \fBconst\fP"
.br
.in -1c

Protected Member Functions inherited from \fBtlm_utils::convenience_socket_base\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~convenience_socket_base\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBvirtual\fP \fBconst\fP \fBchar\fP * tlm_utils::passthrough_socket_base::get_report_type () const\fR [private]\fP, \fR [virtual]\fP"

.PP
Implements \fBtlm_utils::convenience_socket_base\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
