.TH "tlm::tlm_bool< D >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_bool< D >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_endian_conv\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_bool\fP (\fBD\fP &d)"
.br
.ti -1c
.RI "\fBoperator bool\fP () \fBconst\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBD\fP \fBmake_uchar_array\fP (\fBuchar\fP \fBc\fP)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "\fBstatic\fP \fBD\fP \fBTLM_TRUE\fP = \fBtlm_bool\fP<\fBD\fP>\fB::make_uchar_array\fP(\fBTLM_BYTE_ENABLED\fP)"
.br
.ti -1c
.RI "\fBstatic\fP \fBD\fP \fBTLM_FALSE\fP = \fBtlm_bool\fP<\fBD\fP>\fB::make_uchar_array\fP(\fBTLM_BYTE_DISABLED\fP)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBbool\fP \fBb\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBD\fP > \fBtlm::tlm_bool\fP< \fBD\fP >::tlm_bool (\fBD\fP & d)\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBD\fP > \fBstatic\fP \fBD\fP \fBtlm::tlm_bool\fP< \fBD\fP >::make_uchar_array (\fBuchar\fP c)\fR [inline]\fP, \fR [static]\fP"

.SS "template<\fBclass\fP \fBD\fP > \fBtlm::tlm_bool\fP< \fBD\fP >\fB::operator\fP \fBbool\fP () const\fR [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBD\fP > \fBbool\fP \fBtlm::tlm_bool\fP< \fBD\fP >::b\fR [private]\fP"

.SS "template<\fBclass\fP \fBD\fP > \fBD\fP \fBtlm::tlm_bool\fP< \fBD\fP >::TLM_FALSE = \fBtlm_bool\fP<\fBD\fP>\fB::make_uchar_array\fP(\fBTLM_BYTE_DISABLED\fP)\fR [static]\fP"

.SS "template<\fBclass\fP \fBD\fP > \fBD\fP \fBtlm::tlm_bool\fP< \fBD\fP >::TLM_TRUE = \fBtlm_bool\fP<\fBD\fP>\fB::make_uchar_array\fP(\fBTLM_BYTE_ENABLED\fP)\fR [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
