.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_sockets/tlm_base_socket_if.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_sockets/tlm_base_socket_if.h
.SH SYNOPSIS
.br
.PP
\fR#include 'sysc/utils/sc_typeindex\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBtlm::tlm_base_socket_if\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBtlm\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBtlm::tlm_socket_category\fP { \fBtlm::TLM_UNKNOWN_SOCKET\fP = 0, \fBtlm::TLM_INITIATOR_SOCKET\fP = 0x1, \fBtlm::TLM_TARGET_SOCKET\fP = 0x2, \fBtlm::TLM_MULTI_SOCKET\fP = 0x10, \fBtlm::TLM_MULTI_INITIATOR_SOCKET\fP = TLM_INITIATOR_SOCKET | TLM_MULTI_SOCKET, \fBtlm::TLM_MULTI_TARGET_SOCKET\fP = TLM_TARGET_SOCKET | TLM_MULTI_SOCKET }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
