.TH "tlm_utils::multi_init_base_if< TYPES >" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm_utils::multi_init_base_if< TYPES >
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <multi_socket_bases\&.h>\fP
.PP
Inherited by \fBtlm_utils::multi_init_base< 32, tlm::tlm_base_protocol_types, 0, sc_core::SC_ONE_OR_MORE_BOUND >\fP, \fBtlm_utils::multi_init_base< BUSWIDTH, tlm::tlm_base_protocol_types, N, POL >\fP, and \fBtlm_utils::multi_init_base< BUSWIDTH, TYPES, N, POL >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP std::vector< \fBcallback_binder_bw\fP< \fBTYPES\fP > * > & \fBget_binders\fP ()=0"
.br
.ti -1c
.RI "\fBvirtual\fP std::vector< \fBtlm::tlm_fw_transport_if\fP< \fBTYPES\fP > * > & \fBget_sockets\fP ()=0"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~multi_init_base_if\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBTYPES\fP  = tlm::tlm_base_protocol_types> \fBvirtual\fP \fBtlm_utils::multi_init_base_if\fP< \fBTYPES\fP >::~\fBmulti_init_base_if\fP ()\fR [inline]\fP, \fR [protected]\fP, \fR [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBTYPES\fP  = tlm::tlm_base_protocol_types> \fBvirtual\fP std::vector< \fBcallback_binder_bw\fP< \fBTYPES\fP > * > & \fBtlm_utils::multi_init_base_if\fP< \fBTYPES\fP >::get_binders ()\fR [pure virtual]\fP"

.PP
Implemented in \fBtlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, POL >\fP, and \fBtlm_utils::multi_passthrough_initiator_socket< MODULE, 32, tlm::tlm_base_protocol_types, 0, sc_core::SC_ZERO_OR_MORE_BOUND >\fP\&.
.SS "template<\fBtypename\fP \fBTYPES\fP  = tlm::tlm_base_protocol_types> \fBvirtual\fP std::vector< \fBtlm::tlm_fw_transport_if\fP< \fBTYPES\fP > * > & \fBtlm_utils::multi_init_base_if\fP< \fBTYPES\fP >::get_sockets ()\fR [pure virtual]\fP"

.PP
Implemented in \fBtlm_utils::multi_passthrough_initiator_socket< MODULE, BUSWIDTH, TYPES, N, POL >\fP, and \fBtlm_utils::multi_passthrough_initiator_socket< MODULE, 32, tlm::tlm_base_protocol_types, 0, sc_core::SC_ZERO_OR_MORE_BOUND >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
