.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_quantum/tlm_quantum.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/tlm_core/tlm_2/tlm_quantum/tlm_quantum.h
.SH SYNOPSIS
.br
.PP
\fR#include 'tlm_core/tlm_2/tlm_quantum/tlm_global_quantum\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
