.TH "tlm::tlm_endian_context" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_endian_context
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_endian_conv\&.h>\fP
.PP
Inherits \fBtlm::tlm_extension< tlm_endian_context >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBtlm_endian_context\fP ()"
.br
.ti -1c
.RI "\fB~tlm_endian_context\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBestablish_dbuf\fP (int len)"
.br
.ti -1c
.RI "\fBvoid\fP \fBestablish_bebuf\fP (int len)"
.br
.ti -1c
.RI "\fBvoid\fP \fBfree\fP ()"
.br
.ti -1c
.RI "\fBtlm_extension_base\fP * \fBclone\fP () \fBconst\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBcopy_from\fP (\fBtlm_extension_base\fP \fBconst\fP &)"
.br
.in -1c

Public Member Functions inherited from \fBtlm::tlm_extension< tlm_endian_context >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~tlm_extension\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsc_dt::uint64\fP \fBaddress\fP"
.br
.ti -1c
.RI "\fBsc_dt::uint64\fP \fBnew_address\fP"
.br
.ti -1c
.RI "\fBuchar\fP * \fBdata_ptr\fP"
.br
.ti -1c
.RI "\fBuchar\fP * \fBbyte_enable\fP"
.br
.ti -1c
.RI "int \fBlength\fP"
.br
.ti -1c
.RI "int \fBstream_width\fP"
.br
.ti -1c
.RI "\fBvoid\fP(* \fBfrom_f\fP )(\fBtlm_generic_payload\fP *\fBtxn\fP, \fBunsigned\fP int \fBsizeof_databus\fP)"
.br
.ti -1c
.RI "int \fBsizeof_databus\fP"
.br
.ti -1c
.RI "\fBuchar\fP * \fBnew_dbuf\fP"
.br
.ti -1c
.RI "\fBuchar\fP * \fBnew_bebuf\fP"
.br
.ti -1c
.RI "int \fBdbuf_size\fP"
.br
.ti -1c
.RI "int \fBbebuf_size\fP"
.br
.ti -1c
.RI "\fBtlm_endian_context\fP * \fBnext\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBtlm::tlm_extension< tlm_endian_context >\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBconst\fP \fBunsigned\fP int \fBID\fP"
.br
.in -1c

Protected Member Functions inherited from \fBtlm::tlm_extension_base\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~tlm_extension_base\fP ()"
.br
.in -1c

Static Protected Member Functions inherited from \fBtlm::tlm_extension_base\fP
.in +1c
.ti -1c
.RI "\fBstatic\fP \fBunsigned\fP int \fBregister_extension\fP (\fBconst\fP std::type_info &)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "tlm::tlm_endian_context::tlm_endian_context ()\fR [inline]\fP"

.SS "tlm::tlm_endian_context::~tlm_endian_context ()\fR [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBtlm_extension_base\fP * tlm::tlm_endian_context::clone () const\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBtlm::tlm_extension< tlm_endian_context >\fP\&.
.SS "\fBvoid\fP tlm::tlm_endian_context::copy_from (\fBtlm_extension_base\fP \fBconst\fP &)\fR [inline]\fP, \fR [virtual]\fP"

.PP
Implements \fBtlm::tlm_extension< tlm_endian_context >\fP\&.
.SS "\fBvoid\fP tlm::tlm_endian_context::establish_bebuf (int len)\fR [inline]\fP"

.SS "\fBvoid\fP tlm::tlm_endian_context::establish_dbuf (int len)\fR [inline]\fP"

.SS "\fBvoid\fP tlm::tlm_endian_context::free ()\fR [inline]\fP, \fR [virtual]\fP"

.PP
Reimplemented from \fBtlm::tlm_extension_base\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsc_dt::uint64\fP tlm::tlm_endian_context::address"

.SS "int tlm::tlm_endian_context::bebuf_size"

.SS "\fBuchar\fP* tlm::tlm_endian_context::byte_enable"

.SS "\fBuchar\fP* tlm::tlm_endian_context::data_ptr"

.SS "int tlm::tlm_endian_context::dbuf_size"

.SS "\fBvoid\fP(* tlm::tlm_endian_context::from_f) (\fBtlm_generic_payload\fP *\fBtxn\fP, \fBunsigned\fP int \fBsizeof_databus\fP)"

.SS "int tlm::tlm_endian_context::length"

.SS "\fBsc_dt::uint64\fP tlm::tlm_endian_context::new_address"

.SS "\fBuchar\fP * tlm::tlm_endian_context::new_bebuf"

.SS "\fBuchar\fP* tlm::tlm_endian_context::new_dbuf"

.SS "\fBtlm_endian_context\fP* tlm::tlm_endian_context::next"

.SS "int tlm::tlm_endian_context::sizeof_databus"

.SS "int tlm::tlm_endian_context::stream_width"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
