.TH "tlm::tlm_base_protocol_types" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
tlm::tlm_base_protocol_types
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <tlm_fw_bw_ifs\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBtlm_generic_payload\fP \fBtlm_payload_type\fP"
.br
.ti -1c
.RI "\fBtypedef\fP \fBtlm_phase\fP \fBtlm_phase_type\fP"
.br
.in -1c
.SH "Member Typedef Documentation"
.PP 
.SS "\fBtypedef\fP \fBtlm_generic_payload\fP \fBtlm::tlm_base_protocol_types::tlm_payload_type\fP"

.SS "\fBtypedef\fP \fBtlm_phase\fP \fBtlm::tlm_base_protocol_types::tlm_phase_type\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
