.TH "Ui::MainWindow" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ui_mainwindow\&.h>\fP
.PP
Inherits \fBUi_MainWindow\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBUi_MainWindow\fP
.in +1c
.ti -1c
.RI "void \fBsetupUi\fP (QMainWindow *\fBMainWindow\fP)"
.br
.ti -1c
.RI "void \fBretranslateUi\fP (QMainWindow *\fBMainWindow\fP)"
.br
.in -1c

Public Attributes inherited from \fBUi_MainWindow\fP
.in +1c
.ti -1c
.RI "QAction * \fBactionNew_Simulation\fP"
.br
.ti -1c
.RI "QAction * \fBactionExamples\fP"
.br
.ti -1c
.RI "QAction * \fBactionLoad_SVG_file\fP"
.br
.ti -1c
.RI "QAction * \fBactionOpenDebugWindow\fP"
.br
.ti -1c
.RI "QAction * \fBaction1\fP"
.br
.ti -1c
.RI "QAction * \fBaction2\fP"
.br
.ti -1c
.RI "QAction * \fBaction3\fP"
.br
.ti -1c
.RI "QWidget * \fBcentralwidget\fP"
.br
.ti -1c
.RI "QHBoxLayout * \fBhorizontalLayout_3\fP"
.br
.ti -1c
.RI "QSplitter * \fBmainSplitter\fP"
.br
.ti -1c
.RI "QWidget * \fBleftContainer\fP"
.br
.ti -1c
.RI "QVBoxLayout * \fBverticalLayout\fP"
.br
.ti -1c
.RI "QWidget * \fBcomponentsInfoContainer\fP"
.br
.ti -1c
.RI "QVBoxLayout * \fBcomponentsLayout\fP"
.br
.ti -1c
.RI "QHBoxLayout * \fBcomponentsTreeTitleLayout\fP"
.br
.ti -1c
.RI "QLabel * \fBcomponentsInfoTitle\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBhorizontalSpacer_3\fP"
.br
.ti -1c
.RI "QLabel * \fBcomponentsInfoState\fP"
.br
.ti -1c
.RI "QTreeWidget * \fBcomponentsTreeWidget\fP"
.br
.ti -1c
.RI "QWidget * \fBsvgLoader\fP"
.br
.ti -1c
.RI "QVBoxLayout * \fBfolderTreeLayout\fP"
.br
.ti -1c
.RI "QHBoxLayout * \fBtreeViewBtnLayout\fP"
.br
.ti -1c
.RI "QPushButton * \fBfolder_btn\fP"
.br
.ti -1c
.RI "QPushButton * \fBcloseFile\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBhorizontalSpacer_2\fP"
.br
.ti -1c
.RI "QTreeView * \fBfileTreeView\fP"
.br
.ti -1c
.RI "QWidget * \fBverticalLayoutWidget_4\fP"
.br
.ti -1c
.RI "QVBoxLayout * \fBsimLayout\fP"
.br
.ti -1c
.RI "QVBoxLayout * \fBsvgAndSimControlLayout\fP"
.br
.ti -1c
.RI "QGridLayout * \fBsvgLayout\fP"
.br
.ti -1c
.RI "QHBoxLayout * \fBsimControlLayout\fP"
.br
.ti -1c
.RI "QLabel * \fBlabel\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBhorizontalSpacer_4\fP"
.br
.ti -1c
.RI "QPushButton * \fBstop_sim\fP"
.br
.ti -1c
.RI "QPushButton * \fBstart_sim\fP"
.br
.ti -1c
.RI "QSpacerItem * \fBhorizontalSpacer\fP"
.br
.ti -1c
.RI "QPushButton * \fBminus_sim\fP"
.br
.ti -1c
.RI "QPushButton * \fBplus_sim\fP"
.br
.ti -1c
.RI "QVBoxLayout * \fBverticalLayout_3\fP"
.br
.ti -1c
.RI "QTabWidget * \fBtabWidget\fP"
.br
.ti -1c
.RI "QWidget * \fBtab\fP"
.br
.ti -1c
.RI "QWidget * \fBverticalLayoutWidget\fP"
.br
.ti -1c
.RI "QVBoxLayout * \fBverticalLayout_2\fP"
.br
.ti -1c
.RI "QPushButton * \fBloadNormalBtn\fP"
.br
.ti -1c
.RI "QPushButton * \fBloadErrorBtn\fP"
.br
.ti -1c
.RI "QWidget * \fBtab_chrono\fP"
.br
.ti -1c
.RI "QMenuBar * \fBmenubar\fP"
.br
.ti -1c
.RI "QMenu * \fBmenuFile\fP"
.br
.ti -1c
.RI "QMenu * \fBmenuDebug\fP"
.br
.ti -1c
.RI "QMenu * \fBmenutest\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
