.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/build/ui_mainwindow.h" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Qt_VHDL_SVG_proj/build/ui_mainwindow.h
.SH SYNOPSIS
.br
.PP
\fR#include <QtCore/QVariant>\fP
.br
\fR#include <QtGui/QAction>\fP
.br
\fR#include <QtWidgets/QApplication>\fP
.br
\fR#include <QtWidgets/QGridLayout>\fP
.br
\fR#include <QtWidgets/QHBoxLayout>\fP
.br
\fR#include <QtWidgets/QHeaderView>\fP
.br
\fR#include <QtWidgets/QLabel>\fP
.br
\fR#include <QtWidgets/QMainWindow>\fP
.br
\fR#include <QtWidgets/QMenu>\fP
.br
\fR#include <QtWidgets/QMenuBar>\fP
.br
\fR#include <QtWidgets/QPushButton>\fP
.br
\fR#include <QtWidgets/QSpacerItem>\fP
.br
\fR#include <QtWidgets/QSplitter>\fP
.br
\fR#include <QtWidgets/QTreeView>\fP
.br
\fR#include <QtWidgets/QTreeWidget>\fP
.br
\fR#include <QtWidgets/QVBoxLayout>\fP
.br
\fR#include <QtWidgets/QWidget>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBUi_MainWindow\fP"
.br
.ti -1c
.RI "class \fBUi::MainWindow\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
