.TH "Ui::MainWindow" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ui_mainwindow\&.h>\fP
.PP
Inherits \fBUi_MainWindow\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBUi_MainWindow\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBsetupUi\fP (QMainWindow *\fBMainWindow\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBretranslateUi\fP (QMainWindow *\fBMainWindow\fP)"
.br
.in -1c

Public Attributes inherited from \fBUi_MainWindow\fP
.in +1c
.ti -1c
.RI "\fBQAction\fP * \fBactionNew_Simulation\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionExamples\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionLoad_SVG_file\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionOpenDebugWindow\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBaction1\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBaction2\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBaction3\fP"
.br
.ti -1c
.RI "QWidget * \fBcentralwidget\fP"
.br
.ti -1c
.RI "\fBQHBoxLayout\fP * \fBhorizontalLayout_3\fP"
.br
.ti -1c
.RI "\fBQSplitter\fP * \fBmainSplitter\fP"
.br
.ti -1c
.RI "QWidget * \fBleftContainer\fP"
.br
.ti -1c
.RI "\fBQVBoxLayout\fP * \fBverticalLayout\fP"
.br
.ti -1c
.RI "QWidget * \fBcomponentsInfoContainer\fP"
.br
.ti -1c
.RI "\fBQVBoxLayout\fP * \fBcomponentsLayout\fP"
.br
.ti -1c
.RI "\fBQLabel\fP * \fBLabel\fP"
.br
.ti -1c
.RI "\fBQTreeWidget\fP * \fBcomponentsTreeWidget\fP"
.br
.ti -1c
.RI "QWidget * \fBsvgLoader\fP"
.br
.ti -1c
.RI "\fBQVBoxLayout\fP * \fBfolderTreeLayout\fP"
.br
.ti -1c
.RI "\fBQHBoxLayout\fP * \fBtreeViewBtnLayout\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBfolder_btn\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBcloseFile\fP"
.br
.ti -1c
.RI "\fBQSpacerItem\fP * \fBhorizontalSpacer_2\fP"
.br
.ti -1c
.RI "\fBQTreeView\fP * \fBfileTreeView\fP"
.br
.ti -1c
.RI "QWidget * \fBverticalLayoutWidget_4\fP"
.br
.ti -1c
.RI "\fBQVBoxLayout\fP * \fBsimLayout\fP"
.br
.ti -1c
.RI "\fBQVBoxLayout\fP * \fBsvgAndSimControlLayout\fP"
.br
.ti -1c
.RI "\fBQGridLayout\fP * \fBsvgLayout\fP"
.br
.ti -1c
.RI "\fBQHBoxLayout\fP * \fBsimControlLayout\fP"
.br
.ti -1c
.RI "\fBQLabel\fP * \fBlabel\fP"
.br
.ti -1c
.RI "\fBQSpacerItem\fP * \fBhorizontalSpacer\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBstop\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBminus\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBplus\fP"
.br
.ti -1c
.RI "\fBQVBoxLayout\fP * \fBverticalLayout_3\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBpushButton\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBpushButton_2\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBpushButton_11\fP"
.br
.ti -1c
.RI "\fBQMenuBar\fP * \fBmenubar\fP"
.br
.ti -1c
.RI "\fBQMenu\fP * \fBmenuFile\fP"
.br
.ti -1c
.RI "\fBQMenu\fP * \fBmenuDebug\fP"
.br
.ti -1c
.RI "\fBQMenu\fP * \fBmenutest\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
