.TH "Ui::MainWindow" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Ui::MainWindow
.SH SYNOPSIS
.br
.PP
.PP
\fR#include <ui_mainwindow\&.h>\fP
.PP
Inherits \fBUi_MainWindow\fP\&.
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBUi_MainWindow\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBsetupUi\fP (QMainWindow *\fBMainWindow\fP)"
.br
.ti -1c
.RI "\fBvoid\fP \fBretranslateUi\fP (QMainWindow *\fBMainWindow\fP)"
.br
.in -1c

Public Attributes inherited from \fBUi_MainWindow\fP
.in +1c
.ti -1c
.RI "\fBQAction\fP * \fBactionMemory\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionProgram_Cache\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionData_Chache\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionPeripherals\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionTerminal\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionRestart\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionCompile\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionNew_simulation\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionReload_simulation\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionPrint\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionNew_source\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionOpen_source\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionSave_source\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionSave_source_as\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionClose_source\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionExamplese\fP"
.br
.ti -1c
.RI "\fBQAction\fP * \fBactionExit\fP"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBcentralwidget\fP"
.br
.ti -1c
.RI "\fBQGridLayout\fP * \fBgridLayout_5\fP"
.br
.ti -1c
.RI "\fBQSplitter\fP * \fBsplitter_2\fP"
.br
.ti -1c
.RI "\fBQSplitter\fP * \fBsplitter\fP"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBlayoutWidget\fP"
.br
.ti -1c
.RI "\fBQGridLayout\fP * \fBgridLayout_3\fP"
.br
.ti -1c
.RI "\fBQTableWidget\fP * \fBtableWidget\fP"
.br
.ti -1c
.RI "\fBQLabel\fP * \fBlabel_4\fP"
.br
.ti -1c
.RI "\fBQTabWidget\fP * \fBtabWidget\fP"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBtab\fP"
.br
.ti -1c
.RI "\fBQGridLayout\fP * \fBgridLayout_7\fP"
.br
.ti -1c
.RI "\fBQSplitter\fP * \fBsplitter_3\fP"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBlayoutWidget1\fP"
.br
.ti -1c
.RI "\fBQVBoxLayout\fP * \fBverticalLayout\fP"
.br
.ti -1c
.RI "\fBQLabel\fP * \fBlabel_2\fP"
.br
.ti -1c
.RI "\fBQGridLayout\fP * \fBgridLayout_6\fP"
.br
.ti -1c
.RI "\fBQGridLayout\fP * \fBgridLayout\fP"
.br
.ti -1c
.RI "\fBQGraphicsView\fP * \fBgraphicsView\fP"
.br
.ti -1c
.RI "\fBQSlider\fP * \fBverticalSlider\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBpushButton_2\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBpushButton\fP"
.br
.ti -1c
.RI "\fBQPushButton\fP * \fBpushButton_3\fP"
.br
.ti -1c
.RI "\fBQCheckBox\fP * \fBcheckBox\fP"
.br
.ti -1c
.RI "\fBQTextBrowser\fP * \fBtextBrowser\fP"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBtab_2\fP"
.br
.ti -1c
.RI "\fBQGridLayout\fP * \fBgridLayout_2\fP"
.br
.ti -1c
.RI "\fBQVBoxLayout\fP * \fBverticalLayout_3\fP"
.br
.ti -1c
.RI "\fBQLabel\fP * \fBlabel\fP"
.br
.ti -1c
.RI "\fBQPlainTextEdit\fP * \fBTextEditor\fP"
.br
.ti -1c
.RI "\fBQWidget\fP * \fBlayoutWidget2\fP"
.br
.ti -1c
.RI "\fBQGridLayout\fP * \fBgridLayout_4\fP"
.br
.ti -1c
.RI "\fBQLabel\fP * \fBlabel_3\fP"
.br
.ti -1c
.RI "\fBQPlainTextEdit\fP * \fBplainTextEdit_2\fP"
.br
.ti -1c
.RI "\fBQStatusBar\fP * \fBstatusbar\fP"
.br
.ti -1c
.RI "\fBQMenuBar\fP * \fBmenuBar\fP"
.br
.ti -1c
.RI "\fBQMenu\fP * \fBmenuFile\fP"
.br
.ti -1c
.RI "\fBQMenu\fP * \fBmenuMachine\fP"
.br
.ti -1c
.RI "\fBQMenu\fP * \fBmenuWindows\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
