.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/visualc.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/compiler/visualc.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_MSVC\fP   \fB_MSC_VER\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_DEPENDENT_TYPES_IN_TEMPLATE_VALUE_PARAMETERS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_VOID_RETURNS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_EXCEPTION_STD_NAMESPACE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_EXPLICIT_FUNCTION_TEMPLATE_ARGUMENTS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INCLASS_MEMBER_INITIALIZATION\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_PRIVATE_IN_AGGREGATE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_ARGUMENT_DEPENDENT_LOOKUP\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INTEGRAL_INT64_T\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_DEDUCED_TYPENAME\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_USING_DECLARATION_OVERLOADS_FROM_TYPENAME_BASE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MEMBER_TEMPLATES\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_MSVC6_MEMBER_TEMPLATES\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MEMBER_TEMPLATE_FRIENDS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_TEMPLATE_PARTIAL_SPECIALIZATION\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_CV_VOID_SPECIALIZATIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_FUNCTION_TEMPLATE_ORDERING\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_USING_TEMPLATE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_SWPRINTF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_TEMPLATE_TEMPLATES\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_SFINAE\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_POINTER_TO_MEMBER_TEMPLATE_PARAMETERS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_IS_ABSTRACT\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_SWPRINTF\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_MEMBER_TEMPLATE_FRIENDS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_INTRINSIC_WCHAR_T\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_NO_EXCEPTIONS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_DISABLE_WIN32\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_DECLSPEC\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_ABI_PREFIX\fP   'sysc/\fBpackages\fP/\fBboost\fP/\fBconfig\fP/\fBabi\fP/\fBmsvc_prefix\&.hpp'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_ABI_SUFFIX\fP   'sysc/\fBpackages\fP/\fBboost\fP/\fBconfig\fP/\fBabi\fP/\fBmsvc_suffix\&.hpp'\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_COMPILER_VERSION\fP   5\&.0"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_COMPILER\fP   'Microsoft \fBVisual\fP \fBC\fP++ \fBversion\fP ' SC_BOOST_STRINGIZE(\fBSC_BOOST_COMPILER_VERSION\fP)"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_ABI_PREFIX   'sysc/\fBpackages\fP/\fBboost\fP/\fBconfig\fP/\fBabi\fP/\fBmsvc_prefix\&.hpp'\fP"

.SS "#\fBdefine\fP SC_BOOST_ABI_SUFFIX   'sysc/\fBpackages\fP/\fBboost\fP/\fBconfig\fP/\fBabi\fP/\fBmsvc_suffix\&.hpp'\fP"

.SS "#\fBdefine\fP SC_BOOST_COMPILER   'Microsoft \fBVisual\fP \fBC\fP++ \fBversion\fP ' SC_BOOST_STRINGIZE(\fBSC_BOOST_COMPILER_VERSION\fP)"

.SS "#\fBdefine\fP SC_BOOST_COMPILER_VERSION   5\&.0"

.SS "#\fBdefine\fP SC_BOOST_DISABLE_WIN32"

.SS "#\fBdefine\fP SC_BOOST_HAS_DECLSPEC"

.SS "#\fBdefine\fP SC_BOOST_MSVC   \fB_MSC_VER\fP"

.SS "#\fBdefine\fP SC_BOOST_MSVC6_MEMBER_TEMPLATES"

.SS "#\fBdefine\fP SC_BOOST_NO_ARGUMENT_DEPENDENT_LOOKUP"

.SS "#\fBdefine\fP SC_BOOST_NO_CV_VOID_SPECIALIZATIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_DEDUCED_TYPENAME"

.SS "#\fBdefine\fP SC_BOOST_NO_DEPENDENT_TYPES_IN_TEMPLATE_VALUE_PARAMETERS"

.SS "#\fBdefine\fP SC_BOOST_NO_EXCEPTION_STD_NAMESPACE"

.SS "#\fBdefine\fP SC_BOOST_NO_EXCEPTIONS"

.SS "#\fBdefine\fP SC_BOOST_NO_EXPLICIT_FUNCTION_TEMPLATE_ARGUMENTS"

.SS "#\fBdefine\fP SC_BOOST_NO_FUNCTION_TEMPLATE_ORDERING"

.SS "#\fBdefine\fP SC_BOOST_NO_INCLASS_MEMBER_INITIALIZATION"

.SS "#\fBdefine\fP SC_BOOST_NO_INTEGRAL_INT64_T"

.SS "#\fBdefine\fP SC_BOOST_NO_INTRINSIC_WCHAR_T"

.SS "#\fBdefine\fP SC_BOOST_NO_IS_ABSTRACT"

.SS "#\fBdefine\fP SC_BOOST_NO_MEMBER_TEMPLATE_FRIENDS"

.SS "#\fBdefine\fP SC_BOOST_NO_MEMBER_TEMPLATE_FRIENDS"

.SS "#\fBdefine\fP SC_BOOST_NO_MEMBER_TEMPLATES"

.SS "#\fBdefine\fP SC_BOOST_NO_POINTER_TO_MEMBER_TEMPLATE_PARAMETERS"

.SS "#\fBdefine\fP SC_BOOST_NO_PRIVATE_IN_AGGREGATE"

.SS "#\fBdefine\fP SC_BOOST_NO_SFINAE"

.SS "#\fBdefine\fP SC_BOOST_NO_SWPRINTF"

.SS "#\fBdefine\fP SC_BOOST_NO_SWPRINTF"

.SS "#\fBdefine\fP SC_BOOST_NO_TEMPLATE_PARTIAL_SPECIALIZATION"

.SS "#\fBdefine\fP SC_BOOST_NO_TEMPLATE_TEMPLATES"

.SS "#\fBdefine\fP SC_BOOST_NO_USING_DECLARATION_OVERLOADS_FROM_TYPENAME_BASE"

.SS "#\fBdefine\fP SC_BOOST_NO_USING_TEMPLATE"

.SS "#\fBdefine\fP SC_BOOST_NO_VOID_RETURNS"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
