.TH "C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/platform/win32.hpp" 3 "VHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/BJRODIER/Documents/QT_REPO/QT_VHDL_simulator/code/Ressources/SystemC/include/sysc/packages/boost/config/platform/win32.hpp
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_PLATFORM\fP   'Win32'"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_DECLSPEC\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_WINTHREADS\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_HAS_FTIME\fP"
.br
.ti -1c
.RI "#\fBdefine\fP \fBSC_BOOST_WINDOWS\fP   1"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#\fBdefine\fP SC_BOOST_HAS_DECLSPEC"

.SS "#\fBdefine\fP SC_BOOST_HAS_FTIME"

.SS "#\fBdefine\fP SC_BOOST_HAS_WINTHREADS"

.SS "#\fBdefine\fP SC_BOOST_PLATFORM   'Win32'"

.SS "#\fBdefine\fP SC_BOOST_WINDOWS   1"

.SH "Author"
.PP 
Generated automatically by Doxygen for VHDL simulator from the source code\&.
