.TH "main.cpp" 3 "SvgVHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <QCoreApplication>\fP
.br
\fR#include <QFile>\fP
.br
\fR#include <QXmlStreamReader>\fP
.br
\fR#include <QDebug>\fP
.br
\fR#include <QResource>\fP
.br
\fR#include <QtSvg>\fP
.br
\fR#include 'svg_link_parser\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (int argc, char * argv[])"

.SH "Author"
.PP 
Generated automatically by Doxygen for SvgVHDL simulator from the source code\&.
