.TH "SvgLinkParser::element_io_list" 3 "SvgVHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgLinkParser::element_io_list \- Struct for storing element IO information\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QString \fBlabel\fP"
.br
.RI "Label of the element\&. "
.ti -1c
.RI "QString \fBtype\fP"
.br
.RI "Type of the element\&. "
.ti -1c
.RI "uint16_t \fBattribute_count\fP"
.br
.RI "Count of attributes\&. "
.ti -1c
.RI "std::vector< QString > \fBinputs\fP"
.br
.RI "Vector of input attributes\&. "
.ti -1c
.RI "std::vector< QString > \fBoutputs\fP"
.br
.RI "Vector of output attributes\&. "
.ti -1c
.RI "std::vector< QString > \fBother_attributes\fP"
.br
.RI "Vector of other attributes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct for storing element IO information\&. 
.SH "Member Data Documentation"
.PP 
.SS "uint16_t SvgLinkParser::element_io_list::attribute_count"

.PP
Count of attributes\&. 
.SS "std::vector<QString> SvgLinkParser::element_io_list::inputs"

.PP
Vector of input attributes\&. 
.SS "QString SvgLinkParser::element_io_list::label"

.PP
Label of the element\&. 
.SS "std::vector<QString> SvgLinkParser::element_io_list::other_attributes"

.PP
Vector of other attributes\&. 
.SS "std::vector<QString> SvgLinkParser::element_io_list::outputs"

.PP
Vector of output attributes\&. 
.SS "QString SvgLinkParser::element_io_list::type"

.PP
Type of the element\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SvgVHDL simulator from the source code\&.
