.TH "SvgLinkParser::s_tree_node" 3 "SvgVHDL simulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SvgLinkParser::s_tree_node \- Struct for representing tree nodes\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "QDomElement \fBelement\fP"
.br
.RI "XML element of the node\&. "
.ti -1c
.RI "\fBs_tree_node_info\fP \fBinfos\fP"
.br
.RI "Information of the node\&. "
.ti -1c
.RI "int \fBlevel\fP"
.br
.RI "Level of the node in the tree\&. "
.ti -1c
.RI "std::vector< \fBs_tree_node\fP > \fBchildren\fP"
.br
.RI "Children nodes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct for representing tree nodes\&. 
.SH "Member Data Documentation"
.PP 
.SS "std::vector<\fBs_tree_node\fP> SvgLinkParser::s_tree_node::children"

.PP
Children nodes\&. 
.SS "QDomElement SvgLinkParser::s_tree_node::element"

.PP
XML element of the node\&. 
.SS "\fBs_tree_node_info\fP SvgLinkParser::s_tree_node::infos"

.PP
Information of the node\&. 
.SS "int SvgLinkParser::s_tree_node::level"

.PP
Level of the node in the tree\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for SvgVHDL simulator from the source code\&.
